hamlet-io/engine

- engine/openapi.ftl
The mock integration type wasn't including request or response templates and wasn't providing a default response code of 200.
> <fix> Add request/response templates for mock requests

- engine/base.ftl
Azure and likely other providers will require number values within templates instead of numbers-as-strings. However, you often want to be able to set an "empty" default value for these attributes which is most easily just an empty string. This PR introduces a function to format a new attribute with the format as a number if content exists, otherwise return an empty string.
Example resource.ftl
``` freemarker
[#function getWebAppIpSecurityRestriction
ipAddress=""
subnetMask=""
vnetSubnetResourceId=""
action=""
tag=""
priority=""
name=""
description=""]
[#return {} +
attributeIfContent("ipAddress", ipAddress) +
attributeIfContent("subnetMask", subnetMask) +
attributeIfContent("vnetSubnetResourceId", vnetSubnetResourceId) +
attributeIfContent("action", action) +
attributeIfContent("tag", …
```
> Feature - numberAttributeIfContent

- engine/common.ftl
- providers/aws/services/dns/id.ftl
- providers/shared/components/spa/id.ftl
- providers/shared/references/Port/id.ftl
Rather than hard-code HTTPS into the SPA Component, this PR introduces the ability to set a port for an SPA provider whilst defaulting to HTTPS.
This PR also migrates some DNS related functions and variables and moves them into Common.ftl alongside other domain-related functions.
> SPA Port Attribute Option

- Jenkinsfile
- providers/awstest/scenarios/lb.ftl
- providers/shared/shared.ftl
- test/aws/run_aws_template_tests.sh
This PR adds an initial testing process to validate template generation and content. 
The initial script focuses on running the aws plugin templates using the awstest provider. The process uses the unitlist to generate the list of deploymentunits in the blueprint and then runs createTemplate.sh on each level using the same deployment unit. This is the only way at the moment to know which unit is required. 
We don't worry about template generation failing, instead we are just focussing on running any test cases which have been generated
> <feature>Jenkinsfile for template testing

- execution/contextTree.sh
So that a v2.0.0 cleanup can be configured, add it to the cleanup order.
> <fix> Include v2.0.0 cleanup in the upgrade order

- engine/common.ftl
- engine/commonApplication.ftl
- engine/occurrence.ftl
- providers/aws/components/computecluster/setup.ftl
- providers/aws/components/contentnode/setup.ftl
- providers/aws/components/datapipeline/state.ftl
- providers/aws/components/dataset/state.ftl
- providers/aws/components/lambda/setup.ftl
- providers/aws/components/mobileapp/setup.ftl
Introduce the idea of a registry having a "scope", with "account" level being the current default.
The initial use case is to be able to reuse the same deployment unit value in different segments of a product, and to associate each use with its own image, rather than sharing images as is currently supported. This change thus introduces "segment" scoped registries.
The scope value is obtained via the "Scope" attribute of a build.
This change needs to be introduced in parallel to or ahead of the equivalent automation change which will see images starting to be segment scoped when stored.
This change is an interim approach until code units are introduced, with the details of the registry to access being attributes of the code unit that can then be queried via buildblueprint.
> <feature> Registry scopes

- aws/templates/fragment/fragment_codeontap.ftl
- aws/templates/fragment/start.ftl
Adds the ability for codeontap agent containers to define their own switch role policies. 
To use this feature you pass an array of Accounts in the agent settings. They will be formatted into an assume role policy required for the container to assume role into the listed accounts 
```
"AWS" : {
"Automation" : {
"Accounts" : {
"Value" : [
"1234567890"
]
},
"Role" : "Automation"
}
},
```
The Role value defines the name of the role that will be configured in the assume role this is also set as a setting for codeontap itself to keep them aligned
> <feature> CodeOnTap Agent switch role policy

- engine/common.ftl
- providers/shared/components/component.ftl
Don't default the host name in certificate configurations so that it can be defined at any point where certificate behaviours are defined (blueprint, tenant, product).
> <fix> Permit host name in certificate behaviours

- aws/createTemplate.sh
- aws/manageCrypto.sh
- aws/runExpoAppPublish.sh
- aws/runLambda.sh
- aws/runSentryRelease.sh
Build blueprint generation was failing because it was forcing the extension of its genplan to be .json.
Tweak the output file expected by all the consumers so the standard output suffix as included in the generated genplan will work correctly.
Also fix the generation of a blueprint to only force the output suffix in the pass that generates the blueprint.
The investigation was triggered by an attempt to encrypt credentials using manageCrypto.sh - one of the clients for createBuildblueprint.
This change thus includes some extra debug messages and ciphertext prefix handling, along with a fix to the handling on in file attribute updates.
> <fix> Build blueprint production

- engine/commonApplication.ftl
Ensure that if ignoreIfNotDefined is not set, an attempt to include an attribute of a link in the context of application code will fail.
At present, an empty string is included in the environment rather than an exception being thrown.
> <fix> Fatal error on missing link attribute

- execution/setContext.sh
Only check the current segment value matches the blueprint if a current value for product has been defined.
The segment is defaulted to "default" in the automation setup processing, so we don't want to trigger the segment check unless we are processing a product (as opposed to an account for instance).
> <fix> Segment checks

- Jenkinsfile
Couple of minor fixes to the Jenkinsile 
- Don't allow multiple builds to run on the same job ( each PR, branch is its own job so won't stop them) 
- Add a quiet period so we aren't trigger lots of builds when merging PR's quickly
> <fix> disable concurrent builds and add quiet period

- aws/createTemplate.sh
The check for existing files in the root of the state directory was including directories as well as files. 
This resulted in it treating units as legacy for whom there was already a unit that contained the name of the new unit.
An example is a pre-existing directory of bff-v1-imp and a new unit of bff-v1.
> <fix> Legacy state directory structure detection

- execution/utility.sh
- providers/aws/components/ecs/setup.ftl
- providers/aws/components/ecs/state.ftl
- providers/aws/components/es/setup.ftl
- providers/aws/services/ecs/id.ftl
- providers/shared/components/ecs/id.ftl
Adds support for on demand Ec2 Instance autoscaling for ECS ( https://docs.amazonaws.cn/en_us/AmazonECS/latest/developerguide/cluster-auto-scaling.html ) 
Essentially it creates a tracked autoscaling policy on the Ec2 Autoscale cluster along with a metric of the required resources for the ECS cluster. When a task starts and there are now instances to service the task, it will sit in a provisioning state until the autoscaling action has completed. 
The same goes when there aren't any tasks to run, the cluster will remove any ec2 instances running without tasks on them 
This required a basic implementation of the ECS capacity providers which provide a way to define where containers should be deployed ( ec2, fargate, fargate spot etc) using weighted rules 
As this is a new feature and people …
> <feature> ECS OnDemand Compute Provider

- providers/aws/components/ecs/setup.ftl
Read ecsCapacityProviderOnDemand id only when compute Provider is ec2OnDemand
Use ecsCapacityProviderOnDemand id in cli as a capacity provider name.
> <fix> read ecsCapacityProviderOnDemand id

- engine/occurrence.ftl
Make the build scope an internal setting so it doesn't appear in the context environment. This decision can be revisited if a use case emerges where it would be useful for the application to know the build scope.
> <fix> Make build scope an internal setting

- providers/shared/deploymentframeworks/default/output.ftl
reinstated genplan pass for parameters since codeontap/gen3#1075
Looks like this just got missed during a refactor.
> Fix - Genplan Parameters Pass

- engine/common.ftl
- engine/setContext.ftl
- providers/shared/deploymentframeworks/default/legacy.ftl
Separate out the idea of overriddable profiles that simplify the amount of config necessary to build a solution from policy profiles which enforce configuration irrespective of what is in the solution.
The existing DeploymentProfiles provide the override mechanism using the standard CMDB override hierarchy. One layer simply redefines the profile defined by a higher one.
Policy profiles use the same format as deployment profiles but are defined within tenant, account and product levels. They can then applied via a "Profiles.Policy" at the same levels.
> <feature> Policy profiles

- execution/utility.sh
- providers/aws/components/baseline/setup.ftl
- providers/shared/references/Environment/id.ftl
When migrating legacy OAIs to the baseline equivalent, don't try and delete the legacy OAI if it is still in use.
Because the legacy stack will still be deleted (as is replaced with baseline's own OAI), cleanup of the legacy OAI will need to be performed manually.
> <fix> Only delete legacy OAI if not in use

- engine/common.ftl
- providers/aws/components/ecs/setup.ftl
Only return numbers instead of empty strings when calculating processor counts. We use the return values in number comparisons which doesn't work for strings
> <fix> only return numbers for processor counts

- engine/base.ftl
Fixes an issue where if a default attribute value of "" is provided and never overwritten, the function attempts to convert it to a number anyway and then errors.
Fixes this problem by only performing the conversion from string-to-number when something is actually provided.
Creating existing Azure templates that utilise this function.
None
> Fix - numberAttributeIfContent function

- aws/runExpoAppPublish.sh
Allows for the ios export method to be defined in expo app publishing
When signing an IOS binary app package the export method needs to align with the type of provisioning profile that is being used. This PR allows for the method to be defined while setting the default to app-store if it is not set. Most app builds are app-store as they either go to test flight or the real app store. The other methods are mostly for private deployment with an MDM solution 
Yes testing has been performed as part of a mobile app build 
None
> <feature> export method configuration in fastlane

- aws/runExpoAppPublish.sh
- aws/runSentryRelease.sh
Fixing the exit code from expo app publish and sentry resale scripts.
This PR includes a minor fix to correctly handle an exit code from app publish and sentry resale scripts. Trap instruction was using `RESULT` variable with a default value `1`. `RESULT` variable was never initialised during the scripts execution what lead to the exit code to be set to`1`.
This fix is required to properly set a build status for Expo Publish and Sentry Release builds.
The minor fix was tested locally and on an OSX agent. It affects only Expo Publish and Sentry Release builds.
> <fix> exit codes from expo app publish and sentry resale scripts

- providers/shared/deploymentframeworks/default/output.ftl
Correct the alternative value used for the pregeneration step.
Pregeneration processing does not require the use of alternatives, and having a non-default value affects the output filename used to save it in the CMDB.
- Ran a local template creation and confirmed the correct output file was generated.
N/A
> <fix> Pregeneration output filename

- legacy/fragment/fragment_jenkins.ftl
Separates the Jenkins HTTP url from the Jenkins JNLP alternate endpoints for ecs agents. This was in place but was incorrectly merged
Allows for the JNLP endpoint to be hosted on a network load balancer with the normal jenkins endpoint on an http load balancer. This allows for agents outside of the VPC to connect to the Jenkins host over JNLP
Deployed to our codepublican service
Change required to the link name when you want to use the JNLP alternate endpoint instead of 
JENKINS_LOCAL_FQDN the setting tested for the FQDN is now JENKINS_JNLP_FQDN 
JENKINS_LOCAL_FQDN is still usable but only for the Jenkins HTTP url endpoint
> <fix> jenkins jnlp alternate endpoint

- providers/shared/components/db/id.ftl
Companion PR to https://github.com/hamlet-io/engine-plugin-aws/pull/2 
Allows you to set either the major or minor version of database engine to use
sometimes you might want to control the specific minor version that you are on for an RDS database engine or you want to restrict the auto update service support 
Tested with client site
- [X ] New feature (non-breaking change which adds functionality)
None
> <feature> rds minor version support

- engine/commonApplication.ftl
- engine/inputdata/setting.ftl
- providers/shared/components/component.ftl
- providers/shared/components/template/id.ftl
Closes: https://github.com/hamlet-io/engine/issues/927
Adds support for a new template component which is intended to provide the support for provisioning external templates within the context of a hamlet deployment 
--- 
Also adds the ability to control the casing for environment variables generated through Settings processing. 
The @Variable marco now supports the ability to define enable or disable uppercasing of the setting name 
This allows for someone to integrate 3rd party templates into the hamlet deployment model and integrate the output mapping and environment level context that we provide 
Deployed to test customer site
> <feature> Template component

- legacy/fragment/fragment_hamlet.ftl
- legacy/fragment/fragment_jenkins.ftl
Adds support for a new properties volume which will replace the codeontap volume that we use to share data between the jenkins master and its agents via EFS
Part of our rename from codeontap to hamlet. Chose a generic name ( properties ) to make things easier to understand
Tested in our codepublican deployment
- [] To use the new volume the environment variable `PROPERTIESVOLUME` which will then mount to the containers under `/var/opt/properties`
> <refactor> jenkins agent hamlet updates

- client/createUnitlist.ftl
Includes suboccurences in the unlist list assembly 
the unit list allows you to find all of the deployment units for a given segment, this is useful for script deployments across units in bulk. It didn't include suboccurences though so you couldn't get everything
tested locally with `${GENERATION_DIR}/createTemplate.sh -l unitlist`
> <fix> Include suboccurrences in unitlist

- providers/shared/components/externalservice/id.ftl
- providers/shared/components/externalservice/state.ftl
Adds link support on the externalservice component
Adding link support to the external service component allows you to build attributes based on other components deployed in your solution, combined with fragment support this allows for a method of link indirection. 
One example where this is useful is for user pools and SPA's. User pools need to whitelist the auth urls that are used by the SPA to perform the login and logout actions. Linking through an external service allows us this whitelist to be populated using the SPA attributes along with additional Urls for local development 
> <feature> external service links

- providers/shared/references/WAFRuleGroup/id.ftl
Minor fix to the reference lookup of the WAF Rule groups
Rule groups were not loading which meant that WAF rules were not being applied
TEsted with deployment
> <fix> WAFRule Group Loading

- engine/setContext.ftl
- providers/shared/components/component.ftl
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/references/WAFProfile/reference.ftl
- providers/shared/references/WAFRule/id.ftl
- providers/shared/references/WAFRule/reference.ftl
Add support for blacklisted and whitelisted geo matches in WAF configurations.
Countries will be allowed/blocked based no the blacklist status of the country group. The WAF configuration is the same as for Cloudfront;
```
"WAF" : { "CountryGroups" : "Australia"}
```
This will permit regional APIs to to geoblocked.
Via deployment
> <feature> WAF GeoMatch Support

- engine/commonApplication.ftl
- providers/shared/components/adaptor/id.ftl
- providers/shared/components/adaptor/setup.ftl
- providers/shared/components/component.ftl
Adds support for the adaptor component. This component has no resources and relies on fragment files to define how it works. It has a scripts code image and registry which can be used to deploy support files or code to make the adaptor component deploy
Following on from the template component #1281 we also need a way to generically define any resource or script to deploy something. This essentially allows us to integrate with any thing we want 
Tested with a local deployment
> <feature> adaptor generic component

- engine/commonApplication.ftl
When context settings were not present, getFinalEnvironment crashes.
Configurations that did not use contextSettings would crash whenever processing a unit that created an environment using ```getFinalEnvironment()```
> <fix> Crash when no context settings

- engine/component.ftl
- engine/occurrence.ftl
Configuration attributes that are provider specific must now be prefixed with the provider value, e.g.
```
"aws:Parameter" : "xyz"
```
It also fixes a bug in the combining of shared and provider specific attributes, where the precedence of the missing value operator prevented the provider specific attributes from being considered.
It is desirable to explicitly identify parameters which are targetted at a specific provider. It will also permit documentation to indicate what are the shared and provider specific attributes for a component.
To date, no provider specific attributes have been used so it is a good time to make this change. 
> <feature> Namespaced provider specific configuration attributes

- providers/shared/components/component.ftl
- providers/shared/components/userpool/id.ftl
Adds support for defining server resources on a user pool which represent services that use this userpool for authentication
Adds extra userpool configuration around user identity and security enhancements
Server resources are required when using system to system authentication from a user pool which is oAuth based rather than OIDC based. When using system to system oauth you can not use the OIDC scopes/claims and instead need to define your own. Server resources allow you to do this. 
Tested on a fresh local deployment
> <feature> userpool resources and advanced sec

- engine/commonApplication.ftl
- providers/shared/components/ecs/id.ftl
Allows the RunMode of a container to be explicitly set in the solution configuration. The existing mode setup is still the default. This just allows for it to be set explicitly 
Wanted to use the mode to define a list of different modes that can be applied to a container that is part of a task
Tested on deployment
> <feature> container run mode explicit configuration

- legacy/fragment/fragment_hamlet.ftl
- legacy/fragment/fragment_jenkins.ftl
Fixes an issue with the migration from the `/var/opt/codeontap/` to `/var/opt/properties` volumes which created a disconnect between the Jenkins master and the agents 
To share shared properties between the agent and the jenkins master in container deployments we use an EFS share which is mounted to the same location in both the Jenkins master and agents. With the move to hamlet this was renamed from the codeontap directory to the properties directory. 
Tested on codepublican deployment
> <fix> support codeontap and properties volume

- engine/common.ftl
- engine/setContext.ftl
This PR implements `skuProfiles` the loading of the skuProfiles reference type into the shared provider. Though the skuProfiles reference type exists within the Azure plugin, there is a current issue with the load-order of reference data from plugins that will be looked at in another ticket. This allows correct loading in the meantime.
Azure has a common concept of a SKU or "Stock Keeping Unit" (think of it like a make/model information) across many resources. The SKU requirements change across resources - sometimes its just a name to indicate the pricing tier of a resource you want, other times its make, model, family, generation etc. This reference type allows for the base provider to implement some default profiles within masterdata, whilst allowing customisation through the CMDB. …
> Feature - Sku Profiles

- providers/shared/components/userpool/id.ftl
Enables the ability to configure userpool federation with the different public identity providers ( google, apple, amazon and facebook ) 
Support public identity logins instead of just enterprise level providers ( SAML or OIDC )
Tested with a template generation on a userpool, haven't tested with an app as I didn't have one configured with the providers
> feature: public login provider support

- providers/shared/components/userpool/id.ftl
In order that missing configuration can be correctly reported, remove the defaults for most of the auth provider config settings.
Also correct a spelling error in one of the attributes.
Defaulting logic wasn't detecting missing values.
Customer deployment
> fix: Remove auth provider defaults

- providers/shared/components/gateway/id.ftl
Adds support for link based network gateways using the `endpoint` engine type 
Allows for integration of complex network component setups like peering which are difficult to cooridinate with infrastructure as code deployments as they require two parties to setup the infrastructure at the same time. With the endpoint engine the details of the peering connection can be provided through an external component attribute. This can also be extended to support linking to other components which offer routing services such as vm instances or network interfaces
> feature(gateway): link based gateways

- providers/shared/components/gateway/id.ftl
Make Endpoint Type and scope optional on gateway component
Not required for all gateway types and when set to mandatory other gateway types could not be deployed as their configuration was invalid
Caught by testing and tested on local deployment
> fix(gateway): remove mandatory requirement on Endpoint details

- providers/shared/components/mobileapp/id.ftl
Companion PR to https://github.com/hamlet-io/engine-plugin-aws/pull/36 
Allows you to specify the path behaviour for a mobile OTA 
Backwards compatibility with the current mobile app deployment process
> feat(mobileapp): OTA Support on CDN routes

- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/references/SecurityProfile/id.ftl
Allows for security profile configuration of API Gateway Custom domain names and if configured the CDN in front of the API Gateway. 
When not using a CDN infront of an API Gateway you can still configure the TLS profile for the APIGateway itself. This is configured independently as providers use different values to set the profile configuration
Tested on live deployment
> feat(apigateway): support gateway and cdn https profiles

- legacy/fragment/fragment_hamlet.ftl
Adds support for jenkins hamlet agents to run as permanent jenkins agents along with ECS ephemeral agents. The expectation is that the these permanent agents will run as services on an ECS cluster alongside task based agents. 
Permanent agents allow for agent level security to be configured when strict permissions are required on who can use the agent. 
Tested in Codepublican deployment
> feat(jenkins): add support for permanent ecs agents

- legacy/fragment/fragment_hamlet.ftl
Supports the ability to add a startup command that is run when a container agent starts up
Sometimes we need to shim in some commands whenever a jenkins agent starts up
> feat(fragment): startup command setting for agent

- legacy/fragment/fragment_hamlet.ftl
Allows automation user to be overridden for hamlet jenkins agents. By default the user is set to ROLE, however you might want to have agents  which use fixed credentials for the agent.
This is a fix to allow the user to configure the agent with sensible defaults
Test locally
> fix(fragment): agent override for aws user

- providers/shared/components/component.ftl
- providers/shared/components/globaldb/id.ftl
Adds a new component type, globaldb which represents managed NoSQL database tables
While we have been leaving some of this configuration to be managed through application code there is quite a bit of system level configuration that you might want to control from the infrastructure as code perspective. 
While this does require some application logic as part of the infrastructure as code deployment to define some keys in the table, such as the primary and secondary keys. All other keys in the table can still be defined by the application. 
Tested locally using a live deployment CMDB in AWS
> feat(globaldb): intial support for global dbs

- engine/engine.ftl
- engine/occurrence.ftl
Place the code that does namespace matching into its own routine and use this routine when processing occurrence settings.
This is to enable reuse of this functionality as part of the dynamic CMDB work.
Essentially the plan is to use the same logic for assembly of solutions, potentially allowing the namespace concept we use for settings to enable selective inclusion of solution fragments based on name not hierarchical position.
Rerun existing template generation noting no change in templates.
> refactor: Namespace matching support

- providers/shared/components/component.ftl
- providers/shared/components/externalnetwork/id.ftl
- providers/shared/components/gateway/id.ftl
- providers/shared/services/external/id.ftl
Adds support for the external network component, it represents networks connected via VPN's or private network connections that are not part of the cloud provider network
External network components have a subcomponent of connections, these represent the "physical" network link between a network and externalnetwork. A gateway and destination is still required to route the network traffic to the external network. 
Support for representing networks as part of hamlet
Tested in local deployment
> feat(externalnetwork): intial external network support

- providers/shared/components/router/id.ftl
Make BGP ASN mandatory for routers 
Even when not using BGP for dyanamic routing providers often still require the BGP ASN to be specified. This allows for different mixes of routing on network resources. To ensure they are unique between the different components they are now mandatory for router components
> feat(router): make BGP ASN mandatory

- providers/shared/components/component.ftl
- providers/shared/components/privateservice/id.ftl
Adds a new component, private services 
Private services are used to offer application services between two networks over a cloud providers private networking. This is commonly used for SaaS offerings in security sensitive areas where the service shouldn't be available over the internet 
From AWS this is know as PrivateLink
> feat(privateservice): intial support for private services

- providers/shared/components/component.ftl
- providers/shared/components/router/id.ftl
Adds support for the router component to define its own static routes. Other components can still define their own routes if that is supported
This was motivated by a couple of things 
- When using a shared AWS transit Gateway routing cannot be defined in the AWS account that the transit gateway is shared with it can only be managed from the account which owns the transit gateway. So in this scenario the router needs to control where to forward traffic 
- Allow for configuring blackhole routes on the router to drop traffic destined to locations it shouldn't go 
Tested in local deployment
> feat(router): static route support

- providers/shared/components/gateway/id.ftl
Adds support on gateways to control the gateway DNS zone provisioning 
When using vpcendpoint gateways which require acceptance you can only provision DNS zones when the endpoint has been accepted. The current configuration for the DNS zone determination was based on the network configuration, this is still the default, and this configuration just allows for overriding that.
> feat(gateway): dns configuration support

- providers/shared/components/gateway/id.ftl
1.  Adds support for setting the destination ports on a gateway, defaulting to any. 
2. Adds a new engine type, privateservice which is intended to replace the existing vpcendpoint engine. 
- Component developers should support both engines for the time being but treat them as the same gateway engine
3. Removes transit gateway as a endpoint engine gateway type 
1. This allows for fine grain access control to be applied on gateways if required for security purposes 
2. This aligns with the name of the new private service component which is the other half of the of the vpc endpoint implementation  and also makes the naming more vendor agnostic 
3. This now has its own engine as part of the router engine 
> Gateway Destination ports

- engine/base.ftl
- providers/shared/components/component.ftl
- providers/shared/components/externalservice/id.ftl
- providers/shared/components/externalservice/state.ftl
- providers/shared/components/lb/id.ftl
- Adds support for external endpoints, endpoints represent the IP/port of an external service and the ability to set static endpoints for load balancing
- Also adds a utility to provide the usable hosts in a given network 
The intention here is to use external service endpoints in network access control or routing. For example you might want to proxy traffic to an external endpoint through a cloud hosted load balancer. In this case you can use a link from the Load balancer using the StaticEndpoints Links also introduced in this PR to route traffic to this external endpoint. 
In future work this can also be used to control Egress Security group access so that you can link to an external service and these endpoints will be used for the Access control rules  
> External endpoints

- engine/common.ftl
Add the ability to control the --delete flag.
To permit stacks to be rolled back, it needs to be possible to copy files to S3 without deleting existing files as part of a prologue script, and for the operation to be repeated after successful stack update but with unneeded files now deleted.
> feat: Bucket cleanup optional when copying files

- providers/shared/components/externalservice/state.ftl
- Set attributes for external service endpoints based on the IP Address Group and Port configuration 
- Minor fix to mark external service endpoints as deployed
When linking to an endpoint it would be useful to get this information as attributes inline with our other components
tested locally
> External Service Endpoint attributes

- providers/shared/components/externalservice/state.ftl
Minor fix to align with the variable used for host IP's. Was originally set to hosts but changed at the end of development
Broken
Tested locally
> fix(externalservice): fix var name for ip listing

- providers/shared/components/externalnetwork/id.ftl
- providers/shared/components/gateway/id.ftl
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/references/SecurityProfile/id.ftl
Adds support for configuring IPSec Site to Site VPN options using a security profile
adds a default IPSec profile based on high security standards
To ensure compliance with other network devices and security requirements we need to be able to configure the IPSec security configuration. Making this a security profile allows for standardised configuration across a deployment as these options can be quite complicated
> feat(externalnetwork+gateway): vpn security profile

- engine/setContext.ftl
Allow SSH bastion instances to be deployed regardless of internet status
When deploying an SSH bastion instance with SSM Console access you can still enable access to the instance without enabling internet access
> fix(bastion): allow ssh when internet access disabled

- legacy/account/account_cmk.ftl
- legacy/account/account_volumeencrypt.ftl
Adds account level units to support enabling region wide ebs volume encryption 
This is implemented as two new account level deployment units 
- cmk - which creates an account level CMK
- volumeencrypt - which enables or disables default volume encryption if the CMK is available 
AWS has introduced a global encryption setting for EBS volumes in a region which allows you to automatically encrypt all volumes at rest
> feat(ec2): volume encryption

- legacy/account/account_console.ftl
- legacy/account/account_volumeencrypt.ftl
Add deployment unit filter to cmk required checks to allow for subset passes to work
if you choose not to use the encryption hardening account level units then the cmk isn't required. These checks should only be run if you have specified the use of the encryption units
Tested locally
> fix(account): only run cmk checks in specific units

- engine/commonApplication.ftl
- engine/setContext.ftl
- legacy/account/account_audit.ftl
- legacy/account/account_s3.ftl
- providers/shared/components/baseline/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/s3/id.ftl
Adds support for configuring S3 Bucket At rest default encryption. Any object can be uploaded to a bucket and the client can specify at rest encryption. Default encryption will apply to any object which hasn't been configured for at rest encryption. 
This is available on all S3 buckets - account, baseline and s3 component buckets  and has been disabled by default to ensure compatibility and migration 
When enabling Encryption the default method in this PR is to use the CMK encryption keys `EncryptionService` that we use for at rest encryption across other services. As a result of this extra policies have to be added to the S3 uploaders IAM policy which permit access to the encryption key. 
If this isn't possible or not supported by the client ( this includes other cloud provider services …
> feat: S3 Bucket encryption

- engine/common.ftl
- engine/commonApplication.ftl
- engine/setContext.ftl
- providers/shared/components/bastion/id.ftl
- providers/shared/components/cache/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/configstore/id.ftl
- providers/shared/components/datapipeline/id.ftl
- providers/shared/components/db/id.ftl
- providers/shared/components/ec2/id.ftl
- providers/shared/components/ecs/id.ftl
- providers/shared/components/efs/id.ftl
- providers/shared/components/es/id.ftl
- providers/shared/components/externalnetwork/id.ftl
- providers/shared/components/externalservice/state.ftl
- providers/shared/components/gateway/id.ftl
- providers/shared/components/lambda/id.ftl
- providers/shared/components/lb/id.ftl
- providers/shared/inputsources/mock/blueprint.ftl
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/references/NetworkProfiles/id.ftl
- providers/shared/references/reference.ftl
Adds support for Network Profiles as part of adding support  fine grained security group management 
Network Profiles move control over the default security group rules from hard-coded values in component implementations into the solution itself. 
The Network profile offers an initial list set of security group rules which will be applied to a component. Currently it supports two ways of specifying rules, through links to components or through network Rules which list port and IP Address combinations. 
Only outbound rules are controlled through the network profile and the default outbound rule is currently set to allow all outbound access, inline with cloud provider defaults and with the current configuration.
Ingress rules are still maintained on each component using the IPAddressGroups …
> Network Profiles and Security Group Control

- engine/component.ftl
- providers/shared/components/component.ftl
- providers/shared/deploymentframeworks/default/legacy.ftl
Capture the mapping between legacy types and their canonical equivalent.
Rework the component utility functions to drive off the legacy type mapping.
Rework the lookup of profiles during processing to support the use of legacy types. In the process, also make this logic case insensitive.
Legacy types should work consistently across all aspects of hamlet operation. 
Local builds.
> Fix: Support legacy types in profiles

- engine/setContext.ftl
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/references/NetworkProfiles/id.ftl
Adds some fixes for network profile base security groups
- Allow for multiple rules to be defined 
- Provide a configuration option to enable/disable enabling egress rules through the GlobalAllow rule
This allows for a simpler implementation approach where you can either allow Global access outbound from all services or chose to enable egress control
> fix(networkProfile): enable or disable egress rules

- providers/shared/components/externalservice/id.ftl
Apply solution configuration for shared serivces as part of the resource group attributes
This fixes a bug where the shared provider resource group were overriding the default configuration applied to exteranl service components. 
Not sure if this is a bug or not but I think this is a right approach
> fix(externalservice): Apply solution config on the resource group

- legacy/account/account_cmk.ftl
- legacy/account/account_console.ftl
Adds support for configuring a dedicated KMS CMK for ssm console access. 
This is mostly to support cases when this has been configured by other hardening services that are outside of hamlet. Uses the account level cmk by default
> feat(console): add dedicated cmk option for console sessions

- legacy/account/account_cmk.ftl
Allows for creating unique aliases for CMK keys created at the account level
Ensures that there aren't collisions with other hardening applied to the AWS account 
Tested locally
> feat(account): allow unique cmk aliases

- engine/common.ftl
- engine/setContext.ftl
- providers/shared/components/apigateway/id.ftl
- providers/shared/components/bastion/id.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/datafeed/id.ftl
- providers/shared/components/ec2/id.ftl
- providers/shared/components/ecs/id.ftl
- providers/shared/components/es/id.ftl
- providers/shared/components/lambda/id.ftl
- providers/shared/components/mobilenotifier/id.ftl
- providers/shared/components/network/id.ftl
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/references/LogFilter/id.ftl
- providers/shared/references/LoggingProfile/id.ftl
- providers/shared/references/reference.ftl
Adds support for configuring a logging profile and creating forwarding rules to other components within this profile 
For security or monitoring purposes you might want to forward logs to another monitoring service for enhanced logging performance or access control. 
The logging profile allows for these forwarding rules to be configured at the profile level allowing them to be applied across a whole solution or a select group of components
Implementation is modelled on the network profile configuration which uses a similar approach for egress and ingress network security control 
> Loggging Profile

- providers/shared/components/component.ftl
Adds a configuration option to control error handling for the S3 Queue permissions migration requirements as part of https://github.com/hamlet-io/engine-plugin-aws/pull/98 
Ensures we don't break deployments when the queue permissions haven't been updated
Tested locally
> fix(s3): adds migration for queue permissions config

- engine/setContext.ftl
Correct logic for detecting if CIDRs are defined.
Current logic returns true even if no CIDRs are found. This creates empty WAF rules which also changes the default rule.
Local template creation.
> fix: If no CIDRs defined, getGroupCIDRs should return false

- engine/schema.ftl
Adds the missing "required" attribute to JSONSchema objects that advises what properties on an object are mandatory. The value was already being collected but never assigned - this PR just assigns it to the resultant object.
Completeness of the schema.
Local schema generation.
> Fix - Adds Missing "required" attribute to schema outputs

- providers/shared/components/component.ftl
- providers/shared/inputsources/shared/masterdata.ftl
Adds logging profiles for WAF services to allow for log fowarding
In AWS WAF logging has to be enabled and sent to a forwarding service to see how traffic is being handled. The logs generated by WAF are separate from the normal logs of a WAF enabled service. So to support setting up log forwarding we need to be able to control this independently from the standard component logging profile
Tested locally on active deployment
- Core - https://github.com/hamlet-io/engine/pull/1366
- AWS - https://github.com/hamlet-io/engine-plugin-aws/pull/105
- Bash Executor -  https://github.com/hamlet-io/executor-bash/pull/71
> feat(waf): add waf logging profiles

- engine/commonApplication.ftl
Adds ingress security group lookups for containers in ecs components
Allows for direct inbound rules for containers to use links as well as subnet based rules
Tested on local template generation
- engine: https://github.com/hamlet-io/engine/pull/1370
- engine-plugin-aws: https://github.com/hamlet-io/engine-plugin-aws/pull/110
> feat(ecs): add lookup for ingress rules based on links for containers

- engine/commonApplication.ftl
- providers/shared/components/component.ftl
- providers/shared/components/filetransfer/id.ftl
- providers/shared/components/user/id.ftl
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/references/SecurityProfile/id.ftl
Adds support for a new component the `filetransfer` component. This component is intended to provide file transfer capabilities using vendor agnostic protocols for cloud based storage. 
The component consists of two parts 
- `filetransfer` which represents the service endpoint itself 
- `users`  - The existing component provides the user drive mapping and credentials management in a similar way that it does for cloud resources and API's. A user component links to the filetransfer server to provision the user on the server. Then links to datasources that it wants available over the filetransfer component. 
This allows each user to be provisioned with the resources they require 
Example of a solution 
```
"user" : {
"user" : {
"Instances" : {
"user1" : {
"DeploymentUnits" : [ "user1"]
}
}, …
```
> feat(filetransfer): support for a file transfer component

- engine/common.ftl
- engine/setContext.ftl
- providers/shared/components/component.ftl
- providers/shared/deploymentframeworks/default/legacy.ftl
extends policy profile support to align with the configuration options for deployment profiles
when deployment profiles apply before the blueprint configuration you need to replicate the configuration you want to apply from the occurrence into the deployment profile and have to ensure that its not listed in the occurrence configuration. Extending policy profiles, which are applied after the blueprint configuration allows you to override a value in the occurrence configuration
The ordering of policy profile application is reversed from deployment profiles to ensure that higher level ( tenant, account ) policies are applied last to ensure they are still the preferred configuration
Tested locally on active deployment
> feat(core): extend policy profiles to occurence level control

- engine/setContext.ftl
- legacy/account/account_cmk.ftl
- legacy/account/account_iam.ftl
- legacy/account/account_volumeencrypt.ftl
- providers/shared/references/ServiceRoles/id.ftl
- providers/shared/references/reference.ftl
A collection of changes to make volume encryption easier to support
- Adds a new reference component Service Roles which allow for account level provisioning of service linked roles - These provide permissions for cloud provider services to access other services 
- Refactors the volume encryption process to check for service roles and to also use a dedicated CMK for encryption. This allows for simpler management of KMS key policy 
When adding policies to a KMS key the principals listed in the key policy have to actually exist. This is different to IAM policies which don't require this 
So in order to provide the autoscaling service with KMS access for volume encryption we need to create the autoscaling service linked role before creating the KMS key and before enabling default volume …
> Service roles and volumeencrypt fixes

- client/createDeployment.ftl
Set all subsets generated as part of resource labels to use all units. Disable this for generation contracts as each label sets the expected subsets
When generating any document using a resource label all deployment units configuration should be included in the template document generation process. Currently they are being skipped and while the resource label subset is finding the document in the generation contract its currently generating an empty file
Tested locally
> fix: use all units by default on resource lables

- providers/shared/inputsources/mock/commandlineoption.ftl
Sets a fixed run Id for the mock input source overriding the shared runId which uses the randomly generated id
When deploying some resources we use the runId as part of the resource name to ensure that they are replaced on each update. Setting a fixed runId for the mock input allows us to test for the existing of these resources 
Tested locally
> fix(mock): set a fixed runId for mock

- providers/shared/components/userpool/id.ftl
Allow for OAuth to be disable on userpool clients
In some cases, such as aws identity pools you might want to create a cilent but not include the oAuth configuration. This allows for this to be controlled on a client by client basis.
Tested locally
> feat(userpool): control oauth on clients

- engine/commonApplication.ftl
Adds support for [docker based health checks](https://docs.docker.com/engine/reference/builder/#healthcheck) for tasks and services in the ECS component
This allows for an out of band process to evaluate the health of a container. ECS will use this information to determine if the task container is healthy or not. If it is not healthy then ECS will replace it. This is useful for tasks which aren't part of a load balancer or will always respond to TCP based health checks
Tested on an active deployment using a local install of hamlet
> feat(ecs): add healthcheck support

- engine/openapi.ftl
Remote quota throttling as only exists on a usage plan
Quota throttling is a client-side throttle, whereas component configuration is for server-side only.
As-yet untested, requires reimplementation of aws provider updates.
> fix(openapi): quota throttling only exists on a usage plan

- engine/engine.ftl
- engine/occurrence.ftl
Sets an explicit preference on how setting name spaces should be evaluated based on their matching patterns
With the following rules: 
- When provided with a list of prefixes the settings from the last prefix will win 
- Within a prefix exact matches are preferred over partial matches
This was found when trying to deploy a component that included a partial match to another component in the solution. As a result of this the exact setting defined on the deployment unit was being overridden by the partial match provided by the other component. 
While it was under a very weird context ( component deployment unit was the same as a tier Id ) this did highlight an assumed ordering of settings that wasn't implemented in the code.
Tested locally
> fix(settings): evaluation preferences for setting namespaces

- providers/shared/inputsources/composite/commandlineoption.ftl
Adds a secondary measure to determining if a definitions object should be `?eval`'d or not.
In a scenario where a Solution includes an `apigateway` for which the spec has not yet been built/deployed, template generation on the component can create a composite object for the "definitions" object that is not valid JSON but a string of the word `null`. This passes the initial check for string content but cannot be evaluated. It provides a particularly unhelpful error message that does not put the user on the right track to fixing the issue.
Local template generation prior to the build/deployment of an API spec.
> fix(apigateway): do not attempt eval if definitions full is null

- engine/common.ftl
Minor fix to handle a deployment unit not being found
Not all occurrences require deployment units so should return an empty string if it is not found. This also helps with troubleshooting misconfigured occurrences where the configuration hasn't been loaded or couldn't be found
Tested locally
> fix: handle no deploymentunit

- legacy/account/account_ecs.ftl
Implements https://github.com/hamlet-io/engine-plugin-aws/issues/123
Provides support for setting ECS account level settings which control account ( region ) wide services
AWS Details on the available services are available here: https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-account-settings.html 
As the settings are reasonably safe in terms of hamlet deployments we have chosen to enable all settings with the exception of container Insights which has a cost implication and can be controlled at the cluster level. 
Names of the settings that we support are based on the AWS cli definition of the settings - https://docs.aws.amazon.com/cli/latest/reference/ecs/put-account-setting.html 
AWS has had to introduce new functionality and potentially breaking changes to the ECS …
> feat: aws ecs account settings

- providers/shared/deploymentframeworks/default/output.ftl
Correct the output type for the pregeneration script
At present, because the output type doesn't match the way the content is generated, the file is empty.
> fix: Output type for pregeneration scripts

- engine/component.ftl
- engine/occurrence.ftl
Extends the global `componentConfiguration` object to allow for "Extensions". Extensions provide additional valid values to an existing shared provider attribute. 
Extensions are not merged into the current structure but remain separate until after the placement is determined for the current occurrence, and the correct extensions to use for a given occurrence is determined by the placement.
<details>
<summary>Testing Extending the Value Sets for the DB Component</summary>
<br>
```
[@addResourceGroupAttributeValues
type=DB_COMPONENT_TYPE
provider=AZURE_PROVIDER
extensions=[
{
"Names" : "Backup",
"Children" : [
{
"Names" : "DeletionPolicy",
"Values" : [ "notadeletionpolicy", "notreal"]
}
]            
},
{
"Names" : "Cluster",
"Children" : [
{
"Names" : "ScalingPolicies",
"Children" : [
{ …
```
> Feat - ResourceGroup Attribute Extensions

- engine/commonApplication.ftl
- legacy/fragment/fragment_hamlet.ftl
- legacy/fragment/fragment_jenkins.ftl
- providers/shared/components/ecs/id.ftl
Adds a collection of changes for ECS to allow for advanced configurations 
- Support setting the hostname for a container within a task
- Exposes volume driver configuration to users to use dynamic provisioning of volumes - mainly for the rexray/ebs volume 
- Support for overriding the container fragment Id when processing fragment files 
- Allows for override of the docker container image to align with the ability to override the image version 
- Adds support for placement constraints - Which allow you to restrict where a task is placed based on the labels assigned to either the ecs host or the task. For example attribute:ecs.availability-zone == ap-southeast-2a would only allow the task to be placed on an ec2 ecs host in ap-southeast-2a
This also adds support for [docker in …
> Ecs container advanced configuration

- client/createDeployment.ftl
- engine/openapi.ftl
A couple of minor fixes 
- Align the resource sets configuration with the updates made to the deployment group changes in #1149 
- When using the `disable` option for OptionsSecurity in the apigateway extensions add an explicit security object so that it doesn't inherit the default security configuration for the API
These fixes we found while working through a new deployment 
Tested on an active deployment
> Various fixes - Resource Sets, openapi

- providers/shared/components/component.ftl
Minor regression fix to align the changes in #1388  with the changes added in #1396 
New attributes added in one PR that wern't covered in a PR to move the container configuration to a new location 
Tested locally
> fix(ecs): add fragment and instance back to container props

- engine/openapi.ftl
Add an explicit value for the passthroughBehaviour attribute of mock API AWS openapi extensions.
Because of the way the mock request handling communicates with the response templates, we should never pass through a payload for a mock.
Customer deployment
> fix: Explicit mock API passthrough behaviour

- engine/common.ftl
- engine/commonApplication.ftl
- engine/occurrence.ftl
Minor fixes for #1402 
- Align function name for product lookup 
- Syntax fixes for trim functions ( freemarker != groovy :) ) 
Some minor fixes to existing changes which caused template generation to fail
Tested locally
> fix: syntax and variable name updates for build scopes

- engine/commonApplication.ftl
- engine/link.ftl
- providers/shared/deploymentframeworks/default/context.ftl
- providers/shared/deploymentframeworks/default/legacy.ftl
- providers/shared/deploymentframeworks/default/model.ftl
Link processing functions to force all values lower-case.
The requirement for lowercase is presently undocumented and unnecessary. Otherwise correctly-formatted links do not trigger errors, so template passes succeed, however they will be missing the intended permissions.
Local template generation and deployment.
> Link Direction Made Case Insensitive

- providers/shared/components/baseline/id.ftl
Adding `Replication` attribute and children to the `baselinedata` subcomponent.
The baseline databuckets are used to store common data such as logging information, which you may want to replicate for backups or to consolidate data elsewhere.
Required in order to test in a provider plugin.
> feat: add databucket replication attributes

- engine/common.ftl
Add ability to specify file patterns to be excluded during a sync operation.
Initial use case is for the lambda authorizer to be able to ignore the openapi.json file provided to it by the api gateway deployment.
> feat: s3 sync exclude support

- engine/entrance.ftl
- engine/provider.ftl
- providers/shared/deploymentframeworks/default/output.ftl
- providers/shared/entrances/entrance.ftl
- providers/shared/entrances/info/entrance.ftl
- providers/shared/entrances/info/id.ftl
- providers/shared/views/info/setup.ftl
- providers/shared/views/schema/setup.ftl
- providers/shared/views/view.ftl
Adds a new info view which is intended to provide details on the hamlet engine and the providers which have been loaded
The initial implementation includes two sections 
- Providers - which shows all providers that have been found along with the components and views they offer 
- Entrances - which provides a list of all entrances, a description of them and their command line options
The primary motivation behind this view is to be able to provide the available entrances to users either directly or through other tools so that they can find out entrances they can use to generate outputs
Tested locally
> feat: hamlet info view

- engine/common.ftl
- engine/openapi.ftl
Add explicit control over scope combining behaviour.
Also improve error detection when generating script files.
When combining openapi spec based security information with integration configuration security information, permit better control over the process used to combine scopes. The initial use case is for authorisers where scopes need to be removed to meet AWS constraints.
> fix: better control over scope combination

- engine/openapi.ftl
Allow the template used to generate api errors to be configurable.
This permits the way errors are reported to be aligned with any local standards.
> feat: API gateway error format control

- engine/openapi.ftl
Make check for type in header look for a generic string.
While the authorizer might want to enforce a stricter check on the authentication type, the API gateway should just enforce general HTTP syntax for this header.
> refactor: Generic check for type in authentication header

- providers/shared/flows/views/flow.ftl
A minor fix to define a primary Provider ( the first provider ) for looking up setup macros for views
A typo in the loading process would provide an array to lookups, this fixes this and makes it easier to understand
Tested locally
> fix: determine a primary provider to use for views

- engine/common.ftl
Minor fix to allow for network processing to continue when network endpoints aren't defined for a region 
Was currently stopping template generation when they couldn't be found
Tested locally
> fix: allow for undefined networkendpoints on a region

- providers/shared/flows/views/flow.ftl
- providers/shared/views/blueprint/setup.ftl
- providers/shared/views/info/setup.ftl
Correct ordering of use to align to macro definition
Any macros will need to have the deployment framework and entrance switched.
> fix: parameter ordering for invokeViewMacro

- engine/commonApplication.ftl
Adds support for configuring task placement constraints on ecs services 
ECS allows you to use constraints and strategies to define where a container is placed in your ECS cluster. Constraints are requirements which must met for the container to be placed, this can include rules such as the availability zone of the ECS Instance must be ap-southeast-2a, only when an ecs instance is available within this az will the container be started 
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-placement-constraints.html 
This is useful when you have an Highly Available cluster of independent services which form a cluster and you want to ensure that they are placed specifically as requsted
Tested locally
> feat(ecs): placement constraint support

- engine/bootstrap.ftl
- engine/provider.ftl
- engine/services.ftl
Adds support for a centralised definition of services and their resources configuration. The main functionality is the introduction of the `serviceResourceConfiguration` hash which accepts updates to sections of data within the structure based on the Provider, Service and Resource that you want to provide details about 
Sections allow for multiple sources of data to be added to a given resource, for example output mappings and diagram class mappings. This also allows for other providers to extend existing resources and services which might be implemented by another provider 
With the data in this structure it is also possible to search for the provider and service that a resource belongs to based on a first returned basis ( some resource names currently overlap within the same provider ). …
> feat: support for centralised service resources

- providers/shared/components/apigateway/id.ftl
New attribute on the `apigateway` component - LogToOpsData. A boolean value that defines whether logs are directed to the OpsData bucket or not.
Need to be able to consolidate logs somewhere. This allows the logs to be placed in a known location (ops data) where other profiles can handle the replication of data elsewhere if required.
* Ultimately the LogProfiles should be able to define such settings however currently they do not. Further discussion around how logging profiles should look need to be had before that could be implemented however, so this attribute is an interim measure.
Local template generation and deployment (alongside matching changes in the AWS provider plugin).
> Feature - APIGateway LogToOpsData

- client/invokeEntrance.ftl
- engine/component.ftl
- engine/provider.ftl
- engine/setContext.ftl
- providers/shared/entrances/deployment/entrance.ftl
- providers/shared/views/info/setup.ftl
- providers/shared/views/schema/setup.ftl
A collection of updates to the engine with the following changes 
- Moves the initialisation of contract outputs in the generationcontract subset to the invokeEntrance file. This allows for debug and error messages as part of the flow and entrance processing stages to be included in the generation contract and provided to users 
- As part of the invokeComponent macro process include a lookup for the deploymentFramework set via the commandLineOptions. This allows you to use a deployment framework lookup which is independent from the placement of the component. This is useful when using the component state from one provider and using a deploymentFramework from a different provider.
- Adds an IsLocal flag to the IP Address Group lookup, the isLocal flag is used to show network CIDR ranges …
> Various changes for providers and entrance setup

- engine/commonApplication.ftl
- providers/shared/components/component.ftl
Adds support for configuring ulimits on containers hosted as part of services and tasks 
For some applications the default ulimits applied to a container can restrict the performance of the service fileopen limits being a key ulimit here, this allows you to configure the ulimits for each container dependent on what is available from the container orchestrator
Tested locally
> feat(containers): ulimit configuration

- providers/shared/components/apigateway/id.ftl
- providers/shared/components/component.ftl
* Separated out the enabling of logging from the logging profile for the `apigateway` component and `WAF` configurations.
Note: I've used objects for the `apigateway` attributes because the intent is for providers to provide any further control they require at the provider level. A bool would not have been sufficient control here but any further configuration here will be provider specific.
The APIGateway provides several kinds of logs - Access Logs, Execution Logs and also WAF Logs. However they are not always able to be configured the same way. Separating out the concerns of "do you want logs?" from "where do you want them?" (`LoggingProfiles`) and creating an attribute structure likes this allows providers to add further control should they wish through namespaced attributes, whilst …
> feat(apigw + waf): separate logging enabled from logging profiles

- engine/base.ftl
Add support for the asterisk character as a substitute for 0.
Better aligns semver support to the equivalent node library.
Local testing
> fix: semver supports asterisk in range indicator

- providers/shared/components/shared/setup.ftl
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/provider.ftl
- providers/shared/references/DeploymentMode/id.ftl
- providers/shared/tasks/manage_deployment/id.ftl
Some additional updates to the management contract and deployment configuration
- Adds Operations to the deployment mode which allows a mode to specify what operations ( create, update, delete ) should be performed as part of the management step. This allows the information to be passed to deployment tasks such as manage stack or manage deployment 
- Adds the deployment provider to the contract step so that the executors can call the appropriate step to mange the deployment 
- Adds a default deployment mode to handle modes provided by the command line which don't have an explicit configuration - this is mostly for backwards compatibility with existing deployments
This allows for the management contract to be used to handle the generate and execution of deployments as part of the …
> feat: add operations and provider to mgmt contract

- engine/common.ftl
- engine/setContext.ftl
- providers/shared/components/component.ftl
- providers/shared/references/ComputeProvider/id.ftl
- providers/shared/references/reference.ftl
Adds support for defining compute providers as part of a solution deployment. While a processor profile defines the type of instance you want or how many, a compute profile defines how to source the processing/compute services to deliver the required resources 
The initial implementation for compute providers is on the ECS/ContainerHost component, on this component we can define the a compute provider and default strategy used when deploying containers onto this host 
A compute provider has two distinct configuration options 
* default provider - which offers the base level capacity and requires a minimum number of instances to be provisioned using this provider - this is used when you want to use a stable provider and a less stable provider 
* additional provider - Are weighted rules …
> feat(ecs): add support for compute providers

- engine/occurrence.ftl
- providers/shared/flows/components/flow.ftl
fix to include the instance and version details for components and
subcomponents. The cache wasn't accounting for the isntances of
subcomponents and as a result if you had two instances of a component
only the first subcomponent was included
Also reworks the caching to use the occurrence details instead of the
sources of the occurrence details
Caching was returning incorrect results for subcomponents where their parent component had multiple instances 
Tested locally and on active deployment
> fix: include int and version in occurrence caching

- engine/common.ftl
- providers/shared/components/lambda/id.ftl
Adds supporting for loading an external zip file as an image for a lambda function
The main motivation for this is to allow for images to be shared across multiple products without the need to rebuild the package each time. This is especially useful for utility lambda functions which are the same across multiple tenants and products
This concern was brought up as part of #1453 which outlines the need for this to support the portability of modules
tested locally and on testing deployment
> feat(lambda): pull images from external source

- legacy/account/account_console.ftl
Fix issue with console buckets created outside of the console stack 
Allows for buckets to be created outside of the account console deployment and instead referenced through a pseudo stack. This was supported in the rest of the template but not in this particular spot
Tested locally
> fix(console): allow for psuedo s3 buckets

- engine/common.ftl
- providers/shared/components/bastion/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/ec2/id.ftl
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/layers/Environment/id.ftl
Adds support for controlling OS patching through solution and environment layer configuration. The environment layer configuration has been included to provide compatibility  with existing configuration
In the AWS provider we currently have some hardcoded configuration which updates ec2 based instances on startup and creates a cron job for regular patching. This move allows for this to be configured and controlled by users. 
Tested locally
> feat: os patching in solution config

- providers/shared/components/component.ftl
Adds the ability to configure the number of successful instances in an autoscaling replacement 
When performing a rolling up date to instances, if any instance fails to update the whole update will be rolled back. This allows for the process to handle one off failures which will be resolved by a replacement of the instance without causing the whole update to fail
Tested locally
> feat: manage one off instance failures

- providers/shared/references/DeploymentMode/id.ftl
Minor fix to default configuration applied when a deployment mode could not be found
Currently the default deployment mode is always applying which means that the deployment modes aren't being used
Tested locally
> fix(reference): deployment mode default hanlding

- providers/shared/components/datafeed/id.ftl
Adds support for including deployment specific prefixes to the user defined prefix
Making paths globally unique for datafeeds is a requirement when creating consolidated data stores or having a path with identifiable details in it. This allows for these details to be injected in the datafeed deployment based on where the datafeed has been deployed
Tested locally
> Data feed deployment specific prefixes

- providers/shared/components/network/id.ftl
Adds the ability to define and create your own network flow logs. Logs can either be sent to s3 or a log, s3 being our current component type name for object store and log for the providers native logging service 
Users can create different flows for different actions which have been applied to the flow ( accept, reject, all ) and then route this to an appropriate destination. 
This deprecates the existing boolean flow logs configuration 
Flow logs can be used for a number of different purposes so allowing for them to be controlled and managed by the user makes sense 
tested locally and on development deployment
> feat(network): flow log control

- providers/shared/components/component.ftl
- providers/shared/components/secretstore/id.ftl
Some refactors and updates to the secretstore configuration
- Breakout the configuration into sections which can be used on other components - ideally this would be metaparameters in the future 
- A template section which allows for the creation of a json based secret with extra parameters ( username etc ) along with specifying a key where a generated secret would be stored 
- Rotation for components which handle secret rotation 
- The secret definition which defines the secret source and the policy required for the secret 
- Adds some extra policy conditions which were missed originally 
Some components require secrets to be provided as part of their deployment, they are also locked to the component so instead of making them subcomponents of the secret store it makes more sense to …
> feat(secretstore): update configuration and make it shareable

- engine/common.ftl
- providers/shared/components/component.ftl
Adds support for explicit alert metric dimensions defined as part of settings or solution configuration
When monitoring systems its common to create your own metrics based on business data which are stored in your monitoring system. This allows you to generate alarms on system infrastructure and business related events. Currently our alert support would only allow for defining metric dimensions based on component resources. As a result of this you couldn't create alerts based on business metrics which don't map to resources
Tested locally
> feat(alerts): get metric dimensions from blueprint

- engine/common.ftl
- engine/commonApplication.ftl
- providers/shared/components/component.ftl
service/task/containerservice/containertask implementation of https://github.com/hamlet-io/engine/issues/1486 
Allows for containers in tasks and services to specify a public docker image to use. On template generation the image will be pulled from the public registry and copied to the hamlet account docker registry. The image reference for the task is then updated to use this image
Simplifies the use of public container images which used to be pulled in via the manageDocker script and didn't specifically align with the public image ( we no store the digests of the images for traceability ) 
Also allows for container deployments to be included in plugins and modules without having to build the images for each usage of the module 
Tested locally
> feat(ecs): support container image sourcing

- legacy/account/account_roles.ftl
Minor fix to align with https://github.com/hamlet-io/engine/pull/1464 which renamed the AWSId value to ProviderId
Align with new naming, backwards compatibility handled higher up the chain
Tested locally
> fix: update for ProviderId migration

- engine/occurrence.ftl
Adds support for components with mixed case naming when handling settings namespaces
When processing settings the namespace the settings are added into is lowercased during the processing step. When using a component with mixed casing in its name it can process everything except access settings which are based on its component name. 
Tested locally
> refactor: support components with mixed case names

- providers/shared/components/component.ftl
- providers/shared/components/id.ftl
- providers/shared/components/queuehost/id.ftl
- providers/shared/inputsources/shared/masterdata.ftl
initial definition of the queuehost component which is aimed to support managed queue broker services such as AmazonMq from AWS. The initial implementation focuses on a rabbitmq broker which requires a single admin user and is managed as a dedicated instance of the broker
Queuehosts differ from a managed queue in that they are actually offering the hosting services to create any number of queues or associated services which can be defined as part of an application 
Tested locally
> Queuehost component

- providers/shared/extensions/dind/extension.ftl
Minor fixes to the dind extension following testing 
- Ensures the hostname doesn't contain _ characters which aren't supported 
- Sets that attributes for the dind images 
The image configuration in solution was removes and replaced with image sourcing the hostname is from the migration to extensions
Tested locally
> fix: dind hostname and image details

- engine/bootstrap.ftl
- engine/inputdata/blueprint.ftl
- engine/provider.ftl
Ensure overrides in the blueprint of the masterdata are not lost during assembly of the blueprintObject.
Previously, the merging of the masterdata with the blueprint caused changes to be lost. This fix introduces a new function to permit the blueprint to be rebased on the master data effectively ensuring that blueprint data takes precedence over master data.
Some comments were also added to the bootstrap process that need confirmation. If correct, then some of the bootstrap processing (currently commented out) can be removed.
> fix: masterdata inclusion in blueprint

- legacy/account/account_ses.ftl
- providers/shared/layers/Account/id.ftl
Add the ability to create account level resources for receiving emails. This covers the active ruleset and any IP filters applied to
incoming emails for the account.
The account configuration should be performed in the same region as will be used to configure the rules for inbound mail receipt. This is done by configuring the specific unit region in the Account object.
Because only one rule set can be active in an account/region, and rules are ordered by referencing the names of existing rules, there is a solution level configuration setting on the inbound mta to set the rule expected to exist.
> feat: account inbound ses configuration

- providers/shared/components/globaldb/id.ftl
Add additional configuration to support secondary indexes and keys with non-string types.
Project need to support more complex globaldb deployments.
Local template generations
> feat: globaldb secondary indexes

- providers/shared/components/s3/id.ftl
- providers/shared/extensions/s3vpcaccess/extension.ftl
An extension that provides access for publically available files in an s3 bucket from the VPC.
For one of the tenants, we faced the situation when SourIP condition wasn't working for accessing the publically available files from the docker containers running on ECS within a VPC, so SourceVPC condition needed to be added.
> feat(s3): add s3vpcaccess

- engine/common.ftl
- providers/shared/components/template/id.ftl
Adds image sourcing via URL to the template component
Adds a configuration option to the Url image source process to handle
content which hasn't been provided as a zip
This allows for directly sourcing a template file into a deployment instead of going through the build process. The standard build process is still supported. This is mostly for quick prototyping or for demonstration purposes
Tested on development environment
> feat(template): url image sourcing

- providers/shared/components/lambda/id.ftl
Minor fix to correct the type field on NewVersionOnDeploy which was set to string instead of boolean 
Types field wasn't being respected and now appears to be validating configuration 
Tested locally
> fix(lambda): correct type for Fixed code version

- engine/engine.ftl
- engine/openapi.ftl
Some minor changes to revert Type configuration on properties which weren't part of the getCompositeObject type updates in #1514 
The Type properties in this PR are not used during getCompositeObject processing so should still be kept as the singular Type to maintain compatibility with their usage
Tested locally
> fix: revert type updates

- engine/commonApplication.ftl
- providers/shared/components/userpool/id.ftl
Adds extensions and links to the AuthProvider sub component of a userpool
This allows for extensions to define the settings required to configure federation to be generated through code in extensions. This allows for links or other dynamically generated values
Tested locally and on development deployment
> feat(userpool): authprovider extensions

- providers/shared/components/spa/id.ftl
adds support for using a URL as the source of SPA. 
This allows for the use of published images that are avaialable from external sources
Tested locally
> feat(spa): image source from url

- providers/shared/tasks/create_schemas/id.ftl
- providers/shared/views/schemaset/setup.ftl
This refactor renames the task parameters from DeploymentGroup and DeploymentUnit for schema set generation to SchemaType and SchemaInstance. 
It also removes the deployment group filter applied when generating the schemaset contract and instead includes all possible schemas which can be generated. The contract executor can then filter and choose which contracts it would like to generate 
While we use the deployment group and unit parameters in create template to generate the outputs these values don't reflect what the task is actually trying to do, generate a schemaset contract which outlines the schemas that need to be generated
Tested locally using hamlet cli
> refactor(schemaset): align task attributes

- providers/shared/views/schema/setup.ftl
Create one schema definition per file output for the `reference` and `attributeset` schema types.
Schema generation was creating individual file outputs for each schema instance, but each output contained all definitions. This was occurring for both `reference` and `attributeset` schema types, though only obvious for the former as the latter only has a single instance.
Local schema generation.
> Fix - Schema Reference Data Outputs

- providers/shared/components/s3/id.ftl
defines configuration for creating inventory reports for the s3 component. 
Inventory reports list the contents of a nominated bucket and generate a listing of the contents
Tested locally
> feat(s3): add support for inventory reports

- providers/shared/components/s3/id.ftl
Use AttributeSet not linkChildrenConfiguration in s3 inventory reports configuration
This usage was missed due to commit sequencing.
> fix: link attributeset in s3 inventory reports

- engine/commonApplication.ftl
minor fix to variable scoping to ensure the context is updated when pulling an image from a registry
template generation when using the containterregistry image source for ECS was failing during template generation 
Tested locally
> fix: image url override for containerregistry

- providers/shared/flows/components/flow.ftl
Adds the Raw Id field for Version and Instance which uses the details from the CMDB or the default value. 
This is useful for user facing output that reads these files. in the CMDB when we have "default" as the instance or version Id its replaced with an empty string. This makes naming and output in deployment easier. But harder to align the whats in the CMDB with query commands
Tested locally
> feat: add raw ids for occurrence details

- providers/shared/inputsources/composite/stackoutput.ftl
- providers/shared/inputsources/mock/stackoutput.ftl
- providers/shared/inputsources/shared/setting.ftl
- providers/shared/inputsources/shared/stackoutput.ftl
- providers/shared/inputsources/whatif/blueprint.ftl
- providers/shared/inputsources/whatif/commandlineoption.ftl
- providers/shared/inputsources/whatif/definition.ftl
- providers/shared/inputsources/whatif/setting.ftl
- providers/shared/inputsources/whatif/stackoutput.ftl
Closes: https://github.com/hamlet-io/engine/issues/1535
- Creates a new input provider, the whatif provider 
- Refactors some of the input processing functions so they can be shared across providers 
The whatif input provider allows you to use a composite CMDB to create and query deployments before actually deploying the changes you've made in your CMDB
Input sources are primarily handled the same way as the composite input source except for StackOutputs. The whatif provider checks to see if a composite stack output can be found and if it can't then it will return a mocked output instead
This allows you to add components to a CMDB to see what they will create before deploying any of their required components. This is really helpful when generating diagrams or running through …
> feat: whatif input provider

- providers/shared/components/apigateway/id.ftl
- providers/shared/components/baseline/id.ftl
- providers/shared/components/lb/id.ftl
With the transition to attribute sets, a few instances of Links lost their `Subobjects` attribute resulting in current processing breaking.
Fixes #1544
Local generation of affected customer blueprint
> fix: Links as subobjects

- engine/bootstrap.ftl
- engine/logging.ftl
Add the ability to stop after a threshold number of fatal errors, as well as the option for a fatal error to always cause processing to stop.
The default behaviour reflects current behaviour where there is no limit so all fatal errors will be reported together.
When debugging complex behaviour, it is sometimes useful to know the state of processing at a particular point, especially when later processing throws a template error. This change permits a fatal error with `stop=true` to be added to know the exact state of variables etc.
The threshold behaviour allows for different user preference e.g. stop on first fatal error or permit multiple fatal errors to be recorded before processing stops.
Local deployments
> feat: Stop on fatal

- providers/shared/inputseeders/shared/id.ftl
This fix uses the unique combine configuration for providers to ensure that we build a list of providers instead of replacing it
the input seeder process uses the mergeObject command to apply state changes as required. When merging the mergeObject behaviour replaces arrays as its hard to merge an array
The main reason for this fix is to handle the update of the provider names command line options when loading plugins from a layer/blueprint. Previously this was being overridden with whatever the shared provider set the value to 
Tested locally
> fix: allow for loading provider input replacement

- providers/shared/inputseeders/shared/masterdata.json
- providers/shared/references/SecurityProfile/id.ftl
Adds the ability to specify the dead peer detection action when a Dead Peer Detection failure occurs as part of the vpngateway security profile
Support configuration of the VPN Gateway as part of hamlet deploy 
Implements: https://github.com/hamlet-io/engine/issues/1562 
Tested locally
> feat(gateway): add dpd action configuration

- providers/shared/components/userpool/id.ftl
Adds support for String or Number based constraints on user pool attributes. Primarily focussed around length and value in line with the support available for AWS Cognito.
These are pretty generic constraints so should flow on to other
providers
https://github.com/hamlet-io/engine-plugin-aws/issues/228 
Tested locally
> feat(userpool): add schema attribute constraints

- engine/logging.ftl
This PR fixes an issue with determining the log level when it isn't empty or set to debug
The log lookup process uses a list to map the string log level to a log
level number. Some entries in the list are empty to handle extra level
spaces.
When the string level is converted it used a startswith check which
considers an empty string as true rather than false
This PR ensures that the log level uses an explicit equals and also
checks that the item in the level list has content
Tested locally
> fix: handling of log level lookup

- providers/shared/components/component.ftl
Update Domain zone configuration 
- Remove mandatory flag from stem - this is only required for base zones 
- Add parent attributes to allow for zone chaining
Template generation failing
Tested locally
> fix: domain zone configuration

- engine/logging.ftl
- providers/shared/inputseeders/shared/id.ftl
Moves the timing log level in the engine below the info step
Currently the timing messages are being included in standard template outputs if the level is set
Tested locally
> refactor: change timing log level

- engine/component.ftl
- engine/occurrence.ftl
- providers/shared/components/shared/setup.ftl
- providers/shared/entrances/unitlist/entrance.ftl
- providers/shared/inputseeders/shared/masterdata.json
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/provider.ftl
- providers/shared/references/DeploymentGroup/id.ftl
- providers/shared/tasks/manage_deployment/id.ftl
- providers/shared/views/unitlist/setup.ftl
- providers/shared/views/view.ftl
Adds the ability to determine the current deployment state of a deployment unit
The following modes are supported:
- deployed - at least one resource can be found in occurrences which
belong to the deployment unit/group
- notdeployed - no resources could be found for in occurrences which
belong to the deployment unit/group
- orphaned - stack outputs exist for this deployment unit/group but are
corresponding deployment/group could not be found in active definitions
The deployment state is included in the managementcontract unitlist which allows for an executor to make decisions on how to manage its tasks based on the current state of the deployment
Its currently hard to know the state of any given deployment unit that has been made within hamlet. The only way at the moment is to look in …
> feat: deployment state reporting

- providers/shared/components/shared/setup.ftl
- providers/shared/deploymentframeworks/default/output.ftl
- providers/shared/entrances/entrance.ftl
- providers/shared/entrances/occurrences/entrance.ftl
- providers/shared/entrances/occurrences/id.ftl
Closes: https://github.com/hamlet-io/engine/issues/1577
- Adds a new entrance to provide information specifically around occurrences.
- Adds a new output which provides the state of each occurrence in the district. To remove repetition subocurrences are removed from any occurrence which has a sub occurrence
For occurrence queries in the python executor we use the blueprint output which is quite complicated to find all the occurrences. Providing a specific output makes it easy to query the occurrence details including finding suboccurrence details 
Tested locally
> feat: add occurrences entrance

- engine/setContext.ftl
- providers/shared/inputseeders/shared/masterdata.json
- providers/shared/inputsources/shared/masterdata.ftl
- providers/shared/provider.ftl
- providers/shared/references/DeploymentMode/id.ftl
Fixes: https://github.com/hamlet-io/executor-python/issues/83
Enforces the use of defined deployment modes
- Any deployment mode that is used must now be defined in the blueprint before they can be used
- Adds two common deployment modes hibernate, and maintenance which are used in existing deployment profiles
- Removes the default deployment mode and the fall back used when getting details
This provides better understanding of how deployment modes works and what the behaviour will be when they are used
Tested locally
> feat: validate deployment mode provided

- providers/shared/views/unitlist/setup.ftl
Some stackoutput files don't include the deployment unit in the stack output. This checks for empty deployment unit entries as we can't include them in the unit list processing
Safer handling of stackoutputs found in the list
Tested locally
> fix: handle empty deployment unit Ids unitlist

- providers/shared/flows/components/flow.ftl
Fixes #1584 
- Fixes an issue where subcomponents would report the rawId for the
component they belong to as their subcomponent details.
- adds the same details as a component in the subcomponent state
details. This ensures that this information is available as required
The RawId represents the Id or Name value as it was provided in the CMDB, this makes it easy to understand the source of a given configuration when using query tools and for performing troubleshooting.
Tested locally
- [X ] None of the above.
> fix: RawId and Name values for subcomponents

- providers/shared/provider.ftl
- providers/shared/tasks/manage_deployment/id.ftl
Add the CurrentState back into the contract output state and make it a mandatory task output since the python executor relies on it
Due to a merge conflict in another PR the current state was removed from the unit list output
Tested locally
> fix: regression in unitlist generation

- Jenkinsfile
- engine/setContext.ftl
- providers/shared/entrances/deployment/entrance.ftl
The introduction of validation for DeploymentGroups at runtime has
caused schema generation to fail. Unless a DeploymentGroup is defined
within a blueprint, the option is invalid as a commandLineOption.
This commit introduces definitions for the groups used for JSONSchema
generation - component, reference, module and attributeset.
It also adds schema generation into the Jenkins pipeline to act as a test for catching this sort of thing in the future.
#1576 
Locally - can now generate schemas the same as before introduction of #1576
> fix: define deploymentgroups for schemas

- Jenkinsfile
Removes the aws and azure providers from the mock schema generation
test
This removes external dependecies on the testing where they aren't required. Changes which are required in plugin repos generally depend on changes in the engine repo. So this essentially creates a dependency loop when changes have been implemented especially around refactors
Will test in PR
> fix: isolate testing to only include local code

- providers/shared/inputseeders/shared/id.ftl
Disable the qualifier transformer in input processing.
At present, solutions have been designed on the assumption that layer ids could be used as the basis for the qualification. The qualifier transformer currently only works on the layer names.
Once layers are better supported in the input processing, the transformer can be updated to include layer ids in the filter and the transformer re-enabled.
Local template generations
> fix: disable qualifier transformer

- providers/shared/references/Storage/id.ftl
Adds the ability to define a mount path for a volume this is used by config scripts to setup and mount a volume
This allows for the volume mounting to be managed as part of an ec2 instance startup. This allows users to define their volumes and where they get mounted 
Tested locally
> feat: adds mount path to volume config

- engine/output.ftl
- fix to account for entrances which use the deployment group as a parameter but don't have deployment group defined in the engine
- renames level_prefix to deployment_group_prefix to align with naming of deployment group
Deployment group and deployment unit have been used as a way to provide parameters to other entrances which don't use the engine defined DeploymentGroups. This uses the deployment group as a standard parameter in output formatting and only performs the lookup and translation where its required. 
Tested locally
> fix: output naming for deployment group prefix

- providers/shared/services/resource.ftl
Correct logic of `isPartOfCurrentDeploymentUnit()`
With the change to the input processing, correct use of `getStatePoint()` in `isPartOfCurrentDeploymentUnit()` to ensure behaviour of function is unchanged.
> fix: current unit detection

- providers/shared/inputseeders/shared/masterdata.json
Removes the startup script store from the masterdata. 
This base startup functionality is now part of the engine init scripts for the providers
Tested locally
> refactor: remove startup scripts from masterdata

- engine/extension.ftl
- engine/inputdata/inputsource.ftl
- providers/shared/deploymentframeworks/default/output.ftl
- providers/shared/inputseeders/shared/id.ftl
Support composite templates to be provided via a filename or via the content being directly included.
As part of moving to dynamic input loading, reliance on pre-assembled content needs to be removed. This change starts the process by using the `?interpret` builtin internally to avoid use of the `[#include]` directive if the content appears to be freemarker markup.
> refactor: composite template inclusion

- engine/inputdata/inputsource.ftl
- providers/shared/inputseeders/shared/id.ftl
When using the loader entrance to refresh the plugin state, no modules need be loaded as they are not needed to determine the plugins required.
Fixes #1615
Local configuration of plugins/modules
The following change needs to be committed for the engine change to take effect
> fix: loader module control

- engine/module.ftl
merges module input state instead of replacing on each invocation of the macro
This allows modules to run the loadModule macro multiple times to simplify modules and make them easier to follow
Tested locally
> fix: handle multiple load modules in module

- engine/entrance.ftl
- engine/inputdata/blueprint.ftl
- engine/inputdata/inputsource.ftl
- engine/output.ftl
- engine/output_writer.ftl
- engine/setContext.ftl
- providers/shared/components/shared/setup.ftl
- providers/shared/flows/views/flow.ftl
- providers/shared/provider.ftl
- providers/shared/views/info/setup.ftl
- providers/shared/views/schema/setup.ftl
- providers/shared/views/schemaset/setup.ftl
- providers/shared/views/unitlist/setup.ftl
Uses the loaded providers as the definitive list of providers that the engine is using for a given pass.
We currently have 2 ways of defining the providers used in a solution the command line options using the -p flag and the CMDB approach which defines the plugins to load which also act as providers
This loaded providers are based on what is found in the plugins along with the command line options used.  This ensures that the providers loaded through the CMDB are included in processing of entrances, and other functions within in the engine
Tested locally
> fix: use loaded providers as definitive providers

- providers/shared/components/apigateway/id.ftl
Adds support for specifying alternate image sources for apigateway
Also includes a none option which can be used in modules which specify the apidefintion and inject it as part of the blueprint processing
Allows for external sources to be used for API Gateway definitions which simplifies the build process and also removes unnecessary pregeneraiton scripts when they aren't required
Tested locally
> feat(apigateway): image sourcing support

- providers/shared/inputseeders/shared/id.ftl
Move the AWS format stack output handling to the shared provider.
The AWS format is also used for pseudo-stacks, so handle this format in the shared provider.
These need to be merged at the same time as this PR.
> fix: pseudo stacks

- engine/base.ftl
- engine/component.ftl
- engine/occurrence.ftl
Updates extensions to handle the addition of extra attributes under a shared attribute along with extra values.
Adds a generic function to prefix attribute names, values and defaults across a whole set of attributes.
Our current prefixing solution doesn't allow you to add new attributes under a shared attribute along and you can't pick and choose which values you support for a given attribute. This allows you to achieve both of these. 
The change has a little magic ( in the use of the prefix) but I think its straightforward enough to understand what is happening 
Tested locally
> feat: add attirbutes during extension processing

- engine/common.ftl
- providers/shared/attributesets/attributeset.ftl
- providers/shared/attributesets/operatingsystem/id.ftl
- providers/shared/attributesets/ospatching/id.ftl
- providers/shared/components/bastion/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/ec2/id.ftl
- providers/shared/layers/Environment/id.ftl
Adds the attributes required to configure the Image used for a virtual machine instance. This can be extended by providers to suit the available configuration options they offer
Part of #1488  Which allows for users to define their own virtual machine images on components as they need to 
Tested locally
> feat: add image configuration support for vms

- engine/output_writer.ftl
- providers/shared/inputseeders/shared/id.ftl
- Fixes an issue in the executor and engine definitions of the passAlternative value
- Disable a noisey debug statement
Alternative template generation was failing to generate different templates
Tested locally
> fix: align alternative config with gen contract

- engine/bootstrap.ftl
- engine/computetask.ftl
- engine/extension.ftl
- engine/provider.ftl
- providers/shared/components/bastion/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/ec2/id.ftl
- providers/shared/computetasks/computetask.ftl
- providers/shared/extensions/extension.ftl
Adds support for compute tasks and their usage through extensions. 
A compute task is defined by component developers and provide a description of the tasks which need to be completed in order for a virtual machine to work as part of a component. The component developer defines tasks and then includes a required list of tasks as part of the state of the occurrence.  
Users can then specify a list of compute task extensions which implement these tasks using the cloud configuration tools provided in the support of the provider and the virtual machine instance. If all of the tasks aren't implemented in the extensions the generation will …
> feat: compute tasks and extensions

- engine/attributeset.ftl
- engine/base.ftl
- engine/occurrence.ftl
Adds support for creating extended attribute sets, extended attribute sets allow for overriding attribute Values, Defaults and AttributeSets along with adding prefixed attributes if they aren't part of the attribute set used as the base. 
Attribute sets are really useful to share configuration and show that the same configuration is being used. However there are times when you might want to override default values at the provider level or add additional attributes across a provider. This allows you to do that and only add the overrides you require. 
Tested locally
> feat: Attribute set extensions

- providers/shared/components/component.ftl
Removes the option to configure wait for signal on autoscaling clusters. This should be enforced as part of our best practices
Removing this option and instead enforcing the use of status signals aligns with the idea of compute tasks and promotes best practice of handling failure in cluster startups 
Tested locally
> refactor: remove wait for signal on autoscaling

- engine/common.ftl
Include a couple of parameters in the certificate behaviour configuration definition that are supported by the code to permit a specific host name value to be used rather than assembling it from the component configuration.
Support existing product configurations.
> fix: certificate behaviour configuration

- engine/common.ftl
- providers/shared/components/bastion/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/ec2/id.ftl
- providers/shared/components/es/id.ftl
- Adds support for defining a storage profile to use through the solution configuration.
- Adds case insensitive matching for the component type when looking up the processor storage profiles
These appear to have missed before when we added profiles for processors and the other methods listed in the profile lookup process appear to have been removed as well. This aligns and standardises the configuration approach. 
Tested locally
> feat: add storage profile configuration

- engine/common.ftl
- providers/shared/components/baseline/id.ftl
- providers/shared/components/s3/id.ftl
- Sets a default storage profile name to handle components which don't have storage profiles configured
- Adds storage profiles to components which might use storage profiles in some providers
Makes the handling of default storage profiles easier and defines configuration requirements that were hiding 
Tested locally
> fix: default storage profile name

- providers/shared/attributesets/links/id.ftl
Add the MTA rule link attribute to the link attributeset.
S3 links to MTA rules are broken. 
> fix: mta rule link attribute

- engine/occurrence.ftl
- providers/shared/flows/components/flow.ftl
- Adds formatting based on the raw id and name values which don't split the id and name values based on - in the id
This ensures unique names and Ids can be generated for all occurrences as these values must be unqiue within the JSON structure of the data
Allows for ensuring there is a unique set of identifiers for each occurrence which is required for  https://github.com/hamlet-io/executor-python/issues/117
Tested locally
- None
- None
- None
> feat: add raw id and name formatting

- client/invokeEntrance.ftl
- engine/bootstrap.ftl
- engine/logging.ftl
- providers/shared/inputseeders/shared/id.ftl
Adds a compact log format to support including log messages as part template generation. This allows for logs to be generated and listed across entrances without flooding the console with information
When debug or fatal logs are found compact mode is disabled and the full log message is logged
Includes a log notes section when logs a written with the count of logs and a notice about the compact log format and how you can disable it 
This allows for logs to be included in entrance invokes that will be successful without flooding a console output with warning messages and their content. Instead just the log message is logged. 
Tested locally
- None
- None
- None
> feat: compact log format for console

- providers/shared/attributesets/links/id.ftl
- providers/shared/flows/components/flow.ftl
- Adds a warning message when an occurrence links to another target which hasn't been deployed
- Adds a link attribute property ActiveRequired which checks to see if the link to an occurrence has been deployed and raises a fatal exception if it can't be found.
implements https://github.com/hamlet-io/engine/issues/1652
This extends existing functionality in the link processing which components can use to throw fatal error on  links that haven't been deployed and allows users to define these dependences themselves. This ensures that components have everything they need to deploy 
While linking to an occurrence that hasn't been deployed is generally handled by the components it is still an potential issue. Raising a warning allows …
> feat: warnings and deployed link failures

- providers/shared/attributesets/alert/id.ftl
- providers/shared/attributesets/attributeset.ftl
- providers/shared/components/apigateway/id.ftl
- providers/shared/components/cache/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/db/id.ftl
- providers/shared/components/es/id.ftl
- providers/shared/components/externalnetwork/id.ftl
- providers/shared/components/lambda/id.ftl
- providers/shared/components/lb/id.ftl
- providers/shared/components/mobilenotifier/id.ftl
- providers/shared/components/queuehost/id.ftl
- providers/shared/components/sqs/id.ftl
- providers/shared/components/topic/id.ftl
Moves the alert configuration from a childConfiguration global variable to an attribute set
Cleaner usage and understanding of the configuration 
- None
- None
- None
> refactor: move alert config into attribute set

- providers/shared/components/healthcheck/id.ftl
Adds the health check component which is intended to implement the function of transaction monitoring on deployed components.
Two types of health checks have been defined: 
- Simple performs basic probe based checks against a provided destination and uses the port configuration to define basic probes
- Complex is a scripted health check intended to be run in a serverless compute environment and is capable of performing complex healthchecks with full synthetic transactions
Implementation of #1653 
Tested locally and confirmed that schema generates correctly 
- https://github.com/hamlet-io/engine/pull/1654
- None
- None
> feat: add healthcheck component definition

- providers/shared/views/blueprint/setup.ftl
Adds the multiAZ flag into the blueprint generation process which mimics the component flow. This should be replaced with a much nicer process though
Partial fix for https://github.com/hamlet-io/engine-plugin-aws/issues/280 
Gets around an issue with tasks that use the blueprint to get more information around the task to be completed.
- None
- None
- None
> fix: set multiAZ flag for blueprint generation

- engine/extension.ftl
- engine/occurrence.ftl
- providers/shared/references/ComputeProvider/id.ftl
- providers/shared/views/schema/setup.ftl
- Adds support for a disable prefix when extending existing values through attribute extensions. 
- Includes attribute extensions and the deployment provider during component schema generation to ensure that the schema aligns with what is available
This is primarily for backwards compatibility for provider specific values which didn't have the provider prefix. This allows the values to be migrated to the appropriate provider but still keep their non-prefixed value
Tested locally
- None
- None
- None
> feat: extend component schema

- providers/shared/components/component.ftl
- providers/shared/components/ecs/id.ftl
- Adds support for specifying the compute provider on the ecs service. When using compute providers the providers available depends on the engine. So we set the default provider to the provider recommended by the engine
- Removes vendor specific attributes from the container definitions and instead uses attribute extensions to define them in the provider
This configuration allows for services to specify the compute provider configuration that they require specifically allowing for different services within the same container host to be hosted using different strategies 
- None
- None
- None
> feat(ecs): add compute provider support on service

- engine/output.ftl
Add the logic to populate the region in filenames from the CMDB info if it isn't provided on the command line. 
This permits the omission of the assembly of the blueprint prior to running the engine.
Local template generation both with and without the CMDB plugin.
- None
- executor-bash - https://github.com/hamlet-io/executor-bash/pull/203
- None
> fix: region in filenames

- engine/inputdata/commandLineOptions.ftl
- engine/inputdata/inputsource.ftl
- providers/shared/entrances/deployment/entrance.ftl
- Expose a method for general use to request a refresh of the input state.
- Remove technical debt
The refresh method is used internally in the input source whenever the seeder configuration of the current input source is changed.
The new use case is for multi-pass processing where the configuration of seeders isn't changing, but the data provided by the seeder varies per pass, so it needs to request the input to be reassessed on each pass.
Also remove technical debt associated with the introduction of the input pipelines
- remove the global `commandLineOptions` variable and associated support as all command line option access should …
> feat: make refresh input state routine public

- client/invokeEntrance.ftl
- engine/output.ftl
- providers/shared/deploymentframeworks/default/output.ftl
- providers/shared/inputseeders/shared/id.ftl
- Adds a status field to contract steps to indicate  if they have already been run. Available values are completed, available and failed 
- Adds an output clear macro which is invoked between entrance passes to ensure the output isn't tainted between passes
- Adds support for adding entrancePasses during the generation contract pass. This allows for the engine to create extra outputs as part of the same call to create the generation contract
- refactors contract steps to allow for them to be passed to the entrancePasses as well as written to file
- removes command line input parameters which are managed by the contract input
The main …
> feat: extend multipass generation support

- providers/shared/components/component.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/ec2/id.ftl
Adds permissions configuration options for ec2 based components. 
With the ability to run user tasks this allows for flexibility in what you can do and what you can access in the tasks
- None
- None
- None
> feat: add base permissions for ec2 components

- client/invokeEntrance.ftl
- engine/commonApplication.ftl
- engine/inputdata/commandLineOptions.ftl
- engine/output.ftl
- legacy/account/account_console.ftl
- providers/shared/components/adaptor/id.ftl
- providers/shared/components/component.ftl
- providers/shared/deploymentframeworks/default/output.ftl
- providers/shared/tasks/process_template_pass/id.ftl
- Adds support for generation converters which allow for generating outputs based on one format and then have the output writer convert it to another one. The  primary usage for this is converting from json to yaml since the generated output is the same but just needs to be converted 
- Adds a more specific configuration option for alternative outputs to allow for applying alternatives to specific subsets instead of all of them 
- Adds a properties section to contracts which contain contextual level information that can be applied to all stages in the contract or provide executors with extra information 
- Refactors the …
> Yaml config contract properties

- engine/output.ftl
- providers/shared/deploymentframeworks/default/output.ftl
- providers/shared/entrances/deployment/entrance.ftl
Adds support for overriding the default subset handling for the templateSubset specfically 
When running the template subset the default subset value is an empty string except for resource sets which override this value to provide support for splitting out specific resources in template processing. This makes this option available to control in generation contract steps
Fixes a regression introduced in https://github.com/hamlet-io/engine/pull/1583
Tested locally
- None
- None
- None
> fix: set deployment unit subset for template

- engine/openapi.ftl
- providers/shared/extensions/extension.ftl
- Adds support for AWS VPC Links for apigateway as part of our openapi integration
- Adds the ability to provide openapi specification for an API as part of a fragment/ extension. This allows for providing or modifying a specification as part of a solution fragment or extension
VPC link allows for private load balancers to be used for backends which are hosted within a VPC. This makes the apigateway the only way for the endpoint to be accessed outside of the VPC 
Setting schema through context allows for creating simple openapi specifications inside of fragment files and removes the need to create build jobs or modules to provide api spec.
- None
- None
- None
> feat: openapi http endpoints and fragment

- providers/shared/components/computecluster/id.ftl
- Adds support for configuring the app image source for a computecluster
- Removes some explicit configuration options which are now covered by compute tasks and haven't been used
Implementation of https://github.com/hamlet-io/engine/issues/1486 for computecluster
Tested locally
- None
- None
- None
> feat(computecluster): image source configuration

- engine/common.ftl
- providers/shared/components/apigateway/id.ftl
Defines base level configuration for enabling mutualTLS on an apigateway component
mutualTLS is used to validate clients calling the apigateway as an authentication method and provides a standard way to provide authentication info.
Tested locally
- None
- None
- None
> Apigateway mutualtls

- providers/shared/components/id.ftl
- providers/shared/computetasks/computetask.ftl
Splits system volumes ( volumes defined as part of each instance ) from data volumes which are fixed volumes running as a standalone component
Data mounts are only supported on fixed instance components like the ec2 component as autoscale groups would fight for the volume. Splitting this allows for ec2 to require data mounts and other component types to ignore them 
Tested locally
- None
- None
- None
> refactor: add compute task for system volumes

- providers/shared/components/globaldb/id.ftl
Adds a definition of change streams to the global db component. 
When working with globaldbs its common to integrate them into event driven designs. The change stream provides a continuous stream of change notifications that a service can consume and perform actions on
Tested locally
- None
- None
- None
> feat(globaldb): define change stream support

- engine/common.ftl
- providers/shared/components/adaptor/id.ftl
- Adds support for adaptors to have attributes based on the pseduo stack outputs created within the adaptor 
- Fixes an issue with the syntax of the sync file command 
- Adds a conditional on file copying to make sure that the file exists
Attribute support allows for the adaptor to be integrated with other components that rely on attributes easily 
- None
- None
- None
> feat: adaptor attributes

- providers/shared/components/mobileapp/id.ftl
Adds support for configuring the image source on mobile apps. Allows for Urls or the standard registry
Implementation of #https://github.com/hamlet-io/engine/issues/1486 which allows for using external images for application components
- None
- None
- None
> feat(mobileapp): add support for image config

- providers/shared/components/contentnode/id.ftl
Adds support for using external zip images for content nodes
Implementation of https://github.com/hamlet-io/engine/issues/1486 which aims to provide better integration for image sources 
- None
- None
- None
> feat(contentnode): add support for image sources

- providers/shared/components/datapipeline/id.ftl
Adds the ability to use an external url for datapipeline image sourcing 
Part of https://github.com/hamlet-io/engine/issues/1486
This allows users to manage images outside of hamlet while still using our deployment process as required 
Tested locally
- None
- None
- None
> feat(datapipeline): image source configuration

- providers/shared/components/dataset/id.ftl
Adds support for defining an external image for dataset components
Allows for external management of images and aligns with https://github.com/hamlet-io/engine/issues/1486 
Tested locally
- None
- None
- None
> feat(dataset): adds support for image config

- legacy/account/account_ses.ftl
Set the active inbound SES ruleset.
Fixes https://github.com/hamlet-io/engine-plugin-aws/issues/318
While a ruleset can be created via cloud formation, setting which ruleset is active can only be done via the CLI.
- https://github.com/hamlet-io/executor-bash/pull/219
- None
- None
> feat: set SES inbound active ruleset

- providers/shared/attributesets/attributeset.ftl
- providers/shared/attributesets/containertask/id.ftl
- providers/shared/components/component.ftl
- Extends ecs placement strategies to support different possible options and makes the strategy a list to allow for using multiple strategies combined 
- moves the container definition to an attribute set to highlight consistency and align with new approaches
This provides flexibility in defining host container hosts are chosen and can be useful when reducing costs vs ensuring redundancy 
Tested on development deployment 
- None
- None
- None
> feat(ecs): extend placement strategy support

- providers/shared/components/bastion/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/ec2/id.ftl
- Adds the ability to configure the management ports for instances deployed as part of components. This accommodates other instance types or OS types that don't just use ssh
- Adds the ability to configure the startup timeout for ec2 provisioning 
- 
Extend the support for other operating systems including windows which uses RDP instead of ssh for management
Tested locally
- None
- None
- None
> feat: add management port configuration to compute

- engine/base.ftl
- engine/inputdata/layer.ftl
- engine/logging.ftl
- providers/shared/inputseeders/shared/id.ftl
Re-enable qualification as a step in input processing.
Fixes #1599 
Support qualification across all forms of input. Reverses https://github.com/hamlet-io/engine/pull/1600
For backwards compatibility, ensure input qualification checks for ids and names of layers. Best practice should be to encourage the use of names and long form qualification but a number of existing cmdbs use ids and short form qualifiers.
This PR also adds some longer form alternatives for the `info` and `warn` macros, as well as an alternative `fatal` macro which always stops processing.
- None
- AWS - https://github.com/hamlet-io/engine-plugin-aws/pull/325
- Azure - …
> feat: input qualification

- engine/base.ftl
- engine/common.ftl
- engine/setContext.ftl
- providers/shared/flows/components/flow.ftl
Remove explicit handling of qualification as it is now performed by the input pipeline.
- simplify overall code base by isolating qualification to one place
- make qualification available on any config in the cmdb
- qualification is recursive so the value of one qualifier can itself contain further qualification 
- AWS - https://github.com/hamlet-io/engine-plugin-aws/pull/325
- Azure - https://github.com/hamlet-io/engine-plugin-azure/pull/260
- None
- None
> refactor: remove explicit qualification support

- engine/common.ftl
Correct call to `getDomainObjects` to remove qualifier support.
Tests failing
Should have been detected as part of testing https://github.com/hamlet-io/engine/pull/1696.
AWS test suite run locally and confiurmed that exception no longer being raised.
- None
- None
- None
> fix: getDomainObjects parameters

- engine/common.ftl
- engine/setContext.ftl
- providers/shared/components/bastion/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/ec2/id.ftl
- Adds a standard function and process for looking up profiles assigned to components
Profiles essentially have two lookup configurations
- Typed: which breaks the profile into typed sections within a profile. This is generally based on the component type or the tier component name of a component
- Explicit: which applies the same profile to all components
The generic function supports both types and uses the lookup process to find the appropriate profile
- Adds some additional profiles found during this update to the ec2 components
- Removes some of the global variables from setContext to reduce the scoping issues with global vars
When …
> refactor: standardise profile lookups

- engine/common.ftl
Adds fatal exception handling for profiles that cannot be found instead of falling to a default. This provides better feedback in development and for users
This change makes profile handling more robust and also provides feedback to users 
- None
- None
- None
> fix: handle missing profiles

- engine/inputdata/inputsource.ftl
removes an append configuration applied on the input pipeline cache that was causing issues with blueprint merging when arrays are used
When adding solution configuration which overrides a masterdata array the arrays were combined instead of merged/replaced
Tested locally
- None
- None
- None
> fix: merge config from input seeders by default

- providers/shared/attributesets/attributeset.ftl
- providers/shared/attributesets/volume/id.ftl
- providers/shared/references/BootstrapProfile/id.ftl
- providers/shared/references/LogFileProfile/id.ftl
- providers/shared/references/Processor/id.ftl
- providers/shared/references/Storage/id.ftl
- adds explicit attributes for the typed profiles that align with component type values along with the older cased values that are used in the existing profiles
- adds an attribute set for volume configuration that is used across the different component type storage profiles
This makes it easier to configure profiles and makes it easier to understand what is available when configuring the profiles
Tested locally and with aws and azure provider test suites 
- None
- None
- None
> refactor: set explicit typed profile attributes

- providers/shared/attributesets/volume/id.ftl
- providers/shared/references/Storage/id.ftl
- Fixes the attribute set configuration for volumes
- Sets a specific profile for elasticsearch which supports a limited subset of volume configuration
Fixes https://github.com/hamlet-io/engine-plugin-aws/issues/338 
The volume configuration wasn't being applied properly due to the incorrect implementation of the Volume attribute set reference
- None
- None
- None
> fix: storage profile volume configuration

- engine/common.ftl
moves the assemble settings function call for registry pulls into the functions used in pregeneration. This allows the pull function to be used for other purposes
This allows the bash function to be used as a more general image management tool 
tested locally
https://github.com/hamlet-io/executor-bash/pull/229 
- None
- None
- None
> refactor: only assemble settings in pregen

- .github/workflows/testing.yml
Adds the engine dir as the workspace when running testing. This ensures that the local contents are being used instead of the latest version
stops issues where changes are made to the engine that need to be tested
Will be tested by this PR
- None
- None
- None
> fix: use workspace for engine dir

- legacy/account/account_console.ftl
- legacy/account/account_ecs.ftl
- legacy/account/account_s3.ftl
- legacy/account/account_sms.ftl
- legacy/account/account_volumeencrypt.ftl
Replace references to the command line option `region` with references to the `regionId` global variable set in setContext.
There is a mix of use of `region` and `regionId` reflecting the fact that the composite assembly process initialises `region` while
`getContext` populates regionId.
With dynamic loading, references to region need to be made more dynamic so removal of direct references to the input value is the first step in preparing for this.
Once all known uses are modified, the variables used to pass in the layer values will be changed which will hopefully flush out any unidentified uses via null/missing exceptions.
The change is straightforward but the most efficient way to confirm is …
> refactor: remove direct references to region

- engine/occurrence.ftl
- providers/shared/attributesets/links/id.ftl
- providers/shared/flows/components/flow.ftl
Introduce a `SubComponent` attribute on links that will replace the use of component type specific link attributes. For now, either will work.
Also expand the checking of component types and the use of the `Type` attribute, particularly as a check on the type of the expected link target and to differentiate between subcomponents with the same id
but different types.
During testing, a bug was discovered in the cacheing of occurrences which wasn't type aware. This has been added to support the subcomponent linking changes.
- avoid an ever growing list of subcomponent attributes
- more stable link schema
- aligns with 
- None
- None
- None
> feat: subcomponent linking

- engine/inputdata/inputsource.ftl
- engine/inputdata/layer.ftl
- engine/module.ftl
- engine/output.ftl
- engine/provider.ftl
- engine/setContext.ftl
- providers/shared/components/shared/setup.ftl
- providers/shared/inputseeders/shared/id.ftl
Permit the use of qualification within layer data.
Rework the handling of layers to permit their data to provide the filter inputs (Id, Name) to their own qualification.
Layer data is processed once to work out the values to use when filtering it, then a second time to work out the effects of qualification on the remaining configuration data.
As part of the refactoring, the active state of layers in now part of the input state and calls to `getActiveLayers` now returns the data in the input state.
Readiness preparation for [ADR0007](https://github.com/hamlet-io/architectural-decision-log/blob/main/adr/0007-placement-support.md)
Fixes #1714 …
> fix: qualification of layer data

- providers/shared/components/template/id.ftl
- adds support for defining suffixes on outputs pulled from nested templates
Adding suffixes allows for outputs from multiple resources within the template into hamlet outputs. Since templates can range in complexity this allows for broader support for collecting outputs
- None
- None
- None
> feat: template output suffixes for mapping

- providers/shared/components/shared/setup.ftl
Adds lookups for suboccurrences when generating testcases. The current setup was only generating test for the Occurrence and skipped the Occurrences it had
Tests generated for a deployment unit which had components and subcomponents wouldn't generate tests if only the subcomponent had tests defined 
Tested using the aws test suite
- None
- None
- None
> fix: include suboccurrences when generate tests

- engine/inputdata/inputsource.ftl
- engine/module.ftl
- providers/shared/inputstages/commandlineoptions/id.ftl
- providers/shared/inputstages/layer/id.ftl
Refactor input processing to permit access to command line options and layers during input processing. 
For some stages of input stages, the state to that point is saved into the global state, and input state accessor routines have been made aware of whether input processing is in progress in order to use this staged state.
Access to layer information is commonly used in extensions and modules.
- None
- None
- None
> refactor: clo/layer access during input processing

- providers/shared/entrances/deployment/entrance.ftl
- providers/shared/inputseeders/shared/masterdata.json
- providers/shared/provider.ftl
- providers/shared/references/DeploymentGroup/id.ftl
- providers/shared/tasks/manage_deployment/id.ftl
- providers/shared/views/unitlist/setup.ftl
- providers/sharedtest/inputseeders/sharedtest/id.ftl
- Adds a district property to deployment groups to scope the deployments included as part of the group
- Includes district details in the management contract
- Includes all deployment groups in the management contract instead of filtering on those that have created outputs
- Adds support for resource sets that do not act as subsets and instead are treated as standalone deployment units
- reorder default deployment group priorities to accommodate other groups
This allows for discovering and listing all available deployments across the hamlet districts and to select which ones you want to use
Tested locally and on development environment
- None
- None
- None
> feat: set districts for deployment groups

- engine/extension.ftl
Remove the direct processing of fragment files.
Input processing now includes fragments in the input state for both composite and dynamic cmdb processing. Currently for composite processing, the fragment is processed twice which can result in errors if the fragment logic is not idempotent.
- None
- None
- None
> fix: duplicate fragment processing

- engine/openapi.ftl
Don't include top level security attribute for openapi 2
AWS previously ignored any global security attribute but now throw an error for openapi 2. They don't throw an error in openapi.
- None
- None
- None
> refactor: remove global security for openapi 2

- providers/shared/components/shared/setup.ftl
fixes an issue when subcomponent deployments have different deployment units or groups defined and test cases were created across all units
Test cases are generated based on deployment outputs so when dealing with components which have multiple deployments all test cases were being included across the different deployments. As a result the test cases would fail when checking for content
Tested locally
- None
- None
- None
> fix: handle tests across sub components deployment

- providers/shared/tasks/install_plugin/id.ftl
fixes the attributes value provided to the install_plugin task
Plugins now use an attribute set so we need to access the attribute set Attributes to align with the plugin install tak 
Tested locally
- None
- None
- None
> fix: get attributes from plugin set

- engine/module.ftl
Allows for calling loadModule multiple times within a given module. 
This is often used to make modules cleaner from a readability side and to isolate sections of the module
- None
- None
- None
> fix: allow for multiple module loads in input processing

- engine/common.ftl
When a domain hasn't been defined on products handle the missing domain and leave the component to determine how to handle it
This allows you to use minimal configuration when deploying a product and rely on cloud provider hostnames if that is possible
Tested locally
- None
- None
- None
> fix: handle missing domains on products

- engine/base.ftl
- providers/shared/attributesets/attributeset.ftl
- providers/shared/attributesets/maintenancewindow/id.ftl
- providers/shared/components/cache/id.ftl
- providers/shared/components/db/id.ftl
- providers/shared/components/queuehost/id.ftl
Standard date manipulation functions added
Standard MaintenanceWindow child added to RDS
Precondition for PR to address https://github.com/hamlet-io/engine/issues/159
Locally
- None
- TBA
- Functionality to be supported within provider plugins for MaintenanceWindow
> Add standard date functions and (optional) MaintenanceWindow to RDS

- engine/inputdata/inputsource.ftl
- engine/module.ftl
- providers/shared/inputseeders/shared/id.ftl
- providers/shared/views/unitlist/setup.ftl
Permit the use of a "marker" value of `hamlet:empty` to signify that the value of a stack output should be an empty string. 
The marker value is converted to lower case so any preference for casing can be used - all lower case recommended.
Correct several bugs related to the handling of fixture and mock stack outputs, mainly related to appending rather than merging stack outputs.
Note that when providing mock stack outputs, Account, Region, and DeploymentUnit must also be provided e.g.
```
stackOutputs=[
{
"Account" : "0123456789",
"Region" : "mock-region-1",
"DeploymentUnit" : "aws-cdn-spa-base",
"cfXwebXcdnspabase": "hamlet:empty"
}
]
```
Fixes #1753 
This is used during …
> fix: permit the mocking of empty values

- providers/shared/components/apigateway/id.ftl
- providers/shared/components/cdn/id.ftl
- providers/shared/components/filetransfer/id.ftl
- providers/shared/components/lb/id.ftl
- providers/shared/components/mta/id.ftl
- providers/shared/components/userpool/id.ftl
adds an alternate name on all Certificate Configuration sections as Hostname.
This aligns more with the configuration that the configuration offers to the user with the Certificate lookup we perform within the engine a consumer of this configuration
tested locally
- None
- None
- None
> refactor: add Hostname as an alternate to Certificate

- engine/setContext.ftl
adds support for including the zone id as part tier based lookups. If the zone Id is included IPAddress group only that zone tier subnet will be returned
This is allows for finding zone based subnets when deploying zone based resources 
Tested locally
- None
- None
- None
> feat: adds zone based lookup for tiers

- engine/base.ftl
- engine/openapi.ftl
At present, the name wildcard processing of `getCompositeObject()` uses freemarker object addition. This means that only one object can contribute the content for any top level attribute.
This change replaces this with the use of `mergeObjects()`. The change will only affect top level attributes with an object value. The effect is that multiple input objects can contribute to the overall value.
A small documentation update for openapi processing is also included.
The driver for the change is the use of modules to provide default settings content which can then be supplemented with explicit settings, an example being the provision of default api gateway integrations in a
module.
Local template …
> refactor: wildcard behaviour of getCompositeObject

- engine/base.ftl
Treat qualifier filter values as regex. 
This will work as normal for fixed values but gives more succinct expression of more complex scenarios.
Local templates generation
- None
- None
- None
> feat: Support regex in qualification filters

- engine/base.ftl
- providers/shared/attributesets/links/id.ftl
- providers/shared/flows/components/flow.ftl
- providers/shared/layers/Product/id.ftl
- providers/shared/layers/Solution/id.ftl
- providers/shared/layers/Tenant/id.ftl
Initial implementation of `linkRefs`.
The actual implementation logic was quite straight forward. It uses recursive logic so nested linkRefs is supported, with detection of circular dependencies included.
A subset of layers currently support the `linkRefs` attribute but adding other simply requires the attribute being added to the layer definition and the layer included in the appropriate place in the layer priority order.
Part of [ADR-0007](https://github.com/hamlet-io/architectural-decision-log/issues/15) implementation.
Also a useful way for modules to expose link based functionality without the consumer needing to know the internal details.
- None
- None
- None
> feat(linkref): initial implementation

- engine/base.ftl
- providers/shared/components/network/id.ftl
- providers/shared/flows/components/flow.ftl
Correct a bug when annotating the result of qualification where it was not handling empty strings correctly.
Also remove some redundant config for DNSQuery logging, and correct the formatting of raw names.
Increased use of qualifiers surfaced the issue when an empty string was the desired value of an attribute under some circumstances.
- None
- None
- None
> fix: annotated qualification

- engine/common.ftl
- providers/shared/components/baseline/id.ftl
Replace use of component specific keys in links with the more generic "SubComponent" attribute.
Component specific link attributes are deprecated.
- None
- None
- None
> refactor: use SubComponent in links

- providers/shared/components/component.ftl
- providers/shared/components/correspondent/id.ftl
- providers/shared/components/firewall/id.ftl
Adds the definition for a correspondent component such as AWS Pinpoint
This allows creating a component for marketing communication such as push, email or SMS notifications
Schema generation testing
- None
- hamlet-io/engine-plugin-aws#391
- None
> feat: add a correspondent component

- engine/occurrence.ftl
- providers/shared/flows/components/flow.ftl
- Adds a check to see if linked occurrences are in the same deployment and doesn't raise a warning if they
- Adds an extra check to see if the occurrence is enabled or not and raises a warning if it is
Removes warnings that can't be fixed ( i.e. an occurrence that is being deployed at the same time as the linking occurrence ) and makes it more obvious why a link had an issue
Tested locally
- None
- None
- None
> refactor: warnings for occurrence links

- providers/shared/components/component.ftl
- providers/shared/components/firewall/id.ftl
adds support for firewalls to add routes into existing route tables using their destination sub component
Allows for firewalls to follow the same pattern that we have in place for gateways where they offer their destinations to route tables
- None
- None
- None
> feat(firewall): routing destination support

- engine/occurrence.ftl
- providers/shared/flows/components/flow.ftl
Add support for Locations on ResourceGroups as a means to determine the placement of resources.
Part of [ADR0007](https://github.com/hamlet-io/architectural-decision-log/blob/main/adr/0007-placement-support.md) implementation.
When determining placements, the resource group id is used as the Location to find the corresponding placement information,
so this means the ids of all resource groups need to be known BEFORE location information is checked.
As a result, when adding a component, any possible resource groups that an implementation might want to use must be
defined. This means that a provider implementer cannot add additional resource groups not already defined when the component was defined.
The existing placement profile …
> feat(locations): location support

- providers/shared/components/user/id.ftl
Removes the required values for the encryption scheme so that it can be controlled by users as required
The current value only allowed one value which wouldn't work and removed the ability to configure it
Tested locally
- None
- None
- None
> fix(user): remove scheme restriction

- providers/shared/flows/components/flow.ftl
Ensure a link that targets a suboccurrence only returns the occurrence containing the suboccurrence.
Link processing not working as expected
- None
- None
- None
> fix: link matching to suboccurrences

- engine/inputdata/commandLineOptions.ftl
- engine/inputdata/district.ftl
- engine/inputdata/layer.ftl
- providers/shared/components/baseline/id.ftl
- providers/shared/entrances/deployment/entrance.ftl
- providers/shared/inputseeders/shared/id.ftl
- Documentation (new or update to existing)
Add functionality to support pushing and popping of districts onto a stack.
The PR also picks up a few minor fixes/doco updates that have been discovered during district testing.
Part of [ADR0007](https://github.com/hamlet-io/architectural-decision-log/blob/main/adr/0007-placement-support.md) implementation.
This functionality will be used in future commits as more of the district support is rolled out. District support is being introduced as a series of small PRs as it involves quite a few changes overall and use of small changes will make it easier to review.
Local template execution.
- …
> refactor: district support

- providers/shared/components/directory/id.ftl
Sets the default IP Access control to the local network. The default policy was using public access
Aligns with standard security policies to ensure the 0.0.0.0/0 is only used when required 
- None
- None
- None
> refactor(directory): set default ip access policy

- providers/shared/components/lb/id.ftl
- Adds support for defining conditions on lb ports to allow for more complex routing of requests received by an HTTP based load balancer
Complex routing for load balancers
Tested locally with AWS provider
- None
- None
- None
> feat(lb): condition support for lb ports

- providers/shared/components/shared/setup.ftl
- providers/shared/references/TestCase/id.ftl
- Extends the cfn-lint structure to support ignoring checks
- Updates the name to align with the tool name rather than a different structure
- Adds support for checkov as a testing tool with support for both arm and cloudformation
- Removes support for CFNNag as it has been removed from the cli
These changes are aimed at making testing easier to use and removes the need for additional software installation that was required for the cfn_nag tooling 
- None
- None
- Anyone currently using `CFNLint: true` will now need to use `cfn-lint: {}` instead
- All use of `CFNNag` in testcases will need to be replaced with the appropriate …
> feat!: extend testing tooling

- providers/shared/components/cdn/id.ftl
Adds the links attribute to CDN routes. This was expected to be in the AWS cdn route setup but was missing
Setup processing expected links to be defined on routes
- None
- None
- None
> fix(cdn): include links in route config

- engine/setContext.ftl
Fixes an issue where the contains match that was used was causing false reports of isOpen cidr ranges.
When using 10.0.0.0/16 it treated this as open where 10.2.0.0/16 was treated as closed. Given that there are only really two cidr options for open have changed it to an == match
- None
- None
- None
> fix: hanlding of 0/0 cidr in ip addr groups

- providers/shared/components/externalnetwork/id.ftl
- Adds support for defining the SharedKey used for ipsec negotiation
- Adds support for defining the internal IP used for BGP peering across a vpn connection
Extends external network connection configuration to align with other VPN providers 
- None
- None
- None
> feat(externalnetwork): SharedKey and BGP Peer

- engine/setContext.ftl
- providers/shared/references/IPAddressGroup/id.ftl
- Adds support for referencing inbuilt named prefix groups in IPAddressGroups
- Defaults group to closed when handling missing tier configuration - mostly a security best practice thing
In providers like Azure there are a collection of Prefix references that map to Azure Services or Generic IP Collections ( Internet, VirtualNetwork etc. ). When using them in Azure they can be used in the same places that CIDR ranges can be used. 
This aligns the concept of the Named prefix groups with our IPAddress Groups 
Tested locally
- None
- None
- None
> feat: add named ip address groups

- engine/commonApplication.ftl
- providers/shared/components/component.ftl
- providers/shared/components/fileshare/id.ftl
- Renames the efs component to fileshare with backwards compatibility for the current type id of EFS
- Adds extended properties to support broader fileshare components
This makes the naming align to the solution level component rather than a particular provider implementation 
Tested locally
- None
- None
- None
> refactor(efs): rename to fileshare

- providers/shared/attributesets/maintenancewindow/id.ftl
- Add maintenance defaults to ensure that a standard window is applied
Currently when no option is defined different AWS services set different windows 
Tested locally
- None
- None
- None
> fix: set maintenance window defaults

- providers/shared/inputseeders/shared/masterdata.json
- Adds winrm ports to masterdata as a standard port for windows remote management
Allows for the ports to be embedded in component deployments 
- None
- None
- None
> chore: add winrm ports to masterdata

- engine/common.ftl
- Handles scenarios where the deployment unit value is null or empty with the move to only include the attribute when required
Exceptions being thrown when deploymentUnit properties were empty when they were required
- None
- None
- None
> fix: handle missing deployment unit

- providers/shared/components/topic/id.ftl
Add filter policy to topic subscriptions
New child attribute of Filters for Subscriptions
Required for https://github.com/gs-dawr/exdoc-mail-aws/issues/49
Local generation, not deployed to AWS
- None
- None
- None
> feat: add filter policies to topic subscriptions

- providers/shared/components/component.ftl
- providers/shared/components/topic/id.ftl
- Adds support for links on topics
- Adds migration attribute on topics when working with S3 notifications
- Links for topics allows for topic level permissions and actions to be created 
- The migration process creates user action on moving from defining queue policies 
- None
- None
- None
> feat(topic): add link support and policy migration

- engine/component.ftl
- engine/occurrence.ftl
- providers/shared/deploymentframeworks/default/output.ftl
- providers/shared/views/info/setup.ftl
- providers/shared/views/schema/setup.ftl
- Adds a standard component function for assembling the attributes of a component
- Adds a base get function for all component configuration
- Use the standard attribute configuration for schema generation
- Adds support for including component type configuration as part of the info view
Ensures that a standard representation of the components attributes can be generated when required
Tested locally and with https://github.com/hamlet-io/executor-python/pull/260
- None
- None
- None
> feat: component type info

- engine/commonApplication.ftl
- providers/shared/extensions/extension.ftl
- Adds the SecretEnvironment macro for extensions which allows for defining a secret whose value will be injected into a container at runtime
- Adds link handling to determine the secret and provide environment separation and permissions
This allows for secrets to be secured and injected into containers as they start. Removing the need for the container to handle decryption of secrets but still keeping things locked down 
Tested locally
- None
- None
- None
> feat(ecs): add support for secrets in containers

- engine/commonApplication.ftl
- providers/shared/attributesets/attributeset.ftl
- providers/shared/attributesets/secretstring/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/db/id.ftl
- Adds definitions for database root credentials and includes a new source of secret store
- Creates an attributeset used to define generation rules for secret strings 
- Adds support for looking up Db secrets when using SecretEnvironment macros
This allows for using secret stores when configuring databases as an alternative to using encrypted strings or settings
Tested locally
- None
- None
- None
> feat: db secret store support

- providers/shared/components/datafeed/id.ftl
Add the ability to include the year, month, day and hour in the prefix.
While the time path is added automatically when not using partitioning, it must be explicitly added when partitioning is used.
- None
- None
- None
> feat(kinesis): Prefix time path control

- providers/shared/components/datafeed/id.ftl
Add ability to explicitly include error type in prefix.
This only applies to the error prefix. For partitioning the error type must be present in the error prefix.
The error type has been put after the time path to maintain consistency with the good data path. Investigations also tend to focus on what happened at a particular time so having the error types after the time path collects all error types under a single point.
- None
- None
- None
> feat(kinesis): ErrorType in prefix

- providers/shared/components/component.ftl
- Allows for controlling if notifications are enabled on s3
This is required to disable notifications when running initial deployments where the topic is required and the topic needs the bucket for policy setup
tested locally
- None
- None
- None
> fix(s3): add enable on notifications

- providers/shared/components/mta/id.ftl
- Adds a new action for logging email events
- Adds a Senders condition to align with recipients
- Moves the EventTypes out of conditions to show they are log events to watch for
- Makes the hostname the default property to highlight what the configuration is for
Highlights the differences between send and receive along with how the actions behave
Tested locally
- None
- None
- None
> refactor: mta rules for send process

- providers/shared/inputseeders/shared/masterdata.json
- providers/shared/provider.ftl
- providers/shared/references/DeploymentMode/id.ftl
- providers/shared/views/unitlist/setup.ftl
- Updates the deployment mode ordering when dealing with orphan deployments to always run these deployments first
This ensures that the resources aren't available for other components to process them if they are not supposed to be there. Currently orphaned deployments were reordering all units when they were found causing issues in deployments
Tested locally
- None
- None
- None
> fix: ensure orphaned deployments are always first

- engine/occurrence.ftl
- Adds support for using RawNames as part of setting namespaces
This makes it easy to understand where settings can be configured and to align with the naming of components in a solution file
closes #1876
Tested locally
- None
- None
- None
> feat: add raw setting namepsaces

- providers/shared/provider.ftl
reverse the order of orphaned resources so they can be deleted based the group they are a member of
When removing dependent deployments the wrong order was being used
Tested locally
- None
- None
- None
> fix: reverse orphaned priority order

- providers/shared/components/s3/id.ftl
Because of the location of the configuration controlling versioning of the s3 bucket, if versioning is turned on, the bucket will automatically be lifecycled.
To permit versioning without lifecycle management, support a separate versioning attribute.
The Versioning attribute on Lifecycle will be deprecated to avoid lifecycle management as an unwanted side effect of enabling versioning.
- None
- https://github.com/hamlet-io/engine-plugin-aws/pull/486
- None
>  fix: s3 versioning without lifecycle management

- engine/common.ftl
- providers/shared/components/component.ftl
Add support for the use of LinkRefs to connect containers to the load balancers against which they need to register.
Fixes #1888 
The support for using link lookup to perform this connection was already in place. The changes in this commit simply add LinkRef processing as part of determining the link definition to use in the lookup.
- None
- None
- None
> feat: LinkRef support for container LB references

- providers/shared/extensions/extension.ftl
- providers/shared/layers/Account/id.ftl
- Adds support for providing jar files instead of zip files for java based functions
- Adds support for including layers as part of lambda functions using an extension macro
The jar file support aligns with the one of the supported models for lambda based functions to avoid having to zip an already compressed ( jar ) package 
Layers allows for the inclusion of OS level installations for lambda runtimes to use 
Tested locally and on active deployment
- None
- None
- None
> feat(lambda): add layers and jar image support

- providers/shared/views/schema/setup.ftl
- Skips processing of any attributes which are not hashes
This is based on the expectation that the attributes are normalised before being processed for their schema
Schema generation failing when inhibitEnabled was found
- None
- None
- None
> fix(schema): attributes which are not hashes

- README.md
- engine/base.ftl
- engine/configuration/component.ftl
- engine/configuration/layer.ftl
- engine/configuration/module.ftl
- engine/configuration/task.ftl
- engine/extension.ftl
- engine/inputdata/layer.ftl
- engine/occurrence.ftl
- providers/shared/attributesets/containertask/id.ftl
- providers/shared/components/apigateway/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/lambda/id.ftl
- providers/shared/components/lb/id.ftl
- providers/shared/components/s3/id.ftl
- providers/shared/components/sqs/id.ftl
- providers/shared/layers/Segment/id.ftl
- providers/shared/references/Port/id.ftl
- providers/shared/references/TestCase/id.ftl
- remove the behaviour where an `Enabled` attribute was added by default to composite objects
- remove use of the `InihibitEnabled` attribute to suppress the default behaviour
- add explicit `Enabled` attributes where they are currently expected by code
- extend the `isPresent` macro to throw an error if it doesn't find an `Enabled` attribute
- restrict the specification of attributes for composite object to use the full object based notation, removing the support for string based attributes.
Part of #1894
- None
- https://github.com/hamlet-io/engine-plugin-aws/pull/491
- None
> refactor: remove implicit Enabled attribute

- engine/configuration/component.ftl
- engine/configuration/task.ftl
- engine/output.ftl
- providers/shared/attributesets/attributeset.ftl
- providers/shared/attributesets/runbook_value/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/runbook/id.ftl
- providers/shared/components/runbook/setup.ftl
- providers/shared/components/runbook/state.ftl
- providers/shared/deploymentframeworks/default/output.ftl
- providers/shared/entrances/entrance.ftl
- providers/shared/entrances/runbook/entrance.ftl
- providers/shared/entrances/runbook/id.ftl
- providers/shared/entrances/runbookinfo/entrance.ftl
- providers/shared/entrances/runbookinfo/id.ftl
- providers/shared/inputseeders/shared/masterdata.json
- providers/shared/references/TestCase/id.ftl
- providers/shared/tasks/conditional_stage_skip/id.ftl
- providers/shared/tasks/task.ftl
- providers/sharedtest/components/internaltest/state.ftl
- providers/sharedtest/inputseeders/sharedtest/id.ftl
- providers/sharedtest/modules/runbook/module.ftl
- Adds support for the runbook component
- Adds entrances to support the generation of a runbook contract for the hamlet engine to execute 
- Adds a conditional task which can be used in runbooks to skip a runbook step if the conditions fail 
The runbook component generates a contract with a collection of tasks to complete. Since the runbook is generated inside hamlet it has access to the full state and details available within the CMDB. This includes settings, link attributes and anything available through the extensions methods 
Using this it is possible to make runbooks which perform operational activities on your hamlet deployments
Tested locally and with test module
- None
- None
- None
> feat: operational runbooks

- providers/shared/components/baseline/id.ftl
- providers/shared/extensions/runbook_get_provider_id/extension.ftl
- providers/shared/extensions/runbook_get_region/extension.ftl
- providers/shared/tasks/set_provider_credentials/id.ftl
- providers/shared/tasks/start_ssh_shell/id.ftl
- providers/shared/tasks/task.ftl
- Adds the required shared tasks for a runbook that will establish an ssh session with a bastion component
- Adds support for including the baseline ssh key as an attribute along with a file
- Adds a standard extension for getting the region as a runbook parameter
These changes are part of an initial implementation in the AWS provider of runbooks which allow for an ssh session to be established through a runbook
Tested locally
- None
- None
- None
> feat: bastion ssh runbook

- .github/workflows/release.yml
- Removes the junit reporter to reduce false error reporting due to PR permissions
The reporting tool was raising warnings on PRs as PRs only have read access to repos and can't create new checks that are required by the reporter. 
It also isn't too useful for hamlets testing approach which tests outputs rather than the code itsself
Will be tested as part of PR
- None
- None
- None
> cd: remove junit reporter from testing

- providers/shared/components/cdn/id.ftl
- Adds support for controlling the timeout for origin connections
- Exposes the TLS protocol used for connections to TLS based Origins
Provides greater control over CDN origins and their behaviour
Tested locally
- None
- None
- None
> feat(cdn): add origin connection timeout support

- engine/commonApplication.ftl
- providers/shared/attributesets/containertask/id.ftl
- Enables InitProcess handling as part of task definitions
This aligns with the --init flag in docker which adds a simple init process to manage zombie processes
This is a recommended feature when working with AWS ECS Exec to ensure that processes created as part of the exec session are cleared up 
Tested locally
- None
- None
- None
> feat(ecs): add initprocess support for containers

- providers/shared/tasks/bash_run_command/id.ftl
- providers/shared/tasks/ssh_copy_file/id.ftl
- providers/shared/tasks/ssh_run_command/id.ftl
- providers/shared/tasks/task.ftl
- Adds support for providing a bastion host for ssh tasks which will be used as an ssh gateway to the host
- Adds a bash command which will execute a bash command and return the results as an output
The ssh support allows for accessing instances within a deployment without manual steps
The local bash command is a general purpose commands to get extra info when required
Tested locally
- None
- None
- None
> feat(tasks): extend ssh tasks and add bash command

- legacy/account/account_ses.ftl
- providers/shared/layers/Account/id.ftl
- Adds support for using IP filtering as an allow list or deny list
This allows for using the IPAddressGroup filtering to drop specific sources or to only allow specific sources based on the IPAccessPolicy defined on the account. This is mainly to support using the filtering for spam or malicious actor blocking.
Tested locally
- None
- None
- None
> feat(ses): add control over IP access policy

- engine/common.ftl
- engine/configuration/reference.ftl
- engine/setContext.ftl
- providers/shared/components/component.ftl
- providers/shared/references/Certificate/id.ftl
- providers/shared/references/Domain/id.ftl
- providers/shared/references/reference.ftl
- providers/shared/views/blueprint/setup.ftl
- Migrates Domain/Certificate handling into Reference data
- Removes the global variable assignment and instead uses getReferenceData calls to get the data when required
This aligns this configuration with our existing reference configuration usage to make things easier to understand and document
Tested locally
- None
- None
- None
> refactor: move domain and certificate to reference data

- engine/configuration/module.ftl
- Ensures both name and provider are considered when loading modules
The default behaviour for configuration sets is to generally merge configuration outputs that share the same id across different providers. In the case of modules the provider/plugin represents a different module, so we need to ensure that the provider is considered when searching for configuration
Fixes #1922 
Tested locally
- None
- None
- None
> fix: module lookup process

- providers/shared/components/backupstore/id.ftl
- separate out conditions from targets
- add an "All" target option to support the use case where everything in a solution should be considered as a candidate target.
When adding backup to the baseline module for a customer, the need for more flexibility in the configuration options was exposed.
- None
- None
- None
> refactor(backup): Configuration options

- providers/shared/components/backupstore/id.ftl
Rely on the encryption key configured in the baseline profile.
Implementation now reflects the intent of the baseline profile.
A different profile can be configured specifically on the backupstore if a different baseline key should be used for encryption.
- None
- None
- None
> refactor: backup encryption key

- engine/base.ftl
- engine/occurrence.ftl
- Handles cases where the disablePrefix and prefix are the same when extending attributes
Attribute prefixes were being added back onto attributes when they should have been ignored 
Tested locally
- None
- None
- None
> fix: prefix handling for shared provider

- providers/shared/components/datafeed/id.ftl
- Adds support to control the compression behaviour for datafeeds sending to buckets
Initially added to troubleshoot an issue but also useful for controlling how the data is saved
Tested locally
- None
- None
- None
> feat(datafeed): compression control for buckets

- legacy/account/account_directory.ftl
- providers/shared/components/directory/id.ftl
- Adds logging configuration to the directory component
- Adds legacy deployment for setting up a resource policy for directory services to access the cloudwatch logs for AWS accounts
Allows for configuring logging on components to forward logs generated by the managed service through to standard logging services
The legacy account policy is to support logging for managed directories and is applied at the account level as only 10 log access policies can be assigned to an Account
Tested locally
- None
- None
- None
> feat(directory): support for log forwarding

- providers/shared/extensions/dind/extension.ftl
- providers/shared/extensions/hamlet/extension.ftl
- Adds the option to use local docker volumes instead of rexray
- Updates image support to allow for containerregistry settings
With the new storage setup for awslinux2 its easier to extend the disks where docker volumes are stored on hosts. As a result of this its safer to use local docker volumes when handling multiple builds jobs
- None
- None
- None
> feat: add support for using local docker volumes for builds

- providers/shared/components/component.ftl
- Adds support for defining a default compute provider on tasks
Allows for the use of capacity providers in AWS for running tasks on demand.
- None
- None
- None
> feat(ecs): add support for default task compute provider

- providers/shared/inputseeders/shared/id.ftl
- Add a warning but continue to process null values found in definition files
In OpenAPI there is a property called nullable within the specification, this is being caught by the current processing and the API definitions are not loaded even though it is valid. 
Tested locally
- None
- None
- None
> fix(apigateway): handling of null values in definitions

- engine/inputdata/district.ftl
- engine/inputdata/inputsource.ftl
- engine/occurrence.ftl
- engine/provider.ftl
- engine/setContext.ftl
- providers/shared/attributesets/attributeset.ftl
- providers/shared/attributesets/district/id.ftl
- providers/shared/components/name.ftl
- providers/shared/districts/account/id.ftl
- providers/shared/districts/district.ftl
- providers/shared/districts/environment/id.ftl
- providers/shared/districts/segment/id.ftl
- providers/shared/districts/tenant/id.ftl
- providers/shared/inputseeders/shared/id.ftl
Expand the district configuration to control the format of full names for resources.
Remove the corresponding configuration in setContext.
Add an "environment" district that does not have segment for simpler deployments.
By driving the full names from the district, full names can reflect whatever district layer configuration is selected.
- Local template generation
- Run engine and aws test suites
- None
- None
- None
> refactor: full names based on district

- engine/common.ftl
- engine/commonApplication.ftl
- fixes an issue where settings s3 keys were being overridden when syncing as file settings
- moves the standard policies for IAM from the shared provider to the aws provider
When working with components that have common first sections of their id ( mgmt, mgmt-worker ) the FullRelativePath  value overlaps between the subcomponents. 
When syncing the asFile settings to s3 this can cause the settings to be overriden as the sync command deletes files that don't match the sync. 
Moving to the FullRawRelativePath ensures the paths are unique for each component or subcomponent. 
Tested locally
- None
- None
- None
> fix: use raw path for settings path prefix

- engine/common.ftl
When syncing content to an s3 bucket, give the ability to set the max-age cache control on the synced files. 
This is mainly for config files that should have a limited cache lifetime.
Local template generation to confirm additional switches on the `s3 sync` command.
Customer deployment once the change is merged.
- None
- None
- None
> feat: max-age control on bucket content

- legacy/account/account_sms.ftl
- Adds the KMS service to the account template loading
- Adds a lookup for the KMS account key id that was missing
Template generation was failing for the account sms unit
tested locally
- None
- None
- None
> fix: encryption of logs for sms account

- providers/shared/inputseeders/shared/id.ftl
- Add the fixture account to the input filter handling
Fixes an issue where the account layer is missing when determining the district 
Tested localy
- None
- None
- None
> fix: include account in mock filter layers

- providers/shared/extensions/dind/extension.ftl
- providers/shared/extensions/hamlet/extension.ftl
- Updates the hamlet and dind ecs extensions to align with the latest supported approaches in hamlet
- Remove the use of the docker-ebs volume extensions as it is no longer supported
- Always use TLS verification for dind to hamlet agent communication
Makes it easier to follow the configuration required for running hamlet CI/CD agent with DIND on ecs and removes deprecated approaches for hamlet and docker hosting
Tested locally
- None
- None
- ! This will require updates to existing hamlet agents running in jenkins
- Update AWS_AUTOMATION_USER to HAMLET_AWS_AUTH_SOURCE/HAMLET_AWS_AUTH_USER as per https://docs.hamlet.io/how-to/configure/provider-authentication
> refactor: hamlet and dind docker extensions

- providers/shared/components/ec2/id.ftl
- Allows for defining the the zones that a given component should be deployed to
This allows for finer grain control over ec2 deployments such as using component instances to control each instance and treating each deployment as an individual service
- None
- None
- None
> feat(ec2): add support for zone based deploy control

- providers/shared/references/Port/id.ftl
- Adds support for defining the HealthCheck Protocol separate from the ports protocol itself
This allows for using more complex load balancing processes where the protocol used for the load balancer is different to the one used for HealthChecks
This was supported but missed in the reference definition and has been updated to handle fallbacks for protocol lookup 
- None
- None
- None
> feat: add support for HealthCheck Protocol

- providers/shared/components/datavolume/id.ftl
- Removes Engine from datavolume and relies on the provider to handle this
- Adds support for controlling the zone that the volume is deployed to
- Removes support for backups on datavolumes
- Removing the engine parameter as its not required and is currently using a vendor specific default value 
- Zone control aligns with changes for the ec2 component where you might want to control how deployments for datavolumes are managed using instances instead of multizone 
- Removing backups reduces the complexity required for the datavolume deployment. Instead of using dedicated backups the backup component should be …
> feat(datavolume): zone control and remove backups

- engine/occurrence.ftl
- engine/output.ftl
- providers/shared/components/shared/setup.ftl
- providers/shared/entrances/entrance.ftl
- providers/shared/entrances/imagedetails/entrance.ftl
- providers/shared/entrances/imagedetails/id.ftl
- Adds am imagedetails entrance which lists the build information for occurrences that have the information available
- Adds the source option to build information to show where the image came from
Used to provide a query command to show what has been deployed to your environments
Tested locally
- None
- None
- None
> feat: add image details entrance for image reference info

- engine/base.ftl
- engine/common.ftl
- engine/setContext.ftl
- providers/shared/components/bastion/id.ftl
- providers/shared/components/cache/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/datavolume/id.ftl
- providers/shared/components/db/id.ftl
- providers/shared/components/ec2/id.ftl
- providers/shared/components/es/id.ftl
- providers/shared/components/fileshare/id.ftl
- providers/shared/components/filetransfer/id.ftl
- providers/shared/components/firewall/id.ftl
- providers/shared/components/gateway/id.ftl
- providers/shared/components/lb/id.ftl
- providers/shared/components/queuehost/id.ftl
- providers/shared/flows/components/flow.ftl
- providers/shared/inputseeders/shared/masterdata.json
- providers/shared/layers/Environment/id.ftl
- providers/shared/layers/Segment/id.ftl
- providers/shared/layers/Solution/id.ftl
- providers/shared/views/blueprint/setup.ftl
- Adds a MultiAZ attribute to all components which currently use MultiAZ in both the aws and azure providers
- Removes the MultiAZ flag on layers that had it configured
- Adds a deployment profile for multiAZ environment control to replicate the current behaviour
- Remove layer support for minor version updates
- Adds deployment profile to control minor version updates per env
- Removes NAT controls at the segment level as they are no longer used
This simplifies where component configuration is sourced from and controlled and allows for removing the Solution layer which isn't really a layer following review of …
> refactor: move multiAZ to standard component configuraiton

- providers/shared/components/firewall/id.ftl
- Change from Type to RuleType on firewall rules to avoid conflict with the global Type attribute
When using the Type attribute on the Parent component the Type on the rule was being overridden if it wasn't set on each firewall rule 
- None
- None
- None
> fix(firewall): rename type attribute on firewall rules

- providers/shared/components/certificateauthority/id.ftl
- providers/shared/components/component.ftl
- Adds support for defining a certificate authority component
Allows for creating private certificate authorities using managed services. This is useful when managing PKI for services that need direct access to public and private keys while maintaining a trust chain which can be defined across all users of the service
Tested locally and with AWS provider
- None
- None
- None
> feat: add certificate authority component

- engine/inputdata/layer.ftl
- engine/setContext.ftl
- providers/shared/layers/Product/id.ftl
- Uses the district type to define the layers that are considered active
- Control handling of missing layes when explicit lookups are used
- Use active layer data filtering instead of explicit layers for setContext data
When running a reference data query in the account level the template generation fails as base layer data was being included for other layers when it didn't need to include it.
Tested locallly
- None
- None
- None
> fix: only include active layers based on district type

- providers/shared/components/dnszone/id.ftl
- Adds the ability to define a network profile for DNS zones
- Adds support for configuring the DNS domain to use
Allows for creating private DNS zones within a VPC for split brain DNS scenarios 
Tested locally
- None
- None
- None
> feat(dnszone): add support for network based configuration

- providers/shared/components/lambda/id.ftl
Add the config to permit provisioned executions of versioned lambda functions.
Tuning of customer applications for production loads usually requires establishing provisioned capacity.
- None
- None
- None
> feat(lambda): provisioned executions

- providers/shared/components/lb/id.ftl
- Allows for controlling if a static endpoint is internal or external to the local network of the load balancer
REquired for some load balancers to ensure traffic is routed properly
- None
- None
- None
> feat(lb): define external or internal for lb endpoints

- providers/shared/views/unitlist/setup.ftl
- Add generation contract for uitlist view
When generating a unitlist for the account level district as there are no occurrences the account layer the generation contract isn't triggered. Adding it into the view ensures that the generation contract is populated when there are no components. 
Tested locally
- None
- None
- None
> fix: add generation contract for unitlist view

- providers/shared/attributesets/alert/id.ftl
- Adds an enable/disable attribute to alerts to control if they are deployed or not
This allows for control over alerts added through deployment profiles that you want to override and remove in particular cases
Tested locally
- None
- None
- None
> feat(alerts): add enable attribute on alerts

- providers/shared/components/lambda/id.ftl
When a new version is created on each deploy, provide control over whether the old versions are deleted or retained.
The default is to retain in line with the previous hard coded value.
The need to delete has become more relevant as versioned lambdas are needed to preprovision lambda instances.
Local template creation. Customer deployment
- None
- None
- None
> feat(lambda): versioned lambda retention policy

- engine/base.ftl
- providers/shared/components/lambda/id.ftl
New attribute AdditionalValues which downgrades a mismatch in Values (currently only on Runtime) to a warning and allows non-specified values
Fixes https://github.com/hamlet-io/engine/issues/1640
Locally
- None
- None
- None
> feat: Support user defined runtime engines with only a warning

- providers/shared/attributesets/attributeset.ftl
- providers/shared/attributesets/contextpath_fullpath/id.ftl
- providers/shared/components/component.ftl
- providers/shared/components/logstore/id.ftl
- providers/shared/references/LogFileGroup/id.ftl
- Defines the log store component used to create an independent log store from other components 
This allows for the creation of a log store that is written to by another component with content that doesn't relate to the execution of that content. 
This could be something like a lambda function which writes log events it receives, so the lambda log group is for running the function and capturing issues in running the function, where the log store is the formatted event content it was processing. 
Tested locally
- None
- None
- None
> feat(logstore): add dedicated log storage component

- engine/common.ftl
- engine/configuration/component.ftl
- legacy/account/account_console.ftl
- Adds support for controlling which tags are applied to occurrences
- Makes tag generation a standardised function that can be applied across providers
- Adds support for adding additional tags to occurrences
implements #1540  and fixes #1994 
This allows users to control their tagging strategies and also include standard tags that are provided by hamlet itself 
Tested locally
- None
- None
- None
> feat: tagging control for occurrences

- providers/shared/components/apigateway/id.ftl
Support additional model values for the case of IP filtering in combination with a lambda authorizer. Also rename the config attribute to more correctly reflect its purpose in controlling authorization rather than authentication.
When used with a lambda authorizer, the default value of "IP" incorrectly provides an explict ALLOW  rather than relying on it to come from the policy provided by the authorizer. By providing explicit values to be used with the authorizer, the configuration can be validated as appropriate.
- None
- None
- None
> refactor(apigateway): authorization models

- providers/shared/components/cdn/id.ftl
- Allows for setting the priority on cdn routes to control the evaluation of rules
When working with CDN's they generally follow a rule based approach where the first rule wins. When working with rules that have overlapping patterns it's important to be able to control the route preferences. 
Tested locally
- None
- None
- None
> feat(cdn): add priority to cdn routes

- providers/shared/components/component.ftl
- providers/shared/components/correspondent/id.ftl
- adds support for defining the configuration required for mobile push notifications
Used when setting up correspondent services like AWS pinpoint for notifications to mobile devices
tested locally
- None
- None
- None
> feat(correspondent): add  support for channel configuration

- engine/bootstrap.ftl
- engine/configuration/dynamicvalues.ftl
- engine/provider.ftl
- providers/shared/components/runbook/setup.ftl
- providers/shared/dynamicvalues/attribute/dynamicvalue.ftl
- providers/shared/dynamicvalues/dynamicvalue.ftl
- providers/shared/dynamicvalues/input/dynamicvalue.ftl
- providers/shared/dynamicvalues/output/dynamicvalue.ftl
- providers/shared/dynamicvalues/setting/dynamicvalue.ftl
- providers/shared/flows/components/flow.ftl
- providers/sharedtest/inputseeders/sharedtest/id.ftl
- providers/sharedtest/modules/dynamicvalue/module.ftl
- providers/sharedtest/modules/internaltest/module.ftl
- providers/sharedtest/modules/runbook/module.ftl
Extends the dynamic value evaluation from solution configuration on runbooks to a more generic function which can be used across all components and their solution configuration 
Dynamic values can be used in solution configuration to represent a value that should be resolved at run time rather than an explicit configuration defined in the solution file. 
They can be used anywhere a string is accepted and can be used at any point in the string. They follow the format of 
`__<type>:<attributes>...__`
Where type is the type attribute assigned to a Dynamic Value Provider and the attributes section represents one or more attributes separated by `:` These attributes are used by the provider to determine the value to replace. When a …
> feat: add support for dynamic value evaulation

- providers/shared/components/id.ftl
- providers/shared/components/lambda/id.ftl
When deploying a fixed lambda version, provide the option of a lambda alias to avoid the need to update references when a new version of the lambda is created.
- simplify deployment management
- None
- None
- None
> feat(lambda): lambda alias

- providers/shared/components/component.ftl
- providers/shared/components/image/id.ftl
- Adds the initial shared definition for an image component
This introduces a dedicated image component which represents the application code image used by other components ( SPA, Docker, API Gateway, Lambda )
Creating a dedicated image allows for greater flexibility in how images are managed  
- A single image component can be used by many components 
- This is clearly defined in the solution
- The image can be maintained separately from the consuming components 
- Consolidates the pulling from external sources management to avoid duplication across setup routines
- None
- None
- None
> feat(image): initial image component 

- engine/output.ftl
- providers/shared/components/shared/setup.ftl
- providers/shared/entrances/entrance.ftl
- providers/shared/entrances/stackoutput/entrance.ftl
- providers/shared/entrances/stackoutput/id.ftl
- providers/shared/inputseeders/shared/id.ftl
- providers/shared/tasks/cmdb_write_stack_output/id.ftl
- Adds the stackoutput entrance which generates a stack output file based on the provided stack output inputs
- Adds a task to call the stackoutput entrance from a runbook
- Adds the CMDB Root dir as a common input parameter
This allows for runbooks to contribute stack outputs for components. This also supports the migration to deployment contracts in the future with the potential to collect all stack outputs generated during a deployment and write them to a single file. 
This would remove the need for multiple pseduo stack outputs and have a single stack output state file.
Tested locally
- None
- None
- None
> feat(entrance): stackoutput entrance

- engine/output.ftl
- make it required that deployment prefix handling is managed for all entrances
If you have defined environment variables that aren't required for a specific entrance then they can be unintentionally added to the output filename and this creates flow on effect issues for consumers of the outputs
Tested locally
- None
- None
- None
> fix(output): output prefix handling

- engine/output.ftl
- add configuration for the output prefix to be used with the `schema` entrance
- correct the spelling of the error where the prefix for an entrance is not known
tram build failing
Local execution of the `create-schemas` entrance
- None
- None
- None
> fix: schema entrance output filename

- engine/output.ftl
- An unexpected filename was being used when generating build blueprints
runExpoApppublish was failing to find the build blueprint
Tested locally
- None
- None
- None
> fix: set buildblueprint output file name

- engine/configuration/dynamicvalues.ftl
- providers/shared/dynamicvalues/input/dynamicvalue.ftl
- providers/shared/dynamicvalues/output/dynamicvalue.ftl
Correct the content of the error message used for `input` and `output` dynamic values when they are used on a component type other than those for runbooks.
Also remove a redundant line of code from the dynamic value core processing function.
- less confusing  user feedback when errors are encountered
Local template generation mainly to ensure no syntax errors were introduced.
- None
- None
- None
> fix(dynamicinput): error message text

- providers/shared/references/Port/id.ftl
- Adds support for enabling and disabling healthchecks
When working with some services the need to run healthchecks isn't required. 
Tested locally
- None
- None
- None
> feat(port): add enable for port healthcheck

- providers/shared/components/lambda/id.ftl
Add node 16 as it is now supported and remove run-times which are either EOL, or either in (or soon to be in) the process of
deprecation by AWS.
Note that because extra values are permitted, older values will pass validation but will generate a warning.
Keep warnings aligned to current status of lambda run-times.
Local template generation. 
- None
- None
- None
> chore(lambda): update lambda runtime versions

- providers/shared/attributesets/attributeset.ftl
- providers/shared/attributesets/cdnorigin/id.ftl
- providers/shared/attributesets/cdnttl/id.ftl
- providers/shared/components/cdn/id.ftl
- providers/shared/components/component.ftl
- Adds support for route independent origins similar to the lb backend
- Adds support for route independent cache policies to share across routes
- Adds support for response header injection if supported by the cdn
- Creates attribute sets to support the split of origins across routes and origins
The primary motivation for this change is to handle complex CDN scenarios where a collection of different routes all need to forward to a single origin but each route has different caching and processing requirements. 
Splitting them out and making it possible to use the same origin on multiple routes can reduce the resource requirements within a deployment as we don't duplicate the origin configuration across each route. 
Tested …
> feat(cdn): extended support for managing complex requirements

- providers/shared/components/adaptor/id.ftl
- providers/shared/components/apigateway/id.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/contentnode/id.ftl
- providers/shared/components/datapipeline/id.ftl
- providers/shared/components/dataset/id.ftl
- providers/shared/components/healthcheck/id.ftl
- providers/shared/components/lambda/id.ftl
- providers/shared/components/mobileapp/id.ftl
- providers/shared/components/spa/id.ftl
- providers/shared/components/template/id.ftl
- Adds configuration for using a link as the source of an image
This supports the introduction of the image component so that image references and sources can be found. This can also be used as a replacement for the shared_build file but managed through the solution.
- None
- None
- None
> feat: add support for links as image sources

- engine/bootstrap.ftl
- engine/common.ftl
- engine/configuration/configuration.ftl
- engine/configuration/solution.ftl
- engine/inputdata/solution.ftl
- engine/occurrence.ftl
- engine/provider.ftl
- engine/setContext.ftl
- providers/shared/inputseeders/shared/masterdata.json
- providers/shared/layers/Segment/id.ftl
- providers/shared/provider.ftl
- providers/shared/references/DeploymentGroup/id.ftl
- providers/shared/solution/tiers/solution.ftl
- Adds support for defining solutions which are applied to a matching district
- Adds support for defining and extending the configuration that makes up the solution
Makes it possible for other districts like the account district to have its own solution/components. Extensions of the solution allow for different ways to define how the district might work, the Tiers model is the primary one for defining components but there might be other configuration approaches that would align with being used in solutions. 
Solutions are merged into each other if multiple matches for a given district are found for an available solution, this allow for solutions to be broken up into more relevant chunks but still need to be deployed into the …
> feat: district based solutions

- engine/base.ftl
- engine/configuration/component.ftl
- engine/configuration/configuration.ftl
- engine/configuration/reference.ftl
- providers/shared/views/schema/setup.ftl
- Splits the expand base configuration attribute sets into a separate function so that it can be processed before the expansion of children
- adds support for nested base attributes that might be in place on children
Schema generation was failing as child base attributes weren't expanded. 
Tested locally
- None
- None
- None
> fix: split expand base configuration

- providers/shared/attributesets/containerhost/id.ftl
- providers/shared/attributesets/containerservice/id.ftl
- providers/shared/attributesets/containertask/id.ftl
- providers/shared/components/bastion/id.ftl
- providers/shared/components/computecluster/id.ftl
- providers/shared/components/datapipeline/id.ftl
- providers/shared/components/ec2/id.ftl
- providers/shared/components/federatedrole/id.ftl
- providers/shared/components/healthcheck/id.ftl
- providers/shared/components/lambda/id.ftl
- providers/shared/components/user/id.ftl
- Remove the AppPublic permissions option as it's not longer available and isn't in use
The App Public permissions option was not a recommended practice and there wasn't use of it across know deployments. 
Tested locally
- None
- None
- None
> refactor: remove app public permissions attribute

- providers/shared/components/globaldb/id.ftl
- Add the ability to enable/disable secondary indexes
Adds the ability to control the use of indexes using qualification
Tested locally
- None
- None
- None
> feat(globaldb): add enable support for indexes

- engine/configuration/dynamicvalues.ftl
- Adds support for objects to be used in dynamic value replacements if the dynamic value reference is the only content of the string
This fixes support for the AWS secrets manager dynamic value which returns an object reference used byb CloudFormation tor resolve the secret 
Adding the check for the object replacement being the only content of the string provides a logical way to handle replacements when dealing with objects
Tested locally
- None
- None
- None
> fix(dynamicvalues): support objects in replace

- providers/shared/components/mobileapp/id.ftl
- Moves all mobileapp configuration from settings over to solution configuration
- Adds support for controlling the filenames of file based settings. This allows for users to identify a specific version of a certificate or profile that is in use
- Adds support for defining a badge that is added to app icons
The primary motivation for this move is to make the complex configuration options required to publish mobile apps documented, type checked and validated via the engine before they are passed to downstream processes. This makes it easier to discover the available options and to support the migration from …
> !refactor(mobileapp): mobileapp solution config

- providers/shared/dynamicvalues/dynamicvalue.ftl
- providers/shared/dynamicvalues/ipaddressgroup/dynamicvalue.ftl
- Adds dynamic value evaluation for IP Address groups returns the evaluated CIDR addresses with support for occurrence based groups as well
While IPAddress Groups have explicit configuration control for most access control, they might also need to be used in settings or other scenarios like WAF Value Sets. 
This allows them to be included in these places without having to use freemarker extensions to get the data. 
Tested locally
- None
- None
- None
> feat(dynamicvalue): add IP Address group support

- providers/shared/components/network/id.ftl
- control what is included as part of the prefix when creating flow logs that are saved to s3
Allows for knowing what is included in the prefix and to allow for the cloud provider to pick the prefix if none are provided
tested locally
- None
- None
- None
> feat(network): add prefix control for flow logs

- providers/shared/components/directory/id.ftl
- providers/shared/components/es/id.ftl
- providers/shared/components/lb/id.ftl
- Ensure that components that can control their logging output have logging enabled by default
Logging is usually only remembered when troubleshooting an issue, and enabling it that point often means you miss something that was going wrong. Along with that its also cheaper to have logging enabled than it is to spend on troubleshooting issues without logs. 
So new recommendation from hamlet side of things is to enable logging by default whenever we can. 
Tested locally
- None
- None
- None
> feat: enable logging by default

- providers/shared/components/userpool/id.ftl
- Lets users define the callback and logout urls for oauth clients as solution level configuration
When combined with dynamic value evaluation this allows for setting the callback/logout urls without having to append paths to other component FQDNS using an external service. 
Tested locally
- None
- None
- None
> feat(userpool): add support callback urls solution

- providers/shared/components/component.ftl
- providers/shared/components/datacatalog/id.ftl
- Adds the datacatalog component which represents the idea of a catalog of data that has been normalised using a datastore process
- Currently includes tables for column based data representation
Data catalogs can be used to map data from different sources into a centralised repository. The initial implementation aims at adding AWS Glue into hamlet. 
Tested locally
- None
- None
- None
> feat(datacatalog): add new component

- providers/shared/inputseeders/shared/masterdata.json
- Adds indexes to the tiers added to masterdata that aren't in the current network order array
- This ensures there aren't collisions in the tiers when they are referenced
Template generation was failing when working with networks that had their own tier configuration defined. 
Tested locally
- None
- None
- None
> fix: set tier indexes for tiers not in network

- providers/shared/references/WAFProfile/reference.ftl
- providers/shared/references/WAFRule/id.ftl
- Adds support for defining more complex WAF rules which perform actions in different ways, such as applying after a rate limit has been hit or using vendor provided protections
Web Application Firewalls are becoming more complex and featured and allow for more than just allow/deny actions. This change includes the ability to use these more complex rules as required 
- None
- None
- None
> feat(waf): add rule engines

- legacy/account/account_audit.ftl
- legacy/account/account_console.ftl
- legacy/account/account_s3.ftl
- Blocks public access for s3 buckets deployed at the account level
Implements https://github.com/hamlet-io/engine-plugin-aws/pull/656 for account level s3 buckets
tested locally
- None
- None
- None
> feat(s3): block public access on account s3

- providers/shared/dynamicvalues/output/dynamicvalue.ftl
- When using the output dynamic value the output format needs to align with how the python executor expects them
- With changes to dynamicvalues this was broken along the way
Was discovered when AWS credentials found in one task contract step didn't get passed through to another step
Tested locally
- None
- None
- None
> fix(dynamicvalue): correct the output for tasks

- providers/shared/references/WAFRule/id.ftl
Align spelling of default engine to that used in the AWS specific logic.
AWS WAF support is incorrectly detecting the default engine type.
As the additional engine types were only recently added, it felt more appropriate to correct the spelling
rather than leave the misspelling in place and add the correct spelling to the possible values.
- None
- None
- None
> fix(wafrule): engine type spelling

- providers/shared/inputseeders/shared/masterdata.json
- Adds a default WAF profile which allows for open access by default
- Aligns with other security profiles and allows for creating rules without the provided OWASP rulesets
This aligns with the updated behaviour in https://github.com/hamlet-io/engine-plugin-aws/pull/668 which brings the WAF security configuration more in line with how the rest of the profiles work across other components. In the AWS provider if the OWASP WAF configuration isn't enable the user could not use the profile to configure the WAF rules. Creating a default open profile and using that as the default aligns with the current behaviour in AWS 
Tested locally
- https://github.com/hamlet-io/engine-plugin-aws/pull/668 
- None
- None
> fix(waf): set default WAFProfile to default

- engine/common.ftl
- engine/commonApplication.ftl
- engine/occurrence.ftl
- engine/setContext.ftl
- providers/shared/extensions/extension.ftl
- providers/shared/flows/components/flow.ftl
- Adds support for Images as part of the occurrence which represent a code image that can be used by an application component
- Removes common functions for registry lookups as registries are managed via the image definition for the provider
- Removes the configuration for docker image attributes around name and version in favour of the container image properties
- Moves image pull scripts from the common provider over to the aws provider as they are specific to AWS images
Standardising and consolidating the image manage process allows us to align how images can be used across all components and introduce more solution based ways to manage images. Providing their own section in state allows for the definition of a standard image …
> feat(image): adds support for images in occurrence

- .github/workflows/release.yml
Update the workflow version to pick up the fix to ensure the edge tag is added correctly to docker images.
Unicycle release was not picking up changes as `edge` tags were not being added to docker builds.
Difficult to test outside of github. Tested immediately following commit.
- None
- None
- None
> fix: update release package version

- providers/shared/components/component.ftl
- providers/shared/components/db/id.ftl
- defines the proxy subcomponent for db's which represents an automated connection pooling proxy service
Connection pooling helps to reduce database resources when establishing connections in for short lived services like lambda functions. Instead of each database client creating a connection to the db, the proxy establishes a set of connections to the database and then clients connect to the proxy. 
The proxy then looks after distributing requests across its connections. DB proxies can also bypass load balancers which might lock connections to a particular host, when this happens autoscaling activities which add new databases might not be used to their full extent, the proxy knows when new hosts are added and will make sure …
> feat(db): add proxy subcomponent

- legacy/account/account_s3.ftl
- Remove the setup of registry markers in the account registry bucket
- Removes the code bucket sync
With the move to fixed registry prefixes to store images the need to initialise the registry isn't really there any more. This is currently causing issues as the s3RegistryIds variable was removed in other image updates
We no longer have components which rely on the code sync process so this has been removed as well
Tested locally
- None
- None
- None
> fix(account_s3): remove s3 registry initialisation

- providers/shared/components/runbook/setup.ftl
- providers/shared/deploymentframeworks/default/output.ftl
- providers/shared/extensions/runbook_image_reference_output/extension.ftl
- providers/shared/extensions/runbook_registry_object_filename/extension.ftl
- providers/shared/extensions/runbook_registry_type_condition/extension.ftl
- Not sure how but the stackoutput generation entrance seems to have been partially removed.
- Adds the output process back in to generate stack output files in the engine
- Adds the resolved inputs for runbooks into the context of steps
- Fixes how a components image is looked up when pushing images via runbook
Added as a collection of fixes found when testing out the image push method for docker containers using the runbook method
Tested locally
- None
- None
- None
> fix: stackoutput generation and image upload runbooks

- legacy/account/account_es.ftl
- Create policy so that Elastic/OpenSearch can log to Cloudwatch
Required for the implementation of Logging 
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/createdomain-configure-slow-logs.html
Tested locally and on dev deployment
- None
- None
- None
> feat(account): add aws es log access policy

- providers/shared/components/userpool/id.ftl
- Adds support for enabling/disabling the hostedUI
Tested locally
- None
- None
- None
> feat(userpool): control enabling hostedUI

- legacy/account/account_audit.ftl
- legacy/account/account_cloudtrail.ftl
- providers/shared/layers/Account/id.ftl
- Adds support for creating an account level cloudtrail trail to track management api calls and store them in the account audit bucket
Cloudtrail auditing provides a log of all activities performed within a cloud provider subscription. They usually focus on management plane calls but can be configured to support some data plane calls for deeply integrated services. 
This adds support for the management activities and closes #679
Tested locally and on test deployment 
- https://github.com/hamlet-io/engine-plugin-aws/pull/687
- None
- None
> feat(cloudtrail): support for account cloudtrail

- legacy/account/account_audit.ftl
- providers/shared/layers/Account/id.ftl
- Adds support for S3 bucket replication for the account level audit service
This allows for replicating the audit logs to an external account or bucket when you need to consolidate logs for security analysis and assurance
'
Tested localy
- https://github.com/hamlet-io/engine-plugin-aws/pull/690
- None
- None
> feat(audit): add support for replication

- providers/shared/components/shared/setup.ftl
- providers/shared/services/resource.ftl
- providers/shared/tasks/cmdb_write_stack_output/id.ftl
- Adds a resource lookup to determine the occurrence a provided stack output belongs 
- Adds alternatives to the stackoutput for each occurrence in a deployment, if a resource matched in the process above is found then the output goes into that alternative
- ensures that occurrences within the same deployment don't override outputs generated by the output task
- When using the runbook before the output between occurrences was overriden
Tested locally
- None
- None
- None
> fix: cmdb write output for occurrences

- providers/shared/components/image/id.ftl
- Add support for configuring additional settings for repositories created to host docker/OCI based image registries
- Image hosting is performed in standard registries for containers which offer a wide range of security and traceability options
- Add lifecycle policy management for images to manage storage capacity 
- None
- None
- None
> feat(image): add docker image repository config

- engine/configuration/component.ftl
- Adds support for locking a deployment to prevent accidental changes
- Initial support is for delete actions
Adding deletion protection is a key recommendation from cloud vendors as an extra lock to prevent the deletion of key resources within a deployment which are generally fixed, this includes things like dbs, load balancers cdn etc, where removing the resource would require significant effort to bring back up. 
This allows for the locks to be maintained in hamlet. 
Tested locally
- None
- None
- None
> feat: add support for deployment locks

- providers/shared/components/shared/setup.ftl
- Don't include the generation contract for stack outputs to avoid git conflicts when two occurrences in a deployment unit update at the same time
When using a single deployment unit for all docker based registries if two pipelines update the image references at the same time conflicts are raised on the generation contract. We don't need to care about what was generated in a single file output so it can just be removed. 
- None
- None
- None
> fix: remove gen contract from stack outputs

- providers/shared/components/lambda/id.ftl
Add nodejs 18 as a known run-time for lambda.
AWS has added support for node 18.
Local build
- None
- None
- None
> refactor(lambda): node 18 run-time

- providers/shared/components/es/id.ftl
- providers/shared/inputseeders/shared/masterdata.json
- providers/shared/references/SecurityProfile/id.ftl
- Adds support for an HTTPS profile option on ES clusters to control TLS encryption setup
- Adds support for configuring a custom hostname/certificate for
- Adds security support for configuring node to node encryption
Aligns with security best practices and what we offer for our other components
Tested locally
- None
- None
- None
> feat(es): encryption and hostname control

- providers/shared/components/cache/id.ftl
- Make the retention period for cache snaphosts use number instead of string
- Sets a default with description so its easier to understand
Wasn't really sure what the option did until I dug into the AWS implementation.
Tested locally
- None
- None
- None
> fix(cache): syntax for retention period

- providers/shared/attributesets/cdnorigin/id.ftl
- providers/shared/components/cdn/id.ftl
Add new QueryParamExclude option to access allExcept querystring policy option
Needed to access allExcept querystring policy option
Local build
- None
- None
- Set QueryParamExclude to true to access allExcept (default = false)
> feat: add support for allExcept on cachepolicy

- providers/shared/layers/Account/id.ftl
- providers/shared/layers/Product/id.ftl
- providers/shared/services/resource.ftl
- Include the region of the point and the deployment unit when trying to determine if a deployment is a part of the current unit
When generating a unit that has the same resource Id in each region the deployment detection would treat the other region as part of the same deployment and not allow for the resource to be created in a new deployment.
Tested locally. 
- None
- None
- None
> fix: include region for deployment checking

- providers/shared/components/mta/id.ftl
- Adds MTA rule support for bouncing emails on receive
Bounce messages provide more contextual information for when people send emails to an email domain. This allows for bounces to be defined based on rules and applied as required
Tested locally
- None
- None
- None
> feat(mta): add support for bouncing emails

- providers/shared/components/lb/id.ftl
- Allows for setting an array of paths for a lb port rule
Allows for consolidating load balancer rules that do the same thing across different paths
Tested locally
- None
- None
- None
> feat(lb): add support for multiple paths

- legacy/account/account_audit.ftl
- providers/shared/components/s3/id.ftl
Add support for control of the object ownership for the bucket.
Also, per https://docs.aws.amazon.com/AmazonS3/latest/userguide/enable-server-access-logging.html, switch from using an ACL to using bucket policy to permit logging to the audit bucket.
- align with AWS best practices
- avoid deployment failures where an SCP enforces bucket owner object ownership.
- 
Local generation. Use in customer site will also be undertaken once part of the unicycle release.
- None
- None
- None
> refactor(s3): object ownership support

- providers/shared/attributesets/container/id.ftl
- providers/shared/attributesets/containerservice/id.ftl
- providers/shared/attributesets/containertask/id.ftl
- Adds task level Cpu/Memory limit configuration
- Adds readonly fs container option
- Adds dependsOn configuration to specific dependencies between containers
Enabling root only file systems requires adding volumes for directories like /tmp. However doing this creates directories owned by root. Running an init container before the actual container lets you align the new volume permissions with what is expected
Tested locally
- None
- None
- None
> feat(ecs): task service limits, readonlyds, depend

- engine/common.ftl
- providers/shared/references/NetworkEndpointGroup/id.ftl
Extend the processing of endpoint services to support privately defined endpoints, as opposed to the public ones offered by cloud providers. 
These endpoints are assumed to be required in all zones supported by the network of the tier in which the gateway is defined.
Support the use of customer defined service endpoints in AWS.
Local template generation. I'll also apply on customer site.
- None
- None
- None
> feat: private endpoint services

- providers/shared/components/network/id.ftl
- Adds the ability to set a network profile on a network. This applies to network resources created as part of the network itself such as default security groups
- Adds enabled attribute for network rules on a user defined ACL
Allows for control over default resources created as part of a network 
Tested locally
- None
- None
- None
> feat(network): support for network profile on net

- providers/shared/components/runbook/setup.ftl
Ensure runbook condition contract steps have a unique id.
At present, if more than one condition is provided, they share the same contract step id resulting in them overwriting each other, an example being `register_docker_push_tag` where even if the registry isn't docker, if a tag is provided it is run regardless.
Customer site
- None
- None
- None
> fix(runbook): multiple conditions

- engine/commonApplication.ftl
Add the reference and tag from the image details as default environment settings so inclusion of these in config files doesn't fail when image components are used.
Currently the inclusion of build information into an spa config file assumes the settings have come via the builds section of the CMDB. With the introduction of image components, this information is available via the occurrence image details rather than via build settings. 
By initialising the default environment with the values from the image information, existing fragment and extension files will continue to work with image components.
Customer site
- None
- None
- None
> fix: image settings

- providers/shared/components/mta/id.ftl
- Adds the ability to stop further processing if a rule is matched
The mail processing engine in some providers will process all matched rules rather than the first match, you could add another rule after the one where it should stop, but this makes it easier to setup
Tested locally
- None
- None
- None
> feat(mta): add stop after match action

- providers/shared/components/apigateway/id.ftl
Add the option of private APIs. For these APIS, traffic filtering is done on the basis of VPC endpoints rather than IP addresses. The VPC endpoints are assumed to be configured via inbound links to external services, which should provide a VPC_ENDPOINTS attribute containing a command separated list of vpc endpoint names.
Adjust the available values for the authorisation model to support either IPs or VPC Endpoints.
- support new AWS feature
- support more security conscious deployment
- None
- None
- None
> feat(apigateway): private APIs

- providers/shared/components/gateway/id.ftl
Add the ability to add policy to vpcendpoint gateway destinations via extensions.
To limit the access provided, support link based extensions that add an explicit 
policy to aws service privatelinks.
As this is new support, don't provide alternative names for the `Extensions` attribute.
- local generation
- customer site following release
- 
- None
- None
- None
> feat(vpcendpoint): policy support

- providers/shared/components/shared/setup.ftl
When generating an occurrence list, don't include sub-occurrences that are disabled. Any component processing should perform an equivalent check but at present the sub-occurrence still appears in the list.
The same doesn't happen to occurrences since the general flow logic completely excludes any occurrence that is disabled.
this fix ensures the behaviour is the same for occurrences or sub-occurrences.
Local cli execution.
- None
- None
- None
> fix: don't list disabled suboccurrences

- providers/shared/components/lb/id.ftl
Provide the ability to control the way in which client IP information will be provided to a target.
The default mirrors the current situation where the lb client is hidden and the lb address is presented.
- Local template generation
- None
- None
- None
> feat(lb): client IP control

- providers/shared/components/user/id.ftl
- Adds the ability to control the components included in the name of a user
When creating and managing user accounts in hamlet, sometimes you want to create centralised accounts that are used for management purposes. In these cases they are only deployed to one environment so you can make the user names as small as possible
Tested locally
- None
- None
- None
> feat(user): add user name control

- providers/shared/references/IPAddressGroup/id.ftl
- providers/shared/references/SecurityProfile/id.ftl
- providers/shared/references/WAFProfile/id.ftl
- providers/shared/references/WAFProfile/reference.ftl
- Enable WAF for userpool components
- Add support for Challenge controls on WAF to require CAPTCHA or bot challenges
- Updates the Id lookup for NAT services
Given the focus on user services from attack adding WAF based services to userpools allows for tight control over how the user pool can be accessed
Tested locally and on active deployment
- None
- None
- None
> feat(waf): add support for waf on userpools

- providers/shared/components/backupstore/id.ftl
Change the priority of backups so they come later in the deployment list in order that components to be backed up already exist when the backups deployment occurs.
This minimises the number of double passes needed to fully deploy backups.
- local template generation
- customer site verification
- None
- None
- None
> refactor(backups): default priority

- providers/shared/components/topic/id.ftl
- Adds the ability to define fixed addresses on a topic subscription
We currently use external links to send notifications to endpoints like email addresses, phone numbers etc. This can be complicated to setup for simple tasks like sending notification emails. The fixed endpoint option here provides a more explicit way to do it. 
Tested locally
- None
- None
- None
> feat(topic): add fixed subscription config

- providers/shared/components/cdn/id.ftl
- Adds support for configuring full hostname based aliases on cdn components
Currently adding multiple aliases to a CDN relies on the multiple parent support in the domains component that CDN uses. However this doesn't allow you to have different hostnames just different domains. 
Adding the explicit ability to add multiple aliases allows you to control this as required. 
Tested locally
- None
- None
- None
> feat(cdn): add support for configuring aliases

- engine/base.ftl
Removes the warning message generated when a non standard value is provided on a field that supports non-standard values.
The warning can't be actioned and just raises messages for no real reason, the field allows people to set extra values. 
Improve user experience 
- None
- None
- None
> refactor: remove typical values warning

- engine/output.ftl
Reinstate the naming used for the stack output file generated by the engine
The file wasn't being written properly when pushing a new image
tested locally
- None
- None
- None
> fix: naming for stack output file

- providers/shared/inputseeders/shared/masterdata.json
Updates the default SSLCertificateAuthority for RDS from `rds-ca-2019` to `rds-ca-rsa2048-g1`, as the former is expiring next month.
According to the [AWS docs for this](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL.html), the recommended CA to move to to ensure the same standards is `rds-ca-rsa2048-g1`.
> chore: bump default RDS SSLCertificateAuthority as 2019 CA expiring

- providers/shared/inputseeders/shared/masterdata.json
- Adds a new WAF Rule `whitelistipsipv6`
- Adds a new WAF Condition `whitelistipsipv6`
Works alongside https://github.com/hamlet-io/engine-plugin-aws/pull/809
> feat: WAF ACL's to support IPv6
