aws/manageSSLCertificate.sh
operation list has been added according to https://github.com/codeontap/gen3/pull/1#issuecomment-276800337
=> add delete and list operations to manageSSLCertificate.sh script

aws/addProcessor.sh, aws/addSolution.sh, aws/addStorage.sh, aws/createTemplate.sh, aws/manageCrypto.sh, aws/manageSSHCertificate.sh
@ml019 , please review and merge
=> get the quotes back

aws/templates/container/container_redirector.ftl
=> Add standard container fragment for docker-redirector

aws/templates/application/application_apigateway.ftl, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_userpool.ftl, aws/templates/name/name_userpool.ftl, aws/templates/resource/resource_userpool.ftl, aws/templates/solution/solution_userpool.ftl
Allows for the creation of Cognito User Pools as solution level deployment units.
=> Add Cognito User Pool Support

aws/templates/solution/solution_userpool.ftl
Minor fix for SMS Vertification IAM Policy
=> SMS Verification Policy Fix

aws/templates/resource/resource_userpool.ftl, aws/templates/solution/solution_userpool.ftl
Fix ARN lookup and ExternalId Requirement on UserPools
=> Fix ExternalId Requirement on UserPool Configuration

aws/templates/application/application_apigateway.ftl, aws/templates/id/id_apigateway.ftl
Fix up the UserPool to API Gateway link
=> Fix for UserPool API Gateway Link

aws/templates/common.ftl, aws/templates/id/id_userpool.ftl, aws/templates/name/name_userpool.ftl, aws/templates/resource/resource_userpool.ftl, aws/templates/solution/solution_userpool.ftl
The Client is required as part of the standard UserPool Configuration. This creates it as part of the userPool setup
=> Add UserPool Client to Cognito UserPool Configuration

aws/templates/createSwaggerExtensions.ftl
Retrying formatting for CORS support
=> Fix up formatting for CORS

aws/templates/createSwaggerExtensions.ftl
=> Continued CORS support

aws/templates/createSwaggerExtensions.ftl
When using IAM auth a Lambda function can be called through a gateway using the credentials of the client. This allows that to happen
=> Update Swagger Spec for IAM based Client Auth

aws/templates/resource/resource_userpool.ftl, aws/templates/solution/solution_userpool.ftl
Allow for customised verification and invitation messages on UserPools
=> Add UserPool Custom Messages

aws/templates/policy/policy_ses.ftl
Allow for SES emails to be sent via API/SDK
=> Add SES Basic Send policy

aws/data/masterData.json, aws/templates/segment/segment_vpc.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl
=> update AMIs, userdata and add daily crons

aws/setContext.sh
Some Solution level components, like userpools need environment and component level properties. These are set in the AppSettings but aren't being applied at the moment.
This PR adds an AppSettings lookup for deployment unit level Appsettings on Solutions
=> Add Unit level appsettings lookup for Solution Components

aws/data/ec2_masterdata.sh, aws/data/masterData.json, aws/templates/segment/segment_vpc.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl
I've also added some error checking to the update script to ensure a profile is provided, and at the end it checks if any differences occurred and if so, copies the new file into data/masterData.json.
That way a git status after running the script will reveal any changes.
Note that the script expects to be run in the data directory. There is a .gitignore file there so the amis directory won't be committed.
I've also updated the regular yum job to do a clean all as well as per AWS recommendations
=> Pick up the latest AMIs as of 20180212

aws/templates/segment/segment_vpc.ftl
=> patch NAT EC2 scaling groups

aws/templates/common.ftl
Based on discussion this afternoon, I think I've got myself set up ok with this as my first feature branch.
=> Add basic support for external links

aws/templates/solution/solution_rds.ftl, aws/utility.sh
Minor Typo fixes and notice that RDS Snapshot has started
=> Fixes for RDS Pre-Deploy Snapshot

aws/templates/common.ftl, aws/templates/setContext.ftl
Quick PR to fix a couple of error introduced with my last PR - bad Michael!
=> Correct a couple of syntax errors introduced by pull/99

aws/data/masterData.json, aws/templates/common.ftl, aws/templates/commonApplication.ftl
Support the ability to add an extra part to a host name, or to use the
provided host value as the host name required (as is the case now).
=> More flexible host name control

aws/manageStack.sh, aws/templates/account/account_s3.ftl, aws/templates/application/application_apigateway.ftl, aws/templates/application/application_contentnode.ftl, aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_alb.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_cognito.ftl, aws/templates/id/id_contenthub.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_rds.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/id_spa.ftl, aws/templates/id/id_sqs.ftl, aws/templates/id/start.ftl, aws/templates/resource/resource_apigateway.ftl, aws/templates/solution/solution_contenthub.ftl, aws/templates/solution/solution_spa.ftl, aws/utility.sh
This is a first cut - yet to be tested. Just wanted to give you visibility of the proposed changes.
Fixes #118
=> Move api gateway lambda permissions to lambda component

aws/utility.sh
Fix characters and remove shifts that aren't required
=> Minor fixes for Contenthub Git script

aws/manageStack.sh, aws/utility.sh
Some extra changes for git sync script
=> Further fixes for Git sync

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_ecs.ftl, aws/templates/common.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/id_sqs.ftl, aws/templates/name/name_s3.ftl, aws/templates/solution/solution_s3.ftl, aws/templates/solution/solution_sqs.ftl
Manage SQS permissions via link roles
Start refactoring use of occurrence/tier/component in generating names/ids.
=> Add SQS link role support

aws/templates/createBlueprint.ftl
Generates a blueprint template which lists the configuration, attributes and parent objects of a deployed Segment based on the segment directory you are in. 
The blueprint shows the full tree from Tenant down to the Component Occurrences with the idea that this could be merged with blueprints from other segments to create a complete picture of what has been deployed/configured
=> Create documentation blueprint with deployment details

aws/utility.sh
Update git pull utility to return 0 status
=> Add return on git pull utility

aws/templates/application/application_contentnode.ftl, aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/id/id_rds.ftl, aws/templates/solution/solution_rds.ftl
Fixes #146
Ensure RDS solution works for iam/lg units even if DB configured but not deployed.
Change contenthub use of occurrence - use tier/component on the occurrence object
=> RDS solution and application contenthub corrections

aws/templates/id/id_ecs.ftl
=> Correct ECS log group id

aws/data/masterData.json, aws/templates/id/id_rds.ftl, aws/templates/resource/resource_rds.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_rds.ftl
AutoMinorVersionUpgrade property is supported on the tier, segment, solution and environment levels.
per  #139
=> add support for controlling AutoMinorVersionUpgrade property

aws/templates/resource/resource_cognito.ftl, aws/templates/solution/solution_userpool.ftl
Adds ability to add email and SMS invite message templates as appsettings properties
Fixes #160
=> Cognito UserPool Invite Message

aws/setContext.sh
Avoid processing the appsettings twice
=> Correct logic for solution level appsettings

aws/templates/id/id_sqs.ftl
=> Standardise format of queue names

aws/createTemplate.sh
Also simplify the logic flow somewhat when creating templates.
=> Detect exceptions during template generation

aws/templates/application/application_ecs.ftl, aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_lambda.ftl, aws/templates/resource/resource_event.ftl, aws/templates/setContext.ftl
=> Component configuration enhancements

aws/templates/solution/solution_cache.ftl
=> Correct CIDR format

aws/templates/common.ftl, aws/templates/id/id_cache.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_rds.ftl, aws/templates/id/id_sqs.ftl, aws/templates/solution/solution_cache.ftl, aws/templates/solution/solution_rds.ftl
Fixes #182 
Convert the cache template to use occurrences. Improve the default
handling of rds and cache.
Add the component full name as an extra attribute of the Core object so
it can be used when defining resource names. Convert existing usage of
formatSegmentFullName to use this new attribute instead.
=> Occurrence support improvements for rds and cache

aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_cache.ftl
Fixes #187 
there's a few related but distinct changes here so they should be rebased and merged rather than squashed.
=> Bugfix ecs container template

aws/templates/commonApplication.ftl
=> Throw exception if no build commit provided for container

aws/templates/common.ftl
=> Remove link fallback processing

aws/templates/commonApplication.ftl, aws/templates/id/id_ecs.ftl
=> Give containers a default link to their lb

aws/templates/account/account_waf.ftl, aws/templates/common.ftl, aws/templates/resource/start.ftl, aws/templates/setContext.ftl, aws/utility.sh
Fixes #217 
* Add an "account" category for account level resources.
* Refactor IP address group processing to correct handling of multiple entries in one address group.
=> Correct WAF template and IP address group processing

aws/manageStack.sh
A couple of typo fixes for the manageStack script.
=> Typo fixes for manageStack

aws/templates/createSwaggerExtensions.ftl
Remove ?as_values from userpoolARN hash
=> Minor fix for userpool swagger mapping 

aws/templates/application/application_apigateway.ftl
Mostly stripping trialing whitespace but also simplify the code used to get the IP whitelist for API Gateway documentation buckets.
=> Simplify code for IP whitelisting of API Gateway docs bucket

aws/templates/application/application_apigateway.ftl, aws/templates/id/id_apigateway.ftl
Allow use of mapping with API gateways mirror current usage by default.
=> Support current default for mapping usage in API gateways

aws/templates/solution/solution_rds.ftl, aws/utility.sh
Minor fix to add region information to KMS decrypt function
=> Fix KMS decryption configuration

aws/templates/id/id_ecs.ftl
Minor fix to variable name for ECS
=> Updated ResourceType for ECS cluster to new variable name format

aws/templates/resource/resource_vpc.ftl
A but of code tidyup as well as this is very old code
=> Correct attribute for security group ingress rules

aws/templates/id/id_rds.ftl, aws/templates/solution/solution_rds.ftl, aws/utility.sh
Adds an encrypted URL attribute to RDS outputs. The URL is a single string containing all of the properties required to connect to the database
=> Add Encrypted RDS URL to attributes

aws/templates/solution/solution_userpool.ftl
Fixes after testing the user pool cli configuration setup. 
When passing in a configured JSON file if a value is "" it is not treated as null and is instead validated against the property conditions. So moves the config to only add what is required. 
also a minor typo fix for the epilogue script
=> Fixes for Userpool cli configuration update

aws/templates/id/id_lambda.ftl, aws/templates/setContext.ftl
Also spelling of variable
Not sure how this one made it through - framework basically didn't run
=> Correct syntax error

aws/templates/container/container_jenkins.ftl, aws/templates/policy/policy_ecs.ftl
Adds ecs management policy which allows for task definition creation and run/stop of tasks.
=> Adds ECS Task Management Policy

aws/setContext.sh
Fix for case where product not being used e.g. manage account
=> Check product is defined - it isn't when managing accounts

aws/setStackContext.sh
Do comparisons against the value of SEGMENT rather than the value of
SEGMENT_SUFFIX.
=> Correct detection of default segment

aws/data/masterData.json, aws/templates/application/application_computecluster.ftl, aws/templates/common.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/resource/start.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl
Fixes https://github.com/codeontap/codeontap/issues/16
#- **New Component: Compute Cluster**
- A compute cluster is an autoscaling ec2 level application deployment it allows for the deployment of code at the ec2/virtual machine level. 
- Deployment: the root directory of the code must contain a script called init.sh which is called on startup as root of an ec2 instance in the auto scale group. Any other code that is saved in the same location of the init.sh or subdirectires will be zipped and copied to the ec2 instance in /opt/codeontap/scripts
- Code Deployment: A rolling update or replacement (depending on configuration of compute cluster)  will be triggered on each code update. This works by updating the launch config logical cloudformation Id with the build reference, this forces …
=> Add Compute Cluster component and refactor init configuration

aws/templates/createSwaggerExtensions.ftl
generate an extended swagger specification with a "/{proxy+}" path to pass through the requests to invalid urls and get 404 instead of 403
see https://forums.aws.amazon.com/thread.jspa?threadID=216684 for details
=> add proxy+ path support

aws/templates/common.ftl
This is a temporary fix until we refactor build reference management.
=> Support cross-segment build references

aws/templates/application/application_computecluster.ftl, aws/templates/id/id_computecluster.ftl
Update Ids to be generated from coreId naming
=> Compute Cluster updates to use instance based Ids

aws/manageCrypto.sh
Checked locations need to align to new directory structure and location
variables.
=> Correct directories checked for file crypto

aws/templates/solution/solution_rds.ftl
Adds some fixes for when an RDS instance is deleted 
- Disable the epilogue and prologue scripts 
- Add a retain deletion policy to the option group as it is used by snapshots of the instance that are left behind after deletion. This includes manual snapshots and the snapshot performed by cloudformation on deletion 
Also adds a helper psuedo stack on creation when you want to create a database that will be used to restore a snapshot. This will be replaced on the first pre-deploy snapshot
=> Fix issues with the deletion of an RDS instance

aws/templates/solution/solution_userpool.ftl, aws/utility.sh
If a userpool has been configured with a domain using the cli it can not be deleted with cloudformation until the domain has been removed.
This adds a prologue script to delete the domain name before removing the userpool
=> Add delete function for userpool domain

aws/templates/id/id_lambda.ftl, aws/templates/policy/policy_lambda.ftl
Provides the policy required for a component to invoke a lambda function
=> Add Lambda invoke role for linking configuration

aws/templates/resource/resource_lb.ftl
Fix formatting layout for idle timeout
=> Fix for idle timeout

aws/templates/application/application_computecluster.ftl, aws/templates/application/application_ecs.ftl, aws/templates/solution/solution_ec2.ftl
Some minor fixes for the security group registration process when linking to a load balancer.
=> Fixes for security group load balancer setup

aws/templates/id/id_rds.ftl
The incorrect config parameter was being checked.
=> Correct addition of encryption scheme to RDS creds

aws/templates/id/id_es.ftl
Add URL and port details to elasticsearch attribbutes
=> Add extra ElasticSearch Attributes

aws/templates/id/id_rds.ftl, aws/templates/solution/solution_rds.ftl
Allows for parameters to be set on an RDS Instance
=> Add DBParameters to RDS solution

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_spa.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_spa.ftl, aws/templates/resource/resource_cf.ftl, aws/templates/solution/solution_spa.ftl, aws/utility.sh
=> Enable compression by default for SPA and API

aws/templates/application/application_lambda.ftl, aws/templates/id/id_lambda.ftl, aws/templates/resource/resource_event.ftl
an additional property for a schedule object to support json input
=> support json input for cloudwatch events

aws/templates/application/application_lambda.ftl, aws/utility.sh
=> release ENIs

aws/templates/application/application_user.ftl, aws/templates/id/id_user.ftl, aws/templates/resource/resource_iam.ftl, aws/templates/solution/solution_user.ftl
Fixes for system user support.
Also moves the componet from solution to application for container fragment support
=> Fix user config

aws/runTask.sh
Allows for the container name to be explicitly set for a runTask
=> Add Container name override for runTask

aws/templates/application/application_user.ftl, aws/templates/id/id_user.ftl
- Allow a single user to have multiple credential formats 
- system - IAM AccessKey/SecretKey 
- console - AWS console user name and password
- Fix link based policies
- Make system credentials available as attributes for linking purposes
=> User component updates and fixes

aws/templates/id/id_lb.ftl
Minor change too add the path attribtue to a load balancer. This is useful for apps which need to know the URL for redirects, links etc.
=> Add path attribute to LB Attributes

aws/data/masterData.json, aws/templates/account/account_s3.ftl, aws/templates/application/application_datapipeline.ftl, aws/templates/common.ftl, aws/templates/id/id_datapipeline.ftl, aws/templates/policy/policy_datapipeline.ftl, aws/utility.sh
Adds support for the provisioning of data pipelines as codeontap components #410 
The pipeline provides as set of environment level parameter values which should reduce the configuration required at the infrastructure level of a pipeline. 
Links provide the various input and output data locations that might be required as part of a pipeline processing task
=> Add Data pipeline support

aws/templates/application/application_datapipeline.ftl
=> Add pipeline code stage uri

aws/templates/application/application_datapipeline.ftl
=> Create sec group iam

aws/templates/application/application_datapipeline.ftl
=> Fix up IAM setup for pipelines

aws/utility.sh
fixed filter value and added wait for 5 seconds to get an ENI detached - not the best solution, probably needs to be replaced with a proper wait loop.
=> Release enis fixes

aws/snapshotRDSDatabase.sh
=> ignore SEGMENT in DB_INSTANCE_IDENTIFIER if it is default

aws/templates/application/application_datapipeline.ftl
A few minor updates for the datapipeline
=> DataPipeline : Update variable config and add AWS region 

aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_cache.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/id_spa.ftl, aws/templates/id/id_sqs.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_lb.ftl
Always provide the "Enabled" attribute for any config attribute with
children.
Add checking of config attribute type.
Add checking of config attribute values.
Add more flexibility in use of default values to be combined with any
provided values.
Once this PR is merged, we can incrementally improve the config to incorporate these new features.
=> Improved Configuration Validation

aws/templates/id/id_apigateway.ftl, aws/templates/id/id_cognito.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/id/id_contenthub.ftl, aws/templates/id/id_datapipeline.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_efs.ftl, aws/templates/id/id_es.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_lb.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/id/id_rds.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/id_spa.ftl, aws/templates/id/id_sqs.ftl, aws/templates/id/id_user.ftl, aws/templates/resource/resource_event.ftl
Add Type and Values to all config definitions
=> Add additional config validations

aws/templates/id/id_mobilenotifier.ftl, aws/templates/id/id_user.ftl
- Align the notifier prefix with the SNS permissions role. 
- Fix type for system user configuraiton
=> Update notifier permissions and update type for system user

aws/templates/solution/solution_ecs.ftl
minor fixes for ECS link lookups for EFS mounts.
=> Fix ecs efs lookup

aws/templates/id/id_mobilenotifier.ftl, aws/templates/policy/policy_sns.ftl
Add ARN's to cover the different ways that notifications can be published
=> Fix notifier arn policy

aws/templates/account/account_s3.ftl
Allow for undefined registry sharing config
=> Fix registry sharing config

aws/data/masterData.json
Minor fix for S3 CORS configuration to align master data property with the resource expected property
=> Fix cors property name

aws/utility.sh
Nothing to pipe the output too
=> Minor fix for elb utility

aws/templates/solution/solution_mobilenotifier.ftl, aws/utility.sh
Minor fix to allow for updates
=> Fix notifier logic

aws/templates/application/application_user.ftl, aws/templates/id/id_user.ftl
Add permissions overrides for users so that minimal permissions can be applied
=> Add permissions overrides for user

aws/templates/solution/solution_userpool.ftl
Minor fix for user pools. Usually a userpool is deployed with a load balancer or api gateway which requires an app client to be configured for the site to work. AWS elastic search instances create there own app client so they don't need our config.
=> only configure app client if urls are available

aws/templates/id/id_mobilenotifier.ftl
=> Correct sms log group id format

aws/templates/common.ftl
Some minor fixes from the migration of Name to Names for configuration attribuets
=> Fix name names refactor

aws/templates/createComponentReference.ftl, aws/templates/setContext.ftl
Clean up attribute details section
=> Fix feature formatting

aws/templates/base.ftl, aws/templates/common.ftl
Also fix domain handling where only a secondary domain is configured.
=> Fix config attribute array conversion

aws/contextTree.sh
Correct format of messages
Use git_mv for renames so they show up as git renames.
Pop temp dir at the end of processing so temp path doesn't keep growing.
=> Various bugfixes

aws/templates/solution/solution_userpool.ftl
Now that attributes create arrays when specified we don't need to create them in solution level template generation
=> Minor fixes to reflect attribute changes in userpool

aws/templates/application/application_apigateway.ftl
In order to minimise the need for multiple deployment passes, define and
staging variables that hold lambda function names irrespective of
whether the lambda is deployed. Normally lambdas are sequenced after the
corresponding api to ensure the resource permissions are created
correctly, but currently that then means a second pass of the api
gateway template is needed to define the corresponding stage variable.
=> Define stage variable for lambda even if its not deployed

aws/data/masterData.json, aws/templates/segment/segment_vpc.ftl
Also a minor fix to make sure that if a network is listed in the index but it is disabled it will still disable the network 
Also moved global tier out of the network index since deploying  a global network would be pretty hard
=> Fix global network definition

aws/templates/createSwaggerExtensions.ftl, aws/templates/resource/resource_lambda.ftl
Missed reference to context not _context
Conditionally invalid function call
=> Correct appointments build deploy failures

aws/templates/solution/solution_spa.ftl
The global tier id was shortened - need to align to that.
=> Align spa redirect lambda link to masterdata

aws/contextTree.sh
A bug in the original 1.3.1 logic meant that it did not rename all
files, particularly template files.
The logic of template file detection meant that if stack processing was
then performed, it was possible to end up with two instances of the
stack file in the cmdb.
The 1.3.1 logic has been upgraded to detect and where possible delete
the duplicate files, or flag the need for manual intervention where
differences exist.
In order to pick up cmdbs that were upgraded with the original 1.3.1
logic, 1.3.2 simply reruns the current 1.3.1 logic. In most cases, it
will be a no-op.
=> Repeat 1.3.1 upgrade

aws/utility.sh
Minor fix for platform app creation
=> Fix for PlatformApp lookup

aws/templates/solution/solution_spa.ftl
Adds a couple of safety checks for enabling the CFRedirect lambda@Edge function 
- Check that we have more than one alias for the distribution 
- If we do make sure that the cfredirect lambda@Edge function has been deployed and is available 
This removes an issue where the cfredirect configuration is added but the lambda@Edge deployment is not. This causes issues with the host header forwarding required for the function to work properly
=> SPA CFRedirect saftey checks 

aws/templates/solution/solution_lb.ftl
minor fixes on Load balancer configuration to exclude the HTTP based load balancer actions from classic and network load balancers as they do not support them
=> Exclude http based rules from other LB

aws/utility.sh
Check for bucket existence so scripts don't fail when buckets are
legitimately missing.
=> S3 utilities better handle missing bucket

aws/templates/common.ftl, aws/templates/id/id_cognito.ftl, aws/templates/solution/solution_ElasticSearch.ftl
Fixes external support for userpools and reverses the incorrect implementation of type processing of external links
=> Revert skipping type handling for external and add cognito ext support

aws/templates/swagger.ftl
Value for sig4 and api key set if any of the explicitly defined verbs
have them set.
=> Default OPTIONS verb follows explicit verbs

aws/templates/id/id_ecs.ftl
Fix to allow for role to be created in iam pass
=> Minor fix for run task role lookup

aws/runPipeline.sh
Add ability to run pipeline from Jenkins. 
This will be used to activate pipelines manually or from webhooks
=> Add pipeline run

aws/templates/base.ftl, aws/templates/engine.ftl, aws/templates/id/start.ftl, aws/templates/name/start.ftl, aws/templates/resource/start.ftl, aws/templates/setContext.ftl
This engine supports qualification and overrides on any configuration
object, along with a new way to manage cmdb loading.
There is further work to do but this release gets the core processing
engine into the master branch.
=> First cut of new processing engine

aws/utility.sh
the aws cli wait command has a time limit on it when waiting for a snapshot to become available. This overrides that and starts the wait command again when the wait command fails 
```
It will poll every 30 seconds until a successful state has been reached. This will exit with a return code of 255 after 60 failed checks.
```
=> Extend rds snapshot wait time

aws/templates/solution/solution_s3.ftl
Minor fix to only run S3 bucket policy macro during template pass.
=> Fix for when s3 bucket policy is created

aws/data/masterData.json
Update to the latest ami regions. This should hopefully help with some stability issues with new nitro based instances t3,m5 and also updates the ecs agent to the latest version. 
Also adds in the new eu-north-1 region
=> Jan - AMI Updates

aws/runExpoAppPublish.sh
A collection of minor fixes to the expo app publishing script based on testing.
=> Fixes to expo app publish

aws/runExpoAppPublish.sh
Adds the ability to host a single version of each SDK build in order to support app update migrations
=> Add support for multi sdk builds

aws/runExpoAppPublish.sh
Adds the ability to detect whether a binary build is required. If the app version or SDK versions are changed a new binary will be generated 
Adds a dynamic build number to ensure that we can upload binaries that have not had an app version change 
Separates generating QR codes from generating binaries. This allows you to use the Expo Client for android without building a binary for android 
Adds an HTML based report to let you know what has been done for a publish
=> Expo Publish - Binary Build detection and detailed html reports

aws/templates/application/application_ecs.ftl
Minor fix for resource lookups with monitoring of resources
=> fix ecs parent resources

aws/runExpoAppPublish.sh
Use public bucket for build report and fix homebrew install
=> Update homebrew install and s3 syncs

aws/runExpoAppPublish.sh
Add the release channel to the EXPO QR url. With the Expo client this adds a badge to the app icon so you can tell them apart
=> <feat> expo release channel

aws/templates/commonApplication.ftl, aws/templates/policy/policy_ec2.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/solution/solution_ec2.ftl
Adds datavolume support to ec2 for an independent data volume which can be moved between components
=> extends datavolume support to ec2

aws/templates/resource/resource_ec2.ftl
Some CFN scripts depend on others in order to get their job done. 
This adds a number based priority to all cfn init scripts to ensure that they are executed in the correct order. 
The order is set by the array which defines the config sets to run. So we just order this array based on a prefixed number to determine priority
=> add priority ordering to cfn init scripts

aws/templates/fragment/fragment_jenkins.ftl
Uses inbuilt java configuration to determine the memory allocation based on the containers max memory limit
=> jenkins fragement memory configuration

aws/templates/id/id_datavolume.ftl, aws/templates/id/id_ecs.ftl
A couple of minor fixes for the data volume id section and determining when to add an execution role
=> <fix>Data volume id ecs execution

aws/templates/segment/segment_baseline.ftl
some minor fixes for testing S3 notifications to SQS queue in the baseline component
=> <fix>Minor fixes from testing SQS notifications from S3

aws/templates/resource/resource_s3.ftl, aws/templates/segment/segment_baseline.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_s3.ftl
add support for suffix filtering in S3 notifications.
=> <feat>S3 Notification suffix

aws/templates/resource/resource_vpc.ftl, aws/templates/segment/segment_gateway.ftl
Make sure that gateway attachment has completed before adding routes for IGW
=> <fix> igw routes depend on attachment

aws/templates/application/application_ecs.ftl
Minor fix to remove extra nested NetworkConfiguration object from ECS Service Template
=> <fix>Remove extra NetworkConfiguration Object

aws/runExpoAppPublish.sh
Environment config is provided as an array with an object in it
=> <fix> mobileapp jq merge of settings

aws/templates/policy/policy_dynamodb.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_configstore.ftl
A couple of minor fixes found when testing the config store deployments
=> <fix> minor fixes for intial configstore deploys

aws/templates/solution/solution_userpool.ftl
missed alternative value in ?then statement
=> <fix> syntax issue in custom domain removal

aws/templates/application/application_datapipeline.ftl, aws/templates/resource/resource_vpc.ftl
Adds support for port ranges in ingress security groups
Adds default policy to pipeline ec2 instances
=> <fix>VPC security port lookup for ranges

aws/templates/segment/segment_network.ftl
a couple of minor fixes up for the lookup of igw details
=> <fix>igw legacy resource lookup

aws/templates/policy/policy_dynamodb.ftl
Minor fix for dynamodb arn formatting
=> <fix>dyanmoDb arn formatting

aws/templates/resource/resource_vpc.ftl
Fix the resource Id and id lookup for Igw and vpc configuration
=> <fix>vpc id lookup for resourceId lookup

aws/runExpoAppPublish.sh
Align IOS configuration to standard pattern
=> <fix>Expo p12 file variable

aws/runExpoAppPublish.sh
Adds support for IOS push notification certificates in expo builds
=> <feat> Expo add ios push certificate support

aws/data/masterData.json, aws/templates/solution/solution_spa.ftl
Switch to use of a profile to select WAF rules.
=> <refactor> Update WAF support for SPA

aws/templates/common.ftl, aws/templates/setContext.ftl
Support the ability to automaticaly add components to domains to
minimise the amount of config necessary to get segment/environment info
into domains and certificates.
=> <feature> Domain inclusions

aws/templates/common.ftl, aws/templates/id/id_cw.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_es.ftl, aws/templates/id/id_kinesis.ftl, aws/templates/id/id_userpool.ftl, aws/templates/policy/policy_cmk.ftl, aws/templates/policy/policy_es.ftl, aws/templates/policy/policy_kinesis.ftl, aws/templates/policy/policy_lambda.ftl, aws/templates/resource/resource_cw.ftl, aws/templates/resource/resource_kinesis.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ElasticSearch.ftl
This PR comes has two new features 
datafeeds for ES indexes which creates a kinesis firehose stream which can be used to stream data into elasticsearch 
The firehose manages the index and its rotation policies along with buffereng and failure detection. Failed uploads are dropped into an S3 bucket and you can also pipe the stream through a lambda function to modify the data before its sent to the data destination 
On top of datafeeds you can also add logwatchers which will add subscriptions to cloudwatch logs that forward filtered logs through to the firehose . This is similar to the logwatchers we have for lambda calls which directly invoke a lambda function based on a filtered log being found 
**Note** to use firehose with cloudwatch log subscriptions ( via logwatchers ) you need to …
=> <feat>Elasticsearch logwatcher using kinesis data firehose

aws/templates/id/id_userpool.ftl, aws/templates/solution/solution_userpool.ftl
Ignore disabled subcomponents of a userpool.
=> <bugfix> Ignore disabled auth providers

aws/createTemplate.sh
#690 
Update doco to reflect segment unit requirements
=> <refactor> templates: remove segment unit control

aws/templates/solution/solution_spa.ftl
Align SPA solution with operations bucket id changes for baseline unit.
=> <bugfix> SPA S3 Access

aws/templates/id/id_userpool.ftl
Wrong variable used for creating the URL I think.
=> <bugfix> Base URL for Userpool custom domain

aws/templates/id/id_network.ftl, aws/templates/segment/segment_network.ftl
Correct the igw gateway reference in the vpc support for legacy igw.
Also correct a few variable name spelling errors.
=> <bugfix> Legacy IGW support

aws/templates/id/id_configstore.ftl, aws/templates/solution/solution_configstore.ftl
Adds support for using a branch name as a secondary sort key for a config table branch. This aligns with DynamoDb sort keys which can be used to create a unique Id if your primary keys have duplicate values 
Having duplicate primary keys is useful when querying since most dynamdb interactions are based on the keys with extra attribute filtering available after the primary key query has been done. 
When enabled on a config store the branches subcomponent Id is used for primary key value and the subcomponent name is used for the secondary key value
=> <feature> config tables - secondary keys

aws/templates/resource/resource_waf.ftl
Only include OWASP config if explicitly requested.
=> <refactor> Change default OWASP logic

aws/templates/swagger.ftl
As per https://swagger.io/docs/specification/authentication/ 
The securityDefinitions has now moved to components -> securitySchemes in openapi  spec. 
This detects the version of the specification and adds the security config where its supposed to go
=> <fix> apigw: openapi3 support for security srvs

aws/templates/application/application_apigateway.ftl, aws/templates/id/id_userpool.ftl
Use the cognito api arn instead of the userpool id when using cognito authentication
=> <fx> apigw: use cogntio api arn

aws/templates/id/id_datafeed.ftl
Adds some basic attributes to datafeeds for linking purposes
=> <fix> datafeed: add basic attributes

aws/templates/resource/resource_lb.ftl
upper case protocols for lb and convert attributes to strings
=> <fix> lb protocol casing

aws/templates/application/application_lambda.ftl
Fragment id is specific to the function.
=> <fix> Derive lambda fragment id from fn

aws/templates/application/application_computecluster.ftl, aws/templates/id/id_bastion.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/segment/segment_bastion.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl
This shouldn't require any cmdb change as the component level is already included in the hierarchy when looking for settings.
=> <refactor> Locate server role via occurrence

providers/aws/component/application/application_apigateway.ftl, providers/aws/component/id/id_userpool.ftl
Fix up defaulting for userpool attribute cleanup
=> <fix> api gateway userpool auth header

aws/templates/fragment/start.ftl, providers/aws/component/application/application_apigateway.ftl, providers/aws/component/application/application_computecluster.ftl, providers/aws/component/application/application_datapipeline.ftl, providers/aws/component/application/application_ecs.ftl, providers/aws/component/application/application_lambda.ftl, providers/aws/component/application/application_mobileapp.ftl, providers/aws/component/application/application_spa.ftl, providers/aws/component/application/application_user.ftl, providers/aws/component/segment/segment_bastion.ftl, providers/aws/component/solution/solution_configstore.ftl, providers/aws/component/solution/solution_ec2.ftl, providers/aws/component/solution/solution_ecs.ftl, providers/aws/component/solution/solution_spa.ftl
Make fragment mode global to align with macros which depend on it 
Also removes extra fragment pass in lambda functions
=> <fix> fragment mode global

providers/aws/component/baseline/setup.ftl, providers/shared/component/component.ftl
A couple of minor fixes to the baseline oai lookup for bucket policy
=> <fix> baseline: oai key lookup for bucket policy

providers/aws/component/serviceregistry/setup.ftl
=> <fix>servreg: network link lookup

providers/aws/component/baseline/setup.ftl
Minor fix when looking up the OAI key in bucket policy
=> <fix> baseline: fix legacy oai lookup for bucket policy

aws/createTemplate.sh, aws/templates/base.ftl, aws/templates/resource/start.ftl
Implement a logging approach aligned to that used in the script
utilities.
This makes the framework available to all providers.
The level of logging included is controlled by GENERATION_LOG_LEVEL.
This means macros can be left enabled but won't generate output unless
their corresponding level is enabled.
Refactor the existing exception detection to work off the new format.
Support serialising messages as comments for scripts so the messages
don't break the script functionality.
=> <feature> Generic logging

aws/runExpoAppPublish.sh
- Adds a workaround for setting the release Channel in the export manifest files 
- Adds an initial commit for using fastlane to build an expoKit based app
=> <feature> fastlane builds for expoKit apps

aws/runExpoAppPublish.sh
some minor fixes from testing new process
=> <fix> Minor fixes to publish job for expo

engine/component.ftl
Change to debug due to subset passes
=> <fix> change severity for missing macro

providers/aws/masterData.ftl, providers/aws/masterData.json
Updates masterdata based on the changes to the Id Name configuration in master data
=> <fix> Add id and name config for child components

providers/aws/masterData.ftl, providers/aws/masterData.json
Add Id and Name to cfredirect versions and instances
=> <fix> instance and version name for cfredirect

aws/runExpoAppPublish.sh
extends the expo fastlane build support to match what we found during testing
=> <feature> Expo Fastlane build support

aws/runExpoAppPublish.sh
A few minor updates 
- Remove verbose logging information about updates 
- Add extra returns for failures 
- Fix up version and bundle identifier updates
=> <fix> Expo fastlane build updates

aws/runPipeline.sh
A couple of changes to datapipeline running 
- Pipeline concurrency checking which won't activate the pipeline if another one is already running 
- This defaults to enabled 
- Better status reporting of pipeline jobs that are running
=> <feature> Pipelines add concurrency saftey and logging

providers/aws/components/sqs/id.ftl
@roleyfoley seems a good one for Ross to get his first review medal.
=> <fix> SQS has a dependency on cloudwatch for alarms

aws/runExpoAppPublish.sh
Extra update so that the certificate aligns with the expected profile
=> <fix> update code sign identity for iphone

aws/runExpoAppPublish.sh
align with different parameter names for the same thing
=> <fix> fastlane - fixup parameter name

aws/runExpoAppPublish.sh
=> <fix> force identity lookup for codesigning

aws/runExpoAppPublish.sh
=> <fix> fastlane certificate import

aws/runExpoAppPublish.sh
When a binary build has completed upload the file to AWS Testflight requires a App Specific password based on 
https://docs.fastlane.tools/actions/upload_to_testflight/
=> Expo Testflight submission

providers/aws/components/baseline/setup.ftl
Minor fix to align with changes to getBaselineLinks
=> <fix> baseline parameter lookup

engine/occurrence.ftl
Inject default values based on suboccurrence key.
=> <fix> Default id/name in suboccurrence processing

aws/runExpoAppPublish.sh
Some minor fixes from testing
- Remove artefact cleanup since this can be done by the automation job
- Fix up parameter name 
- Remove unused type check
=> <fix> expo testflight fix up naming of variable

providers/aws/components/userpool/setup.ftl, providers/aws/components/userpool/state.ftl
fix to restore role for userpool after it was removed during the refactoring of federated roles
=> <fix> userpool role id lookup

aws/runExpoAppPublish.sh
Minor fixes to the expo build script
=> <fix> bunlde hosting location and remove cleanup

aws/runExpoAppPublish.sh
Apple Id means different things in different places :(
=> <fix> fastlane fix app id for upload

aws/runExpoAppPublish.sh
=> <fix> Expo publish syntax

aws/runExpoAppPublish.sh, aws/runSentryRelease.sh
Introducing a script that allows to upload source maps files for a specified release. Sentry CLI is installed using yarn, configuration is done via environment variables on Jenkins level.
=> <feature> sentry releases

aws/runExpoAppPublish.sh
Adds an override for the expo id manifest file to get around an issue with file system
=> <feature> expo app id override

aws/runExpoAppPublish.sh, aws/runSentryRelease.sh
specify the url-prefix for sentry release files
create a sentry release for each export
=> <feature> upload source maps for the current expo sdk version only

aws/runExpoAppPublish.sh
Some minor fixes to the expo id override updates
=> <fix> expo id override

providers/aws/components/contenthub/setup.ftl
Minor typo fix for contenthubs
=> <fix> contenthub typo

providers/aws/components/apigateway/setup.ftl, providers/aws/components/contenthub/id.ftl, providers/aws/components/contenthub/setup.ftl
- Fix up pseudo stack output to enable deployment detection 
- remove external type from link type lookups
=> <fix> contenthub deployed detection

providers/aws/components/contentnode/setup.ftl
Remove break that was used in old loop based occurrence processing
=> <fix> cleanup loop config from contentnode

engine/commonApplication.ftl
=> <fix> taskContainers remove old debug

providers/aws/components/ecs/setup.ftl, providers/aws/components/lb/setup.ftl, providers/aws/components/lb/state.ftl
Extension of #910 to allow for this to work in state as well as setup
=> <fix> Lb Port Id name lookup

providers/aws/components/lb/setup.ftl
Add opsData bucket lookup for lb
=> <fix> lb baseline lookup for lb logging

providers/aws/components/apigateway/setup.ftl
Fix to align with how utility script actually works not how I thought it did :)
=> <fix> APIGw: fix for publisher copying

providers/aws/components/apigateway/setup.ftl
Remove the dist directory from swagger copies
=> <fix> APIGw Swagger dist copy

providers/aws/components/gateway/state.ftl, providers/aws/components/lb/state.ftl, providers/aws/components/mobilenotifier/setup.ftl, providers/shared/components/baseline/id.ftl
Fix a few spelling errors and make error messages unique so its more
obvious where an error is occurring.
Also fix an error when an undefined variable was referenced in a debug
statement.
=> <fix> Correct spelling of Unkown

engine/common.ftl, engine/setContext.ftl
Also add a couple of utility routines to reduce the amount of code
duplication.
=> <fix> Add id/name defaulting for domains and certificates

providers/aws/components/federatedrole/setup.ftl
A couple of minor fixes to handle federated role validation rules
=> <fix> Federated role validation rules

providers/aws/components/federatedrole/setup.ftl, providers/aws/components/userpool/state.ftl
Some minor fixes after testing rule based federated role assignments 
- fix up client attribute overrides from parent
- Fix up rule mapping type
=> <fix> identity pools fixes for rule based rules

providers/aws/components/federatedrole/state.ftl, providers/aws/services/cognito/resource.ftl, providers/shared/components/federatedrole/id.ftl
- Adds federated role attributes 
- Minor fix in attribute property for role mapping default behaviour
=> <feature> Federated Role Attributes

engine/swagger.ftl
A couple of minor fixes for swagger updates 
- Remove nested path for proxy responses 
- make schemes an array
=> <fix> swagger paths and schemes for swaggerv2

providers/aws/components/datafeed/setup.ftl, providers/aws/components/s3/setup.ftl, providers/aws/services/kinesis/resource.ftl, providers/shared/components/datafeed/id.ftl
Adds support the S3 as a datafeed/kinesis firehose destination
Some slight differences between the ES backend and the S3 one but nothing major 
Also adds fix for baseline lookup on S3 components
=> <feature> datafeed s3 destination 

providers/aws/components/s3/state.ftl, providers/aws/services/s3/policy.ftl
Add datafeed role permissions for kinesis to send to S3
=> <fix> datafeed S3 permissions

providers/aws/components/ec2/setup.ftl
Minor fix to add Volume Mounts into ec2 context
=> <fix> add VolumeMounts into ec2 setup

providers/aws/components/dataset/state.ftl
Minor fix to align with the new db database component type
=> <fix> dataset - update to support new db component type

providers/aws/components/cdn/setup.ftl, providers/shared/components/cdn/id.ftl
Adds support for managing custom error responses for CDNs. It maintains the error page configuration from the SPA while also adding the ability to specifc response code handling as well
=> <feature> CDN Error Response config

aws/manageDeployment.sh
deploying existing Azure ARM templates /w COT CMDB.
Implimenting in the AWS directory for now, to be split out as we separate out more of the provider-specific features of COT into provider-independent scripts.
Closes codeontap/gen3-azure#18
=> feature - manageDeployment

providers/shared/components/db/id.ftl
Silly thing behind the keyboard making problems
=> <fix> RDS note typo

aws/runPipeline.sh
minor fix to pipeline activation logic and sleep between state check
=> <fix> AWS Pipeline activation logic

providers/shared/components/network/id.ftl
=> added missing comma

aws/createReference.sh, providers/aws/components/es/id.ftl, providers/aws/components/federatedrole/setup.ftl, providers/aws/components/userpool/state.ftl, providers/shared/deploymentframeworks/default/legacy.ftl
This PR fixes external link state lookup when using the legacy occurrence model. When an external link has a type defined the state macro for the component should be called based on the placement profile. 
Along with these fixes this PR also includes some attribute alignment between an external and managed userpool attributes to make sure it works during linking
=> <fix> external links userpools

aws/utility.sh, providers/aws/components/userpool/setup.ftl, providers/shared/components/userpool/id.ftl
Adds support for OIDC federation with Cognito Userpools. Configuration can either be provided through settings or solution configuration as the URLS can get quite long and the client secret should be encrypted
=> <feature> OIDC userpool federation

engine/output.ftl
- expose the output component behaviour so it can be varied
- change the default to add rather than append
- override the behaviour for merging content into an existing json output
=> Ensure adding output works for arrays and objects

providers/aws/components/userpool/setup.ftl, providers/aws/services/cognito/resource.ftl
Follows on from #980,  but now with the added benefit of having RTFM
=> <fix> Userpool temp password validity

providers/aws/services/autoscaling/resource.ftl, providers/shared/components/component.ftl
@roleyfoley , a small fix for ScaleOut type of Cooldown object
=> <fix> ScaleOut type of Cooldown

providers/aws/components/datavolume/setup.ftl
disable maintenance window setup when backups are disabled
=> <fix> datavolume disablebackup

providers/aws/components/mobilenotifier/setup.ftl
=> <fix> mobileplatform typo

engine/bootstrap.ftl
Typo fix for determining the accountRegion
=> <fix> command line option typo

engine/bootstrap.ftl
And fix the product Region as well
=> <fix> CommandLine productRegion typo

providers/aws/services/vpc/resource.ftl, providers/shared/references/Category/id.ftl, providers/shared/references/Environment/id.ftl, providers/shared/references/Region/id.ftl
Make sure Id and name are available on reference data which is used in naming 
Also use .Configured check for ports now that it's available
=> <fix> add id/name for environments and fix port lookup

aws/templates/createBlueprint.ftl, providers/aws/components/bastion/setup.ftl, providers/aws/components/datapipeline/setup.ftl, providers/aws/components/ec2/setup.ftl, providers/aws/components/ecs/setup.ftl, providers/aws/services/ec2/resource.ftl
When hibernating an autoscaling group make sure to set the maximum above the minimum number in the group 
Also add an error message if an ssh key can not be found
=> <fix> Ec2 Autoscale hibernate

engine/setContext.ftl, providers/shared/references/IPAddressGroup/id.ftl
Fix IPAddress Group reference loading
=> <fix> IPAddress Group Reference Data

engine/swagger.ftl
Pass through any fields in an openapi path object that don't correspond to verbs (including the AWS "any" verb)
=> <fix>Support additional fields of path objects in openapi

providers/aws/components/ecs/setup.ftl, providers/aws/components/ecs/state.ftl, providers/shared/components/component.ftl
The PR contains two minor fixes:
1) The correct default value for scaling policy type
2) Event Rule as a part of CF template for Fargate ESC task.
=> Minor fixes for scaling policy and task schedule

providers/shared/references/Port/id.ftl
Missed Certificate in port configuration
=> <fix> Port Reference attribute for certificate

aws/utility.sh, providers/aws/components/db/setup.ftl, providers/aws/masterData.ftl, providers/aws/masterData.json, providers/shared/components/db/id.ftl, providers/shared/references/SecurityProfile/id.ftl
A new PR instead of accidentally closed #1028
=> update RDS CA epilogue script

aws/utility.sh
Workaround for jq using 'null' for a missing value instead of no string
And a heap of whitespace cleanup
=> <fix> eni release script for lambda

aws/utility.sh
Make sure we wait for the rds instance to be in a happy state to be updated
=> <fix> RDS update CA Fix

providers/aws/services/iam/resource.ftl
Fixes #1048
Groups IAM policies into a new policy resource based on a grouping limit
=> <fix> IAM policy group statements to allow for size limit

providers/aws/services/iam/resource.ftl
use a smaller number for policy file
=> <fix> IAM policy - use smaller grouping number

providers/aws/services/iam/resource.ftl
Introduce a length limit and nested grouping
This feels a little crazy but seems to be the best we can do
=> <fix> IAM Policy length

providers/aws/services/iam/resource.ftl
Add outputs on managed policy so we can switch between the iam subsets
=> <fix>Managed Policy Output for IAM subset

providers/aws/components/user/setup.ftl
minor copy and paste fix for user link policies
=> <fix> user link policy id

providers/aws/components/user/setup.ftl
Fix subset dependencies between managed policy and attachment for the user component
=> <fix> user - fix managed policies dependencies

providers/aws/components/db/setup.ftl
Fix up RDS CA update output to reduce rds-ca config
=> <fix> RDS output variable for pseduo stack

aws/runTask.sh
closes #1064 
runTask has been failing to locate the ECS Cluster and Task as a result of the recent changes to when id/name is added
This PR uses a generated blueprint to locate the ECS details instead which ensures that the cluster ARN can be found
Still need to search for the ARN of the task since deploys don't save state
- Adds support for instance and version on the task and cluster 
- Updates outputs to provide more detail
- use awscli query for JSON filtering where possible
=> <fix> runTask locate task using blueprint

aws/createTemplate.sh
Align the createTemplate help text with configuration of the script
Add option for setting the input source to document the option
=> <refactor> Cleanup createTemplate help

providers/aws/ec2_masterdata.sh, providers/aws/inputsources/shared/masterdata.ftl, providers/aws/masterData.json
Bump the AMI images to the latest versions to apply security updates
=> <chore> Update AMI Ids to latest images

aws/manageFileCrypto.sh
Adds support for setting the key alias and key id on manageFileCrypto
=> <fix> Add kms key options to manage file crypto

aws/runLambda.sh, aws/runTask.sh
Some mostly syntax fixes for the run Lambda task script
=> <fix> Run Lambda Task script

providers/aws/components/s3/setup.ftl
to enable versioning without enabling expiration rules
=> <fix> check if lifecycle is enabled when adding an expiration rule

providers/aws/components/topic/setup.ftl, providers/aws/services/sqs/policy.ftl
Adds support for Lambda and SQS to be used for topic subscriptions
=> <feature> SNS topic Subscriptions for AWS services

aws/createTemplate.sh
wrong condition for skipping the context setup
=> <fix> Create template mock skipping

aws/runExpoAppPublish.sh, aws/runLambda.sh
Make build blueprint output explicit
=> <fix> build blueprint outdir

providers/aws/components/user/setup.ftl
Main use will be for development to test access to S3 based resources.
=> <Feature> Add asFile support for user component

engine/inputdata/setting.ftl
Fortunately my mis-spelling was consistent
=> <fix> Minor typos in settings loading

engine/commonApplication.ftl, providers/aws/components/apigateway/state.ftl, providers/shared/components/externalservice/id.ftl, providers/shared/components/externalservice/state.ftl
Adds support for external services to use fragments
Which also adds support for _context environment control
Minor fix for apigateway region lookup
=> <feature> ExternalService Fragment and Env control

aws/utility.sh
Add a routine to determine whether a given semver value lies within a range of values.
Also add extra convenience methods for logging.
=> <Feature> semver range checking

aws/contextTree.sh
Upgrades to newer cmdb versions can now be prevented unless the gen3 framework version is compatible.
This allows support for new cmdb features to be added without triggering immediate updates for clients who have yet to move to a compatible version of gen3.
=> <Feature> Constrain cmdb upgrades

aws/createTemplate.sh
Don't create defaults for output dir as it works based on empty values
=> <Fix> template output default

aws/contextTree.sh, aws/setContext.sh, aws/utility.sh
Reorder the searches to favour the more common cmdb directory layouts.
Preference v2.0.0 as it will become the most common layout.
=> <refactor> Prepare for transition to v2.0.0 cmdb format

aws/utility.sh, providers/aws/components/baseline/setup.ftl
some minor fixes
- Fail if file can't be found during file encryption
- align order of encrypt_kms_files params
=> <fix> ssh key encryption variable order

aws/manageDeployment.sh
This PR introduces a load of the Azure utilities scripts.
=> created load of azure utilities shell script.

providers/aws/components/bastion/setup.ftl, providers/aws/components/bastion/state.ftl, providers/aws/components/ec2/setup.ftl, providers/aws/components/ec2/state.ftl, providers/aws/components/ecs/setup.ftl, providers/aws/components/gateway/setup.ftl, providers/aws/components/gateway/state.ftl, providers/aws/services/vpc/resource.ftl
Catch up with the latest tagging support with EIP support
=> <feature> EIP Tagging Support

providers/aws/services/ec2/resource.ftl
Make sure storage profile is the expected type before looking for volumes
=> <fix> storage profile volume lookups

aws/utility.sh, providers/aws/components/db/setup.ftl
A minor fix for correct db URL generation
=> <fix>pass engine to get_rds_url function

providers/aws/components/topic/setup.ftl
A couple of macro fix ups from #1136
=> <fix> Topic macro naming

aws/manageDeployment.sh
Closes #1154 
- Provider registration now correctly handles more than 1 provider.
- Updated the pretty-print of the output to no longer be an info-level output.
=> corrected provider registration being unable to handle an array

providers/aws/components/bastion/setup.ftl, providers/aws/components/cache/setup.ftl, providers/aws/components/computecluster/setup.ftl, providers/aws/components/db/setup.ftl, providers/aws/components/db/state.ftl, providers/aws/components/ecs/setup.ftl, providers/aws/components/es/setup.ftl, providers/aws/components/es/state.ftl, providers/shared/components/es/id.ftl, providers/shared/references/Processor/id.ftl
A collection of updates for ES 
- Adds support for ES on VPC 
- Moves cognito from CLI to Cloudformation 
- Adds logging support to cloudwatch 
- Adds Processor support for controlling node counts with fixed counts 
- Version upgrade support for ES cluster - by default cloudformation replaces on version changes 
Updated processor profile reference to include specific coniguration for each component type which use processor profiles
=> <feature> ES Improvements

providers/aws/components/db/setup.ftl
=> <fix> Align RDS Cluster instance CA

execution/freemarker.sh
Fix up freemarker wrapper location
=> <fix> freemarker wrapper path location

aws/manageSSLCertificate.sh, aws/rebootRDSDatabase.sh, aws/runExpoAppPublish.sh, aws/runLambda.sh, aws/runSentryRelease.sh, aws/runTask.sh, aws/snapshotRDSDatabase.sh, aws/updateObjectACL.sh
Cleanup cleanupContext.sh location
=> <fix> fix cleanupContext location

aws/templates/createBlueprint.ftl, aws/templates/createBuildblueprint.ftl, providers/aws/components/dataset/state.ftl, providers/aws/components/es/state.ftl
Adds support for ES dataset snapshots for promotion via the s3 dataset approach
=> <feature> es dataset support

engine/openapi.ftl
valueIfTrue doesn't appear to work for this comparison, the only way I could get it to work was to add the actual freemarker ?then syntax
=> <fix> valueIfTrue for swagger options

execution/contextTree.sh, execution/setStackContext.sh
Permit mixed case paths to cmdbs.
Correct minor syntax error in setStackContenxt.sh
=> <fix> Corrections for cmdb v2.0.1 upgrade

execution/contextTree.sh
Minor typo in v2.0.1 legacy handling.
=> <Fix> Legacy handling for v2.0.1 upgrade

providers/aws/components/es/setup.ftl
Add support for restoring data from an S3 dataset into an ES snapshot store
=> <feature> Add support for ES S3 restoration

providers/aws/components/userpool/setup.ftl
Add support for external services in userpool client links
=> <feature> userpool client external service support

providers/aws/components/apigateway/setup.ftl
Yell if the certificate can't be found so that cloudformation doesn't have to do it for us
=> <feature> APIGateway - error on missing cert

providers/aws/components/federatedrole/setup.ftl, providers/aws/components/userpool/state.ftl
minor fixes on federated role attributes to align with userpool configuration
=> <fix> Federated role attributes for userpool

providers/aws/components/dataset/state.ftl
Adds some missed parameters for build S3 based ES snapshots as S3 datasets
=> <fix> Dataset ES location attributes

aws/templates/createBlueprint.ftl, aws/templates/createBuildblueprint.ftl
Allows for the optional title details on blueprint files
=> <fix> Blueprint support for optional title details

aws/templates/createBlueprint.ftl
Add support for name attribute in blueprint
=> <fix> Add name support in blueprint

execution/setContext.sh
So we can easily manage tenant and product level profiles, add a file pattern to include these in the blueprint.
=> <feature> Permit loading of a dedicated file for profiles

aws/runTask.sh
Remove the null conversion as build blueprint always has a value ( empty included ) defined for Instance/Version Name 
Adds a type search to make sure its the right thing
=> <fix> runTask fix up the lookup for instances

aws/runTask.sh
falling asleep at the wheel...
=> <fix> RunTask Variable substituion

aws/templates/account/account_sms.ftl
Update account template to align with latest settings handling.
This is a temporary fix until account support gets refactored to use occurrences etc.
=> <fix> Account SMS configuration

providers/aws/components/es/setup.ftl, providers/shared/references/Storage/id.ftl
Some minor fixes for provisioned IOPS support
=> <fix> Storage Profile type and Iops

engine/base.ftl
ensure function call is conditional on the content
=> Fix Number Attribute If Content

Jenkinsfile, test/aws/run_aws_template_tests.sh
On successful completion of testing trigger a docker image build
=> <feature> jenkins docker build

providers/aws/inputsources/mock/commandlineoption.ftl, providers/shared/inputsources/mock/blueprint.ftl, providers/shared/inputsources/mock/commandlineoption.ftl, providers/shared/inputsources/mock/masterdata.ftl
A couple of minor fixups to the mock data to make it vendor agnostic.
=> <fix>Align mock data to providers

execution/setContext.sh
Permit profile files to be defined at the shared and segment level.
=> <fix> Shared and segment level profiles

providers/aws/components/apigateway/setup.ftl, providers/shared/components/apigateway/id.ftl
Permit individual publishers for an API to be disabled.
=> <feature> Allow API publishers to be disabled

providers/aws/components/gateway/setup.ftl, providers/aws/components/network/setup.ftl
Check that suboccurrences are not disabled before processing them.
=> <fix> Ignore disabled network and gateway subcomponents

providers/aws/components/lambda/setup.ftl
minor fix to lambda release script﻿
=> <fix>Typo in lambda ENI script

providers/aws/components/userpool/setup.ftl
Use Cloud Formation to define the complete set of lambda triggers rather than using the CLI to do it.
This is now possible because of updated Userpool support in Cloud Formation.
=> <fix> All userpool lambda triggers set by CF

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, PULL_REQUEST_TEMPLATE.md
Created PR and Issue templates to standardise the documentation around features, bugs etc. etc.
Leaving open to discuss the templates, will merge once we're all happy with them.
=> PR and Issue Templates

engine/commonApplication.ftl
Minor fix to align with settingName function changes in #1281 
Casing control was provided for integration with external templates
Tested with active deployment
=> <fix>Missed setting name casing

providers/shared/components/template/id.ftl
Add Link Component configuration to Tempaltes
Templates already had support for Link processing, however the links component configuration wasn't added
Tested in local deployment
=> <fix> template links

providers/shared/components/db/id.ftl
Allow for any encryption scheme to be used for databases
This allows the user to set any scheme which works with their application or preference
Tested locally
=> <refactor> remove encryption scheme value requirements

engine/common.ftl, engine/setContext.ftl
Removes skuProfiles from the shared provider, as changes to setContext prevent other providers from loading.
Breaking bug.
Removing newly added content only.
=> removed sku profiles from shared

engine/bootstrap.ftl
This PR swaps around the two following data imports in bootstrap.ftl:
Current order: 
- start off the blueprint by importing shared masterdata
- import both shared and plugin providers including their reference data.
The order of operations at present prevents the load of reference data from plugin providers.
locally tested on my machine using the Azure plugin provider and the new reference data dype `skuProfiles`.
=> Fix - Reference Data from Plugins

providers/shared/components/baseline/id.ftl
Add's a 3rd type of data bucket role that may be defined on a baseline component - "staticWebsite"
Azure has an interesting way of enabling static website access on a Storage Account container - the container must be called $web and simply by calling it this it is available to be setup as a SPA backend. Adding this role allows the logic behind this to be seperated out from the rest of the data stores.
Locally generated and deployed.
=> Feature - New Data Storage Role

engine/common.ftl, providers/shared/components/userpool/id.ftl
Companion PR to https://github.com/hamlet-io/engine-plugin-aws/pull/31 which allows for the encryption scheme to be specified, this will be added to the attribute value
Helps support securing the user pool client secret
=> feature(userpool): Add Encryption schema to cient secrets

providers/shared/deploymentframeworks/default/legacy.ftl
When determining which subcomponents to generate, look for the definition of the subcomponents on the instance or version configuration.
Previously, subcomponents could only be defined at the component type level.
The use case driving this PR was an API lambda function when one instance was based on python and another on javascript. Without this fix, it was only possible to have one runtime defined for the entire lambda component in the solution.
As with other configuration, it is still possible to provide this variability via profiles, but this change will permit this to be more conventionally represented in the solution itself.
Permit more flexibility in subcomponent configuration
Customer deployment
=> refactor: Subcomponent config on instance/version

providers/shared/inputsources/shared/masterdata.ftl, providers/shared/references/SecurityProfile/id.ftl
Alows for configuration of the HTTPSProfile for network load balancer engines
Supporting Master data changes for https://github.com/hamlet-io/engine-plugin-aws/pull/58 
=> feat(lb): Network load balancer TLS offload

providers/shared/references/TestCase/id.ftl
1. Added parameters.json, prologue.sh and epilogue.sh to available TestCase OutputSuffix types.
2. Minor syntax updates.
1. Passes for all 3 are now available. Primarily I wanted this for parameters.json which is used by the azure plugin.
Currently creating Azure provider test cases and will use this to test against the parameters.json file.
=> Feature - Latest Output Suffix Types for TestCases

legacy/account/account_console.ftl, providers/shared/references/BaselineProfile/id.ftl
Updates the existing console account level unit with the following:
- Enables KMS encryption for SSM Sessions
- Adds support for both S3 and cloudwatch for SSM session log storage 
- Moves to Cloudformation for creating the document now that the Session Document Type is supported 
- Includes a cleanup script to remove the old documents and to also override manual updates which were made before this was applied 
Session manager is very useful in secure environments where internet access isn't permitted, these environments usually have strong encryption requirements so we need to support these and also support logging to different data stores 
=> feat(console): Update console support for encryption

providers/shared/components/lb/id.ftl
Adds support for WAF configuration on load balancers
WAF is a common front door function which we enable for CDN's and API Gateways, this should also be available on  load balancers which support HTTP based inspection
=> feat(lb): WAF integration

providers/shared/references/Bootstrap/id.ftl, providers/shared/references/Bootstrap/reference.ftl
Adds additional configuration attributes to the Bootstrap reference data type.
The Azure provider handles the execution of bootstrap scripts with a specific resource type for Virtual Machine Extensions. A common scenario will be to want to group these extensions together by purpose along with their individual configurations for simple re-use. hamlet already has a reference data type for these by way of `BootstrapProfiles` and `Bootstraps`. 
The additional configuration required by Azure VM Extensions is also general enough that it could easily be adapted for other providers or even for support of more advanced shell/powershell scripts that accept inputs. (Whether hamlet should actually support this is another thing entirely...)
An alternative to this implementation would be to have the …
=> Refactor - Bootstrap Reference Data

legacy/fragment/fragment_hamlet.ftl
Allows for setting global AZ environment variables for authentication with Azure 
These settings would generally be the same across a whole hamlet tenancy. To ensure they are available to all tasks run on the agent we make them available via the agent container env vars
Tested locally
=> Hamlet Agent - Azure default environment variables

providers/shared/inputsources/shared/masterdata.ftl
Add a description to the global outbound rule
Better understanding and also makes sure that if an older rule is replaced we can track when this was used
Tested locally
=> fix(masterdata): add global outbound rule description

providers/shared/components/component.ftl, providers/shared/components/secretstore/id.ftl
Initial implementation of the `secretstore` component, incl. `secret` subcomponent.
Currently credentials are managed in a variety of ways across providers. Hamlet allows for the encryption and storage of secrets within the CMDB, however it has become common for cloud providers to offer secret management services. This change will enable hamlet providers to support those secret stores and reduce the need for the encryption and storage of values within a Hamlet solution.
Definition only
=> New Component - SecretStore

providers/shared/components/userpool/id.ftl
Adds supports for email verification type.
To support a verification email for Cognito with a link instead of code.
=> feature(cognito): support email verification type

engine/setContext.ftl
Adds support for finding the subnet CIDR ranges using IP Address Groups. 
subnets can be looked up using the syntax in an IPAddressGroups array
`_tier:<tier id>` 
This will return all of the subnets for the provided tier
This is useful for services like network load balancers which only support IP based security groups 
Tested locally
=> feat: tier based network lookup

client/createSchema.ftl, engine/component.ftl, engine/inputdata/reference.ftl, engine/schema.ftl, engine/setContext.ftl, providers/shared/deploymentframeworks/default/legacy.ftl, providers/shared/deploymentframeworks/default/output.ftl, providers/shared/schemas/schemas.ftl
Adds a new deployment level "schema", which creates [JSONSchema](https://json-schema.org/) output files.
There are two initial subsets implemented currently - `reference` and `component`
`component` creates a JSONSchema for the definitions of all discovered components. Configuration for a given component is discovered and combined across all providers and then implemented collectively. Additional configuration that is defined by a plugin can be identified by its name-spaced attribute name:
```json
{
"aws:QueuePermissionMigration": {
"type": "boolean",
"description": "Deprecation alert: set to true once policy updated for queue",
"default": false
}
}
``` 
`reference` creates a JSONSchema for similarly discovered Reference Data.
Bigger examples at the bottom.
hamlet-io/docs#5
Local schema …
=> Feature - Template Deployment Level "Schema"

engine/openapi.ftl
* Allows for the setting of `apigateway` throttling within an `apigw.json` settings file
* throttling can be set at any combination of API, Version and Method levels
Would like to be able to throttle an API Gateway to prevent the backend from getting overwhelmed
Local template generation and deployment (with corresponding AWS PR)
=> Enable throttling settings on apigw

engine/openapi.ftl
Refactors the API Gateway components throttling configuration into a simpler structure.
* We don't need the "API" level of rate limiting, as as it is, one "stage" or "version" becomes a unique apigateway instance anyway - so its effectively covered by the "Stage" level rate limiting config.
* The existing attribute "Patterns" on the component can be used for creating the method-level rate limits.
* Also implements throttling based on quota as well - A quota has a limit and time period, and if set, throttling will occur if the limit is exceeded within the time period.
Refactor to make better use of existing attributes. Desire to implement rate limiting based on a quota.
Still requires testing.
- [ x] New feature (non-breaking change which adds functionality)
=> Feat apigw throttling

providers/shared/components/component.ftl
Would like to offer the capability for rate limiting on a WAF.
Local template generation and deployment in AWS provider.
=> Enable Configuration of WAF IP Rate Limiting

providers/shared/deploymentframeworks/default/output.ftl
Define the output format for the pregeneration subset.
The format was not specified resulting in no output macro being invoked.
=> fix: Pregeneration output format

legacy/fragment/fragment_hamlet.ftl
Minor fix to the hamlet agent fragment to support EFS link based properties volumes
Allows for the hamlet agent to mount the efs share with properties files on demand instead of relying on the host to have it mounted
=> fix(fragment): hamlet agent properties mounts

providers/shared/components/ecs/id.ftl
minor fix to include deployment details for the base ecs component. 
Seems to have disappeared along the way somewhere...
=> fix(ecs): reinstate deployment details

engine/common.ftl, engine/commonApplication.ftl, engine/occurrence.ftl
Implement additional build reference scopes
See https://github.com/hamlet-io/executor-bash/pull/95 for background.
=> feat: "account" and fixed build scope

engine/openapi.ftl
For a token based authorizer, allow the integration configuration to include toekn validity expressions.
Try and do as much validation via the api gateway as possible.
Client deployment
=> feat: add support for token validity expressions

engine/openapi.ftl
fix typo in openapi template
Ye Ol Squiggle vs Normal bracket
Tested locally
=> fix: typo in openapi syntax

engine/base.ftl, engine/commonApplication.ftl, engine/inputdata/setting.ftl, engine/occurrence.ftl, engine/openapi.ftl, engine/output.ftl, engine/setContext.ftl, providers/shared/deploymentframeworks/default/output.ftl, providers/shared/flows/components/flow.ftl, providers/shared/flows/context/context.ftl, providers/shared/views/blueprint/setup.ftl
Change all usage of "COT" to "Hamlet".
Tidy up activity to align messaging with renaming of the framework.
Should only be merged AFTER
=> refactor: switch COT to Hamlet

engine/openapi.ftl
Add case insensitive match for "bearer".
Spec calls for this and in general, good to be generous in what we accept.
=> fix: case insensitive token validity expression

engine/openapi.ftl
Correct the http status on the api gateway for the case of an authorizer failure.
Error was incorrectly being reported as a 500.
=> fix: 403 status on authorizer failure

engine/openapi.ftl
Align messages included in code mapping to the http status code being returned.
Align to avoid confusion.
=> fix: authorizer failure messages

engine/openapi.ftl
Permit the template used to generate the output for each api gateway status to be customised on a per status basis.
Accommodate the possibility of different formats for different status values.
=> feat: template control per api gateway status

engine/base.ftl, engine/schema.ftl, providers/shared/views/schema/setup.ftl
Updates to Hamlet JSONSchema:
* Components with SubComponents now define JSONSchema "reference" attributes to their children.
* Created mechanism for simply defining new sub-schemas and allowing them to be easily referenced (dubbed "metaparameters" but effectively they are "common" schema)
* Created first metaparameter - Links
* Addresses 1/2 follow-up actions outlined in hamlet-io/docs#52
* Links are large in size, and everywhere. Metaparameters allow for re-use of already shared configuration.
Local schema generation : `hamlet create template -i mock -l schema -u metaparameter -o .`
Not going to track them here but will be on the lookout for more metaparameters and flesh out the practice more so its more extensible at every level of a blueprint.
=> Feat: New Schema Type - metaparameters

engine/base.ftl
Add utility routines to support processing of semver based version identifiers.
These routines will be used as part of transitioning cmdb migrations from bash scripts to within the hamlet engine.
=> feat: semver support

engine/occurrence.ftl, providers/shared/flows/components/flow.ftl
Adds a couple of changes to the occurrence and its processing 
- Adds an occurrence cache to reduce the repetition of occurrence building during link processing  
- Moves the setting namespace configuration for the occurrence into it's own section of the occurrence. This keeps the settings lookups consistent and also allows them to be visible to users without having to modify the hamlet code itself ( with debug statements ) 
Occurrence caching is for performance reasons 
SettingNamespace is for better user understanding
Tested locally
=> Occurrence Updates

legacy/account/account_iam.ftl, providers/shared/references/ServiceRoles/id.ftl
Adds support for providing a description to service linked roles
Allows for existing roles to be folded into the cloudformation service linked roles support
Tested locally on active deployment
=> fix(aws-iam): add descriptions for service roles

engine/setContext.ftl
Corrects a global variable that was renamed during a recent file relocation.
It's failing baseline template generation.
Templates generate once more.
=> fix(s3): renamed global var back to dataOffline

engine/setContext.ftl, legacy/account/account_ecs.ftl
Minor fix to the check we perform on layer content
Now that we use getCompositeObject to construct the layer content, the layer will always return default values, so we now need to check if the Id field has content to determine if the layer was found or not. We should remove some of this processing in the future but this will do the job for now
Tested locally
=> Layer details

engine/common.ftl
Extend range of attributes supported on CertificateBehaviours object
Template generations were failing.
Local template builds
=> fix: possible certificate behaviour attributes

engine/common.ftl
Provide a more complete list of parts that make up host and domain behaviours.
The current list of inclusions doesn't cover some scenarios which are being used by current projects.
=> fix: expand range of certificate behaviours

providers/shared/layers/Account/id.ftl
minor fix to account layer configuration to align with implementation
Template generation was currently failing
Tested locally
=> fix(accountlayer): fix console logging

providers/shared/layers/Account/id.ftl
Implement a new Account-layer attribute Provider
issue #1465
Not yet tested. will be with the incoming executor repo changes.
* contributes to hamlet-io/engine#1462
* unblocks hamlet-io/executor-bash/issues/128
* Closes  #1465
=> updated account layer by adding provider attribute.

providers/shared/views/schema/setup.ftl
Corrected the `metaparameter` scheme generation.
Note: I restructured the input object to reflect how it would appear as a `reference` or `component` composite object. This is in preparation for a subsequent PR to define metaparameters as their own data structure.
The schema generation macro for this data type was incorrectly being told to reference metaparameters (itself) instead of defining its schema.
=> fix(schema): metaparameters should not ref links

engine/common.ftl, engine/setContext.ftl, providers/shared/inputsources/mock/blueprint.ftl, providers/shared/layers/Account/id.ftl
We updated AWSId attribute for account layer with ProviderId.
hamlet-io/engine#1463
Required further changes in other repos in order to be tested.
Series of other issue hamlet-io/engine#1462.
Closes hamlet-io/engine#1463
=> Refactor Account layer's AWSId attribute to ProviderId

engine/occurrence.ftl
Remove a stray bracket from `occurrence.ftl`
Broke execution of anything
Local testing
=> fix: erroneous bracket

providers/shared/components/component.ftl, providers/shared/components/mta/id.ftl, providers/shared/flows/components/flow.ftl
Initial configuration for #1499 
The "Message Transfer Agent" component represents the capability to send or receive emails. Each occurrence either supports sending or receiving. If both are required, two occurrences should be configured.
An MTA may have zero or more rule subcomponents. Rules are evaluated in order and if they fire, execute a sequence of actions.
While debugging the MTA, a couple of logging improvements to the component flow were also made.
Local template generation and customer deployment
=> feat: MTA component

engine/schema.ftl
JSONSchema is able to define a property as "any of the following" data
types, defined as an Array of Objects, each object with a single
attribute - "type".
Currently the JSONSchema being generated will define this structure
incorrectly, placing each object inside of its own array. This is not
only incorrect JSONSchema but also invalid JSON more broadly.
This removes the additional arrays, so the resulting array isThis is not
only incorrect JSONSchema but also invalid JSON more broadly.
This commit removes the unnecessary level of arrays.
current structure:
```json
[
[
{
"type" : "string"
}
],
[
{
"type" : "bool"
}
]
]
```
new structure:
```json
[
{
"type" : "string"
},
{
"type" : "bool"
}
]
```
Some schemas are wrong/invalid.
Local schema generation.
=> fix: schema assignment of multiple data types

providers/shared/components/externalnetwork/id.ftl
Updates the external network configuration schema to include the required attributes for alerting
Allows for alerting on resources deployed as part of external network integration 
Tested locally
=> feat(externalnetwork): Alerting support

engine/schema.ftl, providers/shared/deploymentframeworks/default/output.ftl, providers/shared/entrances/entrance.ftl, providers/shared/entrances/schemaset/entrance.ftl, providers/shared/entrances/schemaset/id.ftl, providers/shared/views/schema/setup.ftl, providers/shared/views/schemaset/setup.ftl, providers/shared/views/view.ftl
* Refactor schema generation to have one file per data type unit. 
* Introduce new entrance - `schemaset` which is used to generate a `schemacontract.json` file. This contract defines the stages/steps required to output all schema definitions for a data type i.e all component schemas.
Closes #1477
Local schema and schema set generation
```
$GENERATION_DIR/createTemplate.sh -i mock -e schema -o . -l component -u baseline
$GENERATION_DIR/createTemplate.sh -i mock -e schemaset -o . -l component
```
=> Feature - Individual Schemas Per Unit

providers/shared/references/ComputeProvider/id.ftl
Update composite object attribute name.
This appears to have been missed in https://github.com/hamlet-io/engine/pull/1514
n/a
=> Bugfix: Updated Composite Object Attribute

providers/shared/tasks/create_schemas/id.ftl, providers/shared/tasks/task.ftl, providers/shared/views/schemaset/setup.ftl
Add new task definition for `schemaset` processing
The parameters defined on a task become contract stage/step parameters. As a contract is read by the python executor, the parameters defined within are passed as arguments to the CLI. The necessary parameters required for schema contract processing is slightly different to existing tasks, hence a new one is required.
Local schema contract generation.
=> Feat - Schemaset Task Type

providers/shared/components/network/id.ftl, providers/shared/layers/Environment/id.ftl, providers/shared/layers/Segment/id.ftl
Remove/disable flag based configuration settings for flowlogs.
Support for flowlogs now needs to be explicitly included on the network component. These changes ensure the default configuration does not trigger the checks in place to report usage of the legacy format of flowlog configuration.
=> fix: flowlog configuration

providers/shared/components/baseline/id.ftl
Adds support for adding extensions to keys. 
The main purpose is to allow for user definition of policies which apply to some key types ( cmk ) t
Tested locally
=> feat(baseline): add support for extensions on keys

legacy/account/account_s3.ftl
A fix to the script store cloning process which was using an older syntax for the clone_git_repo utility function
The script was failing to run as the repo couldn't be found
TEsted locally
=> fix(account): update script store clone setup

providers/shared/extensions/jenkins/extension.ftl
A minor update to the jenkins extension which forces the upgrade of plugins which are provided by the Jenkins docker image. 
This ensures that updates are aligned with what we expect in startup scripts and on going maintenance
See https://github.com/jenkinsci/docker/blob/master/README.md for details on the install process
Tested on deployments
=> feat(jenkins): handle plugin upgrades

providers/shared/views/schema/setup.ftl, providers/shared/views/schemaset/setup.ftl
Modules require an accurate, up-to-date method for providing
documentation on their expected structure. This commit introduces
module schemas to the possible JSONSchemas that can be generated,
allowing modules to self-document their inputs.
Addresses concerns raised in hamlet-io/lambda-s3-support#1
example structure:
```json
{
"$schema": "http://json-schema.org/draft-07/schema#",
"type": "object",
"$id": "https://hamlet.io/schema/latest/blueprint/module-consolidatelogs-schema.json",
"definitions": {
"consolidatelogs": {
"type": "object",
"patternProperties": {
"^[A-Za-z_][A-Za-z0-9_]*$": {
"properties": {
"namePrefix": {
"type": "object",
"description": "A prefix appended to component names and deployment units to ensure uniquness"
},
"deploymentProfile": {
"type": "object", …
```
=> Feature - Module JSONSchemas

providers/shared/extensions/cfredirect/README.md, providers/shared/extensions/cleanup/README.md, providers/shared/extensions/couchdb/README.md, providers/shared/extensions/dind/README.md, providers/shared/extensions/esfilter/README.md, providers/shared/extensions/hamlet/README.md, providers/shared/extensions/jenkins/README.md, providers/shared/extensions/logstash/README.md, providers/shared/extensions/mongodb/README.md, providers/shared/extensions/noenv/README.md, providers/shared/extensions/rabbit/README.md, providers/shared/extensions/redirector/README.md, providers/shared/extensions/s3vpcaccess/README.md
Add basic readme for the existing shared provider extensions.
These extensions are distributed with Hamlet and available to everyone, but their intent/purpose isn't documented outside of the extension themselves.
Though the extensions are simple enough to read, they aren't great to link to from other documentation sources such as blog posts, tutorials, etc.
n/a
=> docs: Add basic README for shared extensions

README.md
Revision and overhaul of the Engine readme
Consistency across the Hamlet Deploy ecosystem
Existing content was severely outdated
n/a
=> docs: overhaul and revision of outdated readme

providers/shared/components/bastion/id.ftl
Defines the IPAddressGroups attribute on the Bastion component definition.
This is currently inconsistent with the way that other IPAddressGroups are handled on components. 
N/a - will require provider changes.
=> feat: ipaddressgroups on bastion component

engine/schema.ftl, providers/shared/deploymentframeworks/default/output.ftl, providers/shared/views/schema/setup.ftl
* refactors the formatting of schema paths
* corrects the path to point to the lasted docs site url
* Updates the root schema $Id value to only be assigned for non-module schemas.
- the docs site has moved to a new URL
- schema paths were being calculated a number of different ways, and were inconsistently applied
- Schemas that are not published publicly on the Hamlet docs site should not contain a $id value that links to that site
Closes https://github.com/hamlet-io/engine/issues/1551
Local schema generation
=> Fix - JSONSchema $Id values

engine/common.ftl, providers/shared/components/component.ftl
Domain assembly was updated to validate and handle missing values but was missing the recursive updates required to use the parent relationships
This ensures the values are present and will be updated on each parent
The domain name assembly processes uses a parent relationship to assemble the resulting domain name which will be used for a host name
Tested locally
=> fix: domain assembly process

test/run_shared_template_tests.sh
Align with the cli changes introduced in https://github.com/hamlet-io/executor-python/pull/89
Testing broken 
Will use CI Testing
=> fix: update hamlet cli test cmds

engine/setContext.ftl
Handle a missing Product `Domain` object.
Domain has been removed as a default attribute in the Tenant pattern. It may not exist in a blueprint.
Couldn't run `hamlet setup` before the change, I can after.
=> fix: handle missing product domain

engine/common.ftl
AWS implementation of https://github.com/hamlet-io/engine-plugin-aws/pull/253 
This removes the metric resource setup that we have for monitoring resources 
Makes the monitoring setup obvious that it is only for AWS cloudwatch 
Tested locally
=> refactor: remove metric setup from core

providers/shared/components/sqs/id.ftl
Allows for providers to define and support different queue ordering strategies
Implements: https://github.com/hamlet-io/engine-plugin-aws/issues/257
Tested locally
=> feat(sqs): ordering configuration for sqs queues

providers/shared/components/sqs/id.ftl
fix for #1592 
Templates broken 
tested locally and using test suite
=> fix(sqs): typo in id details

providers/shared/inputseeders/shared/id.ftl, providers/sharedtest/inputseeders/sharedtest/id.ftl
Register seeder in the state pipeline not the config pipeline.
It is intended to seed outputs with mock data so should be in the state pipeline.
Local test suite
=> fix: shared fixture seeder

providers/shared/deploymentframeworks/default/output.ftl
return value for schema output with move to new output handling
Schema generation was failing 
Tested locally
=> fix: schema output return

providers/shared/views/blueprint/setup.ftl
Minor syntax fix in blueprint generation
Template generation was failing for the blueprint
Tested locally
=> fix: typo in blueprint generation

engine/output.ftl, providers/shared/deploymentframeworks/default/output.ftl, providers/shared/views/info/setup.ftl
- correct the filename prefixes for diagrams/info entrances
- fix a macro that should have been a function
Would like things to work
Running the entrances locally
=> [Fix] Output File Names / Macro-ish Functions

Jenkinsfile
Run hamlet bootstrap and update hamlet-cli on testing runs 
Hamlet components are closely linked and we often introduce changes which impact each other. To make sure testing is effective we should get the latest changes to the other components
Testing will be done by Jenkins
=> feat(cd): install the latest hamlet for testing

engine/output.ftl
Ensures a line break is included on each text based output that is generated by the engine.
Fixes #1616 
Tested locally
=> fix: line breaks in text output writing

engine/base.ftl
Ensure the configuration for all explicitly listed attributes are included in the result when a wildcard is specified.
Permit the wildcard to occur anywhere in the attribute list so lists can be concatenated.
Fixes #1598
In reviewing the code, a couple of possible improvements were identified but not implemented as they would constitute a change in functionality. TODOs were added instead.
- handle configuration using any of the attribute name alternatives - currently the name used on the most specific configuration object is used
- When processing attributes that have not been explicitly configured, the `+` operator is used to generate the effective configuration, whereas the use of `mergeObjects()` would more accurately reflect the logic of …
=> fix: composite object wildcard handling

providers/shared/views/schema/setup.ftl
Adds `layer` to the valid schema sections
Closes #1617 
Local schema generation
Once implemented, the schemas will need to be incorporated into the docs reference data on the site.
=> feat(schema): add layers to the valid schema sections

providers/shared/deploymentframeworks/default/output.ftl
Updates the state output type to align with the output handler changes.
Output generation was producing now output for the occurrences entrance
Tested locally
=> fix: update state output to align with output

providers/shared/views/schemaset/setup.ftl
- chore - maintains schemas
Updates the schemaset contract with they `layer` schema section.
Include all schema sections in the schemaset.
Locally
=> chore(schemas): add layer schemas to schemaset

providers/shared/attributesets/attributeset.ftl, providers/shared/attributesets/computeimage/id.ftl, providers/shared/attributesets/ecs_computeimage/id.ftl, providers/shared/components/bastion/id.ftl, providers/shared/components/component.ftl, providers/shared/components/computecluster/id.ftl, providers/shared/components/ec2/id.ftl
Moves compute image source configuration into an attribute set across all compute instance based components
Simplifies the configuration and remove duplication
Tested locally
=> refactor: Compute Image attributeset

providers/shared/components/lambda/id.ftl
Add the specific runtime value needed for using node 14 with lambda.
Keeping up with AWS ...
=> chore: add node 14 support for lambda

client/invokeEntrance.ftl, engine/logging.ftl, engine/output.ftl, legacy/fragment/start.ftl, providers/shared/inputseeders/shared/id.ftl
- Adds support for handling exceptions generated through log messages in the engine itself. This allows for the engine to stop processing if it finds logs which match the stop level
- Adds support for in-line log messages. Once an output has been generated the content of the output is scanned for the presence of Hamlet*: messages which will be included in the logMessages found during processing
- Updates the stop message action to use the logWriter process to output the context of the stop. This allows for extra logs to be included as required.
This allows for the engine to define when things went wrong instead of relying on the …
=> feat: handle log based exceptions in engine

legacy/account/account_s3.ftl
Ensure script store sync function is not empty .
Avoid a bash quirk where functions can't be empty
=> Fix: account s3 code sync

engine/bootstrap.ftl, engine/inputdata/inputsource.ftl, engine/setContext.ftl, providers/shared/inputseeders/shared/id.ftl, providers/shared/inputstages/inputstage.ftl, providers/shared/layers/Account/id.ftl, providers/shared/layers/Product/id.ftl
A range of fixes to use of dynamic cmdb loading. The main fix was to layer processing to avoid layer attribute errors during intermediate passes of the config pipeline.
Prepare for switching from the use of composites to the use of dynamic cmdb loading. Some of the changes are designed so that the blueprint processing in `setContext.sh` can be removed but until filename management is entirely within the engine, it will need to stay in place.
Local template generation, both with and without the CMDB plugin. Test suite was also run locally.
- None
- Bash executor - https://github.com/hamlet-io/executor-bash/pull/202
- AWS - 
- Azure - 
- None
=> fix: dynamic cmdb loading

providers/shared/components/healthcheck/id.ftl, providers/shared/extensions/extension.ftl
- Updates the healthcheck configuration parameters to include some extra configuration options from testing with the aws provider implementation
- Adds an extension macro for specifying the complex healthcheck script when using the complex check type
Cleans up and rearranges the parameters to align with what should work for most providers
Tested locally
- None
- https://github.com/hamlet-io/engine-plugin-aws/pull/282
- None
=> feat(healthcheck): update parameters from testing

providers/shared/extensions/dind/extension.ftl
removes a global assignment of the settings var which was overriding the composite settings global variable
This was overriding the composite settings var that is used during input processing 
Tested locally
- None
- None
- None
=> fix: remove global settings assignement

.dockerignore, .github/workflows/package.yml, Dockerfile
Initial support for creating an aretefact image of the hamlet engine 
Packaging support as part of  https://github.com/hamlet-io/architectural-decision-log/issues/11
- None
- None
- None
=> feat: add support for packaging

providers/shared/extensions/extension.ftl
Adds a macro for providing parameters to template components without having to work within the requirements of the settings configuration
Template parameters support more complex objects like references or other template functions. With settings these are escaped and treated as strings. Using an explicit macro makes it easier to work with templates 
Tested locally
- None
- None
- None
=> feat(template): add parameter extension macro

.github/workflows/test.yml
Adds a pull request trigger to ci testing to make sure we run the testing
testing not testing
Tested on aws plugin 
- None
- None
- None
=> fix(ci): add pull request trigger

engine/setContext.ftl
Support expiration of flowlogs when they are stored in S3.
For now, the same pattern as used for general operations and data expiration was followed.
- None
- https://github.com/hamlet-io/engine-plugin-aws/pull/343
- None
=> feat: s3 flowlog expiration

.github/workflows/changelog.yml, .github/workflows/package.yml, .github/workflows/testing.yml, .gitignore
Updates the pipelines to align with testing and operational usage
- Make the changelog PR a draft and mark the unreleased changes as latest. This allows us to tag the release with a change log and not have to move it
- Only run packaging if the testing passes
- Add support for writing build details into the source
Makes the CI process more stable and easier
Tested with AWS repo
- None
- None
- None
=> refactor(ci): updates from testing and ops

.dockerignore
- adds the .git dir to the dockerignore file to reduce the size of the image
- remove an older wrapper binary from the repo to reduce size
Reduce the size of the docker image and to remove binaries no longer in use
Tested locally
- None
- None
- None
=> refactor(ci): remove git and binaries from docker

.github/workflows/package.yml
Fixes issues with tagging for of images
Was broken 
- None
- None
- None
=> fix(ci): default tag for images

providers/shared/inputseeders/shared/masterdata.json
Add "sqlsvr" as Port 1433 definition
Precondition for supporting MSSQL Server on RDS
Local generation
- None
- None
- None
=> Add sql server port to masterdata

engine/setContext.ftl
- adds some handling when running the component flow on the account level district as it stands
This allows for running the unitlist for account level deployments in their current state where the unit list is built based on a view invoked as part of the unitlist entrance that also runs a component flow as well.
- None
- None
- None
=> refactor: handle non segment districts in flows

engine/openapi.ftl
Move removal of the top level security attribute to just before the result is returned so it removes user defined content as well.
Handle a user provided top level security attribute
- None
- None
- None
=> refactor: swagger 2.0 top level security removal

providers/shared/components/network/id.ftl
Adds configuration for enabling DNS query logging which logs all DNS requests made within a network
Meets auditing requirements and can be useful for troubleshooting issues
Tested with AWS implementation
- None
- None
- None
=> feat(network): dns query logging

engine/occurrence.ftl
Support the ability to include multiple values in build references.
This will permit a transition from deployment unit based references to occurrence based references.
- None
- None
- None
=> feat: multi-value build references

engine/base.ftl
Add the `qualifier:` namespace to the qualifier specific attributes.
A namespace makes it more obvious that qualification is being used and ensures there aren't attribute clashes.
- None
- None
- None
=> refactor: namespace qualifier attributes

providers/shared/inputseeders/shared/id.ftl
When mocking an input, mark it as such so that subsequent providers can choose whether to override an existing value.
Later seeders may wish to replace generic mock values with values more targetted to a specific provider.
TBC
- None
- None
- None
=> fix: whatif state processing

providers/shared/components/component.ftl, providers/shared/components/directory/id.ftl, providers/shared/components/id.ftl, providers/shared/inputseeders/shared/masterdata.json
https://github.com/hamlet-io/engine/issues/1756
- None
- None
- None
=> feat(ds): New Component - Directory Services

providers/shared/components/cache/id.ftl
- Adds descriptions to key cache configuration attributes
- Sets permitted values for the Engine
- Sets the engine version to a mandatory value
Makes the cache configuration aligned with our standard configuration approach and increase documentation details
Tested locally
- None
- None
- None
=> refactor(cache): attribute descriptions

providers/shared/extensions/extension.ftl
cleans up handling of cfForwardHeaders to support arrays of config inline with the macro name
Simple update to handle Headers configuration
- None
- None
- None
=> refactor: cloudfront header extension handling

providers/shared/computetasks/computetask.ftl
Add new computer task definition
https://github.com/gs-gs/ha-ema-arcgis/issues/10
Locally and deployed to AWS
- None
- None
- None
=> feat(av): separate av computer task

providers/shared/flows/components/flow.ftl
Restructure the handling of the legacy logic for lambda functions to better cope with links with no subcomponent but where the occurrence does have suboccurrences.
Unit tests failing.
Local test execution
- None
- None
- None
=> fix: flow legacy lambda handling

.github/workflows/release.yml, README.md
- removes the use of dos2unix in release pipeline
- Updates documentation to highlight install guide
- Uses the right hamlet package for install processes
Removes the need to install extra packages 
Makes it easier to follow install guide
Tested locally
- None
- None
- None
=> refactor: remove use of dos2unix

engine/common.ftl, engine/commonApplication.ftl, engine/component.ftl, engine/extension.ftl, engine/setContext.ftl, legacy/account/account_console.ftl, legacy/account/account_ecs.ftl, legacy/account/account_s3.ftl, legacy/account/account_ses.ftl, legacy/account/account_sms.ftl, legacy/account/account_volumeencrypt.ftl, providers/shared/extensions/logstash/extension.ftl, providers/shared/extensions/rabbit/extension.ftl, providers/shared/flows/components/flow.ftl, providers/shared/views/blueprint/setup.ftl, providers/shared/views/releaseinfo/setup.ftl
Replace the use of global variables in setContext() with accessor functions for the same information.
NOTE: dependent PRs need to be merged at the same time as this PR to avoid failures.
This is in preparation for full district support, where all config and state access needs to be via the input state.
- None
- azure - https://github.com/hamlet-io/engine-plugin-azure/pull/278
- aws - https://github.com/hamlet-io/engine-plugin-aws/pull/421
- None
=> refactor: setContext wrapper functions (1)

engine/setContext.ftl
The global variables that have been converted so far all relate to the AWS provider so make the check more specific so as not to trigger errors with other providers such as Azure.
- Ensure changes work with all providers
- Ensure test suites pass
- 
Local execution of aws and azure test suites
- None
- None
- None
=> fix: condition on setting global variables

.github/workflows/release.yml
Use the HAMLET_ENGINE environment variable which will install and set the global engine on the install of the pip package.
Reduces the setup time as it only requires the setup and install of one engine
Will be tested on this pipeline 
- None
- None
- None
=> refactor(cd): use env for hamlet engine

providers/shared/components/directory/id.ftl
- Updates the default username of the directory component to align with the username used by most providers
- Updates secret linking to allow for either an existing secret or a secret store to generate a secret in
Use more generic default standards and highlight the different ways to provide the secret to the component
- None
- None
- None
=> refactor(directory): rename default username

client/createOpenapiExtensions.ftl, providers/shared/extensions/hamlet/extension.ftl, providers/shared/inputseeders/shared/id.ftl
- Updates json loading to use the freemarker eval_json directive instead of eval
Aligns with the recommendations from freemarker 
https://freemarker.apache.org/docs/ref_builtins_expert.html#ref_builtin_eval 
Tested locally
- None
- None
- None
=> refactor: use eval_json for json loading

providers/shared/inputseeders/shared/masterdata.json
- Adds an _orphan deployment mode to masterdata which defines how to handle orphaned deployments
Changes were added to the management contract step which checked that the provided deployment mode was defined in the solution. If it wasn't the units weren't added to the deployment 
fixes https://github.com/hamlet-io/engine/issues/1795
Tested locally
- None
- None
- None
=> fix: orphan deployment detection

providers/shared/components/mta/id.ftl
Add new attributes to outbound MTA
Required for https://github.com/gs-dawr/exdoc-mail-aws/issues/55
Locally and deployed to AWS
- None
- None
- None
=> feat: outbound mta

engine/commonApplication.ftl, providers/shared/attributesets/containertask/id.ftl
- Adds the gpu attribute to specify the number of GPU's for a container
Allows for configuring/enabling GPU's for container based deployments
tested locally and on deployment
- None
- None
- None
=> feat: add gpu support for containers

engine/common.ftl
Permit the override of the base output points.
Treat outputs provided by the caller as of higher priority than the base set of points added by default (account, region, unit, mode).
This permits the (admittedly rare) situation when the default values are not appropriate. In most cases, the caller assumes the function will add these values.
- None
- None
- None
=> refactor: pseudo stack outputs

providers/shared/components/component.ftl, providers/shared/references/WAFRule/reference.ftl
Add support for WAFv2 controlled by Version attribute
Required for https://github.com/hamlet-io/engine/issues/1768
Locally generated and deployed to AWS
- None
- None
- None
=> Add support for WAFv2

providers/shared/components/template/id.ftl
- Adds the ref attribute to the end of the template to allow for looking setting the ref attribute for sub id suffixes
Allows for a standard ref for properties that don't quite align with the current attributes
tested locally
- None
- None
- None
=> feat: add ref attribute to template

providers/shared/components/component.ftl
Change the WAF default to be v1
Feedback on https://github.com/hamlet-io/engine-plugin-aws/pull/459
Local generation
- None
- None
- None
=> feat: set waf default to v1

engine/extension.ftl
Ensure extension defaults do not override any values provided by component implementations.
Ensure existing extension processing works as expected.
Local generation of SPA
- None
- None
- None
=> fix: Extension defaults handling

engine/base.ftl
- Adds support for creating a compressed set of attributes. The compression finds duplicate attributes based on the Names field of the attribute and combines the attributes into a single attribute 
- Fixes an issue where child objects weren't being normalised 
- Includes descriptions that weren't included in normalisation
This is useful when you are performing tasks on the composite configuration attributes themselves and provides standard functions for detailing with composite configuration.
Tested locally
- None
- None
- None
=> feat: composite configuration compression

engine/base.ftl
Correct the logic to determine if a default value for an attribute has been provided
- only add the `Default` attribute to the normalised structure if a default value is provided
- handle multiple normalisations on the same set of attributes which can occur for nested attribute structures.
- refactor the handling of the inhibiting of the `Enabled` attribute to ensure it doesn't result in content in the resulting object
- deployments are failing with validation errors
Local template generation and running of the engine test suite
- None
- None
- None
=> fix: composite object default attribute processing

engine/configuration/component.ftl, providers/shared/views/schemalist/setup.ftl
- Fixes copy and paste error on the component configuration definition 
- Fixes the source of the schemasets to align with configuration scopes
Fixes the component configuration scope and schema set lookups to ensure that the component schema is generated
Tested locally
- None
- None
- None
=> fix: component configuration set

providers/shared/views/schema/setup.ftl
- Fixes an issue where including a array of type was being treated as separate types instead of a single type
Schema generation was failing
Tested locally
- None
- None
- None
=> fix(schema): handle multiple types for attribute

providers/shared/views/schema/setup.ftl
- Fixes an issue with ARRAY_OF_TYPE attribute types in schema generation being handled as multiple types instead of a single type
Schema generation was marking ARRAY_OF_STRING as two types an array and a string
Tested locally
- None
- None
- None
=> fix(schema): handle array of type in schemas

engine/base.ftl, providers/shared/references/Domain/id.ftl
- Fixes an issue where Parent or Parents could be used for domain hierarchy handling
Domain name generation failing when Parents used instead of Parent
Tested locally
- None
- None
- None
=> fix: domain parent handling

providers/shared/components/cdn/id.ftl
- Allow for logging profile to be defined on cdn components
Configuration and logging subscription support for cdn components
- None
- None
- None
=> fix(cdn): add logging profile

engine/commonApplication.ftl, engine/occurrence.ftl
- Includes component settings as part of the setting environment for environment variable injection
Treats component settings like other settings when determining environment setup
- None
- None
- None
=> fix: include component settings in environment

providers/shared/components/lb/id.ftl
- Adds the ability to configure a logging profile on lb components
Template generation was failing when this was expected to be available
TEsted locally
- None
- None
- None
=> fix(lb): add required logging profile to lb

providers/shared/components/globaldb/id.ftl
- Adds alerts definition for globaldb components
Support for monitoring globaldbs
Tested locally
- None
- None
- None
=> feat(globaldb): add alerts support

legacy/account/account_s3.ftl
- Use getReference when looking up bucket policy bucket destination
A complicated process was being used to find the bucket name along with a fixed dependency. Using the reference ensures the dependency is met and that cfn_lint is happy
Tested locally
- None
- None
- None
=> refactor(s3): use recommended process for bucket policy

providers/shared/components/healthcheck/id.ftl
- conflict with the default component base type
Template generation issues with type/engine conflict
- None
- None
- None
=> refactor: remove type based attributes from healthchecks

engine/inputdata/district.ftl
- Use the district type to lookup the naming pattern required
Naming wasn't working as expected as the district could not be found to determine the name to use.
Tested locally
- None
- None
- None
=> fix: district type for district lookup

.github/workflows/release.yml, engine.ini
- Adds an engine.ini definition file that will be used during testing of the provider
- Removes the java installation process as its no longer required
- Fixes an issue where the testing environment variable override wasn't applied when running testing. This meant that the test results wern't based on the local changes. 
- None
- None
- None
=> refactor: use local engine definition for testing

engine/common.ftl
When generating scripts to upload asFile objects, sort the names so the ordering of the uploads remains consistent.
This assists in preventing false positives when trying to detect changes in templates.
It also assists debugging when trying to locate an item in the list.
- None
- None
**NOTE:** Because the current order is indeterminate, it is expected that when first applied, this change may
generate a false positive for template change, but after that point, the order will then be stable.
=> refactor: asfile ordering

providers/shared/components/cdn/id.ftl
- Adds an enable parameter to event handlers 
- Adds descriptions to component attributes
Allows for controlling event handler definitions through qualifiers without having to add and remove entire handlers
tested locally 
- None
- None
- None
=> feat(cdn): add support for disabling event handlers

providers/shared/inputseeders/shared/id.ftl
- Add a type check on the Region object to ensure refs are accounted for
Handles issues when adding new attributes for stacks that add multiple instances
Tested locally
- None
- None
- None
=> fix: support regions in state that use refs

legacy/account/account_console.ftl, legacy/account/account_directory.ftl
- Add a lookup for the accountCMKId after it was removed as a global var
- Switch to use log policy resource macro to ensure outputs are created
Template generation failing for account level deployments
Tested locally on a new deployment
- None
- None
- None
=> fix(account): minor fixes for account level aws deployments

engine/occurrence.ftl, providers/shared/components/shared/setup.ftl, providers/shared/inputseeders/shared/id.ftl
- Remove the fixture output handler from the mock outputs
- Handle missing test profiles and test cases
Removing the fixture handler from the mock provider makes testing processes more flexible as it now requires the outputs to exist or they can be easily mocked 
Throw exceptions for missing test profiles and test cases to ensure that expected testing is run 
Tested locally with the aws provider which relies on this output mocking to not be in place
- None
- None
- None
=> refactor: testing output handling and test profiles

providers/shared/components/runbook/setup.ftl
- Ensure that disabled tasks aren't included in runbooks
All SubComponents currently have an Enabled parameter but they are not being followed. This ensures that that happens.
- None
- None
- None
=> fix(runbook): don't include disabled tasks

engine/common.ftl, providers/shared/attributesets/lbattach/id.ftl
- sets alternate attribute names for SubComponent for Ports
- changes the lblink lookup to support it
Template generation failing as the link content was set to Null so content checking failed
Tested locally
- None
- None
- None
=> fix: lb link lookup

providers/shared/components/lb/id.ftl
- Allows for controlling if a condition is enabled or not using overrides
This allows for including conditions at different layers of a solution and using the Enable/Disable flag to override the status of a given condition
- None
- None
- None
=> feat(lb): add enable support for conditions

engine/configuration/dynamicvalues.ftl
- Ensure that lists are reconstructed when resolving dynamic values
Template generation failing as all but one item removed from list
tested locally 
- None
- None
- None
=> fix(dynamicvalue): resolve handling for lists

engine/configuration/dynamicvalues.ftl
- Fix the name for the configuration scope
Make sure the  schema can be found where it should be
- None
- None
- None
=> fix(dynamicvalue): fix typo in configuration scope

providers/shared/components/correspondent/id.ftl
Minor fix for Pinpoint APNS Sandbox component configuration.
Needed for APNs Sandbox configuration.
Locally
- None
- None
- None
=> fix: correct private key property name

providers/shared/components/runbook/id.ftl, providers/shared/components/runbook/setup.ftl, providers/shared/dynamicvalues/input/dynamicvalue.ftl
- Updates the runbook processing to support dynamic or context values in conditions
- Adds support for the NotEquals condition
- Change to resolving inputs before passing to the runbook executor
Allows for more complex processing of conditions and parameters when working in runbooks
Tested locally
- None
- None
- None
=> refactor(runbook): support dynamic values in conditions

providers/shared/components/sqs/id.ftl, providers/shared/components/topic/id.ftl
- Adds support for extensions on topic and sqs components
- Allows for control of policies or other values that can be provided by extensions
tested locally 
- None
- None
- None
=> feat: add support for topic and queue extensions

providers/shared/dynamicvalues/attribute/dynamicvalue.ftl
- When a link cannot be found for an attribute dynamicvalue don't raise a fatal error as it might not be deployed yet
Fatal error stopping the ability to deploy the component that hasn't been deployed
tested locally
- None
- None
- None
=> fix(dynamicvalue): remove fatal on missing link

providers/shared/components/baseline/id.ftl
- Adds support for extensions on baseline data components for adding policy and other extension based setups
Allows for control over bucket policy applied to baseline data components inline with what's available on the s3 component.
Tested locally
- None
- None
- None
=> feat(baseline): add extension support for data

providers/shared/flows/components/flow.ftl
- Add more details on the source of the link when a link has been misconfigured
With links used across a whole heap of things now a missing link detail error could come from anywhere. This helps in making it easier to find where the bad link is. 
Tested locally
- None
- None
- None
=> feat: extend missing link detail error message

engine/occurrence.ftl, providers/shared/flows/components/flow.ftl
- Moves the component settings which are defined in the solution into a dedicated resolution process
- Updates the component settings after dynamic values have been evaluated in the solution to update them
This allows for dynamic values to work when processing component level settings
Tested locally
- None
- None
- None
=> fix: update component settings for dynamic values

providers/shared/inputseeders/shared/masterdata.json
- minor fix to align with the introduction of fixed tier assignments
Template generation was failing and the shared tier wasn't listed in the older form of tier setups
tested locally
- None
- None
- None
=> fix: set fixed index for shared tier

engine/base.ftl
- Ensure that nested base attribute sets are expanded
- When expanding child attribute sets apply base expansion to ensure all attributes are caught
More failures in template generation that wern't caught with testing.
- None
- None
- None
=> fix: nested expansion of attributes

providers/shared/components/mobileapp/id.ftl
- Remove an accidental copy paste on the expo id override
Would lead to incorrect builds of mobile apps 
- None
- None
- None
=> fix(mobileapp): remove default on expo id override

engine/common.ftl
- Some minor updates to the pseudo stack output script that is generated by the engine to align with shell check and its recommendations
Makes it easier to follow in the engine. Updates the call to BASH_SOURCE to align with the fact that BAS
Tested locally
- None
- None
- None
=> refactor: shellcheck updates for pseudo stack

providers/shared/attributesets/cdnorigin/id.ftl, providers/shared/components/cdn/id.ftl
- Ensures that links are available on all subcomponents so that dynamic links and other link based lookups can be performed as required
- Updates the name of the specific link for Origin to OriginLink to reduce confusion between Links and Link on the Origin subcomponent
The links attribute was missed in the setup of origins initially and as you can insert additional values being able to use dynamic values is handy.
Tested locally
- None
- None
- None
=> fix(cdn): support for links on subcomponent

providers/shared/components/runbook/setup.ftl
- Fixes a missing comma which could cause issues when setting up conditions for runbook steps
Template generation broken
- None
- None
- None
=> fix(runbook): minor typo in code for conditions

.github/workflows/changelog.yml, .github/workflows/release.yml
- disable changelog generation for tags
- use shared workflow for engine image generation
- Standard pattern for building engine part images
- removes extra pipeline run that didn't work and wasn't needed
- None
- None
- None
=> refactor: standardise github actions

providers/shared/attributesets/scalingpolicy/id.ftl
- Add an Enable attribute to control if a scaling policy should be enabled or not
More control over how policies can be controlled
Tested locally
- None
- None
- None
=> feat(attributeset): add enable for scaling policy

providers/shared/components/db/id.ftl
- Makes the extra database monitoring services enabled by default
Database monitoring is always a critical service so ensuring that the monitoring services are always enabled makes it easier to manage and troubleshoot issues when they come up
Tested locally
- None
- None
- None
=> feat(db): make enhanced monitoring the default

providers/shared/components/baseline/id.ftl, providers/shared/components/s3/id.ftl
- Adds option to control the use of encryption in transit - Enabled by default
This aligns with security best practices of ensuring that all data is encrypted as it moves through the system
tested locally
- None
- None
- None
=> feat(s3): add support for transit encryption

providers/shared/layers/Account/id.ftl
- Adds support for latest configuration options required for ecs account level settings
- Enables container insights by default within AWS
The ECS account level settings move along as they go when introducing new changes. This ensures we keep up with them
Tested locally
- None
- None
- None
=> refactor(account:ecs): support for account level

providers/shared/attributesets/waf/id.ftl, providers/shared/references/WAFRule/reference.ftl
- Removes setting the version on WAF configuration
Reduces the configuration and maintenance required for working with WAF. This probably shouldn't have been included in the core in the first place as the verisons were AWS only. 
Tested locally
- None
- None
- None
=> refactor(waf): remove version control option

providers/shared/components/sqs/id.ftl
- Adds configuration options to manage the encryption processes used when dealing with an SQS queue
Aligns with recommended best practices of encrypting data throughout its processing life.
Tested locally
- None
- None
- None
=> feat(sqs): add support for encryption at rest

providers/shared/components/db/id.ftl
- Adds the ability to enable and export logs to a cloud providers standard logging service
Makes it easier to troubleshoot and investigate issues with more information
Tested locally
- None
- None
- None
=> feat(db): add support for configuring db logging

providers/shared/components/cdn/id.ftl
- Add the option to include the body in cdn handler functions
This is useful for event handlers which might need to inspect the body of a request to determine or modify the contents of a request body. 
Tested locally
- None
- None
- None
=> feat(cdn): include body for event handler function

providers/shared/services/resource.ftl
- Reverts the change for checking the region when using deployment units
Producing unexpected results for reference lookups
- None
- None
- None
=> fix: revert region inclusion in du check

providers/shared/components/userpool/id.ftl
- Adds support for enabling/disabling schema attributes
Adds easy control over the schema attributes to include across different deployments
Tested locally
- None
- None
- None
=> feat(userpool): add schema enable attributes

providers/shared/references/WAFProfile/reference.ftl
Handle the block action when its not included for the inbuilt rule generation
Template generation fails
- None
- None
- None
=> fix: handle missing block action

providers/shared/references/WAFCondition/id.ftl, providers/shared/references/WAFProfile/id.ftl, providers/shared/references/WAFProfile/reference.ftl, providers/shared/references/WAFRule/id.ftl
- Adds vendor managed rule overrides
- Docs and validation for WAF Conditions
- Handle missing action for vendor rules
Handles the extended capabilities for WAF required in https://github.com/hamlet-io/engine-plugin-aws/pull/748
Tested locally
- None
- None
- None
=> feat(waf): add extended support for vendor rules

engine/common.ftl, engine/setContext.ftl, providers/shared/components/baseline/id.ftl, providers/shared/references/LogFilter/id.ftl
- Update global vars to use use reference lookup functions
Mostly a chore to remove some more of the setContext global vars and replace them with the appropriate function lookups
Tested locally
- None
- None
- None
=> refactor: use reference lookup methods over global

providers/shared/references/ComputeProvider/id.ftl
- Allows you to set the providers that are available for containers to use
Gives you the ability to remove  virtual machines from solutions entirely if other methods are available
Tested locally
- None
- None
- None
=> feat(computeprovider): set available providers

providers/shared/components/user/id.ftl
Add ability to specify IP addresses from which requests can come for a user.
- tighter restrictions on use of IAM users
- better alignment to customer policies
- local template generation
- 
- None
- None
- None
=> feat(user): source IP filtering

providers/shared/components/userpool/id.ftl
Add the WAF solution configuration as it was lost along the way 
Fix testing and make the thing work
Tested locally
- None
- None
- None
=> fix(userpool): add waf section that was lost

providers/shared/components/userpool/id.ftl
Add the profiles for security and logging on userpools to align with the inclusion of WAF
- Was lost along the way in changes to enabling waf on userpools
- None
- None
- None
=> fix: missing waf userpool attrs

engine/output.ftl, legacy/account/account_apigateway.ftl, legacy/account/account_audit.ftl, legacy/account/account_cloudtrail.ftl, legacy/account/account_cmk.ftl, legacy/account/account_console.ftl, legacy/account/account_directory.ftl, legacy/account/account_ecs.ftl, legacy/account/account_es.ftl, legacy/account/account_iam.ftl, legacy/account/account_roles.ftl, legacy/account/account_s3.ftl, legacy/account/account_ses.ftl, legacy/account/account_sms.ftl, legacy/account/account_volumeencrypt.ftl, providers/shared/deploymentframeworks/default/output.ftl, providers/shared/inputseeders/shared/id.ftl, providers/shared/tasks/file_delete/id.ftl, providers/shared/tasks/file_path_details/id.ftl, providers/shared/tasks/task.ftl
- Adds support for deployment contract outputs
- Adds the cf_dir as a variable to enable finding the output files for a deployment
Make deployments available in the engine
- None
- None
- None
=> feat: add deployment contract support and cf_dir
