hamlet-io/engine

aws/templates/resource/resource_vpc.ftl
When running Gen3 as a solution template the following error is being produced: 
15:20:17 Jan 16, 2018 4:20:17 AM freemarker.log._JULLoggerFactory$JULLogger error
15:20:17 SEVERE: Error executing FreeMarker template
15:20:17 FreeMarker template error:
15:20:17 Macro "createDependentSecurityGroup" has no parameter with name "extensions".
15:20:17 
15:20:17 ----
Checked createDependentSecurityGroup and it doesn't have an extension parameter, however it looks like createComponentSecurityGroup does have the extension parameter and it is being used in in the same section of the code generation. 
Updated the SecurityGroup creation method to support the extensions.
=> Fix Security Group Component Reference

aws/templates/policy/policy_sns.ftl, aws/templates/resource/resource_userpool.ftl, aws/templates/solution/solution_userpool.ftl
Cognito UserPool MFA is performed through SNS based SMS messages. This adds support to add the IAM policy required to publish SNS Messages by Cognito
=> Add SMS Configuration for User Pool MFA 

aws/manageStack.sh, aws/templates/application/application_apigateway.ftl
Our existing docs generation doesn't seem to produce the expected results. Examples don't seem to be included correctly and the ability to test the API from the UI has been a requested feature. 
This changes the default docs generation from aglio to SwaggerUI. The swagger JSON is included in the static files and the docs generated on the fly using the swagger spec. 
To support the Test API the API host needs to be included in the SwaggerSpec which is added as part of the deployment process.
=> Move API static doc generation to SwaggerUI

aws/templates/createSwaggerExtensions.ftl
Cross-Origin Resource Sharing (CORS) is used to authorise access to resources using headers. 
Its implemented using the options verb which is expected to respond with a set of headers that describe how the resource can be accessed. 
This PR checks to see if the options verb has been added as part of the swagger spec that is being processed, if it hasn't then the API Gateway will be configured to use a mock response to implement CORS using the default configuration of: 
```json
"responses": {
"default": {
"statusCode": "200",
"responseParameters": {
"method.response.header.Access-Control-Allow-Headers": "Content-Type,X-Amz-Date,Authorization,X-Api-Key",
"method.response.header.Access-Control-Allow-Methods": "*",
"method.response.header.Access-Control-Allow-Origin": "*"
}
}
}
```
The set …
=> Add API Gateway Mock Response for CORS Headers

aws/templates/createSwaggerExtensions.ftl
The AWS integration response headers require single quotes for the header that is being inserted. 
This fixes it up
=> Fix for character escaping in Swagger

aws/templates/application/application_apigateway.ftl, aws/templates/common.ftl, aws/templates/createSwaggerExtensions.ftl, aws/templates/id/id_userpool.ftl, aws/templates/name/name_userpool.ftl, aws/templates/name/start.ftl, aws/templates/policy/policy_userpool.ftl, aws/templates/resource/resource_iam.ftl, aws/templates/resource/resource_userpool.ftl, aws/templates/solution/solution_userpool.ftl
- Adds the setup of an Identity pool for a cognito user pool. 
- Creates IAM roles with a default policy attached for unauthenticated users and authenticated users. 
- Adds API gateway link support to update the role with a policy to allow invoke access on the API
- Adds IAM Role creation for Federated services and web identity roles
=> User Pools Identity Pool Support

aws/templates/application/application_apigateway.ftl, aws/templates/createSwaggerExtensions.ftl
When an a Cognito User pool authorizer is setup on an API gateway via Cloudformation they are overridden by the Swagger based import. 
This moves the authorizer configuration into the swagger spec and allows for Userpool auth to be enabled on paths like existing sig4 or API key configuration. 
In its current state the Arn of the Cognito User Pool needs to be added to the apigw.json configuration due to the way the Swagger spec is built
Properties for apigw.json are: 
"userPool" : booleen - Enables UserPool Auth
"userPoolArn" : string - the ARN of the user Pool
=> Add Cognito User Pool Configuration to Swagger Build

aws/templates/application/application_lambda.ftl, aws/templates/createSwaggerExtensions.ftl, aws/templates/id/id_lambda.ftl
When invoking a lambda function via API Gateway the identity provided to the Lambda function is the API Gateways id. If using Cognito you would like to idenitfy the user in lambda.
This changes passes the user credentials to the lambda function when called and enables the Cognito auth role to invoke the lambda function
=> Allow CognitoUser pool to invoke Lambda Function

aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/segment/segment_s3.ftl, aws/templates/setContext.ftl
Some applications need to be able to make S3 data available with public read access. This adds support for a public prefix which when set adds an S3 Bucket policy to the AppData Segment Bucket. 
The policy allows public read access to data hosted within a sub prefix of the components appdata prefix. 
A IP whitelist is also required to restrict the access and make the user specific global if they want it to be fully public
=> Add Public App data bucket 

aws/templates/common.ftl, aws/templates/segment/segment_s3.ftl, aws/templates/setContext.ftl
The first implementation put the public data in with the existing App data. This change splits public data to a seperate root prefix in the S3 bucket. Ensuring that the data can't mix
=> Split existing App data and New App Public locations

aws/templates/common.ftl, aws/templates/solution/solution_spa.ftl
Currently when cloudfront returns a 404 or 403 error page it is set to returning the index.html page. 
This makes sense for applications that authenticate a user as this forces them back to the login page or to a standard index page.
For static sites this has the potential to return actual content instead of an error page.
This allows for the custom error page to be defined in the SPA Cloudfront configuration 
````json
{
"SPA" : {
"CloudFront" : { 
"ErrorPage" : "/index.html" 
}
} 
}
````
=> Add ability to define custom error page for SPA

aws/contextTree.sh, aws/templates/account/account_audit.ftl, aws/templates/resource/resource_s3.ftl
Adds support for an audit log hosted in S3. 
The first stage of this is to enable S3 Server access logging for all s3 buckets deployed by codeontap to a centralised s3 bucket. 
Auditing is enabled at the account level, through the deployment of the audit deployment unit. If this is deployed all s3 buckets that are created will have Server Access logging enabled on it with logs going to an account level audit bucket. 
The option is intentionally not configurable at the bucket level to ensure that it is enabled if auditing is enabled.
=> Add Account level audit logging

aws/templates/application/application_lambda.ftl, aws/templates/id/id_event.ftl, aws/templates/id/id_lambda.ftl, aws/templates/resource/resource_event.ftl, aws/templates/resource/resource_lambda.ftl
a scheduled event rule will be created along with lambda function in order to keep it warm.
an example - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#w2ab2c21c10d637c13
=> add schedule event rule resource support

aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/resource/resource_event.ftl, aws/templates/resource/resource_lambda.ftl
This allows for schedules to be added to a lambda function explicitly. This can be used for automated lambda invokes, for tasks like reporting or cleanup. 
Schedules are a function property and have 4 values 
* Name - A generic name for cloudformation purposes 
* Enabled - State of the schedule 
* Expression - A cron or rate definition as per https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/ScheduledEvents.html 
* InputPath - A path which is sent in a JSON payload as { "path" : value }
=> Add schedules to Lambda Componets

aws/templates/application/application_apigateway.ftl, aws/templates/common.ftl, aws/templates/name/name_s3.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_s3.ftl
I refactored the bucket support to use a couple of format routines for different bucket types and added s3 as a valid destination for a link.
I didn't add Cloudfront/Certificate support yet - figured I'd wait until we had a project that needed it.
=> Add s3 link support

aws/templates/application/application_apigateway.ftl
If no buildCommit is present, then there is no swagger definition to use
to create the gateway so abort processing with an exception.
Also pick up a syntax error when creating the documentation bucket
=> Add precondition checking for the API Gateway

aws/templates/solution/solution_ecs.ftl
* Move definition of ecsEFSVolumeId so its available for the entire template.
* add checking of the id in case we want to mange efs volume creation as a deployment unit in its own right - much like iam,lg etc.
=> Handle absence of cluster wide storage configuration for ecs cluster

aws/templates/id/id_spa.ftl, aws/templates/solution/solution_spa.ftl
Allow for Error Specific Error pages for CloudFront responses. 
Adds two parameters to the SPA CloudFront Configuration
DeniedPage - for 403 responses
NotFoundPage - for 404 responses
If either of these these are set the default ErrorPage is overridden with the value set in the parameter. 
If they aren't set, default to the generic ErrorPage
=> Error Specific Custom SPA CloudFront Pages

aws/templates/application/application_contentnode.ftl, aws/templates/common.ftl, aws/templates/id/id_contenthub.ftl
Reorder pathing to follow least specific to more specific flow.
Fix link lookup to use external lookup as the type instead of contenthub 
Added Path styling, allowing for the use of a nested folder structure or single folder containing each of the included properties
=> Contenthub Path Naming Fixes and Link Lookup

aws/manageStack.sh, aws/templates/application/application_contentnode.ftl, aws/templates/id/id_contenthub.ftl, aws/templates/id/start.ftl, aws/templates/solution/solution_contenthub.ftl, aws/utility.sh
In order to push changes to Github credentials need to be provided when the repo is pulled. 
This adds the ability to lookup the github credentials using the env variable set by the Jenkins server.
=> Support for credentials in Content Hub Git pulls

aws/createTemplate.sh
Change urandom usage from cat to dd. doing a cat from urandom within in a script causes the script to block. Worked fine from a Mac but seems to cause an issue on the automation server
=> beta run id fix

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_contentnode.ftl, aws/templates/application/application_ecs.ftl, aws/templates/application/application_lambda.ftl, aws/templates/application/application_spa.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/createBlueprint.ftl, aws/templates/id/id_alb.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_cognito.ftl, aws/templates/id/id_contenthub.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_event.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_rds.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/id_sqs.ftl, aws/templates/resource/resource_lambda.ftl, aws/templates/resource/start.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_alb.ftl, aws/templates/solution/solution_contenthub.ftl, aws/templates/solution/solution_ecs.ftl, aws/templates/solution/solution_efs.ftl, aws/templates/solution/solution_rds.ftl, aws/templates/solution/solution_s3.ftl, aws/templates/solution/solution_spa.ftl, aws/templates/solution/solution_sqs.ftl
This feature uses getOccurrences to handle subcomponents, so we can more cleanly support ECS services/tasks and lambda functions.
With the increased use of links (and getOccurrences under the hood), I've also started moving the details of resource id creation into the getXXXState routines. This localises the definition of ids and means we need fewer format routines, because the ids can instead be obtained via occurrence.State.Resources[alias], where alias is the logical purpose of the id for the component. I have taken this approach in refactoring ECS and lambda, but we should use this approach more generally as it centralises id definition.
I've also added an "Id" and "Name" attribute to the core attributes of an occurrence. These are very often used in generating ids and names - indeed …
=> Feature getoccurrence ecsservice ecstask lambdafunction support

aws/createTemplate.sh
Removes uppercase characters from the runId. Also extended the urandom sample to ensure that we can get 10 characters. 
fixes #142
=> Remove Uppercase characters from runId

aws/templates/segment/segment_vpc.ftl, aws/templates/solution/solution_alb.ftl
Correct access to segment CIDR - it in now in a separate Network object
=> Correct access to segment CIDR for ALB/self-hosted NAT

aws/manageStack.sh
Cloudformation stacks can behave in a large number of different ways. This PR adds some extra handling error conditions to make sure we know if an issue has occurred
Stack status will have the following results
- *FAILED - throw 255 error code and fatal message
- ROLLBACK*COMPLETE - throw 127 error code and a warning message - the world should continue but it won't have updated 
- *COMPLETE - return ok and notify the stack has completed 
This would cover CREATE,UPDATE, and DELETE actions
Fixes #152
=> Add Better error handling for Stack management

aws/templates/common.ftl, aws/templates/createBlueprint.ftl, aws/templates/resource/start.ftl, aws/templates/solution/solution_cache.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_efs.ftl, aws/templates/solution/solution_elb.ftl, aws/templates/solution/solution_rds.ftl
Fixes #145 
With the move to use occurrences more heavily, the global component level
variables can be phased out.
This is a first cut at this - componentId and componentType are still
used in quite a number of places but other variables can be removed
in preparation for a more general move to use of occurrences.
There are also a few other minor code style improvements as well.
=> Reduce use of global variables

aws/templates/commonApplication.ftl, aws/templates/id/id_ecs.ftl
Fixes #176 
Supercedes PR #177 
If no maximum memory limit is set, add a default limit as a multiplier
of the memory reservation (currently 1.5).
This ensures memory leaks don't bring down the server where no limit has
been set.
Where no maximum limit is explicitly required, set the maximum to 0 or
to any string e.g. "nolimit".
=> Introduce a default memory limit for ECS containers

aws/templates/commonApplication.ftl
Subcomponent definition now has Id and Name listed instead of a single value. Environment Variables only accept a string as a value and at the moment the template is receiving a hash.
=> Set Subcomponent to Name for Environment Variables

aws/templates/id/id_rds.ftl
Adds a DATABASE URL attribute which allows for a database to be configured and connected using a single environment variable name.
=> Add a DATABASE URL Attribute for RDS instances

aws/data/masterData.json
=> Increase default ECS instance size to a t2.medium

aws/templates/common.ftl
Link processing now gives priority to instance/version values on links
over those of the occurrence carrying the link, when attempting to match
link target candidates.
Fixes #201
=> Improved link matching rules

aws/templates/id/id_apigateway.ftl
Fixes #203 
@roleyfoley this will likely affect smallcraft and IPC. Before merging this change, you can set the "IncludePathInUrls configuration option to false for the APIs to inhibit the new behaviour, while the code gets changed to not have to control this. Note there is a separate attribute for the implementation code to know what path it will see - basically INTERNAL_PATH = basepath in swagger
Include the version path in URL attributes - selection of version can
then be controlled via the links in the solution.
Provide an ability to turn this off for backwards compatability.
Also provide an attribute with the path that the implementation (e.g.
lambda) will see. The suspicion is that this varies depending on the
configuraiotn of custom domains. As the gateway knows its configuration, …
=> Control paths in URLs for API Gateway

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_cognito.ftl, aws/templates/id/id_lambda.ftl, aws/templates/name/name_cognito.ftl, aws/templates/resource/resource_cognito.ftl, aws/templates/solution/solution_userpool.ftl
Issue #162 
- Converted userpool solution to an occurrence based component
- Fixed some configuration properties casing so that they worked with the occurrence default settings
- Added Trigger links to user pool. When a lambda is linked from a user pool using one of the named actions for userpool event, the specified function will be set in the LambdaConfig section of the user pool template 
- Added inbound link properties to allow the lambda function to grant permission for the userpool to invoke it using the standard linking methods 
- Added ARN and Name attributes to lambda functions so that they can be looked up easily as part of a link 
- Added option to stop an error if a link is not found, because lambda functions are created during the application level deployment phase they …
=> Add Cogntio event lambda triggers

aws/templates/commonApplication.ftl, aws/templates/id/id_alb.ftl, aws/templates/id/id_ecs.ftl
Fixes #210
* remove the custom matching code and replace with a call to getLinkTarget.
* support instance and version overrides in line general link processing
=> Use link routine for container load balancers

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_contentnode.ftl, aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/solution/solution_s3.ftl, aws/templates/solution/solution_userpool.ftl
Fixes #220 
Change behaviour of getLinkTarget to return an empty object if a link
isn't matched, rather than a partially populated one.
Add code to detect situations where getLinkTarget may return an empty
object. An exception is generated in this case, so the aim is to have
the template complete successfully so the Exception detection logic can
then report the failure to match the link.
=> Correct detection of unresolvable links

aws/contextTree.sh, aws/createTemplate.sh
Fixes #222 
As part of #133 blueprint files will be generated as part of the manageUnit Process when a deployment is completed. This moves the blueprint output location to a dedicated infrastructure folder. 
Also adding in a find for Tenant Infrastructure to align gen3 and gen3-automation contextTrees
=> Move Blueprint Generation location to dedicated infrastructure folder

aws/templates/commonApplication.ftl
Only create a specific target group for a versioned container if the match was against an unversioned load balancer i.e. create a target group per version.
This ensures that if the occurrence match has used instance and version, the default target group is used for the resolved load balancer.
=> Be more specific when creating a target group for a version

aws/templates/commonApplication.ftl
Need to be able to explicitly provide empty values for matching when
linking a container to a lb.
=> Correct handling of empty lb linkage values

aws/createTemplate.sh, aws/templates/createBlueprint.ftl
Couple of changes to support the continuous generation of blueprints 
- Update template generation to only perform a template pass ( no prologue, epilogue or config) 
- Remove Solution from nesting in template and move to segment property 
- Only include occurrences where one resource has been deployed
=> Updates to Blueprint Generation

aws/manageStack.sh
Allow the change set error submission error to be seen when something goes wrong with a change set submission
=> Add error reporting for Change Set Submissions

aws/templates/id/id_lambda.ftl
It appears keepalives of 30 minutes are insufficient to keep lambda alive in ap-southeast-2.
Reducing to 6 mins for now.
=> Increase keepalive frequency

aws/templates/createBlueprint.ftl
Since the blueprint generation is currently used for documentation purposes, passwords and keys should not be provided. 
Instead the attribute should still be displayed but the contents hashed out using ***. This means that existence of the attribute is known but the content isn't
=> Remove Passwords and Keys from Blueprint generation

aws/templates/id/id_rds.ftl, aws/templates/resource/resource_rds.ftl, aws/templates/solution/solution_rds.ftl, aws/utility.sh
- Add support for manual snapshot restoration
- Enables snapshot on deploy by default 
To use manual snapshot restoration add a prologue pseudo stack with the an output: 
````json
{
"OutputKey": "manualsnapshotX<RDSId>",
"OutputValue": "<snapshot Identifier>"
}
````
- Adds Support for the conversion of an instance to a database encrypted at rest from one that hasn't been encrypted from the start
- Requires SnapshotOnDeploy to be enabled
=> RDS updates for snapshot management and at rest encryption

aws/templates/resource/resource_rds.ftl
Database was hardcoded to be the product name rather than the passed database name value
=> Save correct value for database name

aws/templates/id/id_rds.ftl, aws/templates/id/start.ftl, aws/templates/solution/solution_rds.ftl, aws/utility.sh
Adds support for a generated password to be created for an RDS instance. With this configuration the password is always encrypted and stored as a stack output.
When generateCredentials is enabled a dummy password is supplied to cloudformation and on the initial creation of the instance a password is generated, encrypted and set on the RDS instance as an epilogue script.
Since cloudformation resets the password to a dummy password each time on each deploy the password will be retrieved decrypted and reset as part of the deployment process
**This process will create some downtime during the deployment as the password will be set to the dummy password in between the cloudformation deployment and the epilogue script reseting the password back to the generated password**
Credentials are …
=> Generate Encrypted Password on RDS creation

aws/templates/id/id_contenthub.ftl, aws/templates/id/id_efs.ftl, aws/templates/id/id_spa.ftl
Some state objects are missing the Role Properties within their state configuration. This adds a default Role object to each of the states.
=> Add Default Role state to State Objects

aws/templates/setContext.ftl
A small tweak so the cmdb upgrade process doesn't break the current branch
=> Legacy credentials formats had a top level Credentials attribute

aws/templates/solution/solution_userpool.ftl, aws/utility.sh
Cognito user pools have the ability to trigger a lambda function based on a specific event that has occurred. The majority of the events are available through cloudformation except for some that have been added recently (Jan 2018).
This adds support for the cognito events which are available via the cli instead of cloudformation. 
The lambda event mappings are added to two seperate arrays: 
- userPoolTriggerConfig - is the array for cloudformation 
- userPoolManualTriggerConfig - is the array for cli based updates
=> Add Support for epilogue based Lambda triggers in Cognito User Pools

aws/templates/solution/solution_userpool.ftl
Instead of passing the JSON values for the lambda config mapping the AWS shorthand format is an easier way to pass the configuration.
=> Update Cognito Epilogue to support AWS shorthand format

aws/templates/application/application_apigateway.ftl, aws/templates/common.ftl, aws/templates/id/id_alb.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_spa.ftl, aws/templates/resource/resource_cf.ftl, aws/templates/solution/solution_alb.ftl, aws/templates/solution/solution_spa.ftl
Support addition of a base path mapping when using cloudfront in front
of the api gateway so the fqdn used in the signature doesn't vary when
the api gateway is recreated.
Also remove the need for tier/component when generating a host name, as
these are already present in the occurrence structure.
=> Add custom domain for api gateway signing

aws/templates/solution/solution_userpool.ftl
Updates to the lambda config for user pools via the CLI overrides all of the lambda triggers which means that all of the lambda to event mappings need to be submitted in a single command, and can't be submitted via cloudformation and then added to via CLI. 
This moves all the lambda triggers to the epilogue processing. The cloudformation processing is still in place for when cloudformation catches up ( we can always dream)
=> Move all Cognito Lambda triggers to epilogue process

aws/templates/application/application_ecs.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_alb.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_elb.ftl, aws/templates/resource/resource_alb.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_alb.ftl, aws/templates/solution/solution_elb.ftl
This allows each listener to carry its own certificate info and be
linked to via ECS containers.
It required the migration of the solution structure representing the
ports so a per-occurrence generation migration step has been added for
cases where older format solutions need to be migrated to support
backwards compatability. This only changes the internal structure used -
the assumption is the actual solution file can be edited separately to
align with the current spec.
=> ALB listeners are now subcomponents of the ALB

aws/templates/id/id_alb.ftl, aws/templates/id/id_cache.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_efs.ftl, aws/templates/id/id_elb.ftl, aws/templates/solution/solution_cache.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_efs.ftl
Ensure ids are unique by using primary component ids (which have the primary resource type in them) when generating sg ids.
Ideally we should switch to including component types in occurrence ids so two components with the same tier/component info but different types have different ids. At present its largely not an issue as the resulting resources tend to be quite different - but sgs are the exception.
=> Use dependent ids for sg

aws/templates/solution/solution_rds.ftl
Typo in RDS epilogue script meant that wrong information was being added to the psuedo stack output. This removes the info object from the output and make it an actual statement again.
=> Minor fix for RDS epilogue script

aws/templates/id/id_contenthub.ftl
A content hub doesn't really have a state so instead of using an existing reference the attributes for a link should be pulled from the configuration.
=> Fix linking configuration for contenthub

aws/templates/application/application_lambda.ftl, aws/templates/name/start.ftl, aws/templates/setContext.ftl
Moves namespaces up to the tenant/product, the idea being that custom metrics are specific for the product and how it behaves. 
The alert metric also now requires a type field which is used to add dimensions to the Alarm configuration to ensure that the right component is generating the alert. 
Also updates alerts to ensure they are unique
=> Fixes for Lambda Alerts and Metric namespacing

aws/templates/account/account_audit.ftl, aws/templates/id/id_s3.ftl, aws/templates/resource/resource_s3.ftl, aws/templates/segment/segment_s3.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_s3.ftl
Fixes #273 and #272 
Adds support for S3 Bucket Versioning and updates lifecycle rules with the following
- Transitioning to glacier storage
- Expiration of non current versions of objects - By default follows the normal expiration config
- Transition of non current versions of objects - By default follows the normal transition config
Usage 
- Account level Audit Bucket 
- Versioning always enabled 
- Configuration - account.json 
```Json 
{
"Account" : {
"Audit" : {
"Backup" : "<Days before Glacier transition>",
"Expiration" : "<Days before deletion>"
}
}
```
- Segment 
- Versioning not available 
- Configuration - Segment and Environment Lifecycle.Backup property, transition not enabled by default 
- Solution 
- Versioning - defaults to disabled
```Json 
{
"Lifecycle" : { 
"Versioning" …
```
=> Adds Glacier Transition rules and versioning to s3 resources

aws/templates/createBlueprint.ftl
Using the resource deployment state to remove occurrrences proved to removed too much. 
This removes this check and instead we will use more fine grained control in documentation generation 
Fixes #284
=> Remove occurrence deployment check

aws/templates/application/application_lambda.ftl, aws/templates/setContext.ftl
The intention of metric dimensions is to filter a metric to the source that generated it. This allows you to have the same metric but reported from different locations. 
Unfortunately dimensions are not available for LogMetrics. After raising a support case with AWS they have advised that at the moment you can not add dimensions to LogMetrics and instead to filter the metric the metric name should include a unique Id. 
This PR updates the metric name to make it unique for each function and then updates the alarm Metric to include the function name. 
The intention would be to move this back to dimensions when they are supported by AWS.
=> Filter LogMetrics using Name instead of dimension

aws/templates/account/account_s3.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_eip.ftl, aws/templates/policy/policy_alb.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ec2.ftl
Updates the S3 Solution component to align with use some of our new features 
- Registration with ALB based load balancers using linking/port definitions
- Converting ID/naming generation to support occurrence structure adds the idea of Zone level resources which individual resources for each zone that could potentially be deployed to 
- Adds the ability to deploy scripts to an Ec2 Instance
**To Deploy a script** 
1. create a code repo with an init.sh script as an entry point with other scripts or content. 
2. The script repo content will be copied to the ec2 instances under /opt/codeontap/scripts 
3. The /opt/codeontap/scripts/init.sh script will then be run on the inital setup of the instance as part of the cfn-init process 
4. The instance will be recreated each time the code is …
=> EC2 Occurrence Conversion, ALB Load Balancing Refactor, Deploy Script

aws/manageStack.sh
At the moment if a stack update fails mid way through we don't see the error that caused it. 
This just displays the error if a describe stack action fails for create or update tasks
=> Show error handling for status updates

aws/templates/account/account_waf.ftl, aws/templates/application/application_apigateway.ftl, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_spa.ftl, aws/templates/segment/segment_s3.ftl, aws/templates/segment/segment_vpc.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ElasticSearch.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_spa.ftl
Experience has shown that the usage capability in IP Address Groups can
be replaced by using more granular address groups and configuring lists
in the solution. This is also more explicit as it is obvious from the
solution what is actually happening, rather than indirectly based on
usage.
As part of this change, mandatory subchildren are now supported. they
will be ignored if the parent doesn;'t exist, but checked for where
there are candidate values to consider.
=> Remove usage functionality from IP Address Groups

aws/cleanupContext.sh, aws/contextTree.sh, aws/createExtendedSwaggerSpecification.sh, aws/createTemplate.sh, aws/manageCrypto.sh, aws/manageStack.sh, aws/rebootRDSDatabase.sh, aws/runTask.sh, aws/setContext.sh, aws/snapshotRDSDatabase.sh, aws/syncAccountBuckets.sh, aws/templates/account/account_s3.ftl, aws/templates/segment/segment_cmk.ftl, aws/utility.sh
All temporary files are now created in a temporary directory, and more
use is made of nested temporary directories to assist in debugging the
flow of function calls.
The composite_* files have been moved into a "cache" directory at the
root of the tree in preparation for improvements in the use of cached
information.
The templates for temporary files now used four X's. With only three,
there was occassionally a temporary file called "aux" created which is
not a valid file/directory name on windows.
=> Cleanup temporary file management

aws/templates/solution/solution_lb.ftl
The health check configuration is on the LB component instead of the listener subcomponent. This fix moves the health check lookup to the LB component so that its properties can be looked up properly
=> Fix LB Healthcheck lookup

aws/contextTree.sh, aws/templates/common.ftl, aws/utility.sh
To make it easier to have files coming from various directories once we
move to shared directories, change the processing of asFiles to be
relative to the root of the cmdb.
This allows the absolute path to vary (e.g. between workspaces for
different Jenkins jobs) but a prepared template should still work.
The commit also removes an unused function to assemble credentials,
which is done as part of assembling the settings.
=> asFile references are now relative to ROOT_DIR

aws/contextTree.sh, aws/data/masterData.json, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_lb.ftl, aws/templates/id/id_spa.ftl, aws/templates/name/start.ftl, aws/templates/policy/policy_dynamodb.ftl, aws/templates/resource/resource_sns.ftl, aws/templates/resource/start.ftl, aws/templates/segment/segment_cmk.ftl, aws/templates/segment/segment_dns.ftl, aws/templates/segment/segment_vpc.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl, aws/templates/solution/solution_lb.ftl, aws/templates/solution/solution_spa.ftl, aws/utility.sh
Move to using the environment by default the segment only if it differs
from the environment and does not have the value of "default".
The next stage will be to change the cmdb layout to explicitly include
the environment in the tree to allow for multi-segment environments.
NOTE: This change may need adjustment to segment.json files where the
environment is not the same as the segment.
=> Support environment and segment in names

aws/contextTree.sh
When provisioning a new account the stack outputs file is empty. currently this is failing because the COMPOSITE_STACK_OUTPUTS variable has not been defined at the start of the function.
=> Bug Fix - Composite Stack output file not found

aws/templates/container/container_jenkins.ftl
Epic https://github.com/codeontap/codeontap/issues/14
JENKINS itself uses the JENKINS_environment variables for different purposes. We should probably move the environment specific configuration to another location to ensure they don't cause issues with Jenkins
=> Moving Jenkins config to JenkinsEnv to avoid builtin properties

aws/templates/application/application_ecs.ftl, aws/templates/common.ftl, aws/templates/container/container_codeontap.ftl, aws/templates/container/container_jenkins.ftl, aws/templates/id/id_ecs.ftl, aws/templates/policy/policy_global.ftl, aws/templates/policy/policy_iam.ftl, aws/templates/resource/resource_ecs.ftl
Epic https://github.com/codeontap/codeontap/issues/14
**Delegated Container Deployment**
Jenkins has the ability to provision slave's on demand using an ECS plugin which creates ecs tasks using the native AWS API. 
To do this you need to essentially create an ECS Task Definition within the Jenkins configuration. Since the properties and configuration are pretty much the same as a cloudformation Task definition we can use our existing Task configuration to generate the configuration file required by Jenkins and then use a groovy init jenkins script to read this file and create the task in the Jenkins config. 
This PR adds a new configuration Property to ECS tasks, DelegateDeployment (defaults to false). When this is set to true, all cloudformation components except the Task Definition (IAM …
=> Delegated Container Deployments and IAM Admin Roles

aws/contextTree.sh, aws/createTemplate.sh, aws/setContext.sh, aws/setStackContext.sh, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/container/container_couchdb.ftl, aws/templates/container/container_filter.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_eip.ftl, aws/templates/id/id_lb.ftl, aws/templates/segment/segment_cmk.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_lb.ftl, aws/templates/solution/solution_userpool.ftl, aws/utility.sh
Introduce an environment directory layer between product and segment
to support multi-segment products.
Rename appsettings to settings, solutions to solutionsv2, and
credentials to operations.
Support a reserved environment of "shared" to support sharing
across all instances of the same segment across environments, as well as
across all segments of all environments.
A segment of "default" will not appear in names, in much the same way as
an instance or version of "default" does not appear in names.
Support for appsettings and credentials has been removed as these have
been superceded by the settings support.
Refactor upgrade support to separate the upgrade process from the cleanup
process.
Remove the automatic migration of ALB config to ensure it is explicit as to
what is expected. Rework …
=> Introduce separate environment directories

aws/contextTree.sh, aws/templates/common.ftl
It is possible to have a parent component not not its subcomponents
(e.g. ECS with services but no tasks), so reinstate the support for
this.
Also correct the debug trace to show solutions dirs for ENVIRONMENT and
SEGMENT rther than opertions dirs.
=> Reinstate allowance for missing subcomponents

aws/contextTree.sh, aws/templates/id/id_ec2.ftl, aws/templates/segment/segment_cmk.ftl, aws/templates/segment/segment_vpc.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl, aws/utility.sh
In order to avoid complexities associated with managing environment
based ssh keypairs, revert to using segment based keypairs.
In order not to affect legacy environments, segments of default will
check if a keypair already exists without the segment, and if so, the
segment-less name will continue to be used.
=> Revert to segment based ssh keypairs

aws/templates/resource/resource_lb.ftl
This is an experimental patch to not provide the type attribute if the
value is the default (application), in order to see if this stops the
triggering of a replacement rather than an update.
=> No LB Type attribute if want default

aws/templates/resource/resource_ec2.ftl
unzip doesn't appear to be installed by default on ECS based instances. So we need to make sure it is installed
=> Add unzip package requirement to scripts setup

aws/templates/application/application_computecluster.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/resource/resource_ec2.ftl
Set the working directory for running the scripts deployment. Allows for relative referencing of scripts. 
Also adds control over the timeout and pause time for deployment and creation
=> compute Cluster refinements 

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_computecluster.ftl
When processing a container fragment some of the processing expects a variable called context. This change makes the context property consistent across application components.
=> Update Application components to same name for context settings

aws/templates/application/application_computecluster.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/resource/resource_ec2.ftl
Adds the ability to treat the init.sh script like a docker entrypoint script which makes the script run to keep the process running constantly. 
When the init.sh script stops a shutdown command is run on the instance which forces the replacement of the instance in the autoscale group. This follows the idea of docker containers.
=> Compute Cluster  docker style entrypoint script 

aws/templates/application/application_computecluster.ftl, aws/templates/resource/resource_lb.ftl
Update the processing order for LB ports to make sure the links are added to the environment variables
Fix for LB output mappings after LB refactoring.
=> Fix LB output mappings and link processing for compute cluster

aws/templates/application/application_computecluster.ftl, aws/templates/common.ftl
Adds security group updates to make sure that load balancers can contact the compute nodes and also adds direct access to ports if required
=> Add Security Group management for compute cluster

aws/templates/commonApplication.ftl
Beware precedence in freemarker!
&& binds more tightly than !
=> Correct logic for ignoring env vars

aws/templates/application/application_computecluster.ftl
When using shared build permissions the local build unit was being used for S3 permissions which meant it couldn't get to the build reference. This broadens the S3 get access to the scripts registry
=> Broaden registry permissions for shared builds

aws/templates/application/application_lambda.ftl, aws/templates/id/id_lambda.ftl
While the log group name for lambda is currently fixed, the log group is
only created when the first lambda message is written.
This prevents the creation of log filters until the lambda runs.
To mitigate this, support the option of manually creating the group with
the AWS required name before creating the function.
Hopefully at some stage AWS will permit customer control of the lambda
log name, so this code positions the framework for this in the future.
=> Support option of creating lambda log group

aws/data/masterData.json
With introduction of environment, the production qualifier should refer to environment not segment.
=> Correct default certificate qualification for production

aws/templates/commonApplication.ftl
Minor fix to save looking up a link that is generated as part of the same function.
=> Fix for load balancer lookup in containers

aws/templates/common.ftl, aws/templates/commonApplication.ftl
Ensure component environment sections only contain strings.
Rework handling of run mode for docker containers and AWS region so it is not affected
by the DefaultEnvironmentVariables setting.
=> Correct handling of environment setting value escaping

aws/templates/application/application_computecluster.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_lb.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ec2.ftl
In order that LB linking can be handled like any other subcomponent,
switch from linking on the basis of source port to linking on the basis
of the subcomponent id, which for an LB is the port mapping.
Also update link support to prefer the use of "PortMapping" to "Port"
for linking. This has meant adding the ability for checking multiple
Link attribute names when linking to a subcomponent to keep backwards
compatability with existing configs that are using "Port" rather than
"PortMapping".
=> Correct logic of linking to LB

aws/templates/solution/solution_ElasticSearch.ftl, aws/templates/solution/solution_userpool.ftl
For elasticsearch and userpools an epilogue script has to be run to update some settings which are not available in cloudformation. However to perform these updates you need the Id or name of the resource to perform the update which isn't available on the initial creation of the component. 
To get around this the epilogue script will provide a warning that another update  has to be made to complete the configuration.
=> Fix epilouge processing to warn of multiple run requirement

aws/templates/id/id_es.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ElasticSearch.ftl
Reserve all IP address groups starting with "_". Initially use these for
an open CIDR (_global) and the current segment nat ips (_segment).
Support a few variants with one or two "_" on either side as well.
Refactor the elastic search support accordingly.
We will likely add an _environment in future if all segments in an
environment need access to something.
=> Introduce reserved IPAddressGroups

aws/templates/resource/resource_es.ftl
Adds the index path and makes it an array. Only seemed to affect the blueprint generation...
=> Minor fix for ESDomain formatting

aws/templates/id/id_rds.ftl, aws/templates/solution/solution_rds.ftl
Allows you to add a prefix to the encrypted strings created as part of the password generation process (e.g. base64:). This is used by some products to determine if the environment variable is encrypted or not.
=> Add Encrypted variable prefix option to RDS Password Generation

aws/utility.sh
aws s3 sync command has some odd behaviour in terms of timestamp
comparisons when file sizes are the same, so ensure all files are copied
by using the local (presumably current) time.
=> Force use of local time on unzip

aws/runTask.sh
Try to find the ECS task using the new naming syntax of product-environment-segment and if not fall back to product-environment.
=> Add environment support for ECS task run

aws/utility.sh
In a url a + is often converted to %20 which is a space. So when passing the password to something like Django the password is interpreted as a space instead of a + and so login fails.
=> add + to password blacklist

aws/data/masterData.json, aws/templates/application/application_ecs.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_lb.ftl, aws/templates/resource/resource_ecs.ftl, aws/templates/resource/resource_lb.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_lb.ftl
This PR has a few networking/ load balancing changes 
- Add support for the awsvpc ECS container network mode 
- This creates an eni for each container in a service which bypasses the host network adapter. This removes issues with exposing the same port on multiple containers since each container has its own IP 
- **Configuration** - ECS Service Component
- NetworkMode - setting the network mode to awsvpc enables awsvpc for all containers within the service (defaults to "" which is the standard ecs network mode) 
- Add Target Type to LB 
- When using awsvpc mode you can't use the instance target type for an ALB or NLB target group since this just goes off the first adapter on the instance that responds. Instead you need to specify the IP address of the ENI for the specific container 
- …
=> ECS awsvpc networking and Network Load balancer Support

aws/templates/application/application_ecs.ftl, aws/templates/common.ftl, aws/templates/container/container_jenkins.ftl, aws/templates/id/id_ecs.ftl, aws/templates/policy/policy_ecs.ftl, aws/templates/resource/resource_ecs.ftl
Delegated deployment was added to codeontap so that we could use the jenkins ecs agent plugin which ran ECS tasks on demand. This essentially required us to build an ECS tasks definition and pass it to the Jenkins server so it could create the task definition itself.
The plugin has been now updated so that you can specify an existing task definition to use and Jenkins will then use it.
This PR removes the DelegatedDeploy Task configuration and instead adds an overall capability for components to run/start an ECS task. Linking to a task with the role run will provide 2 Attributes 
- ECSHOST - The ARN of the ECS host the Task belongs to 
- DEFINITION - The family name of the TaskDefinition 
DEFINITION is only available if the task has a fixed family name as this allows for the task to be …
=> ECS Remove Delegated Domain and add Task run Configuration

aws/templates/id/id_s3.ftl, aws/templates/solution/solution_s3.ftl
Adds the ability to make a solution S3 bucket publicly accessible through bucket policy 
Configuration
- PublicAccess
- Enabled 
- default: false 
- IPAddressGruops 
- default: _localnet
- Permissions 
- default: ro (read only) 
- Possible options: rw (read write), wo (write only) 
- Prefix 
- default "" 
- add a prefix to the object policy
=> S3 Public Bucket Access

aws/templates/id/id_lb.ftl, aws/templates/resource/resource_lb.ftl, aws/templates/solution/solution_lb.ftl
Adds the ability to configure the idle timeout on an LB component. The default is currently set to 60 seconds which can be a problem for long running tasks that don't send back progress updates.
=> Add idle timeout configuration to LB component

aws/templates/id/id_lambda.ftl
The name attribute for a lambda is provided as the Ref Attribute and doens't have its own output reference
=> Fix lookup of lambda name attribtue

aws/templates/application/application_ecs.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_ecs.ftl
Allows for IP address group rules to be specified on a container port without a load balancer. 
This is useful in scenarios where a container registers with another service and its IP address is included in the registration and two way communication is required (both initiating) 
Also adds a name attribute as a placeholder attribute on services. This allows you to link to a service and access its settings/config via a container fragment.
please merge before #363 as this PR will cause conflicts with it.
=> Add IP Address group control to  container ports

aws/templates/id/id_rds.ftl, aws/templates/solution/solution_rds.ftl
The current implementation of the encryption prefix setup for generated credentials stored the prefix in the psuedo stack file. 
This isn't actually required and instead this should be performed at template generation time. This fix allows for passwords and URLs that have been generated with the prefix in the pseudo stack file to be left as they are. Urls that have the prefix will be automatically updated but passwords would need to be updated manually or reset the password
=> Move encryption prefix handling to run time instead of psuedo stack

aws/templates/application/application_computecluster.ftl, aws/templates/application/application_ecs.ftl, aws/templates/common.ftl, aws/templates/id/id_cognito.ftl, aws/templates/id/id_lb.ftl, aws/templates/resource/resource_cognito.ftl, aws/templates/resource/resource_lb.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_lb.ftl, aws/templates/solution/solution_userpool.ftl, aws/utility.sh
Adds support for a load balancer to authenticate clients using a cognito user pool (https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/) 
To support this a number of changes are required 
- UserPools
- Configuration
- OAuth - Scopes - The oAuth scopes presented to the client - Default openid
- OAuth - Flows - The oAuth flows used for authentication - Default code (authorisation code grant) 
- LoadBalancer - Port
- Configuration 
- Path - The client side path which will match to a specific target group or action - Default default
- Priority - If a rule needs to be created the priority of the rule against other rules ( lowest wins) - Default 100 
- Links - Adds standard links
- Authentication - SessionCookieName - The cookie used to determine if authentication is required - …
=> Add Support for Cognito Auth with Application Load Balancers

aws/templates/application/application_ecs.ftl, aws/templates/commonApplication.ftl, aws/templates/container/container_codeontap.ftl, aws/templates/container/container_jenkins.ftl, aws/templates/container/container_redirector.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/resource/resource_ecs.ftl, aws/templates/solution/solution_ecs.ftl
A few changes required for the codeontap task container 
- Remove all standard environment variables to prevent issues with environment variables defined during codeontap process
- Add ManagedPolicy Container fragment macro to attach predefined polices to task role
- Add codeontap container configuration to use a comma separated list env variable AWS_AUTOMATION_POLICIES to attach managed policies which have been defined for switching roles to other accounts 
- Add new AWSProfile volume to codeontap container which is used for a persistent aws cli config file. Config file maps to /var/opt/awsprofile/config and sets AWS_CONFIG_PROFILE variable to match
- Add the ability to configure Privileged mode to containers so that they can access the host (required for docker in docker scenarios) 
- …
=> Codeontap task container configuration

aws/createSSLCertificateRequest.sh
Include specific openssl config for SR generation inline so it is explicit and doesn't require config of installation config files
=> Support SAN in SSL CSR generation

aws/templates/solution/solution_lb.ftl
Rename IP Address group lookup in LB solution component so that it doesn't overlap with the global ipAddressGroups Variable. 
Not sure how this snuck in.
=> Fix up IP Address lookup for LB component

aws/templates/application/application_lambda.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_lambda.ftl
Support an optional switch to place the environment settings in a config
file rather than as environment variables.
This avoids the limit on environment size in lambda.
Regardless of the switch, the core settings are still defined in order
that the bucket and settings prefix are available.
The variable CONFIG_FILE is also set with the relative filename of the
config file relative to the SETTINGS_PREFIX path.
=> Add environment file support for lambda

aws/templates/application/application_ecs.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ecs.ftl
Adds a configuration option on an ECS service to add links in between the containers in a task definition.
This allows containers in the same task definition to communicate without port mappings.
The service must be using the bridge network mode to enable this feature
=> Add container network linking in service definitions

aws/templates/solution/solution_lb.ftl, aws/templates/solution/solution_userpool.ftl
Adds the ability to use external links to enable cognito based authentication on a load balancer. 
Also adds the reverse link to provide callback URLS to a cognito userpool
=> Add external link support for Cognito LB auth

aws/templates/common.ftl, aws/templates/resource/resource_ecs.ftl
Add minor fix which makes sure that when using container network links that it doesn't create a link for its self.
=> Add fix for circular references in links

aws/templates/application/application_ecs.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ecs.ftl
Container links are actually only available in a unidirectional setup because the container needs to be available on the start up of the linking container. 
This change makes the ContainerNetworkLinks a container property, you can set a list of container names that are part of your service/task definition and they will be added as host file entries on the container that has ContainerNetworkLinks configured
=> Update Network link to explicit container links

aws/templates/policy/policy_s3.ftl
Some actions in S3 like ListObjects in the boto api are performed against the S3 bucket instead of the objects in the bucket. 
This PR adds a new function getS3BucketStatement which allows for bucket level permissions to be applied. 
It also uses the s3:prefix condition to control what can be listed within the bucket 
See: https://docs.aws.amazon.com/AmazonS3/latest/dev/amazon-s3-policy-keys.html#bucket-keys-in-amazon-s3-policies
=> Add Bucket to S3 related Policies

aws/templates/id/id_cognito.ftl, aws/templates/resource/resource_cognito.ftl, aws/templates/solution/solution_userpool.ftl
Minor updates to cognito user pools. 
- Lets you set a LogOutURL via an external link 
- Moves the userpool domain to its own resource to prevent overlap in cli command json outputs
- Remove outputs that are supported in cloudformation but not in cognito (??)
=> Add External link logout urls for Cognito

aws/templates/solution/solution_rds.ftl, aws/utility.sh
The MasterUsername of an rds instance can not be changed once it has been deployed, this also includes snapshots. 
Since we can't change the username we need to make sure that the solution configuration matches the snapshot username.
This adds a check on the username of a manual snapshot to make sure that the solution configuration matches it. This will raise an exception and you need to fix the config.
=> Add RDS Snapshot MasterUsername check

aws/templates/application/application_apigateway.ftl
For regional APIs, we need the host field so it can match the
custom domain name on the API.
=> Pass host field through for regional apis

aws/utility.sh
Need to quote the paths so they are not expanded by the shell.
=> Escape paths for cloudfront distribution invalidation

aws/templates/container/container_cleanup.ftl, aws/templates/container/container_codeontap.ftl, aws/templates/container/container_couchdb.ftl, aws/templates/container/container_filter.ftl, aws/templates/container/container_jenkins.ftl, aws/templates/container/container_logstash.ftl, aws/templates/container/container_mongodb.ftl, aws/templates/container/container_rabbit.ftl, aws/templates/container/container_redirector.ftl, aws/templates/container/start.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ec2.ftl
Adds the ability to have shared container fragments. When a container Id starts with an underscore its instance and version details are ignored when processing container fragments. 
This allows for container fragments that can be shared between all instances and versions of a container.
=> Shared container fragments

aws/templates/commonApplication.ftl
When working with appsettings as files you might not know exactly how many files you are being given. 
This permission allows you to list the objects in the components settings prefix only in order to run a listObjects command from within an app. 
Also adds a minor fix to include sensitive settings as environment variables
=> Add List Bucket permissions to standard policy

aws/templates/common.ftl, aws/templates/id/id_cw.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/id/id_sns.ftl, aws/templates/policy/policy_cw.ftl, aws/templates/policy/policy_sns.ftl, aws/templates/resource/resource_sns.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_mobilenotifier.ftl, aws/utility.sh
Adds initial support for mobile notifiers which are used to send push notifications to multiple mobile platforms 
A mobilenotifier resource containers a list of platforms, each of these platforms send notifications to a specific mobile platform, APNS (Apple), Google etc. 
Each platform is configured with an engine, we currently support: 
- APNS
- APNS_SANDBOX
- GCM
- SMS 
With the exception of SMS each of them require credentials provided by the mobile platform. For apple this is a certificate and private key and for GCM this is a shared secret. These need to be encrypted using KMS and stored as credentials, with the name format 
```
<platformId>_Principal - APNS only - this is the certificate provided by apple  - not required for GCM
<platformId_Credential - APNS - private certificate - …
```
=> Mobile Notification Proxy

aws/templates/commonApplication.ftl, aws/templates/resource/resource_ecs.ftl
Adds the ability to define startup overrides on containers using a container fragment macro. 
Both the entrypoint and command are available as separate macros as they map to different properties
=> Container Startup Overrides

aws/templates/commonApplication.ftl
A recent change initially saw only general settings included. This was
then changed so that only sensitive settings were included.
Revert it back to the way it was so they are all included.
=> Ensure all product settings included by default

aws/templates/common.ftl, aws/templates/id/id_iam.ftl, aws/templates/id/id_user.ftl, aws/templates/resource/resource_iam.ftl, aws/templates/solution/solution_user.ftl, aws/utility.sh
Adds the ability to create users as a solution level component. 
Users have two types:
- system - generates an IAM Access/Secret key only
- user - generates and sets a Password only 
secrets and passwords are encrypted using the segment encryption key and stored in a pseudo stack
=> Add System user support

aws/createTemplate.sh, aws/templates/application/application_lambda.ftl, aws/templates/commonApplication.ftl, aws/templates/resource/start.ftl
Include the runId as metadata in every template
Treate runId differences as not significant unless specifically
requested.
Update "config as file" support to include runId in the S3 object to
trigger code updates when the config file contents change (assuming the
request asks for them to be treated as significant).
Align lambda code with the config as file changes.
NOTE: the api-gateway template already uses the runId to trigger redeploys
so will automatically be affected by the same switch flagging runId
differences as significant.
=> Allow treating of runId as significant

aws/manageStack.sh
When creating named IAM resources (IAM users) you need to specify an extra capability in order to provision them with cloudformation
=> Add named IAM capability to cloudformation tasks

aws/templates/solution/solution_ec2.ftl
Add a config file to solution level ec2 components which contain the details of any links that are in place for it.
=> Add Link Variables for ec2 solution components

aws/data/masterData.json, aws/templates/application/application_computecluster.ftl, aws/templates/common.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/id/id_cw.ftl, aws/templates/id/id_ec2.ftl, aws/templates/policy/policy_cw.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl
Adds support for the provisioning of the awslogs agent to enable Ec2 based logging to Cloudwatch. 
LogFiles are grouped into LogFileGroups based on the logging content, with the defaults as system, security, docker, aws-system, aws-ecs 
Each ec2 based component has a LogProfile assigned to it which is a list of LogFileGroups. 
The awslogs agent is installed as part of the cfn-init process and the config file is deployed as part of this process.
=> Add awslogs agent support for Cloudwatch Ec2 Logging

aws/templates/application/application_user.ftl, aws/templates/id/id_user.ftl, aws/templates/id/start.ftl, aws/utility.sh
The SES SMTP password is made from a hash of a users IAM SECRET Access key 
This PR adds this hashed smtp password into the attributes of a user application component.
This does not apply SES permissions just creates the password that is required
=> Add SES SMTP Password Generation

aws/templates/application/application_computecluster.ftl, aws/templates/id/id_cw.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl
After deploying the existing configuration it shows that searching logs when they are split into groups is going to be difficult. Instead the logs will be consolidated down to a single log group which allows for the logs to be searched across an entire component. 
The exception is the ecs logs which have a dedicated instancelogs log group to seperate container logs from host logs.
=> consolidate instance logs into single log group

aws/templates/commonApplication.ftl
Underscore symbol is escaped in the environment variable `SETTINGS_FILE` value, so a filename shall not contain it.
=> remove underscore from config filename

aws/runTask.sh
Add Version and Instance support to the runTask Command
Without this when you have multiple instances or versions configured the filter returns multiple task definitions which fails when the task is run with both
=> Add support for tasks and versions in runTask

aws/templates/id/id_lb.ftl, aws/templates/resource/resource_lb.ftl, aws/templates/solution/solution_lb.ftl
Reorganise the logic of LB processing to support addition of redirect
and fixed response rules on ALB.
Separate out determination of which is the first port mapping for a
given source port.
Add redirect and fixed response rule creation via CLI.
Fixed response values are taken from the settings if present, otherwise
from the solution.
Add explicit flag controlling creation of target group, as we don't need
one for redirects or fixed responses.
Remove redundant copy of case statement for creating the classic LB.
=> Support for redirects and fixed response on ALB

aws/templates/base.ftl, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_cache.ftl, aws/templates/id/id_cognito.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/id/id_contenthub.ftl, aws/templates/id/id_datapipeline.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_efs.ftl, aws/templates/id/id_es.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_lb.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/id/id_rds.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/id_spa.ftl, aws/templates/id/id_sqs.ftl, aws/templates/id/id_user.ftl, aws/templates/setContext.ftl
Use constants for types
Introduce types for arrays of base types. The most common usage is array
of strings.
Update values checking to handle arrays of values.
Add some descriptive material in regards to qualifiers in prepraration
for its implementation.
Split all the "base" stuff from common.
=> Refactor type support

aws/createTemplate.sh, aws/templates/base.ftl, aws/templates/id/id_datapipeline.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_rds.ftl, aws/templates/solution/solution_ecs.ftl
For legacy containers that don't support task roles, allow permissions
to be added to the ecs instance service role.
The main target at this point is the rabbit container.
An alternative was to attach container policies to the ecs role rather than task roles, but this got messy in terms of ensuring everything was included into the iam subset and handling use of managed policies, so I just opted for adding the same policy via fragments at the solution level.
=> Add fragment support for ecs solution

aws/contextTree.sh, aws/createBuildBlueprint.sh, aws/createTemplate.sh, aws/templates/account/account_s3.ftl, aws/templates/common.ftl, aws/templates/createBuildBlueprint.ftl, aws/templates/id/id_dataset.ftl
Ref: #425
Adds support for an S3 buckets contents to be treated in a similar way to a code artefact. 
A dataset does not provision any resources directly instead it adds an application level layer to a solution component, in this case an S3 bucket.
A dataset adds extra attributes to the existing solution component level attribute which tell other components 2 main pieces of information
- Where data can be uploaded to if the data set needs to be updated - the master data location 
- Where the latest built version of the data is available - this location of the data in the S3 based account-registry 
This component also allows for application builds to be processed using the deployment unit
=> S3 Datasets

aws/templates/common.ftl, aws/templates/id/id_rds.ftl, aws/templates/solution/solution_rds.ftl, aws/utility.sh
Fixes #431 
Instead of using a getExistingRefernce to determine the hostname the RDS hostname is looked up using the AWS cli when generating the encrypted URL. 
Also a couple of extra fixes for the size type attribute exceptions
=> Add hostname fix for RDS and minor type lookup fix

aws/templates/application/application_computecluster.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_ec2.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl
Adds the ability to create files and directories on ec2 based instance components with fragment macros
- File - creates a file with optionally specified contents
- Directory - Creates a directory, if the directory already exists updates dir permissions and its child with the settings in the macro
=> Add fragment support for file and directory creation

aws/data/masterData.json, aws/templates/id/id_s3.ftl, aws/templates/resource/resource_s3.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_s3.ftl
Fixes: https://github.com/codeontap/codeontap/issues/35 
Adds support for CORS Profiles to be defined and applied to S3 Buckets. Created a set of basic default CORS Profiles which can be used for S3 bucket actions S3Read,S3Write,S3Delete.
=> Add CORS Profiles and enable for S3

aws/templates/application/application_computecluster.ftl, aws/templates/application/application_lambda.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl
- Sets starter object in context 
- Fixes script creation if files or dirs aren't present
- Aligns Managed Policy config across components which are using it
=> Fixes for file and dir creation

aws/templates/base.ftl
When an appsettings is set as a boolean or number in the app settings it should be converted to a string when it is converted into environment variables.
=> Add conversion of boolean and number in string setup

aws/templates/id/id_lb.ftl, aws/templates/solution/solution_lb.ftl, aws/utility.sh
Minor fix for redirect policy. When applying the current redirect rule I get the following error: 
> An error occurred (ValidationError) when calling the CreateRule operation: 1 validation error detected: Value 'https' at 'actions.1.member.redirectConfig.protocol' failed to satisfy constraint: Member must satisfy regular expression pattern: ^(HTTPS?|#\{protocol\})$
Looks like the protocol can either be HTTPS or the protocol variable. 
Also made Permanent enabled by default since this would make the default redirect config perform an http -> https redirect as it would be expected.
=> Fix redirect config

aws/contextTree.sh, aws/createTemplate.sh, aws/templates/account/account_apigateway.ftl, aws/templates/account/account_audit.ftl, aws/templates/account/account_cert.ftl, aws/templates/account/account_roles.ftl, aws/templates/account/account_s3.ftl, aws/templates/account/account_sms.ftl, aws/templates/account/account_waf.ftl, aws/templates/common.ftl, aws/templates/createAccountTemplate.ftl, aws/utility.sh
Support IAM pass to create roles before they are needed for other units
such as SMS.
Reorganise settings so account level settings can be accessed separate
from the tier/component occurrence setting processing.
Add SMS unit for account level SMS setting control.
=> Refactor account level support

aws/templates/common.ftl
Not all settings categories are available for all components so we need to allow for them to be undefined.
=> Make settings stores optional

aws/data/masterData.json, aws/templates/application/application_computecluster.ftl, aws/templates/application/application_ecs.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_lb.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/resource/resource_lb.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_lb.ftl, aws/utility.sh
This PR includes a number of changes and fixes for the LB component 
**Features** 
- Host Filtering - Adds a condition on a listener rule for the generated DNS hostname of the site. This prevents requests to the load balancer IP addresses which can be used for malicious probing. The option is applied on each port mapping and can only be used on ports with certificates configured 
**Changes**
- For Application Load balancers all listener rules are now created via CLI instead of cloudformation. This allows the rules to be managed easier and stops overalaps between cli and cloudformation which prevents updates 
- As part of this process all listener rules are removed before adding the new rules. This ensures that rules are cleaned up and only the configured rules will be applied. This will …
=> LB Fixes and Improvements

aws/templates/resource/resource_ec2.ftl
Since the bootstrap directories are user defined we can't reliably use a wild card search to update the file permissions. 
Instead we will use find to update the permissions on all files downloaded into the bootstrap directory
=> Change to find for baseline permissions

aws/templates/application/application_lambda.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_sqs.ftl, aws/templates/resource/resource_lambda.ftl, aws/templates/resource/start.ftl
Add a resource for lambda "pull" event sources.
Add a new link role called "event" to detect when an event source should
be created.
Add processing for SQS as an event source to lambd support.
Normal outbound link processing provides the mechanism to permit lambda
to poll the SQS queue and manage message removal.
=> Add SQS as an event source for lambda

aws/templates/id/id_sqs.ftl
Lambda doesn't need to be able to send messages, only read/delete them.
=> Correct permissions for SQS as lambda event source

aws/createTemplate.sh, aws/templates/commonApplication.ftl, aws/templates/resource/start.ftl
Adds a fix for Lambda functions using config files stored in s3 where the config file changes but the lambda funciton doesn't. This change ensures that they should update together
Also adds diff checking on *.sh scripts that are generated. This allows for .sh files to be ignored if they haven't changed
=> RunId Fixes for Lambda And .sh scripts

aws/data/masterData.json, aws/templates/application/application_apigateway.ftl, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_lb.ftl, aws/templates/id/id_spa.ftl, aws/templates/resource/resource_cf.ftl, aws/templates/resource/resource_lb.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_lb.ftl, aws/templates/solution/solution_spa.ftl
Moves the HTTPS cipher profile configuration out of hard coded temaplate config into a profile stored i the master data file.
This allows for the profile to be configured at all levels and also adds support for profiles to be set as part of the component configuration.
=> HTTPS Security Profile as master data

aws/data/masterData.json, aws/templates/application/application_lambda.ftl, aws/templates/id/id_cw.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/policy/policy_sns.ftl, aws/templates/resource/resource_cw.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_mobilenotifier.ftl
This PR adds support for a LogWatcher, logwatchers can be configured with 2 types
- Metric - When the given filter is matched increment a cloudwatch metric by 1. Combine this with alerts to generate alerts based on log events
- Subscription - When the given filter is matched forward the log to the linked component. This is use to provide log forwarding functionality 
Links are used with log subscriptions to join them to a lambda function which is triggered when the log message and the message will be provided to the lambda function event call 
Also adds a LogFilters master data section which allows you to use predefined filters across mutiple log watchers. 
Currently supported on the following Components
- Lambda
- Mobile Notifier 
**Exmaple** 
```
"notifier" : {
"DeploymentUnits" : …
```
=> LogWatchers - Trigger Lambda based on log events

aws/createTemplate.sh, aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_lambda.ftl, aws/templates/setContext.ftl
Add the ability to select whether environment values should be serialised as strings or native JSON types
When everything is serialised as a string, add an optional prefix for objects and arrays so the consumer knows to process the contents as serialisable as JSON
=> Add finer grained control over environment serialisation

aws/data/masterData.json, aws/templates/application/application_lambda.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/resource/resource_cw.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_mobilenotifier.ftl
Instead of making a logwatcher part of the logging component it is now part of the destination receiving the log at the moment this is just Lambda 
In this setup the lambda with a log watch links to a component that it wants to watch. This will configure the log subscription as part of the lambda deployment. 
Log metrics stay with the component that generates the log but they are now part of the logs pass to make sure they are created with their log. 
Minor fix for the wall logs log filter pattern as well
=> Rework Log Watchers to be based on the receiver of the log

aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_lambda.ftl
Processing can always assume a link target object has a Role attribute,
though it may be empty.
Also add "invoke" as the default inbound and outbound role for lambda.
=> getLinkTarget always returns the effective role

aws/templates/application/application_apigateway.ftl, aws/templates/resource/resource_apigateway.ftl
At present, cloud formation reports a circular reference if the resource policy references the apiId. 
A feature update to allow this has been lodged. 
Seems dumb given its a resource policy.
=> Workaround for self reference error in api gateway templates

aws/templates/commonApplication.ftl
Set `CONFIG_FILE` with an s3 url value so it can be used in code instead of `OPSDATA_BUCKET`, `SETTINGS_PREFIX`, `SETTINGS_FILE` combination.
=> use CONFIG_FILE with s3 url value instead of SETTINGS_FILE

aws/contextTree.sh, aws/templates/account/account_sms.ftl, aws/templates/createAccountTemplate.ftl, aws/templates/id/id_cw.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/name/name_mobilenotifier.ftl, aws/templates/solution/solution_mobilenotifier.ftl, aws/templates/swagger.ftl
The SMS service only supports one pair of sms logs so shift their
management to the account level.
The local notifier is still supported to allow linking but will always
return the same logs.
=> Move SMS cloudwatch log creation to account level

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_computecluster.ftl, aws/templates/application/application_datapipeline.ftl, aws/templates/application/application_lambda.ftl, aws/templates/application/application_spa.ftl, aws/templates/application/application_user.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/createSwaggerExtensions.ftl, aws/templates/fragment/fragment_codeontap.ftl, aws/templates/fragment/fragment_jenkins.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl
Align context references to the standard of identifying framework
related values by starting them with an underscore.
=> Context references now use _context

aws/data/masterData.json, aws/templates/common.ftl
A certificate or certificate behaviour object can now have a HostParts
array, listing the parts to be considered for a host name.
This list is used to drive the candidate parts considered, so anything
not in this list will not be included.
In addition, the booleans in IncludeInHost continue to apply for those
parts in the HostParts array. However, if the boolean is not present, is
it considered to have a value of true.
It is thus possible to override the host structure either via the
HostParts array or via controlling the flags for each part. By default,
the flags are used to not provide the Environment in the host name in
production environments.
=> Add control over the ordering of host name parts

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_apiusageplan.ftl, aws/templates/application/application_user.ftl, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_user.ftl, aws/templates/resource/resource_apigateway.ftl
Allow the creation of a usage plan that can then be linked to from users.
Create an API key for the user to be included into any usage plans to which they are linked.
Move creation of some API Gateway resources to macros as they now occur in multiple places.
A user is given permission to invoke any api to which the usage plan is linked.
=> Add support for usage plans

aws/templates/common.ftl, aws/templates/id/id_sqs.ftl, aws/templates/policy/policy_sqs.ftl, aws/templates/setContext.ftl
A link can now have a "Type" attribute. It is only considered where the
link is external.
If present, it is used to determine what the target component type is
and generate the occurrence structure on this basis. this permits IAM
roles etc to still be generated even though the target is external.
Support needs to be explicitly added to any component state routine for
it to be supported. At present only SQS queues are implemented.
=> Introduce framework for typed links

aws/templates/application/application_computecluster.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ecs.ftl
Adds control to the autoscale update process to control what happens when an autoscaling Ec2 Instance is updated. 
This does not cover off when to autoscale just what happens when Cloudofmation interacts with an autoscale cluster. 
This introduces a few changes to our current autoscale cluster setup 
- Enables CFN Signal by default, cfn signal is used to notify cloudformation that Ec2 has finished its cfn-init tasks and that the instance is ready to go. If the signal is not received the instance will be marked as a failure 
- Enables rolling updates of ec2 instances in the cluster - Cloudformation can be configured to either create a new Autoscale Group with brand new instances or roll through each instance in an existing Autoscale group and replace each instance in the cluster. This …
=> Add AutoScale Update Controls 

aws/templates/application/application_apigateway.ftl, aws/templates/id/id_apigateway.ftl
Always enable these for now. Cloudwatch log can be created in lg unit.
=> Enable access logs for API Gateway

.gitignore, aws/createReference.sh, aws/templates/common.ftl, aws/templates/createBuildBlueprint.ftl, aws/templates/createComponentReference.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_cache.ftl, aws/templates/id/id_cognito.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/id/id_contenthub.ftl, aws/templates/id/id_datapipeline.ftl, aws/templates/id/id_dataset.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_efs.ftl, aws/templates/id/id_es.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_lb.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/id/id_rds.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/id_spa.ftl, aws/templates/id/id_sqs.ftl, aws/templates/id/id_user.ftl, aws/templates/setContext.ftl
- Adds support for generate a markdown based reference document based on the component configuration defined in the *id.ftl files. 
- Adds a properties section to the component configuration objects which adds documentation or immutable attributes for a component 
Properties have the following types
- Description - A description of the component and what it does  
- Note - A informational note. Severity can also be set on a Note property to highlight the note appropriately 
- Providers - The providers that support the component 
- ComponentLevel - The level ( segment, solution, application, etc ) that the component is deployed with 
- Updated all Attribute name properties to **Names** instead of **Name**.  Single string is still accepted and will be converted to a single item list during …
=> Component reference and id properties

aws/templates/resource/start.ftl
Scope stack output lookups to the specified account. This can be overridden, when required
=> Default stack outputs to the defined account

aws/templates/application/application_datapipeline.ftl, aws/templates/application/application_user.ftl, aws/templates/common.ftl, aws/templates/createAccountTemplate.ftl, aws/templates/createApplicationTemplate.ftl, aws/templates/createMultipleTemplate.ftl, aws/templates/createProductTemplate.ftl, aws/templates/createSegmentTemplate.ftl, aws/templates/createSolutionTemplate.ftl, aws/templates/resource/start.ftl, aws/templates/solution/solution_contenthub.ftl, aws/templates/solution/solution_mobilenotifier.ftl, aws/templates/solution/solution_rds.ftl, aws/utility.sh
Add the standard stack outputs to pseudo stack files generated as part of the epilogue/prologue process. 
This ensures that when deploying the same environment to multiple accounts that the stack outputs align as they are supposed to be. 
Also adds some minor fixes for system users with console credentials
=> Add Standard outputs to pseudo stack outputs

aws/templates/id/id_user.ftl
Names use the full name rather than the short name unless there are length limitations
=> Use full name for api keys

aws/templates/resource/start.ftl
Also default to empty if not found so that createReferenceTemplate doesn't trip up when account isn't defined
=> Add Region default filter to migrateId

aws/contextTree.sh, aws/templates/segment/segment_cmk.ftl, aws/utility.sh
When deploying the same environment to a new account or to multiple regions we need to have separate encyrpted ssh keys for each account-region combination for the environment-segment. 
This PR adds this behaviour for the creation of new ssh keys and upgrades the existing CMDB update existing ssh keys 
Along with this, older stack output files didn't reference the account in the file name. This PR adds an upgrade step which renames all stack output files to include the account-region combination. 
It also checks that the minimum stack output values are available in the stack outputs file itself. and adds the default Account and Region to the files.
=> Ensure StackOutputs and SSH Keys reference their account and region

aws/templates/application/application_ecs.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ecs.ftl
Fix: for Port Mapping configuration which allows for Host - Container mappings to be defined without a load balancer. 
Feature: ECS placement strategies - initially adds daemon support which ensures that all ECS instance have a single instance of the service running all the time
=> ECS Service - Fix Port Mapping to Host and add daemon placement strategy

aws/templates/fragment/fragment_rabbit.ftl
Remove the default settings from the container and make the loglevel configurable using settings.
=> Rabbit - Remove variables and make log level configurable

aws/templates/commonApplication.ftl
ECS containers without LB configuration should be able to create Security Groups
=> Allow Security group ingress rules for non LB containers

aws/templates/application/application_apiusageplan.ftl, aws/templates/application/application_lambda.ftl, aws/templates/application/application_user.ftl, aws/templates/common.ftl, aws/templates/solution/solution_userpool.ftl
By default, getLinkTargets will only return active links - the target is
enabled and deployed. It will still return external links regardless.
This means there is no need to check for deployment in most situations.
Occasionally, such as with users, you may wish to have different logic
depending on whether the target is deployed or not, in which case the
Octivenly flag can be set to false, and isTargetActive() used to control
the logic flow.
=> Add active link target detection

aws/templates/solution/solution_lb.ftl
With the potential for multiple rules in the config due to domain
redirects, change the logic for determining if a forward rule is
required.
=> Add a forward rule if no redirect or fixed rule

aws/templates/resource/resource_lb.ftl
Redirect rules always need to start with a / to signify the start of the path.
=> Make sure Path property is a valid path

aws/templates/application/application_ecs.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_ecs.ftl
Adds support for Alarms and Log Metrics on ECS Containers. 
Depending on the Logging type configured, Task Log Group or Container Log group the configuration is either defined on the Task or on the Container.
=> Add support for Log Mertics and Alarms to Container Deployments

aws/templates/fragment/fragment_cfredirect.ftl, aws/templates/id/id_lambda.ftl
For S3, the host needs to be adjusted to match the signature
that will be generated as part of the origin request.
=> Force Host header to match origin

aws/data/masterData.json, aws/templates/application/application_lambda.ftl, aws/templates/commonApplication.ftl, aws/templates/fragment/fragment_cfredirect.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_spa.ftl, aws/templates/resource/resource_lambda.ftl, aws/templates/solution/solution_spa.ftl
Adds a version to the cfredirect configuration. Once deployed Lambda@Edge functions have big problems with being updated. 
Locking the cfredirect function to only deploy once means that you have a fixed version Id that can be referenced by CloudFront. If any updates need to be made to the function then a new version of the function needs to be created in the codeontap repository and then rolled out to each CloudFront distribution thorugh the configuration option
```
RedirectAliases : {
RedirectVersion : ""
}
```
Also introduces codeHash checking for lambda functions which does allow the lambda version to enforce no new changes to the code package. However this does not work for inline ZipFile contents since the deployment package changes on each deployment.
=> Fix lambda version config

aws/templates/solution/solution_lb.ftl
Standard forwarding on an application load balancer should be the last resort so that it can be overridden with anything more specific. 
This change only adds the forward rule if no other primary rule has been added
=> Make sure forwarding is a last resort

aws/templates/solution/solution_s3.ftl
The bucketPolicy Resource is only available if bucket policy has been configured. Minor fix to make sure the bucketPolicy ID isn't looked up when its not needed
=> Minor fix for bucket policy Id lookup

aws/templates/id/id_sqs.ftl
to get an additional broker url with sqs:// protocol instead of https://
=> add PRODUCT_URL attribute to sqs resource with sqs:// prefix

aws/templates/common.ftl, aws/templates/solution/solution_ElasticSearch.ftl
When using types for external links skip the collection of the type specific occurrence configuration as it won't be available for the link. 
This means that external links with types do need to be processed specially but this was required anyway.
=> Skip type processing for external links

aws/templates/solution/solution_lb.ftl
Minor fix for LB to SPA redirect rule to make sure protocol matches casing requirements
=> Fix casing for LB ->  SPA redirect rule

aws/createTemplate.sh, aws/data/masterData.json, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_bastion.ftl, aws/templates/id/id_cache.ftl, aws/templates/id/id_cognito.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/id/id_datapipeline.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_efs.ftl, aws/templates/id/id_es.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_lb.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/id/id_rds.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/id_spa.ftl, aws/templates/id/id_sqs.ftl, aws/templates/id/id_user.ftl, aws/templates/resource/start.ftl, aws/templates/setContext.ftl
Adds the idea of Deployment Profiles, deployment profiles modify the solution configuration based on the deploymentMode which the createTemplate job is being run under. 
This allows you to modify the template generation based on a given scenario. The main examples of this would be to enable maintenance mode or to hibernate a deployment. 
The default configuration that is part of this PR is to add custom configuration for the maintenance deployment Mode .
With the default configuration if you run a ManageEnvironment with the DEPLOYMENT_MODE set to maintenance all, deployed load balancers will be updated to include a new lbport ( listener rule )  called httpsmaintenance. This provides a fixed response that says the site is down for maintenance. 
DeploymentProfile configuration is based on …
=> Deployment Modes and Profiles

aws/data/masterData.json, aws/templates/common.ftl
This causes issues with Network and classic load balancers because they don't support the protocols or fixed responses that application engine load balancers do
=> Don't default LB maintenance in DeploymentProfiles

aws/utility.sh
When syncing to an S3 bucket we don't need to know if the prefix already exists since we will be copying new data up to it.
=> Minor fix to bucket sync to allow for new prefix

aws/templates/id/id_ecs.ftl
Added to state generation but not attributes
=> Fix log metric attribute definition on ecs host

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_ecs.ftl, aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_cw.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/resource/resource_apigateway.ftl, aws/templates/resource/resource_ecs.ftl, aws/templates/resource/resource_lambda.ftl, aws/templates/resource/resource_sns.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ecs.ftl, aws/templates/solution/solution_mobilenotifier.ftl, aws/templates/solution/solution_sqs.ftl
This PR adds support for Metric based alerting and Log Metrics for the following Components
- APIGateway - Metric Alerts and Log Metrics 
- Mobile Notifier - Metric Alerts and Log Metrics 
- Lambda - Metric Alerts and Log Metrics 
- ECS Hosts - Metric Alerts and Log Metrics 
- ECS Services - Metric Alerts and Log Metrics 
- ECS Tasks - Log Metrics  ( Metrics not available for Tasks ) 
- ECS Containers - Log Metric ( When container based logs are enabled ) 
To support this all of the resources metrics and dimensions have been mapped to their appropriate values and outputs have been added for ECS hosts and ECS Tasks 
My brain hurts now...
=> Extend alerting and Log Metric support

aws/templates/application/application_ecs.ftl, aws/templates/application/application_lambda.ftl, aws/templates/id/id_ecs.ftl, aws/templates/policy/policy_ecs.ftl, aws/templates/resource/resource_event.ftl
Depends on #621 for ECS output mappings
ECS tasks can be triggered through CloudWatch events which provide a cron like schedule for running tasks.
We currently use this on lambda functions and this PR extends that functionality for ECS tasks. This can be used for long running tasks or using code already in a container for a scheduled task.
The command/entrypoint can not be overridden when it is invoked so the task must be able to run using the command/entry point the task is deployed with ( They can be overriden when defining the task using fragment files )
=> Add support for time based scheduled ECS tasks

aws/templates/id/id_s3.ftl, aws/templates/id/start.ftl, aws/templates/policy/policy_s3.ftl, aws/templates/resource/resource_s3.ftl, aws/templates/solution/solution_s3.ftl
Adds the ability to replicate data between s3 buckets in different regions ( the actual functionality supports accounts but hasn't been implemented in this PR) 
To enable replication the following configuration needs to be applied
- 2 Solution level S3 buckets deployed 
- 1 in your primary region 
- 1 in a secondary region ( region can be set using the product object and adding a region override for the bucket's deployment unit ) i.e. if deployment unit was `stgrep`
```
{
"Product" : {
"Title" : "Walks Register",
"Name" : "walksregister",
"Id" : "register",
"Domain" : "walksregister",
"stgrep" : {
"Region" : "eu-west-1"
}
}
}
```
- On the Source Bucket  add a link to the destination bucket with the role `replicadestination`
- On the Destination Bucket add a link to the source bucket with …
=> Add support for cross region replication in S3

aws/data/masterData.json, aws/templates/application/application_ecs.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_rds.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/resource/resource_rds.ftl, aws/templates/solution/solution_ecs.ftl, aws/templates/solution/solution_rds.ftl
Allows for a component to be deployed in a hibernated state. 
In a hibernated state resources which are generally charged on a time basis are shutdown or removed with specific configuration to restore them if they are state based, like RDS. 
This is intended to be used with deployment Profiles/deployment modes so that you can run a management environment using a specific deployment mode which enables hibernation on the component. 
This PR adds hibernate support for two components 
- RDS 
- Creates a snapshot of the database and then removes the RDS instance from the cloudformation template, leaving everything else behind. RDS instances can be shutdown but will automatically restart after 7 days 
- Has two startup modes, restore and replace. restore uses the snapshot to rebuild the …
=> Add support for componets to hibernate resources

aws/templates/commonApplication.ftl
ENTRYPOINT and CMD now assume either a single string or an array as
input.
=> Make handling of docker overrides consistent

aws/templates/account/account_s3.ftl, aws/templates/id/id_dataset.ftl, aws/templates/id/id_rds.ftl, aws/templates/resource/resource_rds.ftl
Add support for the RDS Data Registry 
This is a continuation of treating data as code within codeontap. The snapshot registry is used to store RDS snapshot artefacts as they cannot be moved out of S3. 
These changes are some minor changes used to support creating a buildblueprint and adds support for the rdssnapshot registry type
=> Support for RDS data registry

aws/templates/application/application_ecs.ftl
The task arn is not available in an initial iam pass at the application level. So we can't actually limit the service role to only run the nominated task. We can at least limit the ECS cluster it runs on
=> Fix Schedule Task role for IAM pass

aws/templates/account/account_audit.ftl, aws/templates/application/application_datapipeline.ftl, aws/templates/resource/resource_s3.ftl, aws/templates/resource/start.ftl
AWS resources seem to have varying limitations on the number of tags which can be applied to a resource. E.g. S3 only allows seven and data pipelines only allow 10 
This PR adds support only the number of required tags to be provided by the core tag function.
=> Add maximum tag counts for aws resource limitations

aws/integrator/manageCredentials.sh, aws/manageCrypto.sh
Script for managing integrator credentials was out of date. The underlying routines now require a JSON path to be provided.
There was also an issue in that some of the telstra tenant credentials included dashes, which were being treated as negatives by JQ, so had to be appropriately escaped.
=> Update management of integrator credentials

aws/templates/fragment/fragment_jenkins.ftl
The codeontap/jenkins-master has some overrides on the standard jenkins attributes to work with our deployment.
This PR brings these into the codeontap deployment so we can override memory allocation and ping timeouts using settings
=> Add overrides to jenkins containers for deployment properties

aws/templates/policy/policy_sns.ftl
SMS publishing doesn't have an ARN can be controlled through IAM conditions.
=> Fix sms Sending permission

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_ecs.ftl, aws/templates/application/application_lambda.ftl, aws/templates/common.ftl, aws/templates/id/id_cache.ftl, aws/templates/id/id_es.ftl, aws/templates/id/id_lb.ftl, aws/templates/id/id_rds.ftl, aws/templates/resource/resource_cache.ftl, aws/templates/resource/resource_cw.ftl, aws/templates/resource/resource_ecs.ftl, aws/templates/resource/resource_es.ftl, aws/templates/resource/resource_lb.ftl, aws/templates/resource/resource_rds.ftl, aws/templates/solution/solution_ElasticSearch.ftl, aws/templates/solution/solution_cache.ftl, aws/templates/solution/solution_ecs.ftl, aws/templates/solution/solution_lb.ftl, aws/templates/solution/solution_mobilenotifier.ftl, aws/templates/solution/solution_rds.ftl, aws/templates/solution/solution_sqs.ftl
- Adds Alert support for the following components/resources
- RDS Component 
- RDS Instance
- Cache 
- Cache Cluster 
- Elastic Search 
- Elastic search domain 
- LB 
- Load balancer - Classic
- Load balancer - Network
- Load balancer - Application 
- Fixes ECS dimension to include the cluster name 
- Fixed minor bug in ECS cluster when a fixed Maximum Count is used instead of Region based count
- Move alarm naming in to shared macro to standardise the naming of alarms 
- Adds Cloudformation Pseudo outputs ( https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/pseudo-parameter-reference.html ) to possible attributes for dimensions
=> Extend Alerts support to more resources

aws/templates/fragment/fragment_codeontap.ftl, aws/templates/fragment/fragment_jenkins.ftl
Removes a startup delay for dynamic agents. In jenkins this is a default behaviour for on demand agents which are persistent. Jenkins will wait a little bit to see if one of the other agents finishes a job and then starts the process of requesting a new instance. 
For container based jobs which only perform one task this is not a desirable feature and so it has been disabled as part of our container deployment.
=> Remove agent startupdelay

aws/contextTree.sh, aws/createExtendedSwaggerSpecification.sh, aws/createReference.sh, aws/createTemplate.sh, aws/manageStack.sh, aws/setContext.sh, aws/utility.sh
When trying to create a smaller image using alpine linux I found that mktemp wasn't working as expected. 
It turns out alpine linux uses the busybox version of mktemp which requires a different template length as a minimum requirement. Since it shouldn't be a big deal to make the template bigger for other distributions this should be a minor change
=> extend temp file creation template to support alpine mktemp

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_ecs.ftl, aws/templates/application/application_lambda.ftl, aws/templates/id/id_es.ftl, aws/templates/solution/solution_ElasticSearch.ftl, aws/templates/solution/solution_cache.ftl, aws/templates/solution/solution_ecs.ftl, aws/templates/solution/solution_lb.ftl, aws/templates/solution/solution_mobilenotifier.ftl, aws/templates/solution/solution_rds.ftl, aws/templates/solution/solution_sqs.ftl
Update alert names to be the Full Name instead of based on the resource name. 
This provides consistent naming in the alert names to make forwarding of alerts easier. 
This does mean that when two monitored resources are defined there will need to be a filter on the resource
=> Fix alert name

aws/templates/solution/solution_rds.ftl
Fix for RDS restore process so that when the backup instance is created multiAZ is not enabled
=> Disable multiAZ for back up restore

aws/templates/resource/resource_lb.ftl
Cross zone load balancing is disabled for network lb's by default.  This enables it for all network load balancers.
=> Enable cross zone lb for network lb

aws/templates/commonApplication.ftl, aws/templates/fragment/fragment_codeontap.ftl, aws/templates/resource/resource_ecs.ftl
Adds support for persisting docker volumes for a given task
This creates a docker volume which is created when the first instance of the the task is initiated. This volume is then kept on the ECS instance which ran it and when a new instance of the tasks is created the same volume is used if the task can be placed on the instance. 
This PR also adds updates to the codeontap agent fragment to uses this persistence technique for the agent home volume
=> Ecs task volume configuration

aws/runLambda.sh
Adds support for invoking a lambda function from a Jenkins job
This uses the build blueprint process to locate the lambda ARN, and only requires the deployment unit to run the task. 
Payload is optional depending on how your function behaves and the last 4kb of the log can be provided optionally if required
=> Add run lambda script

aws/data/masterData.json
Add a basic monitoring profile for CPU and memory usage on the services that we currently support for cloud watch monitoring
=> Add basic CPU memory monitoring profile

aws/runExpoAppPublish.sh, aws/templates/common.ftl, aws/templates/id/id_mobileapp.ftl
Adds initial support for building expo based mobile apps
Expo requires contextual settings for OTA updates to be available at build time for the application. As a result of this we need to build the app for each environment. 
The approach here is to have a build job which runs the necessary tests ( using node), install the dependencies then zip the contents of the src code directory.
Then on deployment the `runExpoAppPublish.sh` script is run which gets the environment context from a build blueprint, generates the OTA content, builds the IOS app and then makes this available. 
It also introduces the mobileapp component which looks after building the required attributes for the app to do its job
=> Expo build support

aws/templates/resource/resource_efs.ftl, aws/templates/segment/segment_bastion.ftl, aws/templates/segment/segment_gateway.ftl, aws/templates/solution/solution_efs.ftl
- EFS: Fix subnet lookup to use results of getSubnets
- Bastion: Allow nondeployed route tables to get around initial migration issues in IAM pass
=> minor fixes for network refactor

aws/templates/id/id_networkgateway.ftl
Workaround for component based multiAZ configuration on get occurrence states
=> default multiAZ config if not found

aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_datavolume.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_ecs.ftl, aws/templates/policy/policy_ec2.ftl, aws/templates/resource/resource_ec2.ftl, aws/templates/resource/resource_ecs.ftl, aws/templates/solution/solution_datavolume.ftl, aws/templates/solution/solution_ecs.ftl
Adds support for persistent data volumes which are managed as a seperate component from compute services. The new component is know as a datavolume and initially supports creating standalone EBS volumes
Also adds the ability to use datavolumes in ECS containers directly through the rexray ebs volume plugin. The plugin manages the mounting and unmounting of an EBS volume to an underlying docker host and then looks after passing the disk through to a container. Configuration has mostly been taken from ( https://aws.amazon.com/blogs/compute/amazon-ecs-and-docker-volume-drivers-amazon-ebs/ ) 
To configure a data volume on a container requires 2 steps 
- Creating a link from the container to the data volume 
- Create a new volume in the fragment file which references the id of the link you …
=> Adds support for persistent data volumes on ECS

aws/templates/segment/segment_bastion.ftl, aws/templates/setContext.ftl
Minor fix for the bastion component to only perform network lookups during the bastion deploymentSubset. 
During the IAM pass the network isn't available so it fails to look it up
=> <fix> skip network lookups for segment iam

aws/templates/id/id_datavolume.ftl, aws/templates/id/id_ssm.ftl, aws/templates/policy/policy_ec2.ftl, aws/templates/policy/policy_lambda.ftl, aws/templates/resource/resource_ssm.ftl, aws/templates/solution/solution_datavolume.ftl
Adds the ability to automatically backup datavolumes through AWS SSM Automation Documents 
AWS SSM Automation allows you to run Documents which can be used to perform tasks within an AWS environment. They can make calls to the AWS API, create cloudformation templates, invoke lambdas and run commands on Ec2 instances 
Combined with maintenance windows you can schedule a collection of tasks to be run against a collection of ec2 instances based on tags, or just run them against non ec2 resources
For data volumes we use two documents provided by AWS, 
- AWS-CreateSnapshot - This makes a call directly to the Ec2 Api to create the snapshot
- AWS-DeleteEbsVolumeSnapshots - Creates a lambda using cfn which lists the current snapshots and removes any older than the retention period
This method …
=> <feat> Add automated snapshots with SSM Automation

aws/templates/application/application_ecs.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ecs.ftl
Adds support for using AWS Fargate for ECS tasks and scheduled. Fargate provides serverless container hosting within your own VPC 
This PR adds support for the fargate ECS engine, it is defined at the service or task level as you can have mixed ECS clusters. 
There are a few ECS capabilities which are not available in Fargate which are outlined in this guide
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/AWS_Fargate.html 
Notable requirements: 
- CPU/Memory requirements are fixed to multiples of 256 ( 256,512,1024 etc ) and allowed memory is based on the CPU allocation 
- No host path volume mounts - volumes can be created and mounted by they are ephemeral and limited to 4Gb in space 
- Network 
- Container must run in awsvpc mode 
- no network links are allowed
- Privileged …
=> <feat> ECS Fargate hosting

aws/templates/application/application_computecluster.ftl, aws/templates/application/application_ecs.ftl, aws/templates/commonApplication.ftl, aws/templates/resource/resource_ecs.ftl, aws/templates/segment/segment_gateway.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_lb.ftl
when using _localnet in IPAddressGroups lookups we need to provide the occurrence to the getIPAddress groups function so that it can do a link lookup on the network for the tier. 
This PR updates the error response when the network cannot be found and also adds occurrence support to resources which live in vpcs.
=> <fix>localnet lookup for services which run in VPCs

aws/templates/id/id_baseline.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/start.ftl
As all known projects have now been deployed using the terminology of
"segments" rather than "containers", the legacy code supporting the old
terminology can be removed.
Technically this is a breaking change but as no project is now using it,
we will treat it as a minor change.
=> <refactor> Remove legacy container (now known as segment) support

aws/contextTree.sh, aws/setContext.sh
Enable cmdb cleanup to be performed in addition to cmdb upgrade.
The cleanup code has been there for a while but was not invoked.
Cleanups are normally a ways behind their corresponding upgrades to give
time for the upgrade to percolate to all active projects. It is also
possible that cleanups will have been manually performed, in which case
the cleanup is a no-op.
The only potential issue is with a local copy of the repo where the current directory
is within one of the directories being removed. In this case, its best to run a template from the root
which will fail but will process the cmdb upgrades/cleanup.
=> <feat> Enable cmdb cleanup

aws/templates/application/application_ecs.ftl, aws/templates/id/id_ecs.ftl, aws/templates/resource/resource_ecs.ftl, aws/utility.sh
The cloudwatch events cloudformation resource doesn't support the awsvpc networking configuration required for fargate containers to be invoked through Cloudwatch events. This PR uses the cli to manage events for the fargate ECS tasks 
- Adds cli functions to support creating cloudwatch events through the cli 
- Adds a cloudformation cli function to lookup stack outputs. This is can be used in epilogue scripts to find arn's or other physical resource Ids that were created in the cloudformation stack - this removes the requirement for two passes when using cli commands to get the resource Ids 
- refactor some of the awsvpc network to align with when services and tasks need networking services
=> <feature> Fargate scheduled tasks

aws/runExpoAppPublish.sh, aws/templates/application/application_mobileapp.ftl, aws/templates/id/id_mobileapp.ftl
Adds the ability to provide settings through to a mobile app. Using fragments and settings environment specific configuration can be provided to an expo app. 
The settings are added to the expo app manifest file under the extra section. Based on https://docs.expo.io/versions/latest/workflow/configuration/#extra
=> <feat> mobile app settings

aws/templates/id/id_mobileapp.ftl
Since all urls are absolute in the expo app configuration we don't need to use an S3 Website and can use the standard https url for S3 access
=> <fix>mobileapp use S3 Url instead of S3 Website

aws/templates/application/application_lambda.ftl, aws/templates/id/id_network.ftl, aws/templates/id/id_vpc.ftl, aws/templates/resource/resource_vpc.ftl, aws/templates/segment/segment_network.ftl
In some older vpc templates the resource Id is different from the output Id. 
Components looking up the network details of the vpc need to always know the output id and the resource Id only required for the vpc's template. 
This PR fixes the Id returned to components looking up the vpc and allows for the resource and output ids to be different.
=> <fix>vpc resource output id differences

aws/templates/id/id_rds.ftl, aws/templates/resource/resource_rds.ftl, aws/templates/resource/start.ftl, aws/templates/solution/solution_rds.ftl
Adds the ability to define the deletion and Updatereplace policies on RDS instances. These policies define what to do when cloudformation deletes a resource or the resource is replaced as part of an update 
In RDS this defaults to `Snapshot` which will create a snapshot of the RDS instance before removing it. In some cases this is required, for example if you have a database which easy to recreate then you can disable this functionality
Also disables the snapshotting during RDS instance replacement template processing
=> <feat> RDS Template policy processing management

aws/templates/application/application_mobileapp.ftl, aws/templates/id/id_userpool.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_lb.ftl, aws/templates/solution/solution_userpool.ftl, aws/utility.sh
Adds support for custom domain names on hosted UI. This adds the existing certificate support to hosted UI's in userpools. 
A couple of manual requirements need to be met before this can be enabled on a userpool
1. You will need an ACM based certificate provisioned for your products domain in the `us-east-1` region. The hosted UI is a cloudfront distribution and cloudfront requires certificates in us-east-1. This will need to be stored as a segment output file like we do for cloudfront
2. As per https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-add-custom-domain.html an A record needs to be present in the base of your domain. I.e. if you have `auth.something.com` for the hosted UI you need to have an A record with any value setup on `something.com` DNS domain. …
=> <feat>Userpool Hosted UI own domain name

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_computecluster.ftl, aws/templates/application/application_ecs.ftl, aws/templates/application/application_lambda.ftl, aws/templates/application/application_mobileapp.ftl, aws/templates/application/application_spa.ftl, aws/templates/application/application_user.ftl, aws/templates/commonApplication.ftl, aws/templates/segment/segment_bastion.ftl, aws/templates/solution/solution_configstore.ftl, aws/templates/solution/solution_spa.ftl
As part of switching to the term "fragment" in preference to the term
"container", remove the availability of the "containerId" variable from
within fragment files.
The switch of filenames has been in place for a while, and use of the
older variable should have been switched to fragmentId. This change will
identify any lingering use of the older term and thus may require
remediation of fragment files.
=> <refactor> Force removal of "containerId" use

aws/templates/base.ftl, aws/templates/commonApplication.ftl
getDescendent is better implemented using standard freemarker fallback behaviour e.g. (a.b.c)!"default".
setDescendent has been superceded by mergeObjects(). The latter is easier to understand and clearer in code because the call shows that portion of the object that will be added/replaced.
=> <refactor> Remove getDescendent and setDescendent Functions

aws/templates/common.ftl, aws/templates/id/id_userpool.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_userpool.ftl, aws/utility.sh
This PR adds support for Cognito User pool federation. User pool federation allows for cognito users to be created in a user pool based on authentication from another provider. 
Once a user has authenticated with Cognito via their authentication provider a user entry is created in the userpool and the user can then authenticate with systems which use this user pool as an idp 
User attributes can also be mapped in to attributes on the user created in the cognito user pool 
Example configuration 
```
"userpool" : { 
"Clients" : {
"default" : {
"ClientGenerateSecret" : false,
"OAuth" : {
"Scopes" : [
"aws.cognito.signin.user.admin",
"email",
"openid",
"profile"
],
"Flows" : [
"code"
]
},
"AuthProviders" : [
"COGNITO",
"GoSource"
],
"Links" : {
"app" : {
"Tier" : "external",
"Component" : …
```
=> <feat> Cognito Userpool federation

aws/contextTree.sh
To properly exclude files which starts with `.`
=> fix path for sensitive settings

aws/templates/id/id_dataset.ftl, aws/templates/id/id_rds.ftl, aws/templates/solution/solution_rds.ftl
This PR adds support for restoring RDS instances based on an rds dataset 
Linking an RDS instance to an rds dataset will make the instance use the data set latest snapshot as a manual snapshot
To enforce this behaviour and make sure that an empty database isn't created a new parameter has also been added to the rds component `AlwaysCreateFromSnapshot` 
With this enable the database instance can only be created when a snapshot has been configured. This prevents empty databases from being created when they were supposed to have a snapshot
=> <feat> RDS restore from rds dataset

aws/templates/id/id_dataset.ftl
Use the dataset deployment unit instead of the current deployment unit. 
Fixes an issue with linking to the dataset
=> <fix>dataset fix du lookup

aws/templates/solution/solution_cache.ftl, aws/templates/solution/solution_rds.ftl
Remove alarms when we hibernate a component and remove resources from the template. This prevents reference lookups in the templates 
Applied to 
- cache 
- rds
=> <fix> remove alarms when hibernating

aws/templates/id/id_dataset.ftl
Quick fix to make sure deployment units aren't breaking other things 
will investigate why a dataset doesn't have a deployment unit next
=> <fix> Dataset deployment unit id lookup

aws/data/masterData.json, aws/templates/account/account_waf.ftl, aws/templates/application/application_apigateway.ftl, aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_waf.ftl, aws/templates/resource/resource_waf.ftl, aws/templates/resource/start.ftl, aws/templates/setContext.ftl
Add support for global and regional WAF configurations
Generate endpoint specific WAF rules/acl so no need for account level
configuration.
Add configuration support for profiles of WAF rules, initially to
support the OWASP 2017 rules sets.
Separate sets of values that may vary between uses of the OWASP rules
from the rules themselves.
Add a default resource policy that ensures the default stage used for
deployments cannotbe accessed via the API.
=> <feature> Expanded WAF Support for API Gateway

aws/data/masterData.json, aws/templates/id/id_baseline.ftl
minor fix for baseline bucket creation which removed the ops data bucket when an update is run on the baseline component. 
This changes the id for a new bucket vs an old bucket to make sure that legacyS3 detection works as expected
=> <fix> baseline use different Id for new bucket

aws/runExpoAppPublish.sh, aws/templates/application/application_mobileapp.ftl, aws/templates/commonApplication.ftl
Remove sensitive variables from mobile apps as they should not be included in binary app builds 
A mobile app would not have permissions to decrypt encrypted values and its possible to access these values without authenticating
=> <fix> remove sensitve variables from mobile apps

aws/templates/application/application_apigateway.ftl, aws/templates/application/application_ecs.ftl, aws/templates/application/application_lambda.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/solution/solution_ecs.ftl, aws/templates/solution/solution_mobilenotifier.ftl
At present, a logMetrics resource attribute is always being added in the
state of any component that supports them.
This causes getLinkTarget to always return the component as deployed even
if it is not.
This change makes creation of logMetric resources conditional on at
least one logMetric being defined.
=> <bugfix> Conditionally create logmetric resources

aws/templates/application/application_datapipeline.ftl, aws/templates/id/id_datapipeline.ftl, aws/utility.sh
When pipelines were first implemented all resources were created in the IAM stack so that they were available to reference in the pipeline values file. 
Instead this refactor creates the resources as normal and then we lookup the cloudformation stack outputs to find out the details of resources created during the template pass. 
This is mainly to reduce the number of outputs created in the iam stack when deploying a large number of resources
=> <refactor>Data pipeline resource creation cleanup

aws/templates/id/id_spa.ftl, aws/templates/resource/resource_cf.ftl, aws/templates/solution/solution_spa.ftl
Adds support for custom routing paths on SPAs. This allows specifc paths to be routed to a other components - currently LB ports are supported 
Example
```
"www" : {
"spa" : {
"Instances" : {
"default" : {
"Versions" : {
"v1" : {
"DeploymentUnits" : ["www-v1"]
}
}
}
},
"CloudFront" : {
"Paths" : {
"api" : {
"PathPattern" : "/api/*",
"Link" : {
"Tier" : "elb",
"Component" : "api-lb",
"Port" : "httpsapi"
}
}
}
}
}
}
``` 
This example would route requests for `/api/*` to the api-lb httpsapi public endpoint
=> <feat> SPA Path based routing to LB

aws/templates/solution/solution_rds.ftl
When running an RDS replacement we spin up a new RDS instance using the snapshot created at the start of the process then do it again. 
This adds the option to instead remove the RDS instance in the replace 1 template and then create a new one in the replace 2 template instead of migrating to one and then to another
=> <feat> rds replace through delete

aws/templates/application/application_datapipeline.ftl, aws/templates/id/id_datapipeline.ftl, aws/utility.sh
Remembered all of the weird conditions with pipelines 
- roles can only be passed as names - so lock the role names to make sure we know what it is 
- add instance profile with the same name as the ec2 resource role 
instance profile has been moved over to the pipeline CFN template which is nicer
=> <fix> pipeline role setup

aws/data/masterData.json
We have a couple of baked in components which aren't required by all solutions. This disables them and means that the would have to be explicitly enabled in solutions which use them
=> <fix> Disable predefined resources which are not required

aws/data/masterData.json, aws/templates/resource/resource_waf.ftl
WAF charges per ACL and per rule so good to minimise the number of rules
as far as possible. The basic OWASP checks can be combined in a single
rule since if any of them matches, the rule fires and the request can be
blocked.
Also rework the naming of rules and conditions to provide more informative
values in the console.
=> <refactor> Reduce rules needed for basic OWASP

aws/data/masterData.json
Multiple conditions in a WAF rule are ANDed, so we need separate rules
for the various OWASP conditions as we want an OR not an AND.
=> <bugfix> OWASP Basic Rules

aws/templates/application/application_computecluster.ftl, aws/templates/application/application_datapipeline.ftl, aws/templates/common.ftl, aws/templates/id/id_bastion.ftl, aws/templates/id/id_cache.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/id/id_datapipeline.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_es.ftl, aws/templates/id/id_rds.ftl, aws/templates/segment/segment_bastion.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_ElasticSearch.ftl, aws/templates/solution/solution_cache.ftl, aws/templates/solution/solution_ec2.ftl, aws/templates/solution/solution_ecs.ftl, aws/templates/solution/solution_rds.ftl
Adds the ability to define a Processor profile on components which have instance types. Currently processor is a Component level configuration which uses the name of the component or type to override the processor group which is selected. 
This PR adds the ability to define the processor group to use through the profile configuration, so that the processor profile can be changes based on deployment Mode ( via deployment Profiles ) or as instance level overrides 
Backwards compatibility with the older style of processor lookup has been maintained, at this stage this is just another way to set the processor
=> <feature>Processor profiles for occurrences

aws/templates/common.ftl, aws/templates/setContext.ftl
* Fixes deployment profiles so that they can be applied at the instance and version level of a component and still get processed 
They used to only be applied at the typeObject level but are now applied as part of the solution configuration generation process
* Adds Enable/Disable to links to allow for Deployment profile modes which might not want a specific link to apply
=> <fix> deployment profiles with instance version

aws/templates/swagger.ftl
Adds the ability to modify the ContentHandling attribute on paths which can be used to tell the apigateway to convert base64 encoded content into a string on response
=> <feature> apigw: add content handling support

aws/templates/application/application_apigateway.ftl, aws/templates/id/id_apigateway.ftl
Based on https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-import-api-basePath.html 
you can specify how API Gateway handles a basepath parameter defined in a swagger spec. This PR adds support for how to handle the basepath 
- ignore
- prepend ( add all of the basepath)
- split ( drop the first path, intended to work with stage names )
=> <feature> Api Gateway - basepath control

aws/templates/application/application_ecs.ftl, aws/templates/common.ftl, aws/templates/commonApplication.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_lb.ftl, aws/templates/id/id_serviceregistry.ftl, aws/templates/resource/resource_cloudmap.ftl, aws/templates/resource/resource_ecs.ftl, aws/templates/setContext.ftl, aws/templates/solution/solution_lb.ftl, aws/templates/solution/solution_registry.ftl
Adds support for service registries which provide a DNS and API based service discovery service based on AWS Cloud Map https://aws.amazon.com/cloud-map/ 
It works in a similar way to Load balancers with a central registry that contains child services. Load balancers or ECS containers ( at the moment) link to a service which allows them to register with CloudMap 
Examples 
The registry itself 
```
"services" : {
"DeploymentUnits" : [ "service-registry"],
"serviceregistry" : {
"Namespace" : {
"IncludeInDomain" : {
"Environment" : true,
"Segment" : true
}
},
"RegistryServices" : {
"www" : {
"ServiceName" : {
"IncludeInHost" : {
"Host" : true,
"Environment" : false,
"Component" : false
},
"RoutingPolicy" : "AllAtOnce",
"Host" : "www"
}
},
"public" : {
"RecordTypes" : [ "A", "AAAA" ], …
```
=> <feature> Service registries

aws/templates/common.ftl, aws/templates/id/id_apigateway.ftl, aws/templates/id/id_baseline.ftl, aws/templates/id/id_bastion.ftl, aws/templates/id/id_cache.ftl, aws/templates/id/id_computecluster.ftl, aws/templates/id/id_configstore.ftl, aws/templates/id/id_contenthub.ftl, aws/templates/id/id_datafeed.ftl, aws/templates/id/id_datapipeline.ftl, aws/templates/id/id_dataset.ftl, aws/templates/id/id_datavolume.ftl, aws/templates/id/id_ec2.ftl, aws/templates/id/id_ecs.ftl, aws/templates/id/id_efs.ftl, aws/templates/id/id_es.ftl, aws/templates/id/id_lambda.ftl, aws/templates/id/id_lb.ftl, aws/templates/id/id_mobileapp.ftl, aws/templates/id/id_mobilenotifier.ftl, aws/templates/id/id_network.ftl, aws/templates/id/id_networkgateway.ftl, aws/templates/id/id_rds.ftl, aws/templates/id/id_s3.ftl, aws/templates/id/id_serviceregistry.ftl, aws/templates/id/id_spa.ftl, aws/templates/id/id_sqs.ftl, aws/templates/id/id_user.ftl, aws/templates/id/id_userpool.ftl
Change state generation logic to use dynamic macro invocation rather
than a static switch table.
This is in preparation for support of multiple providers and deployment
frameworks.
=> <refactor> Add dynamic state routine lookup

aws/templates/commonApplication.ftl
task was using global version of resources instead of local
=> <fix> ECS task variable scope

providers/aws/component/application/application_apigateway.ftl, providers/aws/component/application/application_computecluster.ftl, providers/aws/component/application/application_datapipeline.ftl, providers/aws/component/application/application_lambda.ftl, providers/aws/component/application/application_mobileapp.ftl, providers/aws/component/application/application_spa.ftl, providers/aws/component/application/application_user.ftl, providers/aws/component/segment/segment_bastion.ftl, providers/aws/component/solution/solution_configstore.ftl, providers/aws/component/solution/solution_ec2.ftl, providers/aws/component/solution/solution_ecs.ftl, providers/aws/component/solution/solution_spa.ftl
The _context variable is modified through a collection of macros in fragment files and so that they can update the context the scope needs to be made global rather than local
=> <fix> update _context variable to use global scope

providers/aws/component/baseline/setup.ftl
fix an issue with new deployments which don't have an existing ops bucket when generate oai credentials
=> <fix> baseline legacy handling

aws/templates/setContext.ftl
Add workaround to include apigateway in default resource lookups 
This is to get around a requirement for this setup in `user/setup.ftl`
```
[@createAPIUsagePlanMember
mode=listMode
id=formatDependentResourceId(AWS_APIGATEWAY_USAGEPLAN_MEMBER_RESOURCE_TYPE, apikeyId, link.Id)
```
=> <fix>user: resource lookup

aws/templates/setContext.ftl, providers/aws/service/apigateway.ftl, providers/aws/service/apiusageplan.ftl, providers/shared/component/component.ftl, providers/shared/component/user.ftl
Add ability to declare static dependencies of one component on
another.
In general, link processing should load all the component definitions
but this happens at run-time. As a result, when the code is loaded
and it is syntactically checked, any use of definitions from a link
component type will fail.
The suspicion is that such use needs to be reconsidered because it
implies an assumption on the part of the depending component as to
the provider of the dependent component. However, for now this feature
will get around this.
=> <feature> Static component dependencies

providers/shared/component/apigateway.ftl
Add static dependency on userpools for api gateway otherwise state routine isn't available for userpools
=> <fix> apigw dependency on userpool component

aws/templates/common.ftl, providers/shared/component/apigateway.ftl
If an external link is specified with type, attempt to load the corresponding template information.
With this fix, remove the static inclusion of userpool into apigateway.
=> <bugfix> External link template inclusion

providers/aws/component/es/state.ftl
The state used to be assigned through a return instead of assigning a variable like it does now so the rest of the macro continues to be evaluated
=> <fix> ES: external vs local state lookup

providers/aws/component/baseline/setup.ftl
minor fix to cleanup how the oai legacy support works for the S3 bucket
=> <fix> cleanup legacy oai support

aws/templates/common.ftl, aws/templates/resource/resource_cognito.ftl, aws/utility.sh, providers/aws/component/federatedrole/setup.ftl, providers/aws/component/federatedrole/state.ftl, providers/aws/component/userpool/setup.ftl, providers/aws/component/userpool/state.ftl, providers/shared/component/component.ftl, providers/shared/component/federatedrole.ftl, providers/shared/component/userpool.ftl
Federated roles provide cloud provider resource credentials to users based on external identity sources. This allows for users to use the same credentials to access an application and cloud provider resources directly 
Example: 
```
"cloudrole" : {
"federatedrole" : { 
"Instances" : {
"default" : {
"DeploymentUnits" : [ "cloudrole" ]
}
},
"Fragment" : "_cloudrole",
"Links" : {
"userpool" : {
"Tier" : "dir",
"Component" : "app-userpool"
}
},
"Assignments" : {
"authenticated" : {
"Type" : "Authenticated",
"Links" : {
"datastore" : {
"Tier" : "db",
"Component" : "data-s3",
"Role" : "none"
}
}
}
}
}
}
```
Fragment
```
[#case "_cloudrole" ]
[#if _context.Assignment == "authenticated" ]
[#if (_context.Links["datastore"]!{})?has_content ]
[@Policy  
[
getS3Statement( 
[
"s3:GetObject", …
```
=> <feat> Federated Roles

providers/aws/components/apigateway/setup.ftl
Now that federated roles have replaced the existing userpool configuration we no longer need IAM permissions to apply for Userpools on APIGateway
=> <fix>apigateway userpool role permissions

aws/templates/createAccountTemplate.ftl, aws/templates/createApplicationTemplate.ftl, aws/templates/createMultipleTemplate.ftl, aws/templates/createProductTemplate.ftl, aws/templates/createSegmentTemplate.ftl, aws/templates/createSolutionTemplate.ftl, engine/bootstrap.ftl, engine/component.ftl, engine/template.ftl, providers/aws/services/resource.ftl
This is the first of several PRs to rework the processing of templates
to add multi-provider support.
The first step is to factor out some generic processing for standard
output formats (text, json), which is what this change does.
Next step will be to make the top level macro for a template
dynamically.
This PR should be reviewed/merged after https://github.com/codeontap/gen3/pull/833.
=> <refactor> Template processing

engine/common.ftl, engine/commonApplication.ftl, engine/setContext.ftl, providers/aws/components/apigateway/setup.ftl, providers/aws/components/baseline/setup.ftl, providers/aws/components/bastion/setup.ftl, providers/aws/components/computecluster/setup.ftl, providers/aws/components/configstore/setup.ftl, providers/aws/components/datafeed/setup.ftl, providers/aws/components/datapipeline/setup.ftl, providers/aws/components/datavolume/setup.ftl, providers/aws/components/ec2/setup.ftl, providers/aws/components/ecs/setup.ftl, providers/aws/components/efs/setup.ftl, providers/aws/components/es/setup.ftl, providers/aws/components/lambda/setup.ftl, providers/aws/components/mobileapp/setup.ftl, providers/aws/components/rds/setup.ftl, providers/aws/components/spa/setup.ftl, providers/aws/components/user/setup.ftl, providers/aws/services/ec2/resource.ftl, providers/aws/services/efs/resource.ftl, providers/aws/services/kinesis/resource.ftl, providers/aws/services/kms/policy.ftl, providers/aws/services/lambda/resource.ftl, providers/aws/services/rds/resource.ftl, providers/aws/services/s3/resource.ftl, providers/shared/components/baseline/id.ftl, providers/shared/components/lambda/id.ftl
This PR moves to using the baseline profile introduced in #834 for all components. 
I've commented out the setContext for the operations and data buckets to make sure that they aren't in use 
Also has some fixes for ES based on the split of the AWS identity pool from our userpool component
=> <refactor> use baselineprofile for all components

engine/common.ftl, providers/aws/components/baseline/setup.ftl, providers/aws/services/iam/resource.ftl, providers/aws/services/s3/resource.ftl, providers/aws/services/sqs/resource.ftl, providers/shared/components/baseline/id.ftl
A couple of commits which are mostly related to baseline components
- Instead of using the legacy OAI key created using the cli, migrate all deployments over to use a cloudformation generated OAI
- The legacy key will still be retained and added to all segment databucket bucket policies if its found
- Adds the activeRequired option to getLinkTarget(s) which will throw a fatal error if a link is not active 
- Fix up the baseline component lookup to include the activeRequired option and an extra exception to highlight why a baseline link has failed 
- Move the resource based policies into the resource files for a service
=> <refactor> baseline: Migrate OAI to cf for all deployments

engine/base.ftl, engine/common.ftl, engine/component.ftl, engine/output.ftl, providers/shared/components/baseline/id.ftl
Added an additional log level to allow timing information to be displayed
and added duration calculations in the core component processing routine.
Changed the default value for enabled to true for all logging macros, as
output now controlled vi the log level selected.
Added a component cache which speeds up all component processing
significantly particularly for units which process all components.
=> <feature> Processing timing and component cache

providers/aws/components/userpool/id.ftl, providers/aws/components/userpool/setup.ftl, providers/shared/components/userpool/id.ftl
- Allow for an empty IDP attribute to be provided in cli config so that IDP identifiers can be disabled 
- Add service dependencies for userpool
=> <fix> userpool remove identifier option

aws/runExpoAppPublish.sh
Allows for bundle IDs to be overriden to support different profiles per environment
=> <feature> expo app bundle id overrides

aws/createTemplate.sh, aws/templates/createBlueprint.ftl, aws/templates/createBuildblueprint.ftl
Use the output framework to generate the blueprint.
Because of the format required, redefine the key processing macro to
generate the output required.
Switch to using the config subset as it is a little simpler but that;s
hidden inside the genplan generation.
=> <fix> Align blueprint generation with output framework

aws/createTemplate.sh, aws/templates/createApplicationTemplate.ftl, engine/component.ftl
Correct the application template to include the correct level.
Treat the absence of any suitable processing macro for a unit as a fatal
error.
Correct the detection of fatal errors in scripts - the length of the
severity indicator was increased to allow for "timing" but the check for
fata was not adjusted accordingly.
=> <fix> Application level templates processing

aws/runExpoAppPublish.sh, providers/aws/components/mobileapp/setup.ftl, providers/aws/components/mobileapp/state.ftl
With the changes to using the baseline profile the APPDATA_BUCKET and OPSDATA_BUCKET variables aren't available until the setup stage instead of the state stage like the used to be 
This PR updates the expo build configuration to rely on a dedicated config file rather than using the build blue print. 
The build blueprint is still required to determine where the config file lives but the actual values required by the build are now baked into the config file provided for the build
=> <fix> Update Expo config setup to support baseline

engine/setContext.ftl, providers/aws/components/baseline/state.ftl, providers/shared/components/baseline/id.ftl
Use standard bucket names for all other buckets in baseline except appData and opsdata which are treated as segment resources for backwards compatability
=> <fix>baseline bucketId Lookup

aws/runExpoAppPublish.sh
Instead of using the multi manifest file which supports multiple SDKs the turtle builds now only accept a single manifest file. This makes sense since a binary can only be built against a single version of the SDK
=> <fix> use sdk specifc manifest for binary

aws/templates/createApplicationTemplate.ftl, engine/bootstrap.ftl, engine/component.ftl, engine/context.ftl, engine/engine.ftl, engine/link.ftl, engine/setContext.ftl, providers/aws/components/federatedrole/setup.ftl, providers/aws/components/user/setup.ftl, providers/shared/deploymentframeworks/default/output.ftl
In order to accommodate accounts and regions as well as cross-product
links, introduce a new in-memory model for processing based on contexts.
It has been designed to make link processing efficient along with
calculating hierarchical overrides and qualification.
So far the code generates a simplified model but doesn't do anything with it.
In order to assist in debugging the new model, a special unit of "model"
has been added to the application level. It produces a config file
containing the model prior to processing commencing.
This commit also fixes a bug with link processing where
instance/versioning processing was wasn't correct.
It also fixes a couple of instances where calls the standardPolices
weren't including the now mandatory baseline links parameter.
=> <feature> First cut of context based in-memory model

engine/commonApplication.ftl, engine/occurrence.ftl, providers/aws/components/apigateway/setup.ftl, providers/aws/components/baseline/setup.ftl, providers/aws/components/baseline/state.ftl, providers/aws/components/bastion/setup.ftl, providers/aws/components/computecluster/setup.ftl, providers/aws/components/configstore/setup.ftl, providers/aws/components/datafeed/setup.ftl, providers/aws/components/datapipeline/setup.ftl, providers/aws/components/datavolume/setup.ftl, providers/aws/components/ec2/setup.ftl, providers/aws/components/ecs/setup.ftl, providers/aws/components/efs/setup.ftl, providers/aws/components/es/setup.ftl, providers/aws/components/federatedrole/setup.ftl, providers/aws/components/lambda/setup.ftl, providers/aws/components/mobileapp/setup.ftl, providers/aws/components/mobileapp/state.ftl, providers/aws/components/rds/setup.ftl, providers/aws/components/spa/setup.ftl, providers/aws/components/topic/setup.ftl, providers/aws/components/user/setup.ftl, providers/shared/components/baseline/id.ftl
Reworks the baseline link setup to work in a similar way to other link processing when determining attributes and environment. 
Previously we treated the baseline attributes as special named attributes applied in the environment as default options. 
This aligns baseline links with existing links so that any baseline component can contribute environment variables to components which use them. At the moment this just covers the existing APPDATA_BUCKET and OPSDATA_BUCKET variables but could change in the future
This fixes an issue with the baseline attributes being removed from the defaultEnvironment which meant they wern't available to fragment files 
Also removes a default Attribute of NOATTRIBUTES and instead relies on the environment variable settings processing to determine if this is a …
=> <fix> Baseline Attributes in default Env

engine/common.ftl
When generating subobject structures, default the subobject id and name
to the subobject key.
This avoids the need to add id/name explicitly to config files such as
the master data.
=> <fix> Default id and name for subobjects

engine/occurrence.ftl, providers/aws/components/apigateway/state.ftl, providers/aws/components/bastion/state.ftl, providers/aws/components/computecluster/state.ftl, providers/aws/components/datafeed/state.ftl, providers/aws/components/ec2/state.ftl, providers/aws/components/ecs/state.ftl, providers/aws/components/lambda/setup.ftl, providers/aws/components/lambda/state.ftl, providers/aws/components/mobilenotifier/state.ftl
Iam and lg resources can be created via the iam and lg units before the corresponding occurrences actually exist.
This commit adds a flag that can be put on any resource in the state of an occurrence. The flag controls whether the resource is considered when deciding if the occurrence is deployed or not.
=> <fix> Ignore iam/lg resources for deployment state

providers/aws/components/bastion/state.ftl, providers/aws/components/computecluster/state.ftl, providers/aws/components/datafeed/state.ftl, providers/aws/components/datapipeline/state.ftl, providers/aws/components/datavolume/state.ftl, providers/aws/components/ec2/state.ftl, providers/aws/components/ecs/state.ftl, providers/aws/components/es/state.ftl, providers/aws/components/network/state.ftl, providers/aws/components/s3/state.ftl
For most components, roles being deployed may not mean the component is deployed since they may have been created in an iam unit.
=> <fix> Ignore role resources in deployment state

providers/aws/components/spa/setup.ftl, providers/aws/masterData.json, providers/shared/components/baseline/id.ftl
Ensure baseline links defined before use in generating _context and handle case of missing baseline components.
Improve error handling in baseline link routines so they don't result in freemarker exceptions. This way, the actual source of any errors can be reported.
=> <fix> SPA baseline processing

providers/aws/components/userpool/id.ftl, providers/aws/masterData.ftl, providers/aws/masterData.json, providers/shared/components/baseline/id.ftl
Also
- add dependency for aws userpool implementation on SNS
- pick up latest masterdata
Note that masterdata.ftl picks up some previous changes to remove ids
that are now no longer needed, as they are injected automatically by
occurrence processing.
=> <fix> Correct fetching of baseline component ids

providers/aws/components/userpool/setup.ftl
Check for the correct deployment unit should use the role id not the pool id.
@roleyfoley please confirm this won't break any other deployments for products using user pools.
=> <fix> Userpool role creation resource dependency

aws/runExpoAppPublish.sh
Adds the option to skip the publishing of an OTA to the CDN but still keep the OTA for injection into a binary build. This would allow for preparing a new binary with libraries before deploying an OTA which enables them
=> <feature> Expo build - skip OTA

engine/common.ftl, providers/aws/components/spa/state.ftl
A couple of minor fixes to the SPA domain lookup
- Typo fix primary domain lookup
- SPA - adds the primary domain lookup instead of using the first domain in the array
=> <fix> SPA: primary domain lookup fixes

providers/aws/components/apigateway/setup.ftl, providers/shared/components/apigateway/id.ftl
Adds ability to use the path in the name of the swagger spec file copied to a publishing endpoint. This is mainly to align with the codeontap/townplanner layout
=> <feature> APIGW: publish with filename control

aws/utility.sh, providers/aws/components/apigateway/setup.ftl, providers/aws/components/contentnode/setup.ftl
Adds a sync mode to content nodes which allows for updates to common directory from multiple sources instead of replacing the directory on each upload
=> <fix> contentndoe sync modes

aws/utility.sh, engine/swagger.ftl, providers/aws/components/apigateway/setup.ftl
Now that the api gateway updates are run as part of the setup script we can access the attributes for the deployment
This PR moves the updates added to a swagger spec as part of the publish process into the standard template extensions. As the deployment updates only affect information and try it now functionality this shouldn't impact the API deployment
=> <refactor> APIGW: move deployment details in to swagger update

providers/aws/components/cache/setup.ftl, providers/aws/components/db/setup.ftl, providers/aws/components/ecs/setup.ftl
Instead of checking that the resource we are hibernating is around we should check that the occurrence is deployed 
For RDS where we remove the RDS instance doing a getExistingReference on the RDSId will end up with a loop of adding and removing the instance
=> <fix> hibernation - fix for determinig deployment

providers/aws/masterData.json
API Gateway has a hard payload size limit of 10MB so align the defaults
for OWASP to align with this,
=> <refactor> Align default OWASP size limit to API limit

providers/aws/masterData.ftl
Regenerate to include change to maximum payload size for OWASP.
=> <fix> regenerate AWS masterdata ftl

providers/aws/masterData.ftl, providers/aws/masterData.json
Revert limit to 4k. If a product requires a higher limit, it should explicitly override the default.
=> <Refactor> Revert OWASP body size limits

aws/setContext.sh, engine/common.ftl, engine/component.ftl, engine/context.ftl, engine/occurrence.ftl, engine/setContext.ftl, providers/aws/masterData.ftl, providers/aws/masterData.json, providers/shared/deploymentframeworks/default/legacy.ftl, providers/shared/deploymentframeworks/default/model.ftl, providers/shared/masterData.ftl
Id and Name attributes are now no longer added to the blueprint if not
present. Instead, they are explicitly defaulted based on attribute keys.
To confirm it is working as expected, all the Ids in the master data that matched the attribute key were removed.
This will also fix an issue where the tier name was using the id not the
name.
=> <refactor> Remove id/name defaulting

aws/cleanupContext.sh
Cleanup logic did not retain temporary files unless GENERATION_DEBUG
was set.
Switch to using willLog which will still honour GENERATION_DEBUG
but will also honour GENERATION_LOG_LEVEL=debug
=> <fix> Use log level in cleanup logic

providers/aws/components/lb/setup.ftl, providers/aws/services/ecs/resource.ftl
A couple of minor fixes 
- ECS Volumes - Allow for the same volume to be shared between containers - Only add one volume entry to the task definition 
- LB - Allow for the creation of a base path only path condition
=> <fix> ECS Volumes and LB Base Path redirects

providers/shared/components/spa/id.ftl
This is a really old bit of config that didn't get picked up with the management of subobjects in the configuration.
A scan of all ftl files suggests this is the only place his error existed - all other definitions use subobjects.
=> <fix> SPA links should be subobjects

engine/commonApplication.ftl, providers/aws/components/apigateway/setup.ftl, providers/aws/components/baseline/setup.ftl, providers/aws/components/bastion/setup.ftl, providers/aws/components/computecluster/setup.ftl, providers/aws/components/configstore/setup.ftl, providers/aws/components/datafeed/setup.ftl, providers/aws/components/datapipeline/setup.ftl, providers/aws/components/datavolume/setup.ftl, providers/aws/components/db/setup.ftl, providers/aws/components/ec2/setup.ftl, providers/aws/components/ecs/setup.ftl, providers/aws/components/efs/setup.ftl, providers/aws/components/es/setup.ftl, providers/aws/components/federatedrole/setup.ftl, providers/aws/components/lambda/setup.ftl, providers/aws/components/lb/setup.ftl, providers/aws/components/mobileapp/setup.ftl, providers/aws/components/mobileapp/state.ftl, providers/aws/components/spa/setup.ftl, providers/aws/components/topic/setup.ftl, providers/aws/components/user/setup.ftl, providers/shared/components/baseline/id.ftl
Refactor the getBaselineLinks routine to accept an occurrence and use this to determine the baseline profile.
The next step as part of the move to use of the context based model will be to use the occurrence in the call to getLinkTarget, so that the correct baseline is used in the situation of multiple products being
available simultaneously.
=> <refactor> Use occurrence to determine baseline links

providers/aws/components/ecs/setup.ftl
`getBaselineLinks` function expects a hash, not a string as occurrence parameter
=> <fix> base link lookup for ecs components

providers/aws/components/cdn/id.ftl, providers/aws/components/cdn/setup.ftl, providers/aws/components/cdn/state.ftl, providers/aws/components/db/setup.ftl, providers/aws/components/s3/setup.ftl, providers/aws/components/s3/state.ftl, providers/aws/components/spa/setup.ftl, providers/aws/components/spa/state.ftl, providers/aws/masterData.ftl, providers/aws/masterData.json, providers/aws/services/cf/resource.ftl, providers/shared/components/cdn/id.ftl, providers/shared/components/component.ftl, providers/shared/components/spa/id.ftl
This PR adds support for a dedicated CDN solution level component and replaces the existing solution level SPA CDN deployment
A CDN component can be used by multiple HTTP based services to provide content distribution services and can also be used for routing between different origins while maintaining a consistent client facing endpoint 
The component itself manages the default configuration for the disribution, certificates, default error responses, default document etc 
A route subcomponent provides the link between the distribution and the origin. Multiple routes can be configured with each route having its own PathPattern applied. 
Example of the Solution Configuration 
```
"web" : {
"Components" : {
"catalog-cdn" : {
"cdn" : {
"Instances" : {
"default" : {
"DeploymentUnits" : [ …
```
=> <feature> CDN Component

providers/aws/components/spa/setup.ftl
Adds a basic genplan and prologue script so that the solution level component can be deleted through the stop deployment mode. If no gen plan is found the template generation fails and the component cannot be deleted
=> <fix> SPA generate solution level genplan with warning about deprecation

providers/aws/components/ecs/setup.ftl
Move target parameters for creating an ECS task to the correct location.
Looks like a bug that crept in with fargate support.
=> <fix> ECS task parameters in wrong code section

engine/occurrence.ftl
Allow for resources to have their deployed status defined in their definition. Can be used for forcing some units to be deployed or to use nonstandard logic to determine the state
=> <fix> Allow resources to be always marked as deployed

providers/aws/components/userpool/setup.ftl, providers/aws/components/userpool/state.ftl
Showing the COTFatal message in resources causes the blueprint generation to fail. It should only fail during generation
=> <fix> userpool don't show error in resources

aws/contextTree.sh
If after filtering the composite outputs the resulting file is empty, filter it for Azure ARM template outputs instead.
=> Adding composite output filtering for azure.

providers/aws/components/cdn/setup.ftl
Adds support for the CDN component to front an APIGateway 
Uses the BasePath and FQDN attributes to determine the origin path
=> <feature> CDN support for APIGateway

aws/templates/fragment/fragment_jenkins.ftl, engine/common.ftl, engine/commonApplication.ftl, engine/output.ftl, engine/setContext.ftl, providers/aws/components/ec2/setup.ftl, providers/aws/components/ecs/setup.ftl, providers/aws/components/ecs/state.ftl, providers/aws/components/serviceregistry/id.ftl, providers/aws/deploymentframeworks/cf/output.ftl, providers/aws/services/ecs/resource.ftl, providers/shared/components/component.ftl
A collection of minor fixes 
- Id/Name defaulting when generating account level templates which don't have a product or environment 
- A fix for when an output conditional generates content 
- Removes the ECS Service Role assignment in favour of the built in one ( https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html) 
When using awsvpc network mode or assigning multiple load balancer target groups the Role value can no longer be assigned and the role that we previously created used the same permissions as the service linked role. The service linked role is created on the first deployment to ECS ( including cluster ) so should not be noticed
- Jenkins - the fragment was using a variable assigned in the setup section of ecs component. This is no longer …
=> <fix> Minor fixes

providers/aws/components/db/setup.ftl, providers/aws/components/db/state.ftl, providers/aws/services/rds/resource.ftl, providers/shared/components/db/id.ftl
Adds support for major version upgrades in RDS 
By default when the engine version parameter is updated on an RDS instance the instance will be removed and replaced with a new instance instead of upgrading the instance 
This PR makes a couple of changes to support RDS upgrading an instance when the major version is changed 
- Parameter groups  - have some weird behaviour where the update of the family parameter can not be changed once it has been set, but the parameter does not trigger the replacement of the group. So instead we now create a new parameter group for each family ( engine + engine version ) combination 
- Option groups - Support having their version updated, however this requires replacement which means the instance is removed instead of the normal update process. So we also …
=> <feature> DB: Major version update support

providers/aws/components/dataset/setup.ftl
All of the dataset component lives in the state routine, however with the introduction of generation plans they are no required. 
This makes sense and also provides feedback if you try and deploy something that doesn't exist so I think this approach of adding a dummy template to deploy makes sense. It also adds wiggle room for future extensions
=> <fix> Add dummy dataset deployment

engine/occurrence.ftl, providers/aws/components/cdn/setup.ftl, providers/aws/components/spa/setup.ftl, providers/aws/components/spa/state.ftl, providers/shared/components/spa/id.ftl
Adds the ability to control the location and CDN pattern used to provide the generated configuration file for spa components. 
This allows for integration with third party spas which have a config file location defined or you need to use the /config/* path ( our default ) in your actual SPA 
Also adds a fix for the resource deployment override setup
=> <feature> SPA config path control

providers/aws/components/spa/setup.ftl
Links seem to be working for subcomponents, so need to make it link to it again now. For some reason it wasn't working when I set it up
=> <fix> SPA should link to CDN route instead of CDN

engine/component.ftl, engine/occurrence.ftl, providers/shared/components/component.ftl
Adds support for settings namespaces. Namespaces allow for custom settings structures for components. At the moment settings are lookedup based on fixed values based on the name of occurrence details. 
SettingNamespaces work in a similar way to domain naming where different occurrence name sections are combined to generate a new namespace. 
Combining Namespaces with deployment profiles offers a way to provide settings to groups of components 
Example 
```
"DeploymentProfiles" : {
"backend" : {
"Modes" : {
"*" : {
"service" : {
"SettingNamespaces" : {
"base" : {
"Name" : "backend",
"Match" : "partial",
"IncludeInNamespace" : {
"Tier" : true,
"Component" : false,
"Type" : false,
"SubComponent" : false, 
"Instance" : true,
"Version" : false,
"Name" : true
}
}
}
},
"task" : { …
```
=> <feature> Core setting namespaces

providers/aws/components/es/setup.ftl
Only check the cognito -> ES configuration setup during the cli subset. This allows for the IAM pass to complete so that updates can be made to cloudroles
=> <fix> userpool only validate cognito config during cli pass

providers/aws/components/userpool/setup.ftl, providers/aws/services/cognito/resource.ftl, providers/shared/components/userpool/id.ftl
Adds the ability to specify MFA as optional on a user pool. This can be used to enable MFA after a userpool has been deployed
=> <fix> userpool add optional mfa config

engine/output.ftl
Combine behaviour needs to be applied only to the content, not to the overall structure of outputs.
=> Shift combine behaviour to content of output section

providers/aws/services/cognito/resource.ftl
Replace UnusedAccountValidityDays with the newer parameter TemporaryPasswordValidityDays ad the old one has been deprecated 
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-passwordpolicy.html 
Assuming this will work for updates to userpools if this has been deprecated
=> <fix> Userpool update validity parameter

engine/common.ftl
@roleyfoley , a small fix required for using Processor profiles for scaling policies.
=> <fix> Typos in processor functions

aws/templates/fragment/fragment_codeontap.ftl
ECS puts volumes on the root filesystem and mounting to /var/lib/docker/volumes seems to be unreliable. 
This removes the codeontap volumes which didn't really add performance changes but bit builds fail due to the small size of the root filesystem
=> <fix> codeontap fragment volumes

providers/aws/components/apigateway/state.ftl, providers/aws/components/ecs/state.ftl, providers/aws/components/es/state.ftl, providers/aws/components/lambda/state.ftl, providers/aws/components/mobilenotifier/setup.ftl, providers/aws/components/mobilenotifier/state.ftl, providers/aws/components/sqs/state.ftl, providers/aws/services/apigateway/resource.ftl, providers/aws/services/ecs/resource.ftl, providers/aws/services/es/resource.ftl, providers/aws/services/lambda/resource.ftl, providers/aws/services/sqs/resource.ftl
Fixes #100  
Adds the region output to resources where required. 
Updates state routines with region specified to use the new output and fall back to the default region until the output is available
=> <fix> Region lookup for attribtues

aws/createTemplate.sh, aws/manageStack.sh
These have been deprecated for a long time so should be safe to remove.
Only use of the scripts is in gen3-automation, where -u and -l are used.
Fixes #14
=> <refactor> Remove deprecated -s and -t switches

providers/aws/components/ecs/setup.ftl, providers/shared/components/ecs/id.ftl
Currently ECS Host configuration is merged with the Service configuration. This means that scaling policies overlap and you can't create a policy which only applies to the hosts. 
This workaround allows them to be treated separatley
=> <fix> Seperate ECS Host from Service scaling policy

aws/createTemplate.sh, engine/occurrence.ftl, providers/shared/deploymentframeworks/default/model.ftl
Add the -g switch to createTemplate to permit the selection of specific resource groups for template generation.
Rename "Construct" methods to "Create" methods. As the name suggests, Create routines build internal structures while "Get" routines should get existing structures.
Also remove a few vestiges of the now-defunct "multiple" level.
=> <feature> Add resource group selection

providers/aws/components/mobilenotifier/state.ftl
The SMS mobile notifier isn't  real component in AWS so instead we just need to fake it to get the policy details
=> <fix> MobileNotifer always mark SMS notifier as deployed

engine/output.ftl
Include severity in script output lines so that error reporting shows the context on generation plan passes which catch the exceptions from configuration validation
=> <fix>Show error context in script output

providers/aws/services/ec2/resource.ftl
Fix for ec2 autoscaling groups with rolling updates enabled. 
You can't set the maxCount to the same or below the MinInstancesInService for rolling updates, Since we want to set it to 1 and the minCount to 0 we need to make sure no instances need to be in service during the updaet 
See https://forums.aws.amazon.com/thread.jspa?threadID=141982 from AWS
=> <fix> Autoscaling rolling update policy

aws/createTemplate.sh, engine/output.ftl, providers/aws/deploymentframeworks/cf/output.ftl, providers/shared/deploymentframeworks/default/output.ftl
Adds the ability to switch provider and framework as a command line option/env var 
This is a workaround for the work we are doing with resource groups which allow for multiple providers to be used in the same template and instead makes it possible to switch between single providers for a given template
It also adds the ability for providers to add output step mappings for generation plans so that providers can customise the outputs generated for different subnets
=> <feature> Provider switch

engine/output.ftl, providers/aws/deploymentframeworks/cf/output.ftl, providers/shared/deploymentframeworks/default/output.ftl
Instead of setting up the possible outputs before a resource output is called we now do it during the loading of the output code.
=> <fix> output Initilisation processing

engine/output.ftl, providers/aws/services/acm/resource.ftl, providers/aws/services/apigateway/resource.ftl, providers/aws/services/autoscaling/resource.ftl, providers/aws/services/cache/resource.ftl, providers/aws/services/cf/resource.ftl, providers/aws/services/cloudmap/resource.ftl, providers/aws/services/cognito/resource.ftl, providers/aws/services/cw/resource.ftl, providers/aws/services/dynamodb/resource.ftl, providers/aws/services/ec2/resource.ftl, providers/aws/services/ecs/resource.ftl, providers/aws/services/efs/resource.ftl, providers/aws/services/es/resource.ftl, providers/aws/services/iam/resource.ftl, providers/aws/services/kinesis/resource.ftl, providers/aws/services/kms/resource.ftl, providers/aws/services/lambda/resource.ftl, providers/aws/services/lb/resource.ftl, providers/aws/services/rds/resource.ftl, providers/aws/services/resource.ftl, providers/aws/services/s3/resource.ftl, providers/aws/services/sns/resource.ftl, providers/aws/services/sqs/resource.ftl, providers/aws/services/ssm/resource.ftl, providers/aws/services/vpc/resource.ftl
This PR addresses the following:
- Output Mappings previously being only instantiated as an empty object within the AWS provider. This prevented other providers from working as they could not merge with an object that didn't exist.
- In order to share the instantiation of the object across providers, this was moved into generation/engine/output.ftl.
- to avoid the potential for conflicting outputMappings between providers, a new macro and function were created to access this object, and incorporate a new object tier for provider.
1. macro - addOutputMapping
2. function - getOutputMappings
The macro will simply add an output mapping to the current providers tier. This has retroactively been applied across AWS resources.
The function is capable of retrieving the mappings for a whole …
=> Moved the instantiation and assignment of outputMappings 

providers/aws/components/ecs/setup.ftl, providers/aws/services/resource.ftl
A couple of minor fixes 
- Add ECS task schedule Role back in 
- Move subnet lookup to handle scheduled tasks which don't use aws vpc 
- Fix for getOutputMappings when use Ref is set on an output which isn't the REF_ATTRIBUTE_TYPE
=> <fix> ECS task schedules and useRef lookup

providers/aws/components/ecs/setup.ftl
`NetworkConfiguration` must be placed under `EcsParameters` of `Target` object.
=> <fix> ECS task CW Event Rule structure

providers/aws/services/ecs/resource.ftl, providers/shared/components/ecs/id.ftl
Set a placement constraint with type `distinctInstance` to a ECS services when MultiAZ is enabled so each task is running on a different container instance.
=> <feature> distinctInstance placement constraint for ECS Tasks

providers/aws/components/sqs/state.ftl
A minor fix required for a successful iam app unit template generation for solution with sqs components.
=> <fix> typo for SQS state region attribute

providers/aws/components/ecs/setup.ftl
Scheduled task doesn't need depedents as they are implied.
Make sure the schdeduled event resource is only deployed for the subset
=> <fix> Ecs task dependencies

providers/aws/components/user/setup.ftl, providers/aws/services/iam/resource.ftl
A continuation on the user policy limit stuff. It turns out that the character limit isn't per inline policy it as actually all inline polices on a user cannot be above 2048 characters. So however they are grouped it doesn't apply 
This policy limit is different for different IAM types ( groups, roles and users ) with users being the most restricted. 
However managed policies enforce their own limit ( 6000 characters)  rather than being dependent on the IAM type. So for users we should try a managed policy instead of inline
=> <fix>IAM user managed policy

providers/aws/services/resource.ftl, providers/shared/services/resource.ftl
This PR addresses the need for any provider to be able to check to see if a given resource is apart of the current deployment. Previously these functions were within the AWS provider, however with a small change to use a provider lookup instead of a hardcoded value, this can be used for any provider.
=> migrated shared resources functions to the shared provider.

providers/aws/inputsources/shared/masterdata.ftl
Add default rds profile for rds into aws masterdata. Seems to have been lost along the way
=> <fix>Add default Security profile for RDS

aws/utility.sh
Make sure we wait for the rds password to be reset before going on. Otherwise it causes downstream failures
=> <fix> RDS add wait for rds master password

engine/inputdata/stackOutput.ftl, providers/aws/services/iam/resource.ftl, providers/shared/services/resource.ftl
Don't use the default stack output mappings for IAM policy. Policy should always be deployed with a role
=> <fix> IAM remove default output for policy

providers/aws/components/apigateway/setup.ftl, providers/aws/inputsources/shared/masterdata.ftl, providers/aws/masterData.json, providers/aws/services/cf/resource.ftl
Add viewer protocol policy configured via the security profile, with the
default being redirect (via the master data).
=> <Feature> Make API Gateway viewer policy configurable

providers/shared/components/baseline/id.ftl
Update function for multi-provider, which may pass own resource names and not have the same Engines available. Defaults to existing AWS configuration without further amendments.
CMK and SSH are set to be mandatory, whilst oai is optional. If the Engine exists but not the resource, no error will be given.
=> Update function for multi-provider

aws/manageDeployment.sh, engine/common.ftl
The initial implimentation of the manageDeployment script was MVP. Now that the Azure provider has a baseline component that utilises the epilogue/prologue scripts, this PR implements them.
Also corrected a minor spelling mistake.
=> Enable Epilogue and Prologue for ManageDeployment script.

aws/runExpoAppPublish.sh
A minor fix to use a build reference as a sentry release for expo builds
=> use a build reference as a sentry release

providers/aws/components/lambda/setup.ftl, providers/aws/components/lambda/state.ftl, providers/aws/services/lambda/resource.ftl, providers/shared/components/lambda/id.ftl
When using Lambda@Edge you can only use versions of lambda functions. You can't use the $LATEST version which is normally implied 
This PR adds a configuration option on Lambda functions which creates a new version of a lambda function on each deployment. This is useful when you have fragment based lambda functions which have been updated
=> <feature> Lambda Create new version on deploy

aws/createBlueprint.sh, aws/createBuildblueprint.sh
Adds help and arguments for blueprint generation. While blueprint is just an extension on the createTemplate.sh script it does have some specific requirements on how it should be run.
=> <feature> Add help and args for blueprint generation

providers/aws/components/db/id.ftl, providers/aws/components/db/setup.ftl, providers/aws/components/db/state.ftl, providers/aws/services/rds/resource.ftl, providers/shared/components/db/id.ftl
Adds the ability to enable the advanced monitoring features for RDS
- QueryPerformance - Enables RDS Performance Insights which provide monitoring details on query impact
- DetailedMetrics - Enables more detailed metrics collection based on an agent installed on the RDS host rather than using the host
Both are disabled by default due to cost restrictions and QueryPerformance is only available on select instance families
QueryPerformance encrypts its data by default so we use the baseline key all the time
=> <feature> RDS Advanced Monitoring

aws/runExpoAppPublish.sh
This PR introduce a fix for overrides in expo master export. Depends on a number of SDK export file might be an array or a single element.
=> <fix>support array and single element master exports formats

aws/createTemplate.sh, providers/aws/components/gateway/state.ftl, providers/aws/inputsources/mock/commandlineoption.ftl
This allows for a testing create template pass to generate outputs without have a CMDB
All configuration is managed through the test case, scnearion and mocking input configuration
Also allows you to override the output directory so that you know where the outputs end up when running in this mode 
Example  ( from any directory as long as you have the gen3 repo cloned and setup with the required environment variables) 
```
${GENERATION_DIR}/createTemplate.sh -o /root/testout -t testlbhttps -i mock -l solution
``` 
Will create the load balancer templates for the testlbhttps testcase ( https://github.com/codeontap/gen3/blob/7d94833e14227795abcca10d6e2606908de1a37a/providers/aws/testcases/testlbhttps.ftl ) and output them to /root/testout 
Input source and level are still required though …
=> <feature> Create test case templates without a cmdb

aws/manageDeployment.sh
* Separated out Resource Group and Deployment Group during deployment. Using the same value limits the deployments to 1 resource group per deployment. Specifying the resource group in this way allows you to create or utilise existing resource groups as necessary.
* Removed DEPLOYMENT_GROUP_NAME (-n) as a script option and replaced it with a concatenated value (DEPLOYMENT_NAME) that will make the deployments easily navigated. Specifying both resource group and deployment group is unnecessary.
*Added Service Provider registration during deployment with pretty terminal output.
=> Service Provider Registration

aws/utility.sh, providers/aws/components/db/setup.ftl, providers/aws/components/db/state.ftl, providers/aws/inputsources/shared/masterdata.ftl, providers/aws/services/rds/id.ftl, providers/aws/services/rds/resource.ftl, providers/shared/components/db/id.ftl
Adds support for AWS Aurora as a database engine 
Aurora runs as a cluster of db instances with storage managed by the cluster resource and the instances used to manage the compute resources. You can deploy up to 16 database instances across all AZs in a region 
Support has been setup in this PR for postgres based installations, mysql is available as well but has a long list of extra options that can be configured 
Most of the configuration is managed behind the scenes within the framework with the following configuration options added 
- new engine - aurora-postgresql
- An extra configuration section for cluster level database parameters 
- Desired, Max and Min counts on the processor component - Desired is in the initial release, Min and Max can be added for autoscaling the db instances
=> <feature> Add Aurora cluster support

providers/aws/components/db/setup.ftl
As part of #1088 the alarm configuration was moved out of the hibernate so that the alarms weren't recreated which trigged a false trigger 
But this means that during the replace template jobs when the database is removed the reference look ups fail. So we need to do a getExistingReference to get the actual value during a replace1 template generation so that the template can deploy without touching the alarms. 
Also removes the unnecessary dependency on the resource which the REf function provides anyway
=> <fix> rds alarm on replace

providers/shared/components/network/id.ftl
Azure requires a link between Network and Gateway components. This PR implements the capability to add links to the Network configuration.
=> Added Linking to Shared Network Component

providers/shared/deploymentframeworks/default/legacy.ftl, providers/shared/deploymentframeworks/default/model.ftl
In a same way that a deployment profile can be made to apply to all
modes via the use of a mode of "\*", add the ability for a deployment
profile to apply to all component types by the user of "\*". This allows
configuration applying to all components sharing a deployment profile to
be separate from that specific to the component type.
=> <Feature> Component type wildcard support in profiles

providers/aws/components/apigateway/state.ftl
With the ability to not include the stage in custom Domain names on API Gateways the stage might not been seen on an APIGateway
This gets around an issue at the moment where you have to set a version on an APIGateway to get the stage name to be populated.
=> <fix> APIGateway Occurrence Naming

providers/aws/components/apigateway/state.ftl, providers/aws/inputsources/shared/masterdata.ftl, providers/aws/masterData.json, providers/shared/deploymentframeworks/default/legacy.ftl, providers/shared/deploymentframeworks/default/model.ftl
Need to tweak the external link processing to check there isn't actually an external tier. If there is, then assume all external links will be managed via components in the external tier of the solution.
The use of the external tier is now our preferred approach rather than external links. It makes the dependencies much more obvious and the layout of the settings more logical. (Sharing of settings could be done via namespaces but links are a lot more explicit). It also means any generated documentation automatically documents the external dependencies and the values expected for eac external dependency.
We will need to change any components that used to rely on setting the type of the link. They will now need to explicitly look for links to "externalservice" components and check that any …
=> <Feature> Add external tier for external services

engine/inputdata/setting.ftl
Use the "^" character to escape any non-alphanumeric characters in an setting name that should not be converted to "_".
The most common use of this would be in settings added to create environment variables, since the setting name becomes to environment name.
=> <Feature> Permit escaping of characters in setting names

aws/contextTree.sh
The v1.1.0 cleanup did not correctly clean up accounts repos so a v1.1.1 cleanup has been added to rerun the 1.1.0 cleanup.
The v1.1.0 cleanup can now handle multiple config/infrastructure pairs in a single repo. This should only affect accounts repos.
=> <Feature> Add 1.1.1 cleanup to rerun 1.1.0 cleanup

providers/aws/components/sqs/setup.ftl, providers/aws/components/topic/setup.ftl
Move the permission to be on the queue side - means the solution needs an inbound link to the queue as well as an outbound subscription from the topic.
=> <fix> SNS subscriptions to SQS

aws/contextTree.sh, aws/createBlueprint.sh, aws/createBuildblueprint.sh, aws/createReference.sh, aws/createTemplate.sh, aws/runLambda.sh, aws/runTask.sh, aws/setContext.sh, aws/setStackContext.sh
Reorganise cmdb to make it easier to manage via branches and dynamic cmdbs
- State is now in its own directory at the same level as config and infrastructure
- Solutions is now under infrastructure
- Builds are separated from settings and are now under infrastructure
- Operations are now in their own directory at same level as config and infrastructure. For consistency with config, a settings subdirectory has been added.
With this layout,
- infrastructure should be the same across environments assuming no builds are being promoted
- product and operations settings are managed consistently
- all the state info is cleanly separated (so potentially in its own repo)
/config/settings
/operations/settings
/infrastructure/solutions
/infrastructure/builds
/state/cf
/state/cot
If config and …
=> <refactor> v2.0.0 restructure of CMDB

providers/aws/components/sqs/setup.ftl, providers/aws/services/sqs/policy.ftl
Correct the format of the resource policy for a service based principal.
Don't include action wildcards as they are not supported on SQS resource
policies (advice from AWS Support Desk).
=> <fix> SNS Subscription to SQS

engine/commonApplication.ftl, providers/shared/components/component.ftl, providers/shared/deploymentframeworks/default/legacy.ftl, providers/shared/deploymentframeworks/default/model.ftl
Add the "IncludeInContext" link attribute to permit only a defined set of
attributes to be included in the context as a result of a link. This
permits environment space to be conserved where only one or two
attributes are needed. The default behaviour is all attributes if the
attribute is missing or empty.
Also change the order in which getFinalEnvironment assembles variables
to permit link attributes to be overridden by component attributes (e.g.
link points to an external service with a default timeout value that the
code wants to override). Anything explicitly set via a fragment file
still overrides everything.
=> <feature> Control link attributes included in context

aws/contextTree.sh, aws/setContext.sh
Mostly there are no cmdb upgrades to be done. On this basis, check the
last version to be checked first and only check the full set of versions
if an upgrade to the last version is required. This assumes the version
lists are ordered, which they are to ensure an upgrade can assume the
cmdb is in the state expected as a result of the previous version
upgrade.
Also fix a minor syntax error with local vs global variables in a bash
script.
=> <feature> Optimise cmdb version checks

aws/utility.sh
As soon as a match is found, stop looping through the provided patterns.
=> <refactor> Terminate findDir on first match

engine/setContext.ftl, providers/shared/inputsources/shared/masterdata.ftl, providers/shared/references/VMImageProfile/id.ftl, providers/shared/references/reference.ftl
New reference type for creating profiles for virtual machine images.
New profiles can now be created as necessary in each providers masterData.ftl.
```
"VMImageProfiles" : {
"bastion" : {
"Publisher" : "Canonical",
"Offering" : "UbuntuServer",
"SKU" : "18.04-LTS"
}
}
```
These profiles can then be referenced in component setup easily through the global var vmImageProfiles:
```
[#local vmssVMImageProfile = vmImageProfiles[BASTION_COMPONENT_TYPE]]
```
=> created VM Image reference type

aws/contextTree.sh
Use it rather than jq to avoid segmentation fault issues with jq and long filenames.
=> <fix> Use manageJSON to assemble composite stack outputs

providers/aws/components/lambda/setup.ftl
If the policies are created in the same stack as the lambda function,
then they must be included as dependencies of the lambda function.
This is because they reference the role they refer to, but don't
directly link to the lambda function. This can cause race conditions
where the role is checked for permissions before the policies are
complete.
This situation arose for a lambda function being used as an
SQS event source, where the source object checks that the lambda
function has permission to read the queue before creating the event
trigger. In this case, it just depends on the function existing, which
in turn was only depending on the role being present.
=> <fix> Lambda policy dependencies if role in same template

aws/contextTree.sh, aws/createTemplate.sh, providers/shared/inputsources/composite/setting.ftl
In preparation for direct file querying from freemarker, move much of the logic to differentiate between cmdb files into freemarker.
The bash scripts now mainly ignore "dot" files and leave the processing based on filenames to freemarker.
While removing a number of directory scans, most of the time in assembly is spent in running jq on each file, which hasn't altered with the commit.
However, by moving the actual processing into freemarker, we are ready to bypass the file scanning in bash and do it directly from the freemarker wrapper.
=> <refactor> Move composite processing into freemarker

aws/contextTree.sh, aws/createTemplate.sh, aws/nullStrip.jq
Replacement PR for #1123  which aligns with the changes introduced in #1121 
Now whenever we load collcetion of files via getFilesAsJSON we pass them through a null strip jq function. 
This also supports cleaning out array null values
=> <feature> Null stripping for freemarker

engine/commonApplication.ftl, providers/shared/components/ecs/id.ftl
Adds links at the subcomponent level for a couple of reasons 
- Allows for links to be shared across multiple containers in the same task/service 
- Allows for links to be managed through deploymentProfiles - containers have unique names which restrict the use of deploymentProfiles
=> <feature> ECS Subcomponent links

engine/common.ftl, providers/aws/components/apigateway/setup.ftl, providers/aws/components/cache/setup.ftl, providers/aws/components/computecluster/setup.ftl, providers/aws/components/db/setup.ftl, providers/aws/components/ecs/setup.ftl, providers/aws/components/es/setup.ftl, providers/aws/components/lambda/setup.ftl, providers/aws/components/lb/setup.ftl, providers/aws/components/mobilenotifier/setup.ftl, providers/aws/components/sqs/setup.ftl, providers/aws/components/topic/setup.ftl, providers/aws/services/cw/resource.ftl, providers/aws/services/resource.ftl
Allows for the resource lookups on alerts to be disabled. 
This is helpful for custom metrics which do not have dimensions that can't be determined by the resources in the component themselves 
Also removes the explicit dependencies on alerts as they aren't required and can cause issues with hibernation
=> <feature> Disable resource type lookups for alerts

providers/shared/components/baseline/id.ftl
for use in assigning the network access policies on keyvault. Defaults to global, which would leave the keyvault relying on permission-based access only. Setting it this way ensures that the COT user who is implementing the infrastructure can access the keyvault during setup. Less open configuration will need to account for the given network that the admins reside on.
=> Added IPAddressGroups attribute to Baseline Keys

providers/aws/components/gateway/setup.ftl, providers/aws/services/vpc/resource.ftl
Once a NAT Gateway has been assinged to an EIP you can't make updates to the EIP, including tagging unless you replace the NAT Gateway 
This disables tags on gatway components for the time being
=> <fix> EIP remove tags on gateway components

providers/shared/deploymentframeworks/default/legacy.ftl
Remove a couple of spurious chars when processing genplans.
=> <fix> Remove extra chars from genplan

providers/aws/services/waf/resource.ftl
https://github.com/codeontap/gen3/pull/1082 removed the analyzeCIDR function without remediating its use in the WAF configuration management.
It was used to determine the type of an IP address range (v4 vs v6).
For now, hard code to IPv4.
=> <fix> Remove analyzeCIDR usage

providers/aws/components/apigateway/setup.ftl, providers/aws/components/lambda/setup.ftl, providers/aws/services/lambda/resource.ftl, providers/shared/components/apigateway/id.ftl, providers/shared/components/component.ftl, providers/shared/components/lambda/id.ftl
Add initial support for AWS X-Ray based on the components that support it via Cloudformation - currently API Gateway and Lambda.
Others will be added as Cloudformation support becomes available. The default config for other services is passthrough which should be sufficient given most flows start with either an API Gateway or Lambda call.
=> <feature> X-Ray control

engine/inputdata/stackOutput.ftl, providers/shared/inputsources/composite/stackoutput.ftl
The shared provider does not have a stackoutput macro, so when getStackOutputObject looks up pseudostacks generated by another provider it cannot find any. This PR copies/renames the primary composite stackoutput macro for AWS into the shared provider.
=> Enable Plugin Provider Pseudo Stacks

providers/aws/components/lb/setup.ftl, providers/aws/services/lb/resource.ftl, providers/aws/services/vpc/resource.ftl
Some minor fixes to lb rules based on the testing results in #1145 
- Change the type of value for target groups - cfn-lint 
- Make the egress security rule an explicit rather than implicit - cfn_nag F1000
=> <fix> lb updates from lint testing

engine/setContext.ftl
The shared baseline component contains the functions required for linking to the baseline. Without pre-loading it, you can't link to it. This PR ensures that its pre-loaded for all providers.
=> Shared Baseline Provider to load for all providers

providers/aws/components/db/setup.ftl, providers/aws/services/rds/resource.ftl
AWS hasn't announced it in documentation yet but they have added support for setting the CA Certificate identifier via Cloudformation on RDS instances 
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/211 
This PR moves our existing CLI support into Cloudformation
=> <refactor> move RDS CA Control to cloudformation

providers/aws/components/es/setup.ftl, providers/shared/references/Processor/id.ftl
To remove the risk of null values causing issues this PR adds default counts to the processor profile configuration. This way we know it will always have a value
=> <fix> Use default values for ES nodes counts instead of value check

providers/aws/components/es/setup.ftl, providers/aws/inputsources/shared/masterdata.ftl, providers/aws/masterData.json, providers/shared/components/es/id.ftl, providers/shared/references/SecurityProfile/id.ftl
A couple more fixes from testing the ES deployment to VPC 
- Creates a Service linked role for Elasticsearch to create ENI - This only needs to be created once per account - the script will check and see if one exists and move on if its not there 
- Adds Security profile to control the endpoint Protocol ( http vs https ) 
- In VPC this updates the security groups 
- Public has HTTPS only control but its not in cloudformation yet 
- Access policies cannot contain IP's when they applied to VPC based instances 
- Moves the IP control over to security groups 
- When you only want IP based auth on VPC based instances you need to add an open access policy 
- Similar to the processor profile splits out the Security Profiles based on their types
=> <fix> ES Acccess Policy Updates

providers/aws/components/es/setup.ftl, providers/aws/inputsources/shared/masterdata.ftl, providers/aws/masterData.json, providers/shared/components/es/id.ftl
Align the advanced options configuration with the composite objects structure 
add default instances sizes for the master nodes ( only applied if the counts enable the master )
=> <fix> ES advanced options

engine/openapi.ftl
Allow for an empty value on ContentHandling validation - the current default value if none is sent
=> <fix> apigateway allow empty on ContentHandling

providers/aws/components/es/setup.ftl, providers/aws/components/es/state.ftl, providers/shared/references/Processor/id.ftl
Since ES data nodes can only be added in counts based on the number of zones selected the explicit count doesn't make sense. This removes the explicit count for data nodes but keeps it for master nodes 
Also adds a new IAM role which can be used to create S3 based snapshot store within the AppData store of the es cluster. Useful for snapshots you want to access
=> <fix> remove es explicit count in favour of per zone

aws/createTemplate.sh, aws/manageDeployment.sh, execution/contextTree.sh, execution/setStackContext.sh
Move existing state files into subdirectories based on the deployment unit.
Also add a placement subdirectory based on the the region.
Definition files are deleted as their names are occurrence rather than deployment unit based, but they are recopied as part of each build so will be refreshed on next build and placed in the correct deployment directory s a result. 
NOTE: The v2.0.1 upgrade will not be triggered by default as the maximum cmdb version for upgrade hasn't been altered. This will permit selective testing before the upgrade being automated more generally.
To test this upgrade set
```export GENERATION_MAX_CMDB_UPGRADE_VERSION=v2.0.1```
=> <feature> CMDB v2.0.1 - Add du/placement subdirectories to the state tree

execution/contextTree.sh
If an upgrade can't happen because of a cmdb being pinned, don't bother
checking subsequent versions.
=> <feature> Don't check all versions of pinned repo

providers/shared/references/Port/id.ftl
Add SuccessCodes as an optional parameter on the HealthCheck data for a port.
=> <Fix> Port reference data can include Success Codes

engine/openapi.ftl
Add "basic" as one of the supported security schemes to support swagger 2.0 format specifications.
=> <Fix> Add support for swagger 2.0 basic scheme

aws/createBlueprint.sh, aws/createBuildblueprint.sh, aws/createTemplate.sh, engine/bootstrap.ftl, engine/component.ftl, engine/output.ftl, engine/provider.ftl, engine/scenario.ftl, engine/setContext.ftl, providers/awstest/awstest.ftl, providers/awstest/scenarios/lb.ftl, providers/shared/deploymentframeworks/default/legacy.ftl, providers/shared/deploymentframeworks/default/output.ftl, providers/shared/references/TestCase/id.ftl, providers/shared/services/resource.ftl, providers/shared/shared.ftl
Another move around for getting the testing idea working 
Moves the loading processing of scenarios into the ability to load additional providers as SubProviders. SubProviders load like normal providers except when it comes to output management which is set by default to the existing GENERATION_PROVIDER variable 
Along with working for scenarios, this allows for codeontap users to load their own providers on top of standard providers, overriding default values or implementing their own components while still using the resources of another provider 
From a testing side this introduces a new provider `awstest` which contains scenarios designed to test the templates that we generate in a unit testing style, while keeping the testing isolated from the real world provider code
=> <refactor> Move test case scenarios into provider

providers/aws/components/lambda/setup.ftl, providers/aws/services/lambda/resource.ftl, providers/shared/components/lambda/id.ftl
Adds support for configuring reserved executions on lambda functions
This is used to ensure that a busy lambda doesn't flood the execution limit on the account and also to ensure that the lambda has room to get busy
=> <feature> lambda reserved executions

execution/contextTree.sh
When transitioning an environment between accounts, it is possible to have the files for more than one account together in the state tree.
To avoid interference, ensure only the files for the account of interest are included.
=> <fix> Filter on account for composite defn/outputs

providers/aws/components/baseline/setup.ftl
The legacy oai credential was not being removed in the transition from cmk to baseline.
The checks to delete the legacy oai/ssh pseudo stacks were also not compatible with cmdbs >= 2.0.1 as they assumed the baseline and cmk stacks were in the same directory. The CF_DIR is now adjusted accordingly in addition to the filename.
=> <fix> cmk to baseline transition

providers/aws/components/lambda/setup.ftl
Lambda needs permissions on the XRay daemon if tracing is enabled. Write access is needed regardless of whether the mode is PassThrough or Active.
=> <fix> XRay permissions for lambda

providers/shared/components/lambda/id.ftl
Add the latest run-times supported by lambda. For now we'll leave some of the older ones like node6 there for existing deployments.
=> <feature> Supported lambda run-times

engine/openapi.ftl
apiKeys can have "in" and "name" provided so include them in the analysis of security schemes.
=> <fix> Handle optional name and in parameters

engine/openapi.ftl
Add the ability to control how security is applied to options verbs which are added automatically through the openapi enrichment process
This is most commonly used for mock CORS preflight checks which are used to determine the appropriate methods that can be consumed at an endpoint 
Since one CORS option controls credentials, clients don't have to send the Authorisation header when making the preflight check using the OPTIONS method. 
More details on CORS and preflight checks are available here
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests
=> <feature> APIGW add option security control

providers/aws/components/db/setup.ftl, providers/aws/services/autoscaling/resource.ftl
- fixes #1205 to include the instance host type when managing encrypted snapshots
- makes the predeploysnapshot Id a reverse of the runId to force the creation of new templates on every template generation - This ensures that at snapshot will be created on each manage Environment 
- Fixes a typo in the function name for autoscaling auroroa
=> <fix> RDS encrypted snapshots

providers/aws/components/mobilenotifier/state.ftl, providers/aws/components/sqs/state.ftl
Change SQS external link state processing to work with the current way the state macro is called.
Also correct the format of the principal for log watchers - looks like AWS have tightened up or changed the principal format for a service invocation.
=> <fix> SQS External Link and logwatch principal

aws/runTask.sh
When using runTask ensure we use the name for all properties in the query
=> <fix> use Name for all runTask properties

aws/runSentryRelease.sh
A quick fix for DEPLOYMENT_UNIT option, align it with expo publish script.
=> <fix> options for run sentry release script
